[2025-03-07 13:53:30,677] [INFO] Starting node at localhost:30139 | index=140 | f=1, k=4 | Role: Replica
[2025-03-07 13:53:39,318] [INFO] [30139] Received PREPARE: id:1741323218379, from:30021, delay:0.0000s, distance:75.94m (Euclidean)
[2025-03-07 13:53:39,318] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,362] [INFO] [30139] Received COMMIT: id:1741323218379, from:30021, delay:0.0000s, distance:75.94m (Euclidean)
[2025-03-07 13:53:39,990] [INFO] [30139] Received PREPARE: id:1741323218379, from:30033, delay:0.0000s, distance:53.00m (Euclidean)
[2025-03-07 13:53:39,990] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,990] [INFO] [30139] Received COMMIT: id:1741323218379, from:30033, delay:0.0000s, distance:53.00m (Euclidean)
[2025-03-07 13:53:40,132] [INFO] [30139] Received PREPARE: id:1741323218379, from:30039, delay:0.0000s, distance:85.74m (Euclidean)
[2025-03-07 13:53:40,132] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,169] [INFO] [30139] Received PREPARE: id:1741323218379, from:30060, delay:0.0000s, distance:118.88m (Euclidean)
[2025-03-07 13:53:40,169] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,275] [INFO] [30139] Received COMMIT: id:1741323218379, from:30060, delay:0.0000s, distance:118.88m (Euclidean)
[2025-03-07 13:53:40,291] [INFO] [30139] Received PREPARE: id:1741323218379, from:30094, delay:0.0000s, distance:123.83m (Euclidean)
[2025-03-07 13:53:40,291] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,401] [INFO] [30139] Received PREPARE: id:1741323218379, from:30012, delay:0.0001s, distance:188.89m (Euclidean)
[2025-03-07 13:53:40,476] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,476] [INFO] [30139] Received COMMIT: id:1741323218379, from:30012, delay:0.0001s, distance:188.89m (Euclidean)
[2025-03-07 13:53:40,476] [INFO] [30139] Received PREPARE: id:1741323218379, from:30044, delay:0.0001s, distance:233.34m (Euclidean)
[2025-03-07 13:53:40,476] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,577] [INFO] [30139] Received PREPARE: id:1741323218379, from:30089, delay:0.0000s, distance:79.23m (Euclidean)
[2025-03-07 13:53:40,577] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,577] [INFO] [30139] Received COMMIT: id:1741323218379, from:30089, delay:0.0000s, distance:79.23m (Euclidean)
[2025-03-07 13:53:40,719] [INFO] [30139] Received PREPARE: id:1741323218379, from:30117, delay:0.0000s, distance:74.21m (Euclidean)
[2025-03-07 13:53:40,719] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,719] [INFO] [30139] Received COMMIT: id:1741323218379, from:30117, delay:0.0000s, distance:74.21m (Euclidean)
[2025-03-07 13:53:40,865] [INFO] [30139] Received PREPARE: id:1741323218379, from:30009, delay:0.0001s, distance:248.92m (Euclidean)
[2025-03-07 13:53:40,865] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,865] [INFO] [30139] Received COMMIT: id:1741323218379, from:30009, delay:0.0001s, distance:248.92m (Euclidean)
[2025-03-07 13:53:40,893] [INFO] [30139] Received PREPARE: id:1741323218379, from:30090, delay:0.0001s, distance:193.79m (Euclidean)
[2025-03-07 13:53:40,893] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,893] [INFO] [30139] Received COMMIT: id:1741323218379, from:30090, delay:0.0001s, distance:193.79m (Euclidean)
[2025-03-07 13:53:41,084] [INFO] [30139] Received COMMIT: id:1741323218379, from:30039, delay:0.0000s, distance:85.74m (Euclidean)
[2025-03-07 13:53:41,150] [INFO] [30139] Received PREPARE: id:1741323218379, from:30034, delay:0.0001s, distance:164.18m (Euclidean)
[2025-03-07 13:53:41,150] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,150] [INFO] [30139] Received COMMIT: id:1741323218379, from:30034, delay:0.0001s, distance:164.18m (Euclidean)
[2025-03-07 13:53:41,734] [INFO] [30139] Received PREPARE: id:1741323218379, from:30087, delay:0.0001s, distance:231.77m (Euclidean)
[2025-03-07 13:53:41,734] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,734] [INFO] [30139] Received COMMIT: id:1741323218379, from:30087, delay:0.0001s, distance:231.77m (Euclidean)
[2025-03-07 13:53:42,000] [INFO] [30139] Received PREPARE: id:1741323218379, from:30086, delay:0.0001s, distance:244.72m (Euclidean)
[2025-03-07 13:53:42,016] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,016] [INFO] [30139] Received COMMIT: id:1741323218379, from:30086, delay:0.0001s, distance:244.72m (Euclidean)
[2025-03-07 13:53:42,143] [INFO] [30139] Received COMMIT: id:1741323218379, from:30044, delay:0.0001s, distance:233.34m (Euclidean)
[2025-03-07 13:53:42,305] [INFO] [30139] Received PREPARE: id:1741323218379, from:30046, delay:0.0000s, distance:122.01m (Euclidean)
[2025-03-07 13:53:42,305] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,313] [INFO] [30139] Received COMMIT: id:1741323218379, from:30046, delay:0.0000s, distance:122.01m (Euclidean)
[2025-03-07 13:53:42,553] [INFO] [30139] Received PREPARE: id:1741323218379, from:30026, delay:0.0001s, distance:237.89m (Euclidean)
[2025-03-07 13:53:42,553] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,553] [INFO] [30139] Received COMMIT: id:1741323218379, from:30026, delay:0.0001s, distance:237.89m (Euclidean)
[2025-03-07 13:53:42,649] [INFO] [30139] Received PREPARE: id:1741323218379, from:30030, delay:0.0001s, distance:191.11m (Euclidean)
[2025-03-07 13:53:42,649] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,650] [INFO] [30139] Received COMMIT: id:1741323218379, from:30030, delay:0.0001s, distance:191.11m (Euclidean)
[2025-03-07 13:53:42,664] [INFO] [30139] Received PREPARE: id:1741323218379, from:30052, delay:0.0000s, distance:144.23m (Euclidean)
[2025-03-07 13:53:42,664] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,702] [INFO] [30139] Received COMMIT: id:1741323218379, from:30052, delay:0.0000s, distance:144.23m (Euclidean)
[2025-03-07 13:53:42,797] [INFO] [30139] Received PREPARE: id:1741323218379, from:30016, delay:0.0002s, distance:287.42m (Euclidean)
[2025-03-07 13:53:42,797] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,296] [INFO] [30139] Received PREPARE: id:1741323218379, from:30097, delay:0.0001s, distance:236.02m (Euclidean)
[2025-03-07 13:53:43,296] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,296] [INFO] [30139] Received COMMIT: id:1741323218379, from:30097, delay:0.0001s, distance:236.02m (Euclidean)
[2025-03-07 13:53:43,296] [INFO] [30139] Received COMMIT: id:1741323218379, from:30002, delay:0.0002s, distance:280.32m (Euclidean)
[2025-03-07 13:53:43,296] [INFO] [30139] Received PREPARE: id:1741323218379, from:30002, delay:0.0002s, distance:280.32m (Euclidean)
[2025-03-07 13:53:43,296] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,328] [INFO] [30139] Received PREPARE: id:1741323218379, from:30083, delay:0.0001s, distance:236.99m (Euclidean)
[2025-03-07 13:53:43,328] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,328] [INFO] [30139] Received COMMIT: id:1741323218379, from:30083, delay:0.0001s, distance:236.99m (Euclidean)
[2025-03-07 13:53:43,391] [INFO] [30139] Received PREPARE: id:1741323218379, from:30053, delay:0.0001s, distance:183.28m (Euclidean)
[2025-03-07 13:53:43,398] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,398] [INFO] [30139] Received COMMIT: id:1741323218379, from:30053, delay:0.0001s, distance:183.28m (Euclidean)
[2025-03-07 13:53:43,502] [INFO] [30139] Received PREPARE: id:1741323218379, from:30005, delay:0.0002s, distance:293.41m (Euclidean)
[2025-03-07 13:53:43,502] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,517] [INFO] [30139] Received COMMIT: id:1741323218379, from:30005, delay:0.0002s, distance:293.41m (Euclidean)
[2025-03-07 13:53:43,530] [INFO] [30139] Received PREPARE: id:1741323218379, from:30062, delay:0.0002s, distance:267.92m (Euclidean)
[2025-03-07 13:53:43,530] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,530] [INFO] [30139] Received COMMIT: id:1741323218379, from:30062, delay:0.0002s, distance:267.92m (Euclidean)
[2025-03-07 13:53:43,549] [INFO] [30139] Received PREPARE: id:1741323218379, from:30037, delay:0.0002s, distance:278.88m (Euclidean)
[2025-03-07 13:53:43,549] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,571] [INFO] [30139] Received COMMIT: id:1741323218379, from:30037, delay:0.0002s, distance:278.88m (Euclidean)
[2025-03-07 13:53:43,628] [INFO] [30139] Received PREPARE: id:1741323218379, from:30036, delay:0.0002s, distance:256.97m (Euclidean)
[2025-03-07 13:53:43,628] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,628] [INFO] [30139] Received COMMIT: id:1741323218379, from:30036, delay:0.0002s, distance:256.97m (Euclidean)
[2025-03-07 13:53:43,802] [INFO] [30139] Received COMMIT: id:1741323218379, from:30016, delay:0.0002s, distance:287.42m (Euclidean)
[2025-03-07 13:53:43,978] [INFO] [30139] Received PREPARE: id:1741323218379, from:30031, delay:0.0001s, distance:244.75m (Euclidean)
[2025-03-07 13:53:43,978] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,992] [INFO] [30139] Received COMMIT: id:1741323218379, from:30031, delay:0.0001s, distance:244.75m (Euclidean)
[2025-03-07 13:53:44,003] [INFO] [30139] Received PREPARE: id:1741323218379, from:30096, delay:0.0002s, distance:277.25m (Euclidean)
[2025-03-07 13:53:44,003] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,017] [INFO] [30139] Received COMMIT: id:1741323218379, from:30096, delay:0.0002s, distance:277.25m (Euclidean)
[2025-03-07 13:53:44,248] [INFO] [30139] Received PREPARE: id:1741323218379, from:30055, delay:0.0002s, distance:275.59m (Euclidean)
[2025-03-07 13:53:44,248] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,248] [INFO] [30139] Received COMMIT: id:1741323218379, from:30094, delay:0.0000s, distance:123.83m (Euclidean)
[2025-03-07 13:53:44,248] [INFO] [30139] Received COMMIT: id:1741323218379, from:30055, delay:0.0002s, distance:275.59m (Euclidean)
[2025-03-07 13:53:44,309] [INFO] [30139] Received PREPARE: id:1741323218379, from:30019, delay:0.0002s, distance:267.00m (Euclidean)
[2025-03-07 13:53:44,309] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,309] [INFO] [30139] Received COMMIT: id:1741323218379, from:30019, delay:0.0002s, distance:267.00m (Euclidean)
[2025-03-07 13:53:44,656] [INFO] [30139] Received PREPARE: id:1741323218379, from:30088, delay:0.0002s, distance:286.73m (Euclidean)
[2025-03-07 13:53:44,656] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,656] [INFO] [30139] Received COMMIT: id:1741323218379, from:30088, delay:0.0002s, distance:286.73m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Received PREPARE: id:1741323218379, from:30049, delay:0.0001s, distance:236.70m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,146] [INFO] [30139] Received PREPARE: id:1741323218379, from:30004, delay:0.0001s, distance:224.78m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,146] [INFO] [30139] Received COMMIT: id:1741323218379, from:30070, delay:0.0002s, distance:277.86m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Received COMMIT: id:1741323218379, from:30010, delay:0.0000s, distance:158.07m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Received COMMIT: id:1741323218379, from:30048, delay:0.0001s, distance:151.20m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Received COMMIT: id:1741323218379, from:30049, delay:0.0001s, distance:236.70m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Received COMMIT: id:1741323218379, from:30004, delay:0.0001s, distance:224.78m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Received PREPARE: id:1741323218379, from:30010, delay:0.0000s, distance:158.07m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,146] [INFO] [30139] Received PREPARE: id:1741323218379, from:30048, delay:0.0001s, distance:151.20m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,146] [INFO] [30139] Received PREPARE: id:1741323218379, from:30070, delay:0.0002s, distance:277.86m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,241] [INFO] [30139] Received PREPARE: id:1741323218379, from:30072, delay:0.0002s, distance:269.49m (Euclidean)
[2025-03-07 13:53:45,241] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,241] [INFO] [30139] Received COMMIT: id:1741323218379, from:30072, delay:0.0002s, distance:269.49m (Euclidean)
[2025-03-07 13:53:45,385] [INFO] [30139] Received PREPARE: id:1741323218379, from:30032, delay:0.0000s, distance:168.34m (Euclidean)
[2025-03-07 13:53:45,385] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,385] [INFO] [30139] Received COMMIT: id:1741323218379, from:30078, delay:0.0001s, distance:244.56m (Euclidean)
[2025-03-07 13:53:45,385] [INFO] [30139] Received COMMIT: id:1741323218379, from:30032, delay:0.0000s, distance:168.34m (Euclidean)
[2025-03-07 13:53:45,385] [INFO] [30139] Received PREPARE: id:1741323218379, from:30078, delay:0.0001s, distance:244.56m (Euclidean)
[2025-03-07 13:53:45,385] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,388] [INFO] [30139] Received PREPARE: id:1741323218379, from:30040, delay:0.0001s, distance:192.52m (Euclidean)
[2025-03-07 13:53:45,388] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,388] [INFO] [30139] Received COMMIT: id:1741323218379, from:30040, delay:0.0001s, distance:192.52m (Euclidean)
[2025-03-07 13:53:45,430] [INFO] [30139] Received PREPARE: id:1741323218379, from:30073, delay:0.0001s, distance:220.57m (Euclidean)
[2025-03-07 13:53:45,430] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,432] [INFO] [30139] Received COMMIT: id:1741323218379, from:30073, delay:0.0001s, distance:220.57m (Euclidean)
[2025-03-07 13:53:45,590] [INFO] [30139] Received COMMIT: id:1741323218379, from:30017, delay:0.0000s, distance:195.28m (Euclidean)
[2025-03-07 13:53:45,590] [INFO] [30139] Received PREPARE: id:1741323218379, from:30017, delay:0.0000s, distance:195.28m (Euclidean)
[2025-03-07 13:53:45,590] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,658] [INFO] [30139] Received PREPARE: id:1741323218379, from:30061, delay:0.0002s, distance:291.15m (Euclidean)
[2025-03-07 13:53:45,658] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,658] [INFO] [30139] Received PREPARE: id:1741323218379, from:30003, delay:0.0000s, distance:191.46m (Euclidean)
[2025-03-07 13:53:45,658] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,658] [INFO] [30139] Received COMMIT: id:1741323218379, from:30061, delay:0.0002s, distance:291.15m (Euclidean)
[2025-03-07 13:53:45,658] [INFO] [30139] Received COMMIT: id:1741323218379, from:30003, delay:0.0000s, distance:191.46m (Euclidean)
[2025-03-07 13:53:45,668] [INFO] [30139] Received PREPARE: id:1741323218379, from:30095, delay:0.0000s, distance:147.11m (Euclidean)
[2025-03-07 13:53:45,668] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,668] [INFO] [30139] Received COMMIT: id:1741323218379, from:30095, delay:0.0000s, distance:147.11m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30139] Received PREPARE: id:1741323218379, from:30091, delay:0.0001s, distance:237.33m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,810] [INFO] [30139] Received COMMIT: id:1741323218379, from:30091, delay:0.0001s, distance:237.33m (Euclidean)
[2025-03-07 13:53:45,921] [INFO] [30139] Received PREPARE: id:1741323218379, from:30006, delay:0.0002s, distance:286.15m (Euclidean)
[2025-03-07 13:53:45,921] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,921] [INFO] [30139] Received COMMIT: id:1741323218379, from:30006, delay:0.0002s, distance:286.15m (Euclidean)
[2025-03-07 13:53:46,011] [INFO] [30139] Received PREPARE: id:1741323218379, from:30099, delay:0.0000s, distance:168.72m (Euclidean)
[2025-03-07 13:53:46,011] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,016] [INFO] [30139] Received COMMIT: id:1741323218379, from:30099, delay:0.0000s, distance:168.72m (Euclidean)
[2025-03-07 13:53:46,032] [INFO] [30139] Received PREPARE: id:1741323218379, from:30104, delay:0.0001s, distance:241.38m (Euclidean)
[2025-03-07 13:53:46,032] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,032] [INFO] [30139] Received COMMIT: id:1741323218379, from:30104, delay:0.0001s, distance:241.38m (Euclidean)
[2025-03-07 13:53:46,063] [INFO] [30139] Received PREPARE: id:1741323218379, from:30098, delay:0.0001s, distance:218.47m (Euclidean)
[2025-03-07 13:53:46,063] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,063] [INFO] [30139] Received COMMIT: id:1741323218379, from:30098, delay:0.0001s, distance:218.47m (Euclidean)
[2025-03-07 13:53:46,116] [INFO] [30139] Received PREPARE: id:1741323218379, from:30035, delay:0.0002s, distance:278.07m (Euclidean)
[2025-03-07 13:53:46,116] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,116] [INFO] [30139] Received COMMIT: id:1741323218379, from:30035, delay:0.0002s, distance:278.07m (Euclidean)
[2025-03-07 13:53:46,237] [INFO] [30139] Received PREPARE: id:1741323218379, from:30058, delay:0.0001s, distance:229.99m (Euclidean)
[2025-03-07 13:53:46,237] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,237] [INFO] [30139] Received COMMIT: id:1741323218379, from:30058, delay:0.0001s, distance:229.99m (Euclidean)
[2025-03-07 13:53:46,557] [INFO] [30139] Received PREPARE: id:1741323218379, from:30041, delay:0.0000s, distance:189.59m (Euclidean)
[2025-03-07 13:53:46,557] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,557] [INFO] [30139] Received COMMIT: id:1741323218379, from:30041, delay:0.0000s, distance:189.59m (Euclidean)
[2025-03-07 13:53:46,574] [INFO] [30139] Received PREPARE: id:1741323218379, from:30043, delay:0.0001s, distance:215.20m (Euclidean)
[2025-03-07 13:53:46,574] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,574] [INFO] [30139] Received COMMIT: id:1741323218379, from:30043, delay:0.0001s, distance:215.20m (Euclidean)
[2025-03-07 13:53:46,586] [INFO] [30139] Received PREPARE: id:1741323218379, from:30042, delay:0.0002s, distance:269.60m (Euclidean)
[2025-03-07 13:53:46,586] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,586] [INFO] [30139] Received COMMIT: id:1741323218379, from:30042, delay:0.0002s, distance:269.60m (Euclidean)
[2025-03-07 13:53:46,633] [INFO] [30139] Received PREPARE: id:1741323218379, from:30014, delay:0.0001s, distance:239.43m (Euclidean)
[2025-03-07 13:53:46,633] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,633] [INFO] [30139] Received COMMIT: id:1741323218379, from:30014, delay:0.0001s, distance:239.43m (Euclidean)
[2025-03-07 13:53:46,649] [INFO] [30139] Received PREPARE: id:1741323218379, from:30028, delay:0.0002s, distance:285.88m (Euclidean)
[2025-03-07 13:53:46,649] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,649] [INFO] [30139] Received COMMIT: id:1741323218379, from:30028, delay:0.0002s, distance:285.88m (Euclidean)
[2025-03-07 13:53:46,697] [INFO] [30139] Received PRE-PREPARE: id:1741323218379, from:Leader(30000), delay:0.0001s, distance:205.08m (Euclidean)
[2025-03-07 13:53:46,697] [INFO] [30139] Broadcasting PREPARE for REQUEST 1741323218379
[2025-03-07 13:53:46,807] [INFO] [30139] Received PREPARE: id:1741323218379, from:30102, delay:0.0001s, distance:216.36m (Euclidean)
[2025-03-07 13:53:46,807] [INFO] [30139] Broadcasting COMMIT for REQUEST 1741323218379
[2025-03-07 13:53:46,871] [INFO] [30139] Received COMMIT: id:1741323218379, from:30102, delay:0.0001s, distance:216.36m (Euclidean)
[2025-03-07 13:53:46,902] [INFO] [30139] Received COMMIT: id:1741323218379, from:30007, delay:0.0000s, distance:82.85m (Euclidean)
[2025-03-07 13:53:46,902] [INFO] [30139] Received PREPARE: id:1741323218379, from:30007, delay:0.0000s, distance:82.85m (Euclidean)
[2025-03-07 13:53:47,665] [INFO] [30139] Received PREPARE: id:1741323218379, from:30136, delay:0.0001s, distance:211.39m (Euclidean)
[2025-03-07 13:53:47,665] [INFO] [30139] Received COMMIT: id:1741323218379, from:30134, delay:0.0001s, distance:176.73m (Euclidean)
[2025-03-07 13:53:47,665] [INFO] [30139] Received COMMIT: id:1741323218379, from:30136, delay:0.0001s, distance:211.39m (Euclidean)
[2025-03-07 13:53:47,665] [INFO] [30139] Received PREPARE: id:1741323218379, from:30134, delay:0.0001s, distance:176.73m (Euclidean)
[2025-03-07 13:53:47,710] [INFO] [30139] Received PREPARE: id:1741323218379, from:30122, delay:0.0002s, distance:267.96m (Euclidean)
[2025-03-07 13:53:47,710] [INFO] [30139] Received COMMIT: id:1741323218379, from:30122, delay:0.0002s, distance:267.96m (Euclidean)
[2025-03-07 13:53:47,929] [INFO] [30139] Received PREPARE: id:1741323218379, from:30110, delay:0.0002s, distance:253.87m (Euclidean)
[2025-03-07 13:53:47,944] [INFO] [30139] Received COMMIT: id:1741323218379, from:30110, delay:0.0002s, distance:253.87m (Euclidean)
[2025-03-07 13:53:48,084] [INFO] [30139] Received PREPARE: id:1741323218379, from:30105, delay:0.0000s, distance:41.35m (Euclidean)
[2025-03-07 13:53:48,087] [INFO] [30139] Received COMMIT: id:1741323218379, from:30105, delay:0.0000s, distance:41.35m (Euclidean)
[2025-03-07 13:53:48,182] [INFO] [30139] Received PREPARE: id:1741323218379, from:30109, delay:0.0000s, distance:119.37m (Euclidean)
[2025-03-07 13:53:48,198] [INFO] [30139] Received COMMIT: id:1741323218379, from:30109, delay:0.0000s, distance:119.37m (Euclidean)
[2025-03-07 13:53:48,214] [INFO] [30139] Received COMMIT: id:1741323218379, from:30158, delay:0.0001s, distance:242.81m (Euclidean)
[2025-03-07 13:53:48,214] [INFO] [30139] Received PREPARE: id:1741323218379, from:30158, delay:0.0001s, distance:242.81m (Euclidean)
[2025-03-07 13:53:48,231] [INFO] [30139] Received PREPARE: id:1741323218379, from:30147, delay:0.0001s, distance:191.09m (Euclidean)
[2025-03-07 13:53:48,231] [INFO] [30139] Received COMMIT: id:1741323218379, from:30147, delay:0.0001s, distance:191.09m (Euclidean)
[2025-03-07 13:53:48,284] [INFO] [30139] Received PREPARE: id:1741323218379, from:30135, delay:0.0001s, distance:228.68m (Euclidean)
[2025-03-07 13:53:48,290] [INFO] [30139] Received COMMIT: id:1741323218379, from:30135, delay:0.0001s, distance:228.68m (Euclidean)
[2025-03-07 13:53:48,305] [INFO] [30139] Received PREPARE: id:1741323218379, from:30153, delay:0.0001s, distance:160.14m (Euclidean)
[2025-03-07 13:53:48,309] [INFO] [30139] Received COMMIT: id:1741323218379, from:30153, delay:0.0001s, distance:160.14m (Euclidean)
[2025-03-07 13:53:48,451] [INFO] [30139] Received PREPARE: id:1741323218379, from:30154, delay:0.0001s, distance:195.84m (Euclidean)
[2025-03-07 13:53:48,453] [INFO] [30139] Received COMMIT: id:1741323218379, from:30154, delay:0.0001s, distance:195.84m (Euclidean)
[2025-03-07 13:53:48,612] [INFO] [30139] Received PREPARE: id:1741323218379, from:30157, delay:0.0001s, distance:213.46m (Euclidean)
[2025-03-07 13:53:48,627] [INFO] [30139] Received COMMIT: id:1741323218379, from:30157, delay:0.0001s, distance:213.46m (Euclidean)
[2025-03-07 13:53:48,672] [INFO] [30139] Received PREPARE: id:1741323218379, from:30131, delay:0.0001s, distance:212.35m (Euclidean)
[2025-03-07 13:53:48,672] [INFO] [30139] Received COMMIT: id:1741323218379, from:30131, delay:0.0001s, distance:212.35m (Euclidean)
[2025-03-07 13:53:48,853] [INFO] [30139] Received PREPARE: id:1741323218379, from:30107, delay:0.0000s, distance:135.93m (Euclidean)
[2025-03-07 13:53:48,861] [INFO] [30139] Received COMMIT: id:1741323218379, from:30107, delay:0.0000s, distance:135.93m (Euclidean)
[2025-03-07 13:53:48,877] [INFO] [30139] Received PREPARE: id:1741323218379, from:30128, delay:0.0001s, distance:197.81m (Euclidean)
[2025-03-07 13:53:48,897] [INFO] [30139] Received COMMIT: id:1741323218379, from:30128, delay:0.0001s, distance:197.81m (Euclidean)
[2025-03-07 13:53:48,929] [INFO] [30139] Received PREPARE: id:1741323218379, from:30151, delay:0.0000s, distance:64.70m (Euclidean)
[2025-03-07 13:53:49,094] [INFO] [30139] Received COMMIT: id:1741323218379, from:30151, delay:0.0000s, distance:64.70m (Euclidean)
[2025-03-07 13:53:49,260] [INFO] [30139] Received PREPARE: id:1741323218379, from:30133, delay:0.0001s, distance:213.99m (Euclidean)
[2025-03-07 13:53:49,260] [INFO] [30139] Received COMMIT: id:1741323218379, from:30133, delay:0.0001s, distance:213.99m (Euclidean)
[2025-03-07 13:53:49,352] [INFO] [30139] Received PREPARE: id:1741323218379, from:30112, delay:0.0001s, distance:198.88m (Euclidean)
[2025-03-07 13:53:49,391] [INFO] [30139] Received COMMIT: id:1741323218379, from:30112, delay:0.0001s, distance:198.88m (Euclidean)
[2025-03-07 13:53:49,522] [INFO] [30139] Received PREPARE: id:1741323218379, from:30144, delay:0.0002s, distance:254.76m (Euclidean)
[2025-03-07 13:53:49,534] [INFO] [30139] Received COMMIT: id:1741323218379, from:30144, delay:0.0002s, distance:254.76m (Euclidean)
[2025-03-07 13:53:50,389] [INFO] [30139] Received PREPARE: id:1741323218379, from:30114, delay:0.0001s, distance:248.92m (Euclidean)
[2025-03-07 13:53:50,389] [INFO] [30139] Received COMMIT: id:1741323218379, from:30114, delay:0.0001s, distance:248.92m (Euclidean)
[2025-03-07 13:53:50,446] [INFO] [30139] Received PREPARE: id:1741323218379, from:30121, delay:0.0000s, distance:70.88m (Euclidean)
[2025-03-07 13:53:50,693] [INFO] [30139] Received PREPARE: id:1741323218379, from:30015, delay:0.0001s, distance:203.31m (Euclidean)
[2025-03-07 13:53:50,693] [INFO] [30139] Received COMMIT: id:1741323218379, from:30015, delay:0.0001s, distance:203.31m (Euclidean)
[2025-03-07 13:53:50,905] [INFO] [30139] Received COMMIT: id:1741323218379, from:30000, delay:0.0001s, distance:205.08m (Euclidean)
[2025-03-07 13:53:51,044] [ERROR] [30139] Error sending to http://localhost:30029/prepare: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30029)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
[2025-03-07 13:53:51,187] [ERROR] [30139] Error sending to http://localhost:30023/prepare: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30023)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
[2025-03-07 13:53:51,298] [INFO] [30139] Received PREPARE: id:1741323218379, from:30130, delay:0.0001s, distance:211.20m (Euclidean)
[2025-03-07 13:53:51,313] [ERROR] [30139] Error sending to http://localhost:30008/commit: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30008, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
[2025-03-07 13:53:51,313] [ERROR] [30139] Error sending to http://localhost:30008/prepare: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30008)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
[2025-03-07 13:53:51,313] [INFO] [30139] Received COMMIT: id:1741323218379, from:30130, delay:0.0001s, distance:211.20m (Euclidean)
[2025-03-07 13:53:51,488] [ERROR] [30139] Error sending to http://localhost:30038/prepare: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('127.0.0.1', 30038)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30038)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('127.0.0.1', 30038)]
[2025-03-07 13:53:51,535] [INFO] [30139] Received PREPARE: id:1741323218379, from:30106, delay:0.0000s, distance:111.67m (Euclidean)
[2025-03-07 13:53:51,678] [ERROR] [30139] Error sending to http://localhost:30027/prepare: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30027)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
[2025-03-07 13:53:51,693] [ERROR] [30139] Error sending to http://localhost:30027/commit: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30027, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
[2025-03-07 13:53:51,725] [ERROR] [30139] Error sending to http://localhost:30038/commit: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('::1', 30038, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30038, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('::1', 30038, 0, 0)]
[2025-03-07 13:53:51,787] [ERROR] [30139] Error sending to http://localhost:30138/prepare: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30138)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
[2025-03-07 13:53:51,803] [ERROR] [30139] Error sending to http://localhost:30029/commit: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30029, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
[2025-03-07 13:53:51,819] [ERROR] [30139] Error sending to http://localhost:30101/prepare: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30101)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
[2025-03-07 13:53:51,882] [INFO] [30139] Received COMMIT: id:1741323218379, from:30121, delay:0.0000s, distance:70.88m (Euclidean)
[2025-03-07 13:53:51,961] [ERROR] [30139] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:53:51,977] [ERROR] [30139] Error sending to http://localhost:30101/commit: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30101, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
[2025-03-07 13:53:52,009] [ERROR] [30139] Error sending to http://localhost:30023/commit: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30023, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
[2025-03-07 13:53:52,009] [INFO] [30139] Received PREPARE: id:1741323218379, from:30116, delay:0.0001s, distance:209.92m (Euclidean)
[2025-03-07 13:53:52,009] [INFO] [30139] Received COMMIT: id:1741323218379, from:30116, delay:0.0001s, distance:209.92m (Euclidean)
[2025-03-07 13:53:52,236] [ERROR] [30139] Error sending to http://localhost:30124/commit: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30124, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
[2025-03-07 13:53:52,236] [ERROR] [30139] Error sending to http://localhost:30063/commit: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30063, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30066/prepare: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30066)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30063/prepare: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30063)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30066/commit: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30066, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30076/commit: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30076, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30138/commit: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30138, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30124/prepare: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
[2025-03-07 13:53:52,244] [ERROR] [30139] Error sending to http://localhost:30076/prepare: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
[2025-03-07 13:53:52,307] [ERROR] [30139] Error sending to http://localhost:30137/prepare: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30137)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
[2025-03-07 13:53:52,307] [ERROR] [30139] Error sending to http://localhost:30137/commit: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30137, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
[2025-03-07 13:53:52,354] [ERROR] [30139] Error sending to http://localhost:30125/commit: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('::1', 30125, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30125, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('::1', 30125, 0, 0)]
[2025-03-07 13:53:52,370] [ERROR] [30139] Error sending to http://localhost:30125/prepare: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('127.0.0.1', 30125)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30125)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('127.0.0.1', 30125)]
[2025-03-07 13:53:52,466] [ERROR] [30139] Error sending to http://localhost:30075/prepare: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30075)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
[2025-03-07 13:53:52,467] [ERROR] [30139] Error sending to http://localhost:30075/commit: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30075, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
[2025-03-07 13:53:52,481] [ERROR] [30139] Error sending to http://localhost:30140/commit: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('::1', 30140, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30140, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('::1', 30140, 0, 0)]
[2025-03-07 13:53:52,497] [ERROR] [30139] Error sending to http://localhost:30140/prepare: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('127.0.0.1', 30140)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30140)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('127.0.0.1', 30140)]
[2025-03-07 13:53:52,597] [INFO] [30139] Received PREPARE: id:1741323218379, from:30118, delay:0.0000s, distance:172.20m (Euclidean)
[2025-03-07 13:53:52,597] [INFO] [30139] Received COMMIT: id:1741323218379, from:30118, delay:0.0000s, distance:172.20m (Euclidean)
[2025-03-07 13:53:52,639] [ERROR] [30139] Error sending to http://localhost:30064/prepare: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30064)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
[2025-03-07 13:53:52,639] [ERROR] [30139] Error sending to http://localhost:30064/commit: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30064, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
[2025-03-07 13:53:52,785] [INFO] [30139] Received PREPARE: id:1741323218379, from:30129, delay:0.0001s, distance:203.48m (Euclidean)
[2025-03-07 13:53:52,785] [INFO] [30139] Received COMMIT: id:1741323218379, from:30129, delay:0.0001s, distance:203.48m (Euclidean)
[2025-03-07 13:53:52,909] [INFO] [30139] Received PREPARE: id:1741323218379, from:30113, delay:0.0000s, distance:155.90m (Euclidean)
[2025-03-07 13:53:53,242] [INFO] [30139] Received COMMIT: id:1741323218379, from:30113, delay:0.0000s, distance:155.90m (Euclidean)
[2025-03-07 13:53:53,543] [INFO] [30139] Received PREPARE: id:1741323218379, from:30155, delay:0.0002s, distance:293.40m (Euclidean)
[2025-03-07 13:53:53,543] [INFO] [30139] Received COMMIT: id:1741323218379, from:30155, delay:0.0002s, distance:293.40m (Euclidean)
[2025-03-07 13:53:53,561] [INFO] [30139] Received PREPARE: id:1741323218379, from:30123, delay:0.0002s, distance:251.51m (Euclidean)
[2025-03-07 13:53:53,565] [INFO] [30139] Received COMMIT: id:1741323218379, from:30123, delay:0.0002s, distance:251.51m (Euclidean)
[2025-03-07 13:53:53,796] [INFO] [30139] Received COMMIT: id:1741323218379, from:30106, delay:0.0000s, distance:111.67m (Euclidean)
[2025-03-07 13:53:53,812] [INFO] [30139] Received PREPARE: id:1741323218379, from:30132, delay:0.0001s, distance:246.44m (Euclidean)
[2025-03-07 13:53:53,894] [INFO] [30139] Received PREPARE: id:1741323218379, from:30127, delay:0.0002s, distance:289.51m (Euclidean)
[2025-03-07 13:53:53,915] [INFO] [30139] Received COMMIT: id:1741323218379, from:30127, delay:0.0002s, distance:289.51m (Euclidean)
[2025-03-07 13:53:53,955] [INFO] [30139] Received PREPARE: id:1741323218379, from:30150, delay:0.0002s, distance:296.51m (Euclidean)
[2025-03-07 13:53:53,955] [INFO] [30139] Received COMMIT: id:1741323218379, from:30150, delay:0.0002s, distance:296.51m (Euclidean)
[2025-03-07 13:53:54,002] [INFO] [30139] Received PREPARE: id:1741323218379, from:30149, delay:0.0000s, distance:106.12m (Euclidean)
[2025-03-07 13:53:54,002] [INFO] [30139] Received COMMIT: id:1741323218379, from:30149, delay:0.0000s, distance:106.12m (Euclidean)
[2025-03-07 13:53:54,182] [INFO] [30139] Received PREPARE: id:1741323218379, from:30159, delay:0.0001s, distance:247.84m (Euclidean)
[2025-03-07 13:53:54,182] [INFO] [30139] Received COMMIT: id:1741323218379, from:30159, delay:0.0001s, distance:247.84m (Euclidean)
[2025-03-07 13:53:54,246] [INFO] [30139] Received PREPARE: id:1741323218379, from:30111, delay:0.0000s, distance:178.80m (Euclidean)
[2025-03-07 13:53:54,246] [INFO] [30139] Received COMMIT: id:1741323218379, from:30111, delay:0.0000s, distance:178.80m (Euclidean)
[2025-03-07 13:53:54,261] [INFO] [30139] Received COMMIT: id:1741323218379, from:30132, delay:0.0001s, distance:246.44m (Euclidean)
[2025-03-07 13:53:54,314] [INFO] [30139] Received PREPARE: id:1741323218379, from:30142, delay:0.0001s, distance:197.98m (Euclidean)
[2025-03-07 13:53:54,334] [INFO] [30139] Received COMMIT: id:1741323218379, from:30142, delay:0.0001s, distance:197.98m (Euclidean)
[2025-03-07 13:53:54,432] [INFO] [30139] Received PREPARE: id:1741323218379, from:30120, delay:0.0001s, distance:222.48m (Euclidean)
[2025-03-07 13:53:54,451] [INFO] [30139] Received PREPARE: id:1741323218379, from:30156, delay:0.0001s, distance:206.90m (Euclidean)
[2025-03-07 13:53:54,475] [INFO] [30139] Received COMMIT: id:1741323218379, from:30120, delay:0.0001s, distance:222.48m (Euclidean)
[2025-03-07 13:53:54,493] [INFO] [30139] Received COMMIT: id:1741323218379, from:30156, delay:0.0001s, distance:206.90m (Euclidean)
[2025-03-07 13:53:54,533] [INFO] [30139] Received PREPARE: id:1741323218379, from:30115, delay:0.0000s, distance:165.08m (Euclidean)
[2025-03-07 13:53:54,598] [INFO] [30139] Received PREPARE: id:1741323218379, from:30152, delay:0.0001s, distance:217.69m (Euclidean)
[2025-03-07 13:53:54,600] [INFO] [30139] Received COMMIT: id:1741323218379, from:30152, delay:0.0001s, distance:217.69m (Euclidean)
[2025-03-07 13:53:54,603] [INFO] [30139] Received COMMIT: id:1741323218379, from:30115, delay:0.0000s, distance:165.08m (Euclidean)
[2025-03-07 13:53:55,660] [INFO] [30139] Received PREPARE: id:1741323218379, from:30022, delay:0.0000s, distance:78.69m (Euclidean)
[2025-03-07 13:53:55,669] [INFO] [30139] Received COMMIT: id:1741323218379, from:30022, delay:0.0000s, distance:78.69m (Euclidean)
[2025-03-07 13:54:55,667] [INFO] Starting node at localhost:30139 | index=140 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:42,119] [INFO] Starting node at localhost:30139 | index=140 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:44,527] [INFO] Starting node at localhost:30139 | index=140 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:03,324] [INFO] [30139] Received PREPARE: id:1741323542381, from:30025, delay:0.0000s, distance:200.66m (Euclidean)
[2025-03-07 13:59:03,324] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,718] [INFO] [30139] Received PREPARE: id:1741323542381, from:30169, delay:0.0000s, distance:73.16m (Euclidean)
[2025-03-07 13:59:03,718] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,033] [INFO] [30139] Received COMMIT: id:1741323542381, from:30025, delay:0.0000s, distance:200.66m (Euclidean)
[2025-03-07 13:59:04,197] [INFO] [30139] Received PREPARE: id:1741323542381, from:30126, delay:0.0000s, distance:133.69m (Euclidean)
[2025-03-07 13:59:04,197] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,197] [INFO] [30139] Received PREPARE: id:1741323542381, from:30154, delay:0.0001s, distance:232.66m (Euclidean)
[2025-03-07 13:59:04,197] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,229] [INFO] [30139] Received PREPARE: id:1741323542381, from:30080, delay:0.0001s, distance:222.94m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,407] [INFO] [30139] Received PREPARE: id:1741323542381, from:30116, delay:0.0000s, distance:69.70m (Euclidean)
[2025-03-07 13:59:04,407] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,407] [INFO] [30139] Received PREPARE: id:1741323542381, from:30168, delay:0.0002s, distance:253.77m (Euclidean)
[2025-03-07 13:59:04,407] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,409] [INFO] [30139] Received COMMIT: id:1741323542381, from:30116, delay:0.0000s, distance:69.70m (Euclidean)
[2025-03-07 13:59:04,543] [INFO] [30139] Received PREPARE: id:1741323542381, from:30013, delay:0.0001s, distance:194.42m (Euclidean)
[2025-03-07 13:59:04,543] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,559] [INFO] [30139] Received COMMIT: id:1741323542381, from:30168, delay:0.0002s, distance:253.77m (Euclidean)
[2025-03-07 13:59:04,626] [INFO] [30139] Received COMMIT: id:1741323542381, from:30080, delay:0.0001s, distance:222.94m (Euclidean)
[2025-03-07 13:59:04,882] [INFO] [30139] Received PREPARE: id:1741323542381, from:30157, delay:0.0001s, distance:241.56m (Euclidean)
[2025-03-07 13:59:04,882] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,884] [INFO] [30139] Received COMMIT: id:1741323542381, from:30157, delay:0.0001s, distance:241.56m (Euclidean)
[2025-03-07 13:59:04,886] [INFO] [30139] Received PREPARE: id:1741323542381, from:30110, delay:0.0000s, distance:172.23m (Euclidean)
[2025-03-07 13:59:04,886] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,943] [INFO] [30139] Received PREPARE: id:1741323542381, from:30127, delay:0.0001s, distance:160.02m (Euclidean)
[2025-03-07 13:59:04,943] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,960] [INFO] [30139] Received COMMIT: id:1741323542381, from:30127, delay:0.0001s, distance:160.02m (Euclidean)
[2025-03-07 13:59:05,056] [INFO] [30139] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:107.73m (Euclidean)
[2025-03-07 13:59:05,056] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,195] [INFO] [30139] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:138.63m (Euclidean)
[2025-03-07 13:59:05,195] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,240] [INFO] [30139] Received COMMIT: id:1741323542381, from:30126, delay:0.0000s, distance:133.69m (Euclidean)
[2025-03-07 13:59:05,242] [INFO] [30139] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:107.73m (Euclidean)
[2025-03-07 13:59:05,243] [INFO] [30139] Received PREPARE: id:1741323542381, from:30124, delay:0.0001s, distance:159.01m (Euclidean)
[2025-03-07 13:59:05,243] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,382] [INFO] [30139] Received PREPARE: id:1741323542381, from:30100, delay:0.0001s, distance:245.56m (Euclidean)
[2025-03-07 13:59:05,382] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,411] [INFO] [30139] Received PREPARE: id:1741323542381, from:30167, delay:0.0002s, distance:287.62m (Euclidean)
[2025-03-07 13:59:05,411] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,442] [INFO] [30139] Received PREPARE: id:1741323542381, from:30057, delay:0.0000s, distance:126.73m (Euclidean)
[2025-03-07 13:59:05,442] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,469] [INFO] [30139] Received COMMIT: id:1741323542381, from:30100, delay:0.0001s, distance:245.56m (Euclidean)
[2025-03-07 13:59:05,509] [INFO] [30139] Received PREPARE: id:1741323542381, from:30005, delay:0.0002s, distance:263.42m (Euclidean)
[2025-03-07 13:59:05,509] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,532] [INFO] [30139] Received COMMIT: id:1741323542381, from:30154, delay:0.0001s, distance:232.66m (Euclidean)
[2025-03-07 13:59:05,612] [INFO] [30139] Received PREPARE: id:1741323542381, from:30037, delay:0.0002s, distance:259.96m (Euclidean)
[2025-03-07 13:59:05,613] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,661] [INFO] [30139] Received COMMIT: id:1741323542381, from:30037, delay:0.0002s, distance:259.96m (Euclidean)
[2025-03-07 13:59:05,683] [INFO] [30139] Received COMMIT: id:1741323542381, from:30005, delay:0.0002s, distance:263.42m (Euclidean)
[2025-03-07 13:59:05,711] [INFO] [30139] Received PREPARE: id:1741323542381, from:30144, delay:0.0002s, distance:252.73m (Euclidean)
[2025-03-07 13:59:05,711] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,712] [INFO] [30139] Received COMMIT: id:1741323542381, from:30144, delay:0.0002s, distance:252.73m (Euclidean)
[2025-03-07 13:59:05,722] [INFO] [30139] Received PREPARE: id:1741323542381, from:30136, delay:0.0001s, distance:245.59m (Euclidean)
[2025-03-07 13:59:05,722] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,778] [INFO] [30139] Received PREPARE: id:1741323542381, from:30035, delay:0.0001s, distance:195.33m (Euclidean)
[2025-03-07 13:59:05,778] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,848] [INFO] [30139] Received COMMIT: id:1741323542381, from:30169, delay:0.0000s, distance:73.16m (Euclidean)
[2025-03-07 13:59:05,938] [INFO] [30139] Received COMMIT: id:1741323542381, from:30035, delay:0.0001s, distance:195.33m (Euclidean)
[2025-03-07 13:59:05,977] [INFO] [30139] Received PREPARE: id:1741323542381, from:30054, delay:0.0000s, distance:147.25m (Euclidean)
[2025-03-07 13:59:05,977] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,179] [INFO] [30139] Received PREPARE: id:1741323542381, from:30199, delay:0.0002s, distance:272.34m (Euclidean)
[2025-03-07 13:59:06,179] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,194] [INFO] [30139] Received PREPARE: id:1741323542381, from:30147, delay:0.0002s, distance:264.20m (Euclidean)
[2025-03-07 13:59:06,194] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,194] [INFO] [30139] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:138.63m (Euclidean)
[2025-03-07 13:59:06,203] [INFO] [30139] Received COMMIT: id:1741323542381, from:30013, delay:0.0001s, distance:194.42m (Euclidean)
[2025-03-07 13:59:06,290] [INFO] [30139] Received PREPARE: id:1741323542381, from:30023, delay:0.0000s, distance:136.93m (Euclidean)
[2025-03-07 13:59:06,290] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,310] [INFO] [30139] Received PREPARE: id:1741323542381, from:30128, delay:0.0002s, distance:273.71m (Euclidean)
[2025-03-07 13:59:06,310] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,361] [INFO] [30139] Received COMMIT: id:1741323542381, from:30147, delay:0.0002s, distance:264.20m (Euclidean)
[2025-03-07 13:59:06,419] [INFO] [30139] Received PREPARE: id:1741323542381, from:30060, delay:0.0001s, distance:195.81m (Euclidean)
[2025-03-07 13:59:06,419] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,484] [INFO] [30139] Received PREPARE: id:1741323542381, from:30196, delay:0.0001s, distance:217.22m (Euclidean)
[2025-03-07 13:59:06,484] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,486] [INFO] [30139] Received COMMIT: id:1741323542381, from:30057, delay:0.0000s, distance:126.73m (Euclidean)
[2025-03-07 13:59:06,578] [INFO] [30139] Received PREPARE: id:1741323542381, from:30093, delay:0.0001s, distance:210.50m (Euclidean)
[2025-03-07 13:59:06,578] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,603] [INFO] [30139] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:81.34m (Euclidean)
[2025-03-07 13:59:06,603] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,627] [INFO] [30139] Received COMMIT: id:1741323542381, from:30093, delay:0.0001s, distance:210.50m (Euclidean)
[2025-03-07 13:59:06,720] [INFO] [30139] Received PREPARE: id:1741323542381, from:30065, delay:0.0001s, distance:236.90m (Euclidean)
[2025-03-07 13:59:06,720] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,821] [INFO] [30139] Received COMMIT: id:1741323542381, from:30128, delay:0.0002s, distance:273.71m (Euclidean)
[2025-03-07 13:59:06,825] [INFO] [30139] Received COMMIT: id:1741323542381, from:30065, delay:0.0001s, distance:236.90m (Euclidean)
[2025-03-07 13:59:06,842] [INFO] [30139] Received PREPARE: id:1741323542381, from:30096, delay:0.0000s, distance:144.32m (Euclidean)
[2025-03-07 13:59:06,842] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,856] [INFO] [30139] Received PREPARE: id:1741323542381, from:30158, delay:0.0001s, distance:206.79m (Euclidean)
[2025-03-07 13:59:06,856] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,910] [INFO] [30139] Received PREPARE: id:1741323542381, from:30085, delay:0.0000s, distance:128.87m (Euclidean)
[2025-03-07 13:59:06,910] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,910] [INFO] [30139] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:81.34m (Euclidean)
[2025-03-07 13:59:07,043] [INFO] [30139] Received COMMIT: id:1741323542381, from:30167, delay:0.0002s, distance:287.62m (Euclidean)
[2025-03-07 13:59:07,105] [INFO] [30139] Received COMMIT: id:1741323542381, from:30196, delay:0.0001s, distance:217.22m (Euclidean)
[2025-03-07 13:59:07,163] [INFO] [30139] Received PREPARE: id:1741323542381, from:30189, delay:0.0002s, distance:250.59m (Euclidean)
[2025-03-07 13:59:07,163] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,202] [INFO] [30139] Received PREPARE: id:1741323542381, from:30107, delay:0.0002s, distance:287.65m (Euclidean)
[2025-03-07 13:59:07,202] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,216] [INFO] [30139] Received COMMIT: id:1741323542381, from:30096, delay:0.0000s, distance:144.32m (Euclidean)
[2025-03-07 13:59:07,309] [INFO] [30139] Received COMMIT: id:1741323542381, from:30060, delay:0.0001s, distance:195.81m (Euclidean)
[2025-03-07 13:59:07,325] [INFO] [30139] Received PREPARE: id:1741323542381, from:30103, delay:0.0000s, distance:196.67m (Euclidean)
[2025-03-07 13:59:07,325] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,467] [INFO] [30139] Received PREPARE: id:1741323542381, from:30174, delay:0.0001s, distance:227.02m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,467] [INFO] [30139] Received PREPARE: id:1741323542381, from:30119, delay:0.0001s, distance:239.23m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,467] [INFO] [30139] Received PREPARE: id:1741323542381, from:30106, delay:0.0001s, distance:184.19m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,467] [INFO] [30139] Received COMMIT: id:1741323542381, from:30106, delay:0.0001s, distance:184.19m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30139] Received COMMIT: id:1741323542381, from:30136, delay:0.0001s, distance:245.59m (Euclidean)
[2025-03-07 13:59:07,516] [INFO] [30139] Received COMMIT: id:1741323542381, from:30199, delay:0.0002s, distance:272.34m (Euclidean)
[2025-03-07 13:59:07,549] [INFO] [30139] Received PREPARE: id:1741323542381, from:30150, delay:0.0000s, distance:173.95m (Euclidean)
[2025-03-07 13:59:07,549] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,557] [INFO] [30139] Received COMMIT: id:1741323542381, from:30110, delay:0.0000s, distance:172.23m (Euclidean)
[2025-03-07 13:59:07,638] [INFO] [30139] Received COMMIT: id:1741323542381, from:30085, delay:0.0000s, distance:128.87m (Euclidean)
[2025-03-07 13:59:07,650] [INFO] [30139] Received COMMIT: id:1741323542381, from:30023, delay:0.0000s, distance:136.93m (Euclidean)
[2025-03-07 13:59:07,795] [INFO] [30139] Received PREPARE: id:1741323542381, from:30133, delay:0.0002s, distance:278.16m (Euclidean)
[2025-03-07 13:59:07,795] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,825] [INFO] [30139] Received PREPARE: id:1741323542381, from:30171, delay:0.0001s, distance:212.21m (Euclidean)
[2025-03-07 13:59:07,825] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,825] [INFO] [30139] Received COMMIT: id:1741323542381, from:30171, delay:0.0001s, distance:212.21m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30139] Received PREPARE: id:1741323542381, from:30028, delay:0.0002s, distance:252.59m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,894] [INFO] [30139] Received COMMIT: id:1741323542381, from:30028, delay:0.0002s, distance:252.59m (Euclidean)
[2025-03-07 13:59:07,935] [INFO] [30139] Received COMMIT: id:1741323542381, from:30107, delay:0.0002s, distance:287.65m (Euclidean)
[2025-03-07 13:59:07,947] [INFO] [30139] Received COMMIT: id:1741323542381, from:30150, delay:0.0000s, distance:173.95m (Euclidean)
[2025-03-07 13:59:07,951] [INFO] [30139] Received COMMIT: id:1741323542381, from:30174, delay:0.0001s, distance:227.02m (Euclidean)
[2025-03-07 13:59:08,025] [INFO] [30139] Received PREPARE: id:1741323542381, from:30059, delay:0.0000s, distance:119.10m (Euclidean)
[2025-03-07 13:59:08,025] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,025] [INFO] [30139] Received COMMIT: id:1741323542381, from:30059, delay:0.0000s, distance:119.10m (Euclidean)
[2025-03-07 13:59:08,040] [INFO] [30139] Received PREPARE: id:1741323542381, from:30190, delay:0.0001s, distance:165.47m (Euclidean)
[2025-03-07 13:59:08,040] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,082] [INFO] [30139] Received PREPARE: id:1741323542381, from:30015, delay:0.0001s, distance:214.34m (Euclidean)
[2025-03-07 13:59:08,082] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,082] [INFO] [30139] Received COMMIT: id:1741323542381, from:30015, delay:0.0001s, distance:214.34m (Euclidean)
[2025-03-07 13:59:08,143] [INFO] [30139] Received PREPARE: id:1741323542381, from:30040, delay:0.0001s, distance:190.88m (Euclidean)
[2025-03-07 13:59:08,143] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,143] [INFO] [30139] Received COMMIT: id:1741323542381, from:30040, delay:0.0001s, distance:190.88m (Euclidean)
[2025-03-07 13:59:08,157] [INFO] [30139] Received COMMIT: id:1741323542381, from:30119, delay:0.0001s, distance:239.23m (Euclidean)
[2025-03-07 13:59:08,195] [INFO] [30139] Received COMMIT: id:1741323542381, from:30189, delay:0.0002s, distance:250.59m (Euclidean)
[2025-03-07 13:59:08,211] [INFO] [30139] Received COMMIT: id:1741323542381, from:30190, delay:0.0001s, distance:165.47m (Euclidean)
[2025-03-07 13:59:08,222] [INFO] [30139] Received COMMIT: id:1741323542381, from:30133, delay:0.0002s, distance:278.16m (Euclidean)
[2025-03-07 13:59:08,329] [INFO] [30139] Received PREPARE: id:1741323542381, from:30118, delay:0.0001s, distance:175.88m (Euclidean)
[2025-03-07 13:59:08,329] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,440] [INFO] [30139] Received COMMIT: id:1741323542381, from:30158, delay:0.0001s, distance:206.79m (Euclidean)
[2025-03-07 13:59:08,440] [INFO] [30139] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:165.91m (Euclidean)
[2025-03-07 13:59:08,440] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,441] [INFO] [30139] Received PREPARE: id:1741323542381, from:30074, delay:0.0002s, distance:263.54m (Euclidean)
[2025-03-07 13:59:08,441] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,441] [INFO] [30139] Received COMMIT: id:1741323542381, from:30118, delay:0.0001s, distance:175.88m (Euclidean)
[2025-03-07 13:59:08,441] [INFO] [30139] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:165.91m (Euclidean)
[2025-03-07 13:59:08,441] [INFO] [30139] Received COMMIT: id:1741323542381, from:30074, delay:0.0002s, distance:263.54m (Euclidean)
[2025-03-07 13:59:08,624] [INFO] [30139] Received COMMIT: id:1741323542381, from:30103, delay:0.0000s, distance:196.67m (Euclidean)
[2025-03-07 13:59:08,624] [INFO] [30139] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:133.44m (Euclidean)
[2025-03-07 13:59:08,624] [INFO] [30139] Received PREPARE: id:1741323542381, from:30109, delay:0.0002s, distance:250.92m (Euclidean)
[2025-03-07 13:59:08,624] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,624] [INFO] [30139] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:133.44m (Euclidean)
[2025-03-07 13:59:08,624] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,626] [INFO] [30139] Received PREPARE: id:1741323542381, from:30062, delay:0.0001s, distance:225.13m (Euclidean)
[2025-03-07 13:59:08,626] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,626] [INFO] [30139] Received COMMIT: id:1741323542381, from:30062, delay:0.0001s, distance:225.13m (Euclidean)
[2025-03-07 13:59:08,657] [INFO] [30139] Received COMMIT: id:1741323542381, from:30054, delay:0.0000s, distance:147.25m (Euclidean)
[2025-03-07 13:59:08,663] [INFO] [30139] Received COMMIT: id:1741323542381, from:30109, delay:0.0002s, distance:250.92m (Euclidean)
[2025-03-07 13:59:08,709] [INFO] [30139] Received PREPARE: id:1741323542381, from:30170, delay:0.0000s, distance:160.14m (Euclidean)
[2025-03-07 13:59:08,711] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,743] [INFO] [30139] Received COMMIT: id:1741323542381, from:30170, delay:0.0000s, distance:160.14m (Euclidean)
[2025-03-07 13:59:08,869] [INFO] [30139] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:155.27m (Euclidean)
[2025-03-07 13:59:08,869] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,869] [INFO] [30139] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:155.27m (Euclidean)
[2025-03-07 13:59:08,879] [INFO] [30139] Received PREPARE: id:1741323542381, from:30182, delay:0.0001s, distance:226.24m (Euclidean)
[2025-03-07 13:59:08,879] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,960] [INFO] [30139] Received PREPARE: id:1741323542381, from:30181, delay:0.0001s, distance:180.07m (Euclidean)
[2025-03-07 13:59:08,960] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,960] [INFO] [30139] Received COMMIT: id:1741323542381, from:30181, delay:0.0001s, distance:180.07m (Euclidean)
[2025-03-07 13:59:08,966] [INFO] [30139] Received PREPARE: id:1741323542381, from:30112, delay:0.0000s, distance:90.59m (Euclidean)
[2025-03-07 13:59:08,966] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,980] [INFO] [30139] Received COMMIT: id:1741323542381, from:30124, delay:0.0001s, distance:159.01m (Euclidean)
[2025-03-07 13:59:09,022] [INFO] [30139] Received PREPARE: id:1741323542381, from:30076, delay:0.0001s, distance:236.17m (Euclidean)
[2025-03-07 13:59:09,022] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,039] [INFO] [30139] Received COMMIT: id:1741323542381, from:30112, delay:0.0000s, distance:90.59m (Euclidean)
[2025-03-07 13:59:09,049] [INFO] [30139] Received COMMIT: id:1741323542381, from:30076, delay:0.0001s, distance:236.17m (Euclidean)
[2025-03-07 13:59:09,120] [INFO] [30139] Received PREPARE: id:1741323542381, from:30066, delay:0.0000s, distance:154.30m (Euclidean)
[2025-03-07 13:59:09,120] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,122] [INFO] [30139] Received COMMIT: id:1741323542381, from:30066, delay:0.0000s, distance:154.30m (Euclidean)
[2025-03-07 13:59:09,144] [INFO] [30139] Received PREPARE: id:1741323542381, from:30063, delay:0.0001s, distance:204.48m (Euclidean)
[2025-03-07 13:59:09,144] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,144] [INFO] [30139] Received COMMIT: id:1741323542381, from:30063, delay:0.0001s, distance:204.48m (Euclidean)
[2025-03-07 13:59:09,220] [INFO] [30139] Received PREPARE: id:1741323542381, from:30121, delay:0.0001s, distance:186.17m (Euclidean)
[2025-03-07 13:59:09,220] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,220] [INFO] [30139] Received COMMIT: id:1741323542381, from:30121, delay:0.0001s, distance:186.17m (Euclidean)
[2025-03-07 13:59:09,320] [INFO] [30139] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:180.52m (Euclidean)
[2025-03-07 13:59:09,320] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,320] [INFO] [30139] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:180.52m (Euclidean)
[2025-03-07 13:59:09,424] [INFO] [30139] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:160.64m (Euclidean)
[2025-03-07 13:59:09,424] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,424] [INFO] [30139] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:160.64m (Euclidean)
[2025-03-07 13:59:09,442] [INFO] [30139] Received PREPARE: id:1741323542381, from:30102, delay:0.0001s, distance:205.62m (Euclidean)
[2025-03-07 13:59:09,444] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,444] [INFO] [30139] Received COMMIT: id:1741323542381, from:30102, delay:0.0001s, distance:205.62m (Euclidean)
[2025-03-07 13:59:09,505] [INFO] [30139] Received PREPARE: id:1741323542381, from:30092, delay:0.0002s, distance:258.49m (Euclidean)
[2025-03-07 13:59:09,505] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,505] [INFO] [30139] Received PREPARE: id:1741323542381, from:30024, delay:0.0002s, distance:252.16m (Euclidean)
[2025-03-07 13:59:09,505] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,506] [INFO] [30139] Received COMMIT: id:1741323542381, from:30024, delay:0.0002s, distance:252.16m (Euclidean)
[2025-03-07 13:59:09,506] [INFO] [30139] Received COMMIT: id:1741323542381, from:30092, delay:0.0002s, distance:258.49m (Euclidean)
[2025-03-07 13:59:09,630] [INFO] [30139] Received PREPARE: id:1741323542381, from:30056, delay:0.0000s, distance:131.03m (Euclidean)
[2025-03-07 13:59:09,630] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,630] [INFO] [30139] Received COMMIT: id:1741323542381, from:30056, delay:0.0000s, distance:131.03m (Euclidean)
[2025-03-07 13:59:09,634] [INFO] [30139] Received COMMIT: id:1741323542381, from:30182, delay:0.0001s, distance:226.24m (Euclidean)
[2025-03-07 13:59:09,736] [INFO] [30139] Received PREPARE: id:1741323542381, from:30180, delay:0.0002s, distance:254.80m (Euclidean)
[2025-03-07 13:59:09,736] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,736] [INFO] [30139] Received PREPARE: id:1741323542381, from:30027, delay:0.0001s, distance:208.84m (Euclidean)
[2025-03-07 13:59:09,736] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,736] [INFO] [30139] Received COMMIT: id:1741323542381, from:30180, delay:0.0002s, distance:254.80m (Euclidean)
[2025-03-07 13:59:09,741] [INFO] [30139] Received COMMIT: id:1741323542381, from:30027, delay:0.0001s, distance:208.84m (Euclidean)
[2025-03-07 13:59:09,741] [INFO] [30139] Received COMMIT: id:1741323542381, from:30046, delay:0.0001s, distance:197.42m (Euclidean)
[2025-03-07 13:59:09,741] [INFO] [30139] Received PREPARE: id:1741323542381, from:30046, delay:0.0001s, distance:197.42m (Euclidean)
[2025-03-07 13:59:09,741] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,759] [INFO] [30139] Received PREPARE: id:1741323542381, from:30191, delay:0.0002s, distance:265.51m (Euclidean)
[2025-03-07 13:59:09,759] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,759] [INFO] [30139] Received COMMIT: id:1741323542381, from:30191, delay:0.0002s, distance:265.51m (Euclidean)
[2025-03-07 13:59:09,901] [INFO] [30139] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:177.07m (Euclidean)
[2025-03-07 13:59:09,901] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,917] [INFO] [30139] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:177.07m (Euclidean)
[2025-03-07 13:59:09,990] [INFO] [30139] Received PREPARE: id:1741323542381, from:30179, delay:0.0001s, distance:237.30m (Euclidean)
[2025-03-07 13:59:09,990] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,990] [INFO] [30139] Received COMMIT: id:1741323542381, from:30179, delay:0.0001s, distance:237.30m (Euclidean)
[2025-03-07 13:59:10,184] [INFO] [30139] Received PREPARE: id:1741323542381, from:30095, delay:0.0000s, distance:133.63m (Euclidean)
[2025-03-07 13:59:10,184] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,194] [INFO] [30139] Received COMMIT: id:1741323542381, from:30095, delay:0.0000s, distance:133.63m (Euclidean)
[2025-03-07 13:59:10,245] [INFO] [30139] Received PREPARE: id:1741323542381, from:30098, delay:0.0000s, distance:139.85m (Euclidean)
[2025-03-07 13:59:10,245] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,247] [INFO] [30139] Received COMMIT: id:1741323542381, from:30098, delay:0.0000s, distance:139.85m (Euclidean)
[2025-03-07 13:59:10,333] [INFO] [30139] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:179.18m (Euclidean)
[2025-03-07 13:59:10,333] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,335] [INFO] [30139] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:179.18m (Euclidean)
[2025-03-07 13:59:10,445] [INFO] [30139] Received PREPARE: id:1741323542381, from:30020, delay:0.0001s, distance:197.40m (Euclidean)
[2025-03-07 13:59:10,445] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,446] [INFO] [30139] Received COMMIT: id:1741323542381, from:30020, delay:0.0001s, distance:197.40m (Euclidean)
[2025-03-07 13:59:10,446] [INFO] [30139] Received COMMIT: id:1741323542381, from:30195, delay:0.0001s, distance:190.39m (Euclidean)
[2025-03-07 13:59:10,446] [INFO] [30139] Received COMMIT: id:1741323542381, from:30120, delay:0.0001s, distance:153.84m (Euclidean)
[2025-03-07 13:59:10,446] [INFO] [30139] Received PREPARE: id:1741323542381, from:30120, delay:0.0001s, distance:153.84m (Euclidean)
[2025-03-07 13:59:10,446] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,448] [INFO] [30139] Received PREPARE: id:1741323542381, from:30115, delay:0.0001s, distance:219.33m (Euclidean)
[2025-03-07 13:59:10,448] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,448] [INFO] [30139] Received PREPARE: id:1741323542381, from:30195, delay:0.0001s, distance:190.39m (Euclidean)
[2025-03-07 13:59:10,448] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,448] [INFO] [30139] Received COMMIT: id:1741323542381, from:30115, delay:0.0001s, distance:219.33m (Euclidean)
[2025-03-07 13:59:10,528] [INFO] [30139] Received PREPARE: id:1741323542381, from:30051, delay:0.0001s, distance:232.86m (Euclidean)
[2025-03-07 13:59:10,528] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,528] [INFO] [30139] Received PREPARE: id:1741323542381, from:30123, delay:0.0000s, distance:131.15m (Euclidean)
[2025-03-07 13:59:10,528] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,528] [INFO] [30139] Received COMMIT: id:1741323542381, from:30123, delay:0.0000s, distance:131.15m (Euclidean)
[2025-03-07 13:59:10,528] [INFO] [30139] Received COMMIT: id:1741323542381, from:30051, delay:0.0001s, distance:232.86m (Euclidean)
[2025-03-07 13:59:10,594] [INFO] [30139] Received PREPARE: id:1741323542381, from:30113, delay:0.0001s, distance:217.73m (Euclidean)
[2025-03-07 13:59:10,594] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,594] [INFO] [30139] Received COMMIT: id:1741323542381, from:30113, delay:0.0001s, distance:217.73m (Euclidean)
[2025-03-07 13:59:10,617] [INFO] [30139] Received PREPARE: id:1741323542381, from:30130, delay:0.0001s, distance:229.83m (Euclidean)
[2025-03-07 13:59:10,617] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,617] [INFO] [30139] Received COMMIT: id:1741323542381, from:30130, delay:0.0001s, distance:229.83m (Euclidean)
[2025-03-07 13:59:10,662] [INFO] [30139] Received PREPARE: id:1741323542381, from:30043, delay:0.0001s, distance:205.83m (Euclidean)
[2025-03-07 13:59:10,662] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,662] [INFO] [30139] Received COMMIT: id:1741323542381, from:30043, delay:0.0001s, distance:205.83m (Euclidean)
[2025-03-07 13:59:10,936] [INFO] [30139] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:187.47m (Euclidean)
[2025-03-07 13:59:10,936] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,936] [INFO] [30139] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:187.47m (Euclidean)
[2025-03-07 13:59:11,362] [INFO] [30139] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:182.23m (Euclidean)
[2025-03-07 13:59:11,362] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,362] [INFO] [30139] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:183.81m (Euclidean)
[2025-03-07 13:59:11,362] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,362] [INFO] [30139] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:183.81m (Euclidean)
[2025-03-07 13:59:11,362] [INFO] [30139] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:182.23m (Euclidean)
[2025-03-07 13:59:11,545] [INFO] [30139] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:170.26m (Euclidean)
[2025-03-07 13:59:11,545] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,545] [INFO] [30139] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:170.26m (Euclidean)
[2025-03-07 13:59:11,585] [INFO] [30139] Received PREPARE: id:1741323542381, from:30089, delay:0.0001s, distance:157.51m (Euclidean)
[2025-03-07 13:59:11,585] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,585] [INFO] [30139] Received PREPARE: id:1741323542381, from:30140, delay:0.0000s, distance:200.82m (Euclidean)
[2025-03-07 13:59:11,585] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,585] [INFO] [30139] Received COMMIT: id:1741323542381, from:30089, delay:0.0001s, distance:157.51m (Euclidean)
[2025-03-07 13:59:11,688] [INFO] [30139] Received PREPARE: id:1741323542381, from:30135, delay:0.0000s, distance:150.74m (Euclidean)
[2025-03-07 13:59:11,688] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,913] [INFO] [30139] Received PREPARE: id:1741323542381, from:30177, delay:0.0002s, distance:261.50m (Euclidean)
[2025-03-07 13:59:11,913] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,913] [INFO] [30139] Received COMMIT: id:1741323542381, from:30177, delay:0.0002s, distance:261.50m (Euclidean)
[2025-03-07 13:59:12,091] [INFO] [30139] Received PREPARE: id:1741323542381, from:30090, delay:0.0000s, distance:174.68m (Euclidean)
[2025-03-07 13:59:12,091] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,091] [INFO] [30139] Received COMMIT: id:1741323542381, from:30090, delay:0.0000s, distance:174.68m (Euclidean)
[2025-03-07 13:59:12,091] [INFO] [30139] Received PREPARE: id:1741323542381, from:30048, delay:0.0001s, distance:201.42m (Euclidean)
[2025-03-07 13:59:12,091] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,091] [INFO] [30139] Received PREPARE: id:1741323542381, from:30070, delay:0.0001s, distance:218.09m (Euclidean)
[2025-03-07 13:59:12,091] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,091] [INFO] [30139] Received COMMIT: id:1741323542381, from:30070, delay:0.0001s, distance:218.09m (Euclidean)
[2025-03-07 13:59:12,091] [INFO] [30139] Received COMMIT: id:1741323542381, from:30048, delay:0.0001s, distance:201.42m (Euclidean)
[2025-03-07 13:59:12,960] [INFO] [30139] Received PREPARE: id:1741323542381, from:30011, delay:0.0000s, distance:177.68m (Euclidean)
[2025-03-07 13:59:12,960] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,960] [INFO] [30139] Received COMMIT: id:1741323542381, from:30011, delay:0.0000s, distance:177.68m (Euclidean)
[2025-03-07 13:59:13,198] [INFO] [30139] Received PREPARE: id:1741323542381, from:30165, delay:0.0000s, distance:98.73m (Euclidean)
[2025-03-07 13:59:13,198] [INFO] [30139] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,200] [INFO] [30139] Received COMMIT: id:1741323542381, from:30165, delay:0.0000s, distance:98.73m (Euclidean)
[2025-03-07 13:59:13,367] [INFO] [30139] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0001s, distance:227.75m (Euclidean)
[2025-03-07 13:59:13,367] [INFO] [30139] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:13,376] [INFO] [30139] Not broadcasting to fault node: 30077
[2025-03-07 13:59:13,386] [INFO] [30139] Not broadcasting to fault node: 30184
[2025-03-07 13:59:13,429] [INFO] [30139] Received COMMIT: id:1741323542381, from:30000, delay:0.0001s, distance:227.75m (Euclidean)
[2025-03-07 13:59:13,545] [INFO] [30139] Received PREPARE: id:1741323542381, from:30010, delay:0.0000s, distance:148.67m (Euclidean)
[2025-03-07 13:59:13,545] [INFO] [30139] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:13,545] [INFO] [30139] Not broadcasting to fault node: 30077
[2025-03-07 13:59:13,559] [INFO] [30139] Not broadcasting to fault node: 30184
[2025-03-07 13:59:13,591] [INFO] [30139] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:99.45m (Euclidean)
[2025-03-07 13:59:13,591] [INFO] [30139] Received COMMIT: id:1741323542381, from:30010, delay:0.0000s, distance:148.67m (Euclidean)
[2025-03-07 13:59:13,814] [INFO] [30139] Received PREPARE: id:1741323542381, from:30069, delay:0.0001s, distance:171.13m (Euclidean)
[2025-03-07 13:59:13,862] [INFO] [30139] Received PREPARE: id:1741323542381, from:30146, delay:0.0001s, distance:187.08m (Euclidean)
[2025-03-07 13:59:14,114] [INFO] [30139] Received COMMIT: id:1741323542381, from:30146, delay:0.0001s, distance:187.08m (Euclidean)
[2025-03-07 13:59:14,397] [INFO] [30139] Received PREPARE: id:1741323542381, from:30137, delay:0.0000s, distance:118.92m (Euclidean)
[2025-03-07 13:59:14,397] [INFO] [30139] Received COMMIT: id:1741323542381, from:30137, delay:0.0000s, distance:118.92m (Euclidean)
[2025-03-07 13:59:14,502] [INFO] [30139] Received PREPARE: id:1741323542381, from:30052, delay:0.0000s, distance:81.82m (Euclidean)
[2025-03-07 13:59:14,666] [INFO] [30139] Received PREPARE: id:1741323542381, from:30187, delay:0.0000s, distance:49.96m (Euclidean)
[2025-03-07 13:59:14,744] [INFO] [30139] Received PREPARE: id:1741323542381, from:30026, delay:0.0002s, distance:274.32m (Euclidean)
[2025-03-07 13:59:14,744] [INFO] [30139] Received COMMIT: id:1741323542381, from:30026, delay:0.0002s, distance:274.32m (Euclidean)
[2025-03-07 13:59:14,750] [INFO] [30139] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:99.45m (Euclidean)
[2025-03-07 13:59:14,750] [INFO] [30139] Received PREPARE: id:1741323542381, from:30193, delay:0.0000s, distance:108.36m (Euclidean)
[2025-03-07 13:59:14,753] [INFO] [30139] Received PREPARE: id:1741323542381, from:30145, delay:0.0001s, distance:183.06m (Euclidean)
[2025-03-07 13:59:14,997] [INFO] [30139] Received PREPARE: id:1741323542381, from:30001, delay:0.0000s, distance:121.44m (Euclidean)
[2025-03-07 13:59:15,011] [INFO] [30139] Received COMMIT: id:1741323542381, from:30140, delay:0.0000s, distance:200.82m (Euclidean)
[2025-03-07 13:59:15,048] [INFO] [30139] Received PREPARE: id:1741323542381, from:30087, delay:0.0000s, distance:130.91m (Euclidean)
[2025-03-07 13:59:15,109] [INFO] [30139] Received COMMIT: id:1741323542381, from:30001, delay:0.0000s, distance:121.44m (Euclidean)
[2025-03-07 13:59:15,282] [INFO] [30139] Received PREPARE: id:1741323542381, from:30117, delay:0.0001s, distance:195.40m (Euclidean)
[2025-03-07 13:59:15,282] [INFO] [30139] Received COMMIT: id:1741323542381, from:30117, delay:0.0001s, distance:195.40m (Euclidean)
[2025-03-07 13:59:15,375] [INFO] [30139] Received PREPARE: id:1741323542381, from:30188, delay:0.0000s, distance:124.74m (Euclidean)
[2025-03-07 13:59:15,385] [INFO] [30139] Received PREPARE: id:1741323542381, from:30033, delay:0.0001s, distance:176.10m (Euclidean)
[2025-03-07 13:59:15,427] [INFO] [30139] Received PREPARE: id:1741323542381, from:30114, delay:0.0000s, distance:120.40m (Euclidean)
[2025-03-07 13:59:15,430] [INFO] [30139] Received COMMIT: id:1741323542381, from:30114, delay:0.0000s, distance:120.40m (Euclidean)
[2025-03-07 13:59:15,513] [INFO] [30139] Received PREPARE: id:1741323542381, from:30091, delay:0.0000s, distance:104.91m (Euclidean)
[2025-03-07 13:59:15,515] [INFO] [30139] Received COMMIT: id:1741323542381, from:30091, delay:0.0000s, distance:104.91m (Euclidean)
[2025-03-07 13:59:15,533] [INFO] [30139] Received PREPARE: id:1741323542381, from:30055, delay:0.0000s, distance:144.36m (Euclidean)
[2025-03-07 13:59:15,533] [INFO] [30139] Received PREPARE: id:1741323542381, from:30088, delay:0.0001s, distance:181.43m (Euclidean)
[2025-03-07 13:59:15,533] [INFO] [30139] Received COMMIT: id:1741323542381, from:30088, delay:0.0001s, distance:181.43m (Euclidean)
[2025-03-07 13:59:15,536] [INFO] [30139] Received COMMIT: id:1741323542381, from:30135, delay:0.0000s, distance:150.74m (Euclidean)
[2025-03-07 13:59:15,565] [INFO] [30139] Received PREPARE: id:1741323542381, from:30067, delay:0.0000s, distance:129.09m (Euclidean)
[2025-03-07 13:59:15,571] [INFO] [30139] Received COMMIT: id:1741323542381, from:30067, delay:0.0000s, distance:129.09m (Euclidean)
[2025-03-07 13:59:15,820] [INFO] [30139] Received COMMIT: id:1741323542381, from:30058, delay:0.0000s, distance:93.37m (Euclidean)
[2025-03-07 13:59:15,820] [INFO] [30139] Received PREPARE: id:1741323542381, from:30058, delay:0.0000s, distance:93.37m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30139] Received PREPARE: id:1741323542381, from:30031, delay:0.0000s, distance:103.71m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30139] Received COMMIT: id:1741323542381, from:30031, delay:0.0000s, distance:103.71m (Euclidean)
[2025-03-07 13:59:15,964] [INFO] [30139] Received COMMIT: id:1741323542381, from:30145, delay:0.0001s, distance:183.06m (Euclidean)
[2025-03-07 13:59:16,047] [INFO] [30139] Received PREPARE: id:1741323542381, from:30079, delay:0.0000s, distance:111.57m (Euclidean)
[2025-03-07 13:59:16,047] [INFO] [30139] Received COMMIT: id:1741323542381, from:30079, delay:0.0000s, distance:111.57m (Euclidean)
[2025-03-07 13:59:16,095] [INFO] [30139] Received COMMIT: id:1741323542381, from:30193, delay:0.0000s, distance:108.36m (Euclidean)
[2025-03-07 13:59:16,196] [INFO] [30139] Received COMMIT: id:1741323542381, from:30052, delay:0.0000s, distance:81.82m (Euclidean)
[2025-03-07 13:59:16,248] [INFO] [30139] Received COMMIT: id:1741323542381, from:30069, delay:0.0001s, distance:171.13m (Euclidean)
[2025-03-07 13:59:16,489] [INFO] [30139] Received PREPARE: id:1741323542381, from:30125, delay:0.0002s, distance:259.06m (Euclidean)
[2025-03-07 13:59:16,509] [INFO] [30139] Received COMMIT: id:1741323542381, from:30087, delay:0.0000s, distance:130.91m (Euclidean)
[2025-03-07 13:59:16,535] [INFO] [30139] Received PREPARE: id:1741323542381, from:30061, delay:0.0000s, distance:123.63m (Euclidean)
[2025-03-07 13:59:16,535] [INFO] [30139] Received COMMIT: id:1741323542381, from:30125, delay:0.0002s, distance:259.06m (Euclidean)
[2025-03-07 13:59:16,535] [INFO] [30139] Received COMMIT: id:1741323542381, from:30061, delay:0.0000s, distance:123.63m (Euclidean)
[2025-03-07 13:59:16,670] [INFO] [30139] Received PREPARE: id:1741323542381, from:30016, delay:0.0001s, distance:209.37m (Euclidean)
[2025-03-07 13:59:16,673] [INFO] [30139] Received COMMIT: id:1741323542381, from:30016, delay:0.0001s, distance:209.37m (Euclidean)
[2025-03-07 13:59:16,721] [INFO] [30139] Received COMMIT: id:1741323542381, from:30055, delay:0.0000s, distance:144.36m (Euclidean)
[2025-03-07 13:59:16,881] [INFO] [30139] Received PREPARE: id:1741323542381, from:30138, delay:0.0000s, distance:94.14m (Euclidean)
[2025-03-07 13:59:16,881] [INFO] [30139] Received COMMIT: id:1741323542381, from:30138, delay:0.0000s, distance:94.14m (Euclidean)
[2025-03-07 13:59:16,948] [INFO] [30139] Received PREPARE: id:1741323542381, from:30081, delay:0.0001s, distance:206.20m (Euclidean)
[2025-03-07 13:59:16,950] [INFO] [30139] Received COMMIT: id:1741323542381, from:30081, delay:0.0001s, distance:206.20m (Euclidean)
[2025-03-07 13:59:17,111] [INFO] [30139] Received PREPARE: id:1741323542381, from:30094, delay:0.0000s, distance:82.73m (Euclidean)
[2025-03-07 13:59:17,117] [INFO] [30139] Received PREPARE: id:1741323542381, from:30039, delay:0.0000s, distance:16.10m (Euclidean)
[2025-03-07 13:59:17,126] [INFO] [30139] Received PREPARE: id:1741323542381, from:30194, delay:0.0001s, distance:182.20m (Euclidean)
[2025-03-07 13:59:17,126] [INFO] [30139] Received COMMIT: id:1741323542381, from:30194, delay:0.0001s, distance:182.20m (Euclidean)
[2025-03-07 13:59:17,140] [INFO] [30139] Received PREPARE: id:1741323542381, from:30160, delay:0.0001s, distance:163.58m (Euclidean)
[2025-03-07 13:59:17,140] [INFO] [30139] Received COMMIT: id:1741323542381, from:30160, delay:0.0001s, distance:163.58m (Euclidean)
[2025-03-07 13:59:17,142] [INFO] [30139] Received COMMIT: id:1741323542381, from:30094, delay:0.0000s, distance:82.73m (Euclidean)
[2025-03-07 13:59:17,313] [INFO] [30139] Received COMMIT: id:1741323542381, from:30033, delay:0.0001s, distance:176.10m (Euclidean)
[2025-03-07 13:59:17,404] [INFO] [30139] Received PREPARE: id:1741323542381, from:30166, delay:0.0000s, distance:49.21m (Euclidean)
[2025-03-07 13:59:17,404] [INFO] [30139] Received COMMIT: id:1741323542381, from:30166, delay:0.0000s, distance:49.21m (Euclidean)
[2025-03-07 13:59:17,447] [INFO] [30139] Received PREPARE: id:1741323542381, from:30042, delay:0.0000s, distance:39.04m (Euclidean)
[2025-03-07 13:59:17,458] [INFO] [30139] Received COMMIT: id:1741323542381, from:30042, delay:0.0000s, distance:39.04m (Euclidean)
[2025-03-07 13:59:17,612] [INFO] [30139] Received PREPARE: id:1741323542381, from:30134, delay:0.0002s, distance:277.82m (Euclidean)
[2025-03-07 13:59:17,618] [INFO] [30139] Received COMMIT: id:1741323542381, from:30134, delay:0.0002s, distance:277.82m (Euclidean)
[2025-03-07 13:59:17,884] [INFO] [30139] Received COMMIT: id:1741323542381, from:30188, delay:0.0000s, distance:124.74m (Euclidean)
[2025-03-07 13:59:18,217] [INFO] [30139] Received PREPARE: id:1741323542381, from:30156, delay:0.0000s, distance:108.72m (Euclidean)
[2025-03-07 13:59:18,217] [INFO] [30139] Received COMMIT: id:1741323542381, from:30156, delay:0.0000s, distance:108.72m (Euclidean)
[2025-03-07 13:59:18,316] [INFO] [30139] Received PREPARE: id:1741323542381, from:30038, delay:0.0000s, distance:145.43m (Euclidean)
[2025-03-07 13:59:18,316] [INFO] [30139] Received COMMIT: id:1741323542381, from:30038, delay:0.0000s, distance:145.43m (Euclidean)
[2025-03-07 13:59:18,471] [INFO] [30139] Received COMMIT: id:1741323542381, from:30039, delay:0.0000s, distance:16.10m (Euclidean)
[2025-03-07 13:59:18,477] [INFO] [30139] Received PREPARE: id:1741323542381, from:30064, delay:0.0001s, distance:187.49m (Euclidean)
[2025-03-07 13:59:18,494] [INFO] [30139] Received COMMIT: id:1741323542381, from:30064, delay:0.0001s, distance:187.49m (Euclidean)
[2025-03-07 13:59:19,445] [INFO] [30139] Received COMMIT: id:1741323542381, from:30071, delay:0.0001s, distance:170.58m (Euclidean)
[2025-03-07 13:59:19,445] [INFO] [30139] Received PREPARE: id:1741323542381, from:30071, delay:0.0001s, distance:170.58m (Euclidean)
[2025-03-07 13:59:20,114] [INFO] [30139] Received PREPARE: id:1741323542381, from:30105, delay:0.0001s, distance:181.59m (Euclidean)
[2025-03-07 13:59:20,114] [INFO] [30139] Received COMMIT: id:1741323542381, from:30105, delay:0.0001s, distance:181.59m (Euclidean)
[2025-03-07 13:59:20,114] [INFO] [30139] Received PREPARE: id:1741323542381, from:30073, delay:0.0001s, distance:154.75m (Euclidean)
[2025-03-07 13:59:20,114] [INFO] [30139] Received COMMIT: id:1741323542381, from:30073, delay:0.0001s, distance:154.75m (Euclidean)
[2025-03-07 13:59:20,184] [INFO] [30139] Received PREPARE: id:1741323542381, from:30198, delay:0.0002s, distance:285.30m (Euclidean)
[2025-03-07 13:59:20,256] [INFO] [30139] Received PREPARE: id:1741323542381, from:30006, delay:0.0000s, distance:129.28m (Euclidean)
[2025-03-07 13:59:20,256] [INFO] [30139] Received COMMIT: id:1741323542381, from:30006, delay:0.0000s, distance:129.28m (Euclidean)
[2025-03-07 13:59:20,287] [INFO] [30139] Received COMMIT: id:1741323542381, from:30198, delay:0.0002s, distance:285.30m (Euclidean)
[2025-03-07 13:59:20,334] [INFO] [30139] Received PREPARE: id:1741323542381, from:30008, delay:0.0000s, distance:65.87m (Euclidean)
[2025-03-07 13:59:20,334] [INFO] [30139] Received COMMIT: id:1741323542381, from:30008, delay:0.0000s, distance:65.87m (Euclidean)
[2025-03-07 13:59:20,395] [INFO] [30139] Received PREPARE: id:1741323542381, from:30019, delay:0.0002s, distance:289.53m (Euclidean)
[2025-03-07 13:59:20,395] [INFO] [30139] Received COMMIT: id:1741323542381, from:30019, delay:0.0002s, distance:289.53m (Euclidean)
[2025-03-07 13:59:20,968] [INFO] [30139] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:165.22m (Euclidean)
[2025-03-07 13:59:20,970] [INFO] [30139] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:165.22m (Euclidean)
[2025-03-07 13:59:21,365] [INFO] [30139] Received PREPARE: id:1741323542381, from:30045, delay:0.0000s, distance:135.01m (Euclidean)
[2025-03-07 13:59:21,367] [INFO] [30139] Received COMMIT: id:1741323542381, from:30045, delay:0.0000s, distance:135.01m (Euclidean)
[2025-03-07 13:59:21,530] [INFO] [30139] Received PREPARE: id:1741323542381, from:30141, delay:0.0001s, distance:221.61m (Euclidean)
[2025-03-07 13:59:21,530] [INFO] [30139] Received COMMIT: id:1741323542381, from:30141, delay:0.0001s, distance:221.61m (Euclidean)
[2025-03-07 13:59:21,564] [INFO] [30139] Received PREPARE: id:1741323542381, from:30050, delay:0.0001s, distance:155.09m (Euclidean)
[2025-03-07 13:59:21,566] [INFO] [30139] Received PREPARE: id:1741323542381, from:30132, delay:0.0000s, distance:92.40m (Euclidean)
[2025-03-07 13:59:21,566] [INFO] [30139] Received PREPARE: id:1741323542381, from:30032, delay:0.0001s, distance:181.11m (Euclidean)
[2025-03-07 13:59:21,566] [INFO] [30139] Received COMMIT: id:1741323542381, from:30032, delay:0.0001s, distance:181.11m (Euclidean)
[2025-03-07 13:59:21,566] [INFO] [30139] Received COMMIT: id:1741323542381, from:30132, delay:0.0000s, distance:92.40m (Euclidean)
[2025-03-07 13:59:21,574] [INFO] [30139] Received COMMIT: id:1741323542381, from:30050, delay:0.0001s, distance:155.09m (Euclidean)
[2025-03-07 13:59:21,706] [INFO] [30139] Received PREPARE: id:1741323542381, from:30017, delay:0.0001s, distance:203.82m (Euclidean)
[2025-03-07 13:59:21,709] [INFO] [30139] Received COMMIT: id:1741323542381, from:30017, delay:0.0001s, distance:203.82m (Euclidean)
[2025-03-07 13:59:21,807] [INFO] [30139] Received PREPARE: id:1741323542381, from:30173, delay:0.0000s, distance:35.23m (Euclidean)
[2025-03-07 13:59:21,820] [INFO] [30139] Received COMMIT: id:1741323542381, from:30173, delay:0.0000s, distance:35.23m (Euclidean)
[2025-03-07 13:59:21,936] [INFO] [30139] Received PREPARE: id:1741323542381, from:30153, delay:0.0001s, distance:225.43m (Euclidean)
[2025-03-07 13:59:21,940] [INFO] [30139] Received COMMIT: id:1741323542381, from:30153, delay:0.0001s, distance:225.43m (Euclidean)
[2025-03-07 13:59:22,008] [INFO] [30139] Received COMMIT: id:1741323542381, from:30187, delay:0.0000s, distance:49.96m (Euclidean)
[2025-03-07 13:59:22,401] [INFO] [30139] Received PREPARE: id:1741323542381, from:30036, delay:0.0000s, distance:108.24m (Euclidean)
[2025-03-07 13:59:22,401] [INFO] [30139] Received COMMIT: id:1741323542381, from:30036, delay:0.0000s, distance:108.24m (Euclidean)
[2025-03-07 13:59:22,496] [INFO] [30139] Received PREPARE: id:1741323542381, from:30131, delay:0.0000s, distance:138.36m (Euclidean)
[2025-03-07 13:59:22,496] [INFO] [30139] Received COMMIT: id:1741323542381, from:30131, delay:0.0000s, distance:138.36m (Euclidean)
[2025-03-07 13:59:22,949] [INFO] [30139] Received PREPARE: id:1741323542381, from:30068, delay:0.0001s, distance:230.85m (Euclidean)
[2025-03-07 13:59:22,949] [INFO] [30139] Received PREPARE: id:1741323542381, from:30162, delay:0.0001s, distance:201.93m (Euclidean)
[2025-03-07 13:59:22,951] [INFO] [30139] Received COMMIT: id:1741323542381, from:30162, delay:0.0001s, distance:201.93m (Euclidean)
[2025-03-07 13:59:22,951] [INFO] [30139] Received COMMIT: id:1741323542381, from:30068, delay:0.0001s, distance:230.85m (Euclidean)
[2025-03-07 13:59:23,575] [INFO] [30139] Received PREPARE: id:1741323542381, from:30022, delay:0.0001s, distance:175.48m (Euclidean)
[2025-03-07 13:59:23,575] [INFO] [30139] Received COMMIT: id:1741323542381, from:30022, delay:0.0001s, distance:175.48m (Euclidean)
[2025-03-07 13:59:23,834] [INFO] [30139] Received PREPARE: id:1741323542381, from:30143, delay:0.0000s, distance:93.91m (Euclidean)
[2025-03-07 13:59:23,834] [INFO] [30139] Received COMMIT: id:1741323542381, from:30143, delay:0.0000s, distance:93.91m (Euclidean)
[2025-03-07 13:59:23,844] [INFO] [30139] Received PREPARE: id:1741323542381, from:30101, delay:0.0001s, distance:229.34m (Euclidean)
[2025-03-07 13:59:23,844] [INFO] [30139] Received COMMIT: id:1741323542381, from:30101, delay:0.0001s, distance:229.34m (Euclidean)
[2025-03-07 13:59:24,529] [INFO] [30139] Received PREPARE: id:1741323542381, from:30122, delay:0.0000s, distance:112.95m (Euclidean)
[2025-03-07 13:59:24,567] [INFO] [30139] Received COMMIT: id:1741323542381, from:30122, delay:0.0000s, distance:112.95m (Euclidean)
[2025-03-07 13:59:25,303] [INFO] [30139] Received PREPARE: id:1741323542381, from:30009, delay:0.0002s, distance:293.75m (Euclidean)
[2025-03-07 13:59:25,303] [INFO] [30139] Received PREPARE: id:1741323542381, from:30185, delay:0.0000s, distance:75.77m (Euclidean)
[2025-03-07 13:59:25,335] [INFO] [30139] Received COMMIT: id:1741323542381, from:30009, delay:0.0002s, distance:293.75m (Euclidean)
[2025-03-07 13:59:25,435] [INFO] [30139] Received PREPARE: id:1741323542381, from:30159, delay:0.0001s, distance:193.63m (Euclidean)
[2025-03-07 13:59:25,438] [INFO] [30139] Received COMMIT: id:1741323542381, from:30159, delay:0.0001s, distance:193.63m (Euclidean)
[2025-03-07 13:59:25,789] [INFO] [30139] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:127.79m (Euclidean)
[2025-03-07 13:59:27,116] [INFO] [30139] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:127.79m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received PREPARE: id:1741323542381, from:30148, delay:0.0001s, distance:178.14m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received PREPARE: id:1741323542381, from:30104, delay:0.0000s, distance:144.86m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received COMMIT: id:1741323542381, from:30014, delay:0.0000s, distance:133.72m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received PREPARE: id:1741323542381, from:30163, delay:0.0000s, distance:73.74m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received COMMIT: id:1741323542381, from:30104, delay:0.0000s, distance:144.86m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received PREPARE: id:1741323542381, from:30083, delay:0.0002s, distance:270.17m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received COMMIT: id:1741323542381, from:30084, delay:0.0000s, distance:129.67m (Euclidean)
[2025-03-07 13:59:27,493] [INFO] [30139] Received PREPARE: id:1741323542381, from:30172, delay:0.0000s, distance:148.67m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received COMMIT: id:1741323542381, from:30083, delay:0.0002s, distance:270.17m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received COMMIT: id:1741323542381, from:30142, delay:0.0000s, distance:133.52m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received PREPARE: id:1741323542381, from:30142, delay:0.0000s, distance:133.52m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received PREPARE: id:1741323542381, from:30084, delay:0.0000s, distance:129.67m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received COMMIT: id:1741323542381, from:30151, delay:0.0000s, distance:75.54m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received COMMIT: id:1741323542381, from:30148, delay:0.0001s, distance:178.14m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received PREPARE: id:1741323542381, from:30082, delay:0.0000s, distance:111.70m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received PREPARE: id:1741323542381, from:30014, delay:0.0000s, distance:133.72m (Euclidean)
[2025-03-07 13:59:27,496] [INFO] [30139] Received PREPARE: id:1741323542381, from:30151, delay:0.0000s, distance:75.54m (Euclidean)
[2025-03-07 13:59:27,560] [INFO] [30139] Received PREPARE: id:1741323542381, from:30047, delay:0.0000s, distance:89.13m (Euclidean)
[2025-03-07 13:59:27,735] [INFO] [30139] Received COMMIT: id:1741323542381, from:30163, delay:0.0000s, distance:73.74m (Euclidean)
[2025-03-07 13:59:27,780] [INFO] [30139] Received PREPARE: id:1741323542381, from:30044, delay:0.0000s, distance:71.74m (Euclidean)
[2025-03-07 13:59:27,856] [INFO] [30139] Received PREPARE: id:1741323542381, from:30075, delay:0.0001s, distance:159.68m (Euclidean)
[2025-03-07 13:59:27,859] [INFO] [30139] Received COMMIT: id:1741323542381, from:30075, delay:0.0001s, distance:159.68m (Euclidean)
[2025-03-07 13:59:27,950] [INFO] [30139] Received PREPARE: id:1741323542381, from:30072, delay:0.0001s, distance:202.30m (Euclidean)
[2025-03-07 13:59:27,951] [INFO] [30139] Received COMMIT: id:1741323542381, from:30072, delay:0.0001s, distance:202.30m (Euclidean)
[2025-03-07 13:59:27,975] [INFO] [30139] Received PREPARE: id:1741323542381, from:30183, delay:0.0001s, distance:174.03m (Euclidean)
[2025-03-07 13:59:27,980] [INFO] [30139] Received COMMIT: id:1741323542381, from:30183, delay:0.0001s, distance:174.03m (Euclidean)
[2025-03-07 13:59:28,087] [INFO] [30139] Received PREPARE: id:1741323542381, from:30152, delay:0.0001s, distance:169.47m (Euclidean)
[2025-03-07 13:59:28,090] [INFO] [30139] Received COMMIT: id:1741323542381, from:30152, delay:0.0001s, distance:169.47m (Euclidean)
[2025-03-07 13:59:28,115] [INFO] [30139] Received COMMIT: id:1741323542381, from:30047, delay:0.0000s, distance:89.13m (Euclidean)
[2025-03-07 13:59:28,152] [INFO] [30139] Received PREPARE: id:1741323542381, from:30018, delay:0.0000s, distance:72.82m (Euclidean)
[2025-03-07 13:59:28,152] [INFO] [30139] Received COMMIT: id:1741323542381, from:30018, delay:0.0000s, distance:72.82m (Euclidean)
[2025-03-07 13:59:28,212] [INFO] [30139] Received PREPARE: id:1741323542381, from:30192, delay:0.0000s, distance:103.61m (Euclidean)
[2025-03-07 13:59:28,213] [INFO] [30139] Received COMMIT: id:1741323542381, from:30192, delay:0.0000s, distance:103.61m (Euclidean)
[2025-03-07 13:59:28,283] [INFO] [30139] Received PREPARE: id:1741323542381, from:30012, delay:0.0001s, distance:190.35m (Euclidean)
[2025-03-07 13:59:28,365] [INFO] [30139] Received PREPARE: id:1741323542381, from:30030, delay:0.0001s, distance:162.18m (Euclidean)
[2025-03-07 13:59:28,365] [INFO] [30139] Received COMMIT: id:1741323542381, from:30012, delay:0.0001s, distance:190.35m (Euclidean)
[2025-03-07 13:59:28,371] [INFO] [30139] Received COMMIT: id:1741323542381, from:30030, delay:0.0001s, distance:162.18m (Euclidean)
[2025-03-07 13:59:28,375] [INFO] [30139] Received COMMIT: id:1741323542381, from:30172, delay:0.0000s, distance:148.67m (Euclidean)
[2025-03-07 13:59:28,589] [INFO] [30139] Received COMMIT: id:1741323542381, from:30044, delay:0.0000s, distance:71.74m (Euclidean)
[2025-03-07 13:59:28,660] [INFO] [30139] Received COMMIT: id:1741323542381, from:30185, delay:0.0000s, distance:75.77m (Euclidean)
[2025-03-07 13:59:28,660] [INFO] [30139] Received PREPARE: id:1741323542381, from:30097, delay:0.0001s, distance:154.39m (Euclidean)
[2025-03-07 13:59:28,810] [INFO] [30139] Received COMMIT: id:1741323542381, from:30082, delay:0.0000s, distance:111.70m (Euclidean)
[2025-03-07 13:59:33,264] [INFO] [30139] Received PREPARE: id:1741323542381, from:30078, delay:0.0001s, distance:151.08m (Euclidean)
[2025-03-07 13:59:33,279] [INFO] [30139] Received COMMIT: id:1741323542381, from:30078, delay:0.0001s, distance:151.08m (Euclidean)
[2025-03-07 13:59:33,295] [INFO] [30139] Received COMMIT: id:1741323542381, from:30097, delay:0.0001s, distance:154.39m (Euclidean)
[2025-03-07 13:59:38,117] [INFO] [30139] Received PREPARE: id:1741323542381, from:30002, delay:0.0001s, distance:226.24m (Euclidean)
[2025-03-07 13:59:38,176] [INFO] [30139] Received COMMIT: id:1741323542381, from:30002, delay:0.0001s, distance:226.24m (Euclidean)
