[2025-03-07 13:50:46,127] [INFO] Starting node at localhost:30103 | index=104 | f=1, k=4 | Role: Replica
[2025-03-07 13:51:29,831] [INFO] Starting node at localhost:30103 | index=104 | f=1, k=4 | Role: Replica
[2025-03-07 13:51:35,467] [INFO] [30103] Received PRE-PREPARE: id:1741323095323, from:Leader(30000), delay:0.0000s, distance:34.66m (Euclidean)
[2025-03-07 13:51:35,467] [INFO] [30103] Broadcasting PREPARE for REQUEST 1741323095323
[2025-03-07 13:51:35,925] [INFO] [30103] Received PREPARE: id:1741323095323, from:30008, delay:0.0000s, distance:150.81m (Euclidean)
[2025-03-07 13:51:35,929] [INFO] [30103] Received PREPARE: id:1741323095323, from:30114, delay:0.0001s, distance:198.40m (Euclidean)
[2025-03-07 13:51:35,929] [INFO] [30103] Broadcasting COMMIT for REQUEST 1741323095323
[2025-03-07 13:51:36,104] [INFO] [30103] Received PREPARE: id:1741323095323, from:30098, delay:0.0001s, distance:160.58m (Euclidean)
[2025-03-07 13:51:36,112] [INFO] [30103] Received PREPARE: id:1741323095323, from:30102, delay:0.0001s, distance:190.86m (Euclidean)
[2025-03-07 13:51:36,112] [INFO] [30103] Received PREPARE: id:1741323095323, from:30110, delay:0.0000s, distance:46.91m (Euclidean)
[2025-03-07 13:51:36,144] [INFO] [30103] Received PREPARE: id:1741323095323, from:30113, delay:0.0000s, distance:130.10m (Euclidean)
[2025-03-07 13:51:36,157] [INFO] [30103] Received PREPARE: id:1741323095323, from:30101, delay:0.0000s, distance:136.32m (Euclidean)
[2025-03-07 13:51:36,169] [INFO] [30103] Received PREPARE: id:1741323095323, from:30053, delay:0.0000s, distance:145.98m (Euclidean)
[2025-03-07 13:51:36,217] [INFO] [30103] Received PREPARE: id:1741323095323, from:30004, delay:0.0000s, distance:86.21m (Euclidean)
[2025-03-07 13:51:36,223] [INFO] [30103] Received COMMIT: id:1741323095323, from:30101, delay:0.0000s, distance:136.32m (Euclidean)
[2025-03-07 13:51:36,232] [INFO] [30103] Received COMMIT: id:1741323095323, from:30102, delay:0.0001s, distance:190.86m (Euclidean)
[2025-03-07 13:51:36,232] [INFO] [LEADER 30103] Sending REPLY for REQUEST 1741323095323 to CLIENT
[2025-03-07 13:51:36,249] [INFO] [30103] Received PREPARE: id:1741323095323, from:30117, delay:0.0001s, distance:193.79m (Euclidean)
[2025-03-07 13:51:36,255] [INFO] [30103] Received PREPARE: id:1741323095323, from:30075, delay:0.0001s, distance:180.68m (Euclidean)
[2025-03-07 13:51:36,255] [INFO] [30103] Received COMMIT: id:1741323095323, from:30075, delay:0.0001s, distance:180.68m (Euclidean)
[2025-03-07 13:51:36,279] [INFO] [30103] Received PREPARE: id:1741323095323, from:30095, delay:0.0000s, distance:143.36m (Euclidean)
[2025-03-07 13:51:36,287] [INFO] [30103] Received PREPARE: id:1741323095323, from:30032, delay:0.0001s, distance:176.44m (Euclidean)
[2025-03-07 13:51:36,287] [INFO] [30103] Received COMMIT: id:1741323095323, from:30117, delay:0.0001s, distance:193.79m (Euclidean)
[2025-03-07 13:51:36,287] [INFO] [30103] Received COMMIT: id:1741323095323, from:30032, delay:0.0001s, distance:176.44m (Euclidean)
[2025-03-07 13:51:36,400] [INFO] [30103] Received PREPARE: id:1741323095323, from:30001, delay:0.0001s, distance:191.51m (Euclidean)
[2025-03-07 13:51:36,405] [INFO] [30103] Received COMMIT: id:1741323095323, from:30008, delay:0.0000s, distance:150.81m (Euclidean)
[2025-03-07 13:51:36,444] [INFO] [30103] Received COMMIT: id:1741323095323, from:30114, delay:0.0001s, distance:198.40m (Euclidean)
[2025-03-07 13:51:36,463] [INFO] [30103] Received PREPARE: id:1741323095323, from:30012, delay:0.0001s, distance:175.25m (Euclidean)
[2025-03-07 13:51:36,504] [INFO] [30103] Received COMMIT: id:1741323095323, from:30098, delay:0.0001s, distance:160.58m (Euclidean)
[2025-03-07 13:51:36,508] [INFO] [30103] Received COMMIT: id:1741323095323, from:30004, delay:0.0000s, distance:86.21m (Euclidean)
[2025-03-07 13:51:36,540] [INFO] [30103] Received PREPARE: id:1741323095323, from:30003, delay:0.0000s, distance:133.89m (Euclidean)
[2025-03-07 13:51:36,543] [INFO] [30103] Received PREPARE: id:1741323095323, from:30005, delay:0.0001s, distance:155.82m (Euclidean)
[2025-03-07 13:51:36,548] [INFO] [30103] Received PREPARE: id:1741323095323, from:30007, delay:0.0000s, distance:84.60m (Euclidean)
[2025-03-07 13:51:36,580] [INFO] [30103] Received PREPARE: id:1741323095323, from:30044, delay:0.0000s, distance:119.09m (Euclidean)
[2025-03-07 13:51:36,630] [INFO] [30103] Received PREPARE: id:1741323095323, from:30021, delay:0.0000s, distance:137.00m (Euclidean)
[2025-03-07 13:51:36,645] [INFO] [30103] Received COMMIT: id:1741323095323, from:30021, delay:0.0000s, distance:137.00m (Euclidean)
[2025-03-07 13:51:36,647] [INFO] [30103] Received PREPARE: id:1741323095323, from:30096, delay:0.0001s, distance:201.45m (Euclidean)
[2025-03-07 13:51:36,656] [INFO] [30103] Received PREPARE: id:1741323095323, from:30015, delay:0.0000s, distance:132.01m (Euclidean)
[2025-03-07 13:51:36,658] [INFO] [30103] Received COMMIT: id:1741323095323, from:30113, delay:0.0000s, distance:130.10m (Euclidean)
[2025-03-07 13:51:36,682] [INFO] [30103] Received PREPARE: id:1741323095323, from:30043, delay:0.0000s, distance:38.32m (Euclidean)
[2025-03-07 13:51:36,733] [INFO] [30103] Received COMMIT: id:1741323095323, from:30096, delay:0.0001s, distance:201.45m (Euclidean)
[2025-03-07 13:51:36,745] [INFO] [30103] Received PREPARE: id:1741323095323, from:30099, delay:0.0000s, distance:119.81m (Euclidean)
[2025-03-07 13:51:36,761] [INFO] [30103] Received COMMIT: id:1741323095323, from:30099, delay:0.0000s, distance:119.81m (Euclidean)
[2025-03-07 13:51:36,761] [INFO] [30103] Received PREPARE: id:1741323095323, from:30092, delay:0.0000s, distance:77.30m (Euclidean)
[2025-03-07 13:51:36,761] [INFO] [30103] Received COMMIT: id:1741323095323, from:30095, delay:0.0000s, distance:143.36m (Euclidean)
[2025-03-07 13:51:36,773] [INFO] [30103] Received COMMIT: id:1741323095323, from:30001, delay:0.0001s, distance:191.51m (Euclidean)
[2025-03-07 13:51:36,773] [INFO] [30103] Received PREPARE: id:1741323095323, from:30109, delay:0.0001s, distance:156.66m (Euclidean)
[2025-03-07 13:51:36,813] [INFO] [30103] Received PREPARE: id:1741323095323, from:30037, delay:0.0000s, distance:121.35m (Euclidean)
[2025-03-07 13:51:36,840] [INFO] [30103] Received COMMIT: id:1741323095323, from:30110, delay:0.0000s, distance:46.91m (Euclidean)
[2025-03-07 13:51:36,842] [INFO] [30103] Received PREPARE: id:1741323095323, from:30024, delay:0.0000s, distance:96.73m (Euclidean)
[2025-03-07 13:51:36,844] [INFO] [30103] Received COMMIT: id:1741323095323, from:30053, delay:0.0000s, distance:145.98m (Euclidean)
[2025-03-07 13:51:36,856] [INFO] [30103] Received COMMIT: id:1741323095323, from:30007, delay:0.0000s, distance:84.60m (Euclidean)
[2025-03-07 13:51:36,871] [INFO] [30103] Received COMMIT: id:1741323095323, from:30012, delay:0.0001s, distance:175.25m (Euclidean)
[2025-03-07 13:51:36,919] [INFO] [30103] Received PREPARE: id:1741323095323, from:30036, delay:0.0000s, distance:68.55m (Euclidean)
[2025-03-07 13:51:36,919] [INFO] [30103] Received COMMIT: id:1741323095323, from:30024, delay:0.0000s, distance:96.73m (Euclidean)
[2025-03-07 13:51:36,926] [INFO] [30103] Received PREPARE: id:1741323095323, from:30028, delay:0.0001s, distance:155.71m (Euclidean)
[2025-03-07 13:51:36,928] [INFO] [30103] Received PREPARE: id:1741323095323, from:30108, delay:0.0000s, distance:118.07m (Euclidean)
[2025-03-07 13:51:36,928] [INFO] [30103] Received COMMIT: id:1741323095323, from:30108, delay:0.0000s, distance:118.07m (Euclidean)
[2025-03-07 13:51:36,937] [INFO] [30103] Received COMMIT: id:1741323095323, from:30028, delay:0.0001s, distance:155.71m (Euclidean)
[2025-03-07 13:51:36,969] [INFO] [30103] Received PREPARE: id:1741323095323, from:30023, delay:0.0000s, distance:56.86m (Euclidean)
[2025-03-07 13:51:36,977] [INFO] [30103] Received COMMIT: id:1741323095323, from:30109, delay:0.0001s, distance:156.66m (Euclidean)
[2025-03-07 13:51:37,004] [INFO] [30103] Received PREPARE: id:1741323095323, from:30013, delay:0.0001s, distance:172.89m (Euclidean)
[2025-03-07 13:51:37,004] [INFO] [30103] Received PREPARE: id:1741323095323, from:30002, delay:0.0000s, distance:72.16m (Euclidean)
[2025-03-07 13:51:37,014] [INFO] [30103] Received COMMIT: id:1741323095323, from:30013, delay:0.0001s, distance:172.89m (Euclidean)
[2025-03-07 13:51:37,019] [INFO] [30103] Received COMMIT: id:1741323095323, from:30044, delay:0.0000s, distance:119.09m (Euclidean)
[2025-03-07 13:51:37,034] [INFO] [30103] Received PREPARE: id:1741323095323, from:30014, delay:0.0000s, distance:115.87m (Euclidean)
[2025-03-07 13:51:37,036] [INFO] [30103] Received COMMIT: id:1741323095323, from:30043, delay:0.0000s, distance:38.32m (Euclidean)
[2025-03-07 13:51:37,062] [INFO] [30103] Received COMMIT: id:1741323095323, from:30005, delay:0.0001s, distance:155.82m (Euclidean)
[2025-03-07 13:51:37,062] [INFO] [30103] Received COMMIT: id:1741323095323, from:30003, delay:0.0000s, distance:133.89m (Euclidean)
[2025-03-07 13:51:37,132] [INFO] [30103] Received PREPARE: id:1741323095323, from:30011, delay:0.0001s, distance:222.69m (Euclidean)
[2025-03-07 13:51:37,132] [INFO] [30103] Received PREPARE: id:1741323095323, from:30078, delay:0.0000s, distance:114.15m (Euclidean)
[2025-03-07 13:51:37,140] [INFO] [30103] Received COMMIT: id:1741323095323, from:30094, delay:0.0001s, distance:162.36m (Euclidean)
[2025-03-07 13:51:37,140] [INFO] [30103] Received COMMIT: id:1741323095323, from:30078, delay:0.0000s, distance:114.15m (Euclidean)
[2025-03-07 13:51:37,140] [INFO] [30103] Received PREPARE: id:1741323095323, from:30094, delay:0.0001s, distance:162.36m (Euclidean)
[2025-03-07 13:51:37,172] [INFO] [30103] Received COMMIT: id:1741323095323, from:30092, delay:0.0000s, distance:77.30m (Euclidean)
[2025-03-07 13:51:37,176] [INFO] [30103] Received PREPARE: id:1741323095323, from:30065, delay:0.0000s, distance:125.56m (Euclidean)
[2025-03-07 13:51:37,178] [INFO] [30103] Received PREPARE: id:1741323095323, from:30116, delay:0.0000s, distance:139.89m (Euclidean)
[2025-03-07 13:51:37,193] [INFO] [30103] Received COMMIT: id:1741323095323, from:30065, delay:0.0000s, distance:125.56m (Euclidean)
[2025-03-07 13:51:37,193] [INFO] [30103] Received COMMIT: id:1741323095323, from:30116, delay:0.0000s, distance:139.89m (Euclidean)
[2025-03-07 13:51:37,222] [INFO] [30103] Received COMMIT: id:1741323095323, from:30014, delay:0.0000s, distance:115.87m (Euclidean)
[2025-03-07 13:51:37,222] [INFO] [30103] Received COMMIT: id:1741323095323, from:30002, delay:0.0000s, distance:72.16m (Euclidean)
[2025-03-07 13:51:37,296] [INFO] [30103] Received PREPARE: id:1741323095323, from:30046, delay:0.0000s, distance:88.18m (Euclidean)
[2025-03-07 13:51:37,299] [INFO] [30103] Received COMMIT: id:1741323095323, from:30015, delay:0.0000s, distance:132.01m (Euclidean)
[2025-03-07 13:51:37,299] [INFO] [30103] Received PREPARE: id:1741323095323, from:30009, delay:0.0000s, distance:93.28m (Euclidean)
[2025-03-07 13:51:37,299] [INFO] [30103] Received COMMIT: id:1741323095323, from:30009, delay:0.0000s, distance:93.28m (Euclidean)
[2025-03-07 13:51:37,325] [INFO] [30103] Received PREPARE: id:1741323095323, from:30088, delay:0.0001s, distance:198.35m (Euclidean)
[2025-03-07 13:51:37,333] [INFO] [30103] Received COMMIT: id:1741323095323, from:30088, delay:0.0001s, distance:198.35m (Euclidean)
[2025-03-07 13:51:37,342] [INFO] [30103] Received PREPARE: id:1741323095323, from:30042, delay:0.0000s, distance:128.89m (Euclidean)
[2025-03-07 13:51:37,355] [INFO] [30103] Received PREPARE: id:1741323095323, from:30033, delay:0.0000s, distance:68.57m (Euclidean)
[2025-03-07 13:51:37,414] [INFO] [30103] Received COMMIT: id:1741323095323, from:30036, delay:0.0000s, distance:68.55m (Euclidean)
[2025-03-07 13:51:37,478] [INFO] [30103] Received COMMIT: id:1741323095323, from:30037, delay:0.0000s, distance:121.35m (Euclidean)
[2025-03-07 13:51:37,494] [INFO] [30103] Received PREPARE: id:1741323095323, from:30107, delay:0.0001s, distance:157.59m (Euclidean)
[2025-03-07 13:51:37,494] [INFO] [30103] Received PREPARE: id:1741323095323, from:30029, delay:0.0001s, distance:151.12m (Euclidean)
[2025-03-07 13:51:37,494] [INFO] [30103] Received COMMIT: id:1741323095323, from:30023, delay:0.0000s, distance:56.86m (Euclidean)
[2025-03-07 13:51:37,494] [INFO] [30103] Received COMMIT: id:1741323095323, from:30029, delay:0.0001s, distance:151.12m (Euclidean)
[2025-03-07 13:51:37,502] [INFO] [30103] Received COMMIT: id:1741323095323, from:30011, delay:0.0001s, distance:222.69m (Euclidean)
[2025-03-07 13:51:37,502] [INFO] [30103] Received COMMIT: id:1741323095323, from:30107, delay:0.0001s, distance:157.59m (Euclidean)
[2025-03-07 13:51:37,516] [INFO] [30103] Received COMMIT: id:1741323095323, from:30111, delay:0.0001s, distance:181.90m (Euclidean)
[2025-03-07 13:51:37,516] [INFO] [30103] Received PREPARE: id:1741323095323, from:30111, delay:0.0001s, distance:181.90m (Euclidean)
[2025-03-07 13:51:37,518] [INFO] [30103] Received COMMIT: id:1741323095323, from:30046, delay:0.0000s, distance:88.18m (Euclidean)
[2025-03-07 13:51:37,582] [INFO] [30103] Received PREPARE: id:1741323095323, from:30104, delay:0.0001s, distance:202.07m (Euclidean)
[2025-03-07 13:51:37,614] [INFO] [30103] Received PREPARE: id:1741323095323, from:30112, delay:0.0000s, distance:42.26m (Euclidean)
[2025-03-07 13:51:37,614] [INFO] [30103] Received COMMIT: id:1741323095323, from:30104, delay:0.0001s, distance:202.07m (Euclidean)
[2025-03-07 13:51:37,621] [INFO] [30103] Received PREPARE: id:1741323095323, from:30025, delay:0.0000s, distance:77.46m (Euclidean)
[2025-03-07 13:51:37,630] [INFO] [30103] Received COMMIT: id:1741323095323, from:30112, delay:0.0000s, distance:42.26m (Euclidean)
[2025-03-07 13:51:37,630] [INFO] [30103] Received PREPARE: id:1741323095323, from:30090, delay:0.0000s, distance:77.40m (Euclidean)
[2025-03-07 13:51:37,639] [INFO] [30103] Received COMMIT: id:1741323095323, from:30090, delay:0.0000s, distance:77.40m (Euclidean)
[2025-03-07 13:51:37,679] [INFO] [30103] Received PREPARE: id:1741323095323, from:30010, delay:0.0001s, distance:224.15m (Euclidean)
[2025-03-07 13:51:37,679] [INFO] [30103] Received COMMIT: id:1741323095323, from:30010, delay:0.0001s, distance:224.15m (Euclidean)
[2025-03-07 13:51:37,700] [INFO] [30103] Received PREPARE: id:1741323095323, from:30050, delay:0.0000s, distance:142.90m (Euclidean)
[2025-03-07 13:51:37,700] [INFO] [30103] Received COMMIT: id:1741323095323, from:30050, delay:0.0000s, distance:142.90m (Euclidean)
[2025-03-07 13:51:37,706] [INFO] [30103] Received COMMIT: id:1741323095323, from:30025, delay:0.0000s, distance:77.46m (Euclidean)
[2025-03-07 13:51:37,740] [INFO] [30103] Received PREPARE: id:1741323095323, from:30022, delay:0.0000s, distance:90.12m (Euclidean)
[2025-03-07 13:51:37,777] [INFO] [30103] Received COMMIT: id:1741323095323, from:30042, delay:0.0000s, distance:128.89m (Euclidean)
[2025-03-07 13:51:37,777] [INFO] [30103] Received PREPARE: id:1741323095323, from:30047, delay:0.0001s, distance:151.29m (Euclidean)
[2025-03-07 13:51:37,777] [INFO] [30103] Received COMMIT: id:1741323095323, from:30047, delay:0.0001s, distance:151.29m (Euclidean)
[2025-03-07 13:51:37,839] [INFO] [30103] Received COMMIT: id:1741323095323, from:30022, delay:0.0000s, distance:90.12m (Euclidean)
[2025-03-07 13:51:37,979] [INFO] [30103] Received COMMIT: id:1741323095323, from:30033, delay:0.0000s, distance:68.57m (Euclidean)
[2025-03-07 13:51:38,001] [INFO] [30103] Received PREPARE: id:1741323095323, from:30097, delay:0.0000s, distance:143.01m (Euclidean)
[2025-03-07 13:51:38,033] [INFO] [30103] Received PREPARE: id:1741323095323, from:30016, delay:0.0001s, distance:221.84m (Euclidean)
[2025-03-07 13:51:38,033] [INFO] [30103] Received PREPARE: id:1741323095323, from:30119, delay:0.0000s, distance:99.54m (Euclidean)
[2025-03-07 13:51:38,054] [INFO] [30103] Received COMMIT: id:1741323095323, from:30119, delay:0.0000s, distance:99.54m (Euclidean)
[2025-03-07 13:51:38,054] [INFO] [30103] Received COMMIT: id:1741323095323, from:30016, delay:0.0001s, distance:221.84m (Euclidean)
[2025-03-07 13:51:38,054] [INFO] [30103] Received COMMIT: id:1741323095323, from:30097, delay:0.0000s, distance:143.01m (Euclidean)
[2025-03-07 13:51:38,054] [INFO] [30103] Received COMMIT: id:1741323095323, from:30031, delay:0.0001s, distance:175.82m (Euclidean)
[2025-03-07 13:51:38,056] [INFO] [30103] Received PREPARE: id:1741323095323, from:30106, delay:0.0001s, distance:155.74m (Euclidean)
[2025-03-07 13:51:38,074] [INFO] [30103] Received PREPARE: id:1741323095323, from:30069, delay:0.0001s, distance:170.76m (Euclidean)
[2025-03-07 13:51:38,074] [INFO] [30103] Received PREPARE: id:1741323095323, from:30079, delay:0.0000s, distance:133.66m (Euclidean)
[2025-03-07 13:51:38,074] [INFO] [30103] Received PREPARE: id:1741323095323, from:30057, delay:0.0000s, distance:107.76m (Euclidean)
[2025-03-07 13:51:38,074] [INFO] [30103] Received PREPARE: id:1741323095323, from:30031, delay:0.0001s, distance:175.82m (Euclidean)
[2025-03-07 13:51:38,088] [INFO] [30103] Received COMMIT: id:1741323095323, from:30057, delay:0.0000s, distance:107.76m (Euclidean)
[2025-03-07 13:51:38,088] [INFO] [30103] Received COMMIT: id:1741323095323, from:30069, delay:0.0001s, distance:170.76m (Euclidean)
[2025-03-07 13:51:38,089] [INFO] [30103] Received COMMIT: id:1741323095323, from:30045, delay:0.0000s, distance:115.67m (Euclidean)
[2025-03-07 13:51:38,089] [INFO] [30103] Received COMMIT: id:1741323095323, from:30079, delay:0.0000s, distance:133.66m (Euclidean)
[2025-03-07 13:51:38,105] [INFO] [30103] Received PREPARE: id:1741323095323, from:30082, delay:0.0001s, distance:190.55m (Euclidean)
[2025-03-07 13:51:38,105] [INFO] [30103] Received PREPARE: id:1741323095323, from:30045, delay:0.0000s, distance:115.67m (Euclidean)
[2025-03-07 13:51:38,105] [INFO] [30103] Received COMMIT: id:1741323095323, from:30082, delay:0.0001s, distance:190.55m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30103] Received COMMIT: id:1741323095323, from:30067, delay:0.0000s, distance:97.96m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30103] Received COMMIT: id:1741323095323, from:30030, delay:0.0000s, distance:74.14m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30103] Received PREPARE: id:1741323095323, from:30030, delay:0.0000s, distance:74.14m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30103] Received PREPARE: id:1741323095323, from:30006, delay:0.0000s, distance:94.00m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30103] Received COMMIT: id:1741323095323, from:30006, delay:0.0000s, distance:94.00m (Euclidean)
[2025-03-07 13:51:38,270] [INFO] [30103] Received PREPARE: id:1741323095323, from:30067, delay:0.0000s, distance:97.96m (Euclidean)
[2025-03-07 13:51:38,294] [INFO] [30103] Received COMMIT: id:1741323095323, from:30056, delay:0.0000s, distance:149.72m (Euclidean)
[2025-03-07 13:51:38,294] [INFO] [30103] Received PREPARE: id:1741323095323, from:30056, delay:0.0000s, distance:149.72m (Euclidean)
[2025-03-07 13:51:38,298] [INFO] [30103] Received PREPARE: id:1741323095323, from:30041, delay:0.0000s, distance:59.45m (Euclidean)
[2025-03-07 13:51:38,373] [INFO] [30103] Received COMMIT: id:1741323095323, from:30040, delay:0.0000s, distance:128.80m (Euclidean)
[2025-03-07 13:51:38,373] [INFO] [30103] Received COMMIT: id:1741323095323, from:30041, delay:0.0000s, distance:59.45m (Euclidean)
[2025-03-07 13:51:38,373] [INFO] [30103] Received PREPARE: id:1741323095323, from:30040, delay:0.0000s, distance:128.80m (Euclidean)
[2025-03-07 13:51:38,419] [INFO] [30103] Received COMMIT: id:1741323095323, from:30106, delay:0.0001s, distance:155.74m (Euclidean)
[2025-03-07 13:51:38,452] [INFO] [30103] Received PREPARE: id:1741323095323, from:30055, delay:0.0000s, distance:149.30m (Euclidean)
[2025-03-07 13:51:38,452] [INFO] [30103] Received COMMIT: id:1741323095323, from:30055, delay:0.0000s, distance:149.30m (Euclidean)
[2025-03-07 13:51:38,573] [INFO] [30103] Received PREPARE: id:1741323095323, from:30084, delay:0.0000s, distance:115.41m (Euclidean)
[2025-03-07 13:51:38,573] [INFO] [30103] Received PREPARE: id:1741323095323, from:30052, delay:0.0000s, distance:160.05m (Euclidean)
[2025-03-07 13:51:38,595] [INFO] [30103] Received COMMIT: id:1741323095323, from:30017, delay:0.0000s, distance:119.63m (Euclidean)
[2025-03-07 13:51:38,595] [INFO] [30103] Received COMMIT: id:1741323095323, from:30052, delay:0.0000s, distance:160.05m (Euclidean)
[2025-03-07 13:51:38,595] [INFO] [30103] Received COMMIT: id:1741323095323, from:30084, delay:0.0000s, distance:115.41m (Euclidean)
[2025-03-07 13:51:38,658] [INFO] [30103] Received PREPARE: id:1741323095323, from:30060, delay:0.0001s, distance:197.62m (Euclidean)
[2025-03-07 13:51:38,658] [INFO] [30103] Received PREPARE: id:1741323095323, from:30017, delay:0.0000s, distance:119.63m (Euclidean)
[2025-03-07 13:51:38,690] [INFO] [30103] Received COMMIT: id:1741323095323, from:30060, delay:0.0001s, distance:197.62m (Euclidean)
[2025-03-07 13:51:38,816] [INFO] [30103] Received PREPARE: id:1741323095323, from:30020, delay:0.0000s, distance:114.37m (Euclidean)
[2025-03-07 13:51:38,816] [INFO] [30103] Received COMMIT: id:1741323095323, from:30020, delay:0.0000s, distance:114.37m (Euclidean)
[2025-03-07 13:51:38,816] [INFO] [30103] Received COMMIT: id:1741323095323, from:30051, delay:0.0000s, distance:125.02m (Euclidean)
[2025-03-07 13:51:38,816] [INFO] [30103] Received PREPARE: id:1741323095323, from:30051, delay:0.0000s, distance:125.02m (Euclidean)
[2025-03-07 13:51:38,928] [INFO] [30103] Received PREPARE: id:1741323095323, from:30054, delay:0.0001s, distance:178.67m (Euclidean)
[2025-03-07 13:51:38,928] [INFO] [30103] Received PREPARE: id:1741323095323, from:30027, delay:0.0001s, distance:163.39m (Euclidean)
[2025-03-07 13:51:38,928] [INFO] [30103] Received COMMIT: id:1741323095323, from:30027, delay:0.0001s, distance:163.39m (Euclidean)
[2025-03-07 13:51:38,931] [INFO] [30103] Received COMMIT: id:1741323095323, from:30054, delay:0.0001s, distance:178.67m (Euclidean)
[2025-03-07 13:51:38,960] [INFO] [30103] Received PREPARE: id:1741323095323, from:30026, delay:0.0001s, distance:173.96m (Euclidean)
[2025-03-07 13:51:38,960] [INFO] [30103] Received COMMIT: id:1741323095323, from:30026, delay:0.0001s, distance:173.96m (Euclidean)
[2025-03-07 13:51:39,166] [INFO] [30103] Received PREPARE: id:1741323095323, from:30019, delay:0.0001s, distance:176.32m (Euclidean)
[2025-03-07 13:51:39,169] [INFO] [30103] Received COMMIT: id:1741323095323, from:30019, delay:0.0001s, distance:176.32m (Euclidean)
[2025-03-07 13:51:39,193] [INFO] [30103] Received PREPARE: id:1741323095323, from:30076, delay:0.0000s, distance:137.11m (Euclidean)
[2025-03-07 13:51:39,193] [INFO] [30103] Received COMMIT: id:1741323095323, from:30076, delay:0.0000s, distance:137.11m (Euclidean)
[2025-03-07 13:51:39,227] [INFO] [30103] Received PREPARE: id:1741323095323, from:30074, delay:0.0001s, distance:191.90m (Euclidean)
[2025-03-07 13:51:39,231] [INFO] [30103] Received COMMIT: id:1741323095323, from:30074, delay:0.0001s, distance:191.90m (Euclidean)
[2025-03-07 13:51:39,514] [INFO] [30103] Received COMMIT: id:1741323095323, from:30000, delay:0.0000s, distance:34.66m (Euclidean)
[2025-03-07 13:51:39,641] [INFO] [30103] Received PREPARE: id:1741323095323, from:30048, delay:0.0001s, distance:209.43m (Euclidean)
[2025-03-07 13:51:39,708] [INFO] [30103] Received PREPARE: id:1741323095323, from:30068, delay:0.0001s, distance:225.84m (Euclidean)
[2025-03-07 13:51:39,720] [INFO] [30103] Received PREPARE: id:1741323095323, from:30018, delay:0.0001s, distance:182.09m (Euclidean)
[2025-03-07 13:51:39,720] [INFO] [30103] Received PREPARE: id:1741323095323, from:30118, delay:0.0001s, distance:224.80m (Euclidean)
[2025-03-07 13:51:39,738] [INFO] [30103] Received PREPARE: id:1741323095323, from:30077, delay:0.0001s, distance:188.28m (Euclidean)
[2025-03-07 13:51:39,769] [INFO] [30103] Received COMMIT: id:1741323095323, from:30048, delay:0.0001s, distance:209.43m (Euclidean)
[2025-03-07 13:51:39,777] [INFO] [30103] Received COMMIT: id:1741323095323, from:30018, delay:0.0001s, distance:182.09m (Euclidean)
[2025-03-07 13:51:39,819] [INFO] [30103] Received COMMIT: id:1741323095323, from:30068, delay:0.0001s, distance:225.84m (Euclidean)
[2025-03-07 13:51:39,885] [INFO] [30103] Received COMMIT: id:1741323095323, from:30077, delay:0.0001s, distance:188.28m (Euclidean)
[2025-03-07 13:51:39,894] [INFO] [30103] Received PREPARE: id:1741323095323, from:30035, delay:0.0001s, distance:194.86m (Euclidean)
[2025-03-07 13:51:39,917] [INFO] [30103] Received COMMIT: id:1741323095323, from:30118, delay:0.0001s, distance:224.80m (Euclidean)
[2025-03-07 13:51:39,955] [INFO] [30103] Received PREPARE: id:1741323095323, from:30066, delay:0.0001s, distance:238.60m (Euclidean)
[2025-03-07 13:51:39,976] [INFO] [30103] Received PREPARE: id:1741323095323, from:30083, delay:0.0001s, distance:195.02m (Euclidean)
[2025-03-07 13:51:39,994] [INFO] [30103] Received COMMIT: id:1741323095323, from:30035, delay:0.0001s, distance:194.86m (Euclidean)
[2025-03-07 13:51:40,041] [INFO] [30103] Received COMMIT: id:1741323095323, from:30066, delay:0.0001s, distance:238.60m (Euclidean)
[2025-03-07 13:51:40,069] [INFO] [30103] Received COMMIT: id:1741323095323, from:30083, delay:0.0001s, distance:195.02m (Euclidean)
[2025-03-07 13:51:40,500] [ERROR] [30103] Error sending to http://localhost:30093/commit: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30093, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
[2025-03-07 13:51:40,546] [ERROR] [30103] Error sending to http://localhost:30091/prepare: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('127.0.0.1', 30091)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('127.0.0.1', 30091)]
[2025-03-07 13:51:40,546] [ERROR] [30103] Error sending to http://localhost:30093/prepare: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30093)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
[2025-03-07 13:51:40,578] [ERROR] [30103] Error sending to http://localhost:30085/prepare: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30085)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
[2025-03-07 13:51:40,643] [ERROR] [30103] Error sending to http://localhost:30081/prepare: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('127.0.0.1', 30081)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30081)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('127.0.0.1', 30081)]
[2025-03-07 13:51:40,770] [ERROR] [30103] Error sending to http://localhost:30091/commit: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('::1', 30091, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30091, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('::1', 30091, 0, 0)]
[2025-03-07 13:51:40,783] [ERROR] [30103] Error sending to http://localhost:30070/prepare: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('127.0.0.1', 30070)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30070)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('127.0.0.1', 30070)]
[2025-03-07 13:51:40,898] [ERROR] [30103] Error sending to http://localhost:30061/prepare: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('127.0.0.1', 30061)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30061)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('127.0.0.1', 30061)]
[2025-03-07 13:51:40,898] [ERROR] [30103] Error sending to http://localhost:30061/commit: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('::1', 30061, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30061, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('::1', 30061, 0, 0)]
[2025-03-07 13:51:40,911] [ERROR] [30103] Error sending to http://localhost:30085/commit: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30085, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
[2025-03-07 13:51:40,911] [ERROR] [30103] Error sending to http://localhost:30058/commit: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('::1', 30058, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30058, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('::1', 30058, 0, 0)]
[2025-03-07 13:51:40,945] [ERROR] [30103] Error sending to http://localhost:30058/prepare: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('127.0.0.1', 30058)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30058)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('127.0.0.1', 30058)]
[2025-03-07 13:51:40,945] [ERROR] [30103] Error sending to http://localhost:30086/commit: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('::1', 30086, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30086, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('::1', 30086, 0, 0)]
[2025-03-07 13:51:40,959] [ERROR] [30103] Error sending to http://localhost:30086/prepare: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('127.0.0.1', 30086)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30086)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('127.0.0.1', 30086)]
[2025-03-07 13:51:40,976] [ERROR] [30103] Error sending to http://localhost:30081/commit: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('::1', 30081, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30081, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('::1', 30081, 0, 0)]
[2025-03-07 13:51:41,088] [ERROR] [30103] Error sending to http://localhost:30070/commit: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('::1', 30070, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30070, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('::1', 30070, 0, 0)]
[2025-03-07 13:51:41,150] [ERROR] [30103] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:51:41,166] [ERROR] [30103] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:51:41,261] [ERROR] [30103] Error sending to http://localhost:30072/commit: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('::1', 30072, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30072, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('::1', 30072, 0, 0)]
[2025-03-07 13:51:41,265] [ERROR] [30103] Error sending to http://localhost:30072/prepare: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('127.0.0.1', 30072)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30072)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('127.0.0.1', 30072)]
[2025-03-07 13:51:41,277] [ERROR] [30103] Error sending to http://localhost:30064/prepare: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30064)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
[2025-03-07 13:51:41,293] [ERROR] [30103] Error sending to http://localhost:30064/commit: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30064, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
[2025-03-07 13:51:41,324] [ERROR] [30103] Error sending to http://localhost:30089/prepare: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('127.0.0.1', 30089)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30089)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('127.0.0.1', 30089)]
[2025-03-07 13:51:41,342] [ERROR] [30103] Error sending to http://localhost:30089/commit: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('::1', 30089, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30089, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('::1', 30089, 0, 0)]
[2025-03-07 13:51:41,372] [INFO] [30103] Received PREPARE: id:1741323095323, from:30034, delay:0.0001s, distance:173.42m (Euclidean)
[2025-03-07 13:51:41,388] [ERROR] [30103] Error sending to http://localhost:30087/prepare: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('127.0.0.1', 30087)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30087)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('127.0.0.1', 30087)]
[2025-03-07 13:51:41,404] [ERROR] [30103] Error sending to http://localhost:30087/commit: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('::1', 30087, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30087, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('::1', 30087, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30103] Error sending to http://localhost:30063/prepare: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30063)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
[2025-03-07 13:51:41,499] [ERROR] [30103] Error sending to http://localhost:30063/commit: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30063, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
[2025-03-07 13:51:41,642] [INFO] [30103] Received PREPARE: id:1741323095323, from:30059, delay:0.0001s, distance:217.00m (Euclidean)
[2025-03-07 13:51:41,690] [ERROR] [30103] Error sending to http://localhost:30073/prepare: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('127.0.0.1', 30073)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30073)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('127.0.0.1', 30073)]
[2025-03-07 13:51:41,690] [ERROR] [30103] Error sending to http://localhost:30073/commit: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('::1', 30073, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30073, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('::1', 30073, 0, 0)]
[2025-03-07 13:51:41,865] [ERROR] [30103] Error sending to http://localhost:30062/prepare: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('127.0.0.1', 30062)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30062)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('127.0.0.1', 30062)]
[2025-03-07 13:51:41,865] [ERROR] [30103] Error sending to http://localhost:30062/commit: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('::1', 30062, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30062, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('::1', 30062, 0, 0)]
[2025-03-07 13:51:41,865] [INFO] [30103] Received PREPARE: id:1741323095323, from:30100, delay:0.0001s, distance:194.87m (Euclidean)
[2025-03-07 13:51:41,907] [INFO] [30103] Received COMMIT: id:1741323095323, from:30034, delay:0.0001s, distance:173.42m (Euclidean)
[2025-03-07 13:51:41,909] [INFO] [30103] Received COMMIT: id:1741323095323, from:30059, delay:0.0001s, distance:217.00m (Euclidean)
[2025-03-07 13:51:42,121] [INFO] [30103] Received PREPARE: id:1741323095323, from:30115, delay:0.0001s, distance:245.66m (Euclidean)
[2025-03-07 13:51:42,153] [INFO] [30103] Received PREPARE: id:1741323095323, from:30038, delay:0.0001s, distance:177.49m (Euclidean)
[2025-03-07 13:51:42,170] [INFO] [30103] Received COMMIT: id:1741323095323, from:30100, delay:0.0001s, distance:194.87m (Euclidean)
[2025-03-07 13:51:42,182] [ERROR] [30103] Error sending to http://localhost:30105/prepare: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('127.0.0.1', 30105)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30105)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('127.0.0.1', 30105)]
[2025-03-07 13:51:42,230] [ERROR] [30103] Error sending to http://localhost:30105/commit: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('::1', 30105, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30105, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('::1', 30105, 0, 0)]
[2025-03-07 13:51:42,326] [INFO] [30103] Received PREPARE: id:1741323095323, from:30080, delay:0.0000s, distance:200.51m (Euclidean)
[2025-03-07 13:51:42,389] [INFO] [30103] Received COMMIT: id:1741323095323, from:30038, delay:0.0001s, distance:177.49m (Euclidean)
[2025-03-07 13:51:42,389] [INFO] [30103] Received COMMIT: id:1741323095323, from:30115, delay:0.0001s, distance:245.66m (Euclidean)
[2025-03-07 13:51:42,436] [INFO] [30103] Received PREPARE: id:1741323095323, from:30049, delay:0.0001s, distance:228.66m (Euclidean)
[2025-03-07 13:51:42,468] [INFO] [30103] Received COMMIT: id:1741323095323, from:30049, delay:0.0001s, distance:228.66m (Euclidean)
[2025-03-07 13:51:42,534] [INFO] [30103] Received PREPARE: id:1741323095323, from:30039, delay:0.0001s, distance:195.00m (Euclidean)
[2025-03-07 13:51:42,548] [INFO] [30103] Received COMMIT: id:1741323095323, from:30080, delay:0.0000s, distance:200.51m (Euclidean)
[2025-03-07 13:51:42,580] [INFO] [30103] Received COMMIT: id:1741323095323, from:30039, delay:0.0001s, distance:195.00m (Euclidean)
[2025-03-07 13:52:35,385] [INFO] Starting node at localhost:30103 | index=104 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:34,888] [INFO] Starting node at localhost:30103 | index=104 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:37,300] [INFO] Starting node at localhost:30103 | index=104 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:02,562] [INFO] [30103] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0000s, distance:60.87m (Euclidean)
[2025-03-07 13:59:02,562] [INFO] [30103] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:02,573] [INFO] [30103] Not broadcasting to fault node: 30077
[2025-03-07 13:59:02,587] [INFO] [30103] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,140] [INFO] [30103] Received PREPARE: id:1741323542381, from:30147, delay:0.0000s, distance:98.04m (Euclidean)
[2025-03-07 13:59:03,197] [INFO] [30103] Received PREPARE: id:1741323542381, from:30177, delay:0.0000s, distance:94.62m (Euclidean)
[2025-03-07 13:59:03,199] [INFO] [30103] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:03,209] [INFO] [30103] Not broadcasting to fault node: 30077
[2025-03-07 13:59:03,261] [INFO] [30103] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,306] [INFO] [30103] Received PREPARE: id:1741323542381, from:30118, delay:0.0000s, distance:150.66m (Euclidean)
[2025-03-07 13:59:03,308] [INFO] [30103] Received PREPARE: id:1741323542381, from:30102, delay:0.0000s, distance:50.35m (Euclidean)
[2025-03-07 13:59:03,402] [INFO] [30103] Received PREPARE: id:1741323542381, from:30195, delay:0.0000s, distance:100.69m (Euclidean)
[2025-03-07 13:59:03,469] [INFO] [30103] Received PREPARE: id:1741323542381, from:30157, delay:0.0000s, distance:135.94m (Euclidean)
[2025-03-07 13:59:03,471] [INFO] [30103] Received PREPARE: id:1741323542381, from:30179, delay:0.0000s, distance:131.98m (Euclidean)
[2025-03-07 13:59:03,728] [INFO] [30103] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:122.03m (Euclidean)
[2025-03-07 13:59:03,730] [INFO] [30103] Received COMMIT: id:1741323542381, from:30179, delay:0.0000s, distance:131.98m (Euclidean)
[2025-03-07 13:59:03,829] [INFO] [30103] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:111.06m (Euclidean)
[2025-03-07 13:59:03,829] [INFO] [30103] Received PREPARE: id:1741323542381, from:30133, delay:0.0000s, distance:144.45m (Euclidean)
[2025-03-07 13:59:03,829] [INFO] [30103] Received PREPARE: id:1741323542381, from:30189, delay:0.0001s, distance:153.35m (Euclidean)
[2025-03-07 13:59:03,829] [INFO] [30103] Received PREPARE: id:1741323542381, from:30113, delay:0.0000s, distance:58.26m (Euclidean)
[2025-03-07 13:59:03,832] [INFO] [30103] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:58.86m (Euclidean)
[2025-03-07 13:59:03,833] [INFO] [30103] Received PREPARE: id:1741323542381, from:30196, delay:0.0000s, distance:135.32m (Euclidean)
[2025-03-07 13:59:03,835] [INFO] [30103] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:70.64m (Euclidean)
[2025-03-07 13:59:03,901] [INFO] [30103] Received PREPARE: id:1741323542381, from:30066, delay:0.0000s, distance:100.34m (Euclidean)
[2025-03-07 13:59:03,915] [INFO] [30103] Received PREPARE: id:1741323542381, from:30065, delay:0.0000s, distance:106.32m (Euclidean)
[2025-03-07 13:59:03,915] [INFO] [30103] Received PREPARE: id:1741323542381, from:30190, delay:0.0001s, distance:190.63m (Euclidean)
[2025-03-07 13:59:03,917] [INFO] [30103] Received PREPARE: id:1741323542381, from:30155, delay:0.0000s, distance:140.38m (Euclidean)
[2025-03-07 13:59:03,917] [INFO] [30103] Received PREPARE: id:1741323542381, from:30095, delay:0.0000s, distance:138.49m (Euclidean)
[2025-03-07 13:59:03,917] [INFO] [30103] Received PREPARE: id:1741323542381, from:30158, delay:0.0000s, distance:95.54m (Euclidean)
[2025-03-07 13:59:03,918] [INFO] [30103] Received PREPARE: id:1741323542381, from:30119, delay:0.0000s, distance:143.72m (Euclidean)
[2025-03-07 13:59:03,918] [INFO] [30103] Received PREPARE: id:1741323542381, from:30136, delay:0.0000s, distance:52.57m (Euclidean)
[2025-03-07 13:59:03,948] [INFO] [30103] Received PREPARE: id:1741323542381, from:30074, delay:0.0000s, distance:105.10m (Euclidean)
[2025-03-07 13:59:03,975] [INFO] [30103] Received COMMIT: id:1741323542381, from:30133, delay:0.0000s, distance:144.45m (Euclidean)
[2025-03-07 13:59:03,975] [INFO] [LEADER 30103] Sending REPLY for REQUEST 1741323542381 to CLIENT
[2025-03-07 13:59:04,026] [INFO] [30103] Received PREPARE: id:1741323542381, from:30124, delay:0.0000s, distance:113.07m (Euclidean)
[2025-03-07 13:59:04,026] [INFO] [30103] Received PREPARE: id:1741323542381, from:30115, delay:0.0000s, distance:117.56m (Euclidean)
[2025-03-07 13:59:04,026] [INFO] [30103] Received PREPARE: id:1741323542381, from:30128, delay:0.0000s, distance:120.93m (Euclidean)
[2025-03-07 13:59:04,028] [INFO] [30103] Received PREPARE: id:1741323542381, from:30109, delay:0.0000s, distance:101.47m (Euclidean)
[2025-03-07 13:59:04,028] [INFO] [30103] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:92.48m (Euclidean)
[2025-03-07 13:59:04,058] [INFO] [30103] Received COMMIT: id:1741323542381, from:30189, delay:0.0001s, distance:153.35m (Euclidean)
[2025-03-07 13:59:04,090] [INFO] [30103] Received PREPARE: id:1741323542381, from:30168, delay:0.0001s, distance:172.82m (Euclidean)
[2025-03-07 13:59:04,103] [INFO] [30103] Received COMMIT: id:1741323542381, from:30147, delay:0.0000s, distance:98.04m (Euclidean)
[2025-03-07 13:59:04,103] [INFO] [30103] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:117.14m (Euclidean)
[2025-03-07 13:59:04,103] [INFO] [30103] Received PREPARE: id:1741323542381, from:30025, delay:0.0000s, distance:136.91m (Euclidean)
[2025-03-07 13:59:04,135] [INFO] [30103] Received PREPARE: id:1741323542381, from:30028, delay:0.0001s, distance:171.98m (Euclidean)
[2025-03-07 13:59:04,135] [INFO] [30103] Received COMMIT: id:1741323542381, from:30118, delay:0.0000s, distance:150.66m (Euclidean)
[2025-03-07 13:59:04,135] [INFO] [30103] Received PREPARE: id:1741323542381, from:30150, delay:0.0000s, distance:59.84m (Euclidean)
[2025-03-07 13:59:04,167] [INFO] [30103] Received COMMIT: id:1741323542381, from:30168, delay:0.0001s, distance:172.82m (Euclidean)
[2025-03-07 13:59:04,167] [INFO] [30103] Received PREPARE: id:1741323542381, from:30144, delay:0.0000s, distance:63.87m (Euclidean)
[2025-03-07 13:59:04,167] [INFO] [30103] Received PREPARE: id:1741323542381, from:30015, delay:0.0000s, distance:64.90m (Euclidean)
[2025-03-07 13:59:04,184] [INFO] [30103] Received PREPARE: id:1741323542381, from:30126, delay:0.0000s, distance:142.91m (Euclidean)
[2025-03-07 13:59:04,202] [INFO] [30103] Received COMMIT: id:1741323542381, from:30124, delay:0.0000s, distance:113.07m (Euclidean)
[2025-03-07 13:59:04,213] [INFO] [30103] Received COMMIT: id:1741323542381, from:30100, delay:0.0000s, distance:102.71m (Euclidean)
[2025-03-07 13:59:04,213] [INFO] [30103] Received PREPARE: id:1741323542381, from:30100, delay:0.0000s, distance:102.71m (Euclidean)
[2025-03-07 13:59:04,225] [INFO] [30103] Received COMMIT: id:1741323542381, from:30115, delay:0.0000s, distance:117.56m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30103] Received COMMIT: id:1741323542381, from:30158, delay:0.0000s, distance:95.54m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30103] Received PREPARE: id:1741323542381, from:30127, delay:0.0001s, distance:173.65m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30103] Received PREPARE: id:1741323542381, from:30170, delay:0.0000s, distance:97.24m (Euclidean)
[2025-03-07 13:59:04,243] [INFO] [30103] Received PREPARE: id:1741323542381, from:30080, delay:0.0001s, distance:189.59m (Euclidean)
[2025-03-07 13:59:04,281] [INFO] [30103] Received COMMIT: id:1741323542381, from:30155, delay:0.0000s, distance:140.38m (Euclidean)
[2025-03-07 13:59:04,333] [INFO] [30103] Received PREPARE: id:1741323542381, from:30037, delay:0.0000s, distance:139.23m (Euclidean)
[2025-03-07 13:59:04,340] [INFO] [30103] Received COMMIT: id:1741323542381, from:30128, delay:0.0000s, distance:120.93m (Euclidean)
[2025-03-07 13:59:04,388] [INFO] [30103] Received PREPARE: id:1741323542381, from:30110, delay:0.0000s, distance:94.03m (Euclidean)
[2025-03-07 13:59:04,388] [INFO] [30103] Received PREPARE: id:1741323542381, from:30182, delay:0.0000s, distance:103.47m (Euclidean)
[2025-03-07 13:59:04,404] [INFO] [30103] Received COMMIT: id:1741323542381, from:30182, delay:0.0000s, distance:103.47m (Euclidean)
[2025-03-07 13:59:04,435] [INFO] [30103] Received PREPARE: id:1741323542381, from:30027, delay:0.0001s, distance:186.51m (Euclidean)
[2025-03-07 13:59:04,445] [INFO] [30103] Received COMMIT: id:1741323542381, from:30126, delay:0.0000s, distance:142.91m (Euclidean)
[2025-03-07 13:59:04,445] [INFO] [30103] Received COMMIT: id:1741323542381, from:30102, delay:0.0000s, distance:50.35m (Euclidean)
[2025-03-07 13:59:04,482] [INFO] [30103] Received PREPARE: id:1741323542381, from:30180, delay:0.0000s, distance:96.87m (Euclidean)
[2025-03-07 13:59:04,501] [INFO] [30103] Received PREPARE: id:1741323542381, from:30035, delay:0.0000s, distance:83.51m (Euclidean)
[2025-03-07 13:59:04,531] [INFO] [30103] Received COMMIT: id:1741323542381, from:30037, delay:0.0000s, distance:139.23m (Euclidean)
[2025-03-07 13:59:04,548] [INFO] [30103] Received COMMIT: id:1741323542381, from:30144, delay:0.0000s, distance:63.87m (Euclidean)
[2025-03-07 13:59:04,612] [INFO] [30103] Received PREPARE: id:1741323542381, from:30063, delay:0.0000s, distance:106.25m (Euclidean)
[2025-03-07 13:59:04,626] [INFO] [30103] Received COMMIT: id:1741323542381, from:30035, delay:0.0000s, distance:83.51m (Euclidean)
[2025-03-07 13:59:04,628] [INFO] [30103] Received PREPARE: id:1741323542381, from:30107, delay:0.0000s, distance:98.60m (Euclidean)
[2025-03-07 13:59:05,060] [INFO] [30103] Received COMMIT: id:1741323542381, from:30025, delay:0.0000s, distance:136.91m (Euclidean)
[2025-03-07 13:59:05,072] [INFO] [30103] Received PREPARE: id:1741323542381, from:30029, delay:0.0001s, distance:187.33m (Euclidean)
[2025-03-07 13:59:05,074] [INFO] [30103] Received COMMIT: id:1741323542381, from:30015, delay:0.0000s, distance:64.90m (Euclidean)
[2025-03-07 13:59:05,076] [INFO] [30103] Received COMMIT: id:1741323542381, from:30127, delay:0.0001s, distance:173.65m (Euclidean)
[2025-03-07 13:59:05,076] [INFO] [30103] Received COMMIT: id:1741323542381, from:30157, delay:0.0000s, distance:135.94m (Euclidean)
[2025-03-07 13:59:05,078] [INFO] [30103] Received PREPARE: id:1741323542381, from:30174, delay:0.0000s, distance:133.78m (Euclidean)
[2025-03-07 13:59:05,078] [INFO] [30103] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:117.82m (Euclidean)
[2025-03-07 13:59:05,078] [INFO] [30103] Received COMMIT: id:1741323542381, from:30195, delay:0.0000s, distance:100.69m (Euclidean)
[2025-03-07 13:59:05,571] [INFO] [30103] Received PREPARE: id:1741323542381, from:30005, delay:0.0000s, distance:118.02m (Euclidean)
[2025-03-07 13:59:05,571] [INFO] [30103] Received PREPARE: id:1741323542381, from:30167, delay:0.0000s, distance:136.11m (Euclidean)
[2025-03-07 13:59:05,571] [INFO] [30103] Received PREPARE: id:1741323542381, from:30085, delay:0.0000s, distance:121.58m (Euclidean)
[2025-03-07 13:59:05,573] [INFO] [30103] Received PREPARE: id:1741323542381, from:30093, delay:0.0000s, distance:134.34m (Euclidean)
[2025-03-07 13:59:05,749] [INFO] [30103] Received COMMIT: id:1741323542381, from:30005, delay:0.0000s, distance:118.02m (Euclidean)
[2025-03-07 13:59:05,756] [INFO] [30103] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:48.53m (Euclidean)
[2025-03-07 13:59:05,767] [INFO] [30103] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:70.64m (Euclidean)
[2025-03-07 13:59:05,767] [INFO] [30103] Received PREPARE: id:1741323542381, from:30116, delay:0.0000s, distance:145.40m (Euclidean)
[2025-03-07 13:59:05,767] [INFO] [30103] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:88.01m (Euclidean)
[2025-03-07 13:59:05,767] [INFO] [30103] Received PREPARE: id:1741323542381, from:30048, delay:0.0000s, distance:17.26m (Euclidean)
[2025-03-07 13:59:05,767] [INFO] [30103] Received COMMIT: id:1741323542381, from:30029, delay:0.0001s, distance:187.33m (Euclidean)
[2025-03-07 13:59:05,767] [INFO] [30103] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:111.06m (Euclidean)
[2025-03-07 13:59:05,772] [INFO] [30103] Received COMMIT: id:1741323542381, from:30170, delay:0.0000s, distance:97.24m (Euclidean)
[2025-03-07 13:59:05,772] [INFO] [30103] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:70.70m (Euclidean)
[2025-03-07 13:59:05,772] [INFO] [30103] Received PREPARE: id:1741323542381, from:30096, delay:0.0000s, distance:120.69m (Euclidean)
[2025-03-07 13:59:05,772] [INFO] [30103] Received COMMIT: id:1741323542381, from:30028, delay:0.0001s, distance:171.98m (Euclidean)
[2025-03-07 13:59:05,774] [INFO] [30103] Received PREPARE: id:1741323542381, from:30181, delay:0.0001s, distance:156.24m (Euclidean)
[2025-03-07 13:59:05,774] [INFO] [30103] Received COMMIT: id:1741323542381, from:30074, delay:0.0000s, distance:105.10m (Euclidean)
[2025-03-07 13:59:06,074] [INFO] [30103] Received PREPARE: id:1741323542381, from:30024, delay:0.0000s, distance:128.60m (Euclidean)
[2025-03-07 13:59:06,074] [INFO] [30103] Received PREPARE: id:1741323542381, from:30089, delay:0.0001s, distance:173.54m (Euclidean)
[2025-03-07 13:59:06,165] [INFO] [30103] Received PREPARE: id:1741323542381, from:30043, delay:0.0000s, distance:80.75m (Euclidean)
[2025-03-07 13:59:06,165] [INFO] [30103] Received PREPARE: id:1741323542381, from:30020, delay:0.0000s, distance:92.49m (Euclidean)
[2025-03-07 13:59:06,168] [INFO] [30103] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:105.10m (Euclidean)
[2025-03-07 13:59:06,168] [INFO] [30103] Received PREPARE: id:1741323542381, from:30013, delay:0.0001s, distance:169.44m (Euclidean)
[2025-03-07 13:59:07,052] [INFO] [30103] Received COMMIT: id:1741323542381, from:30013, delay:0.0001s, distance:169.44m (Euclidean)
[2025-03-07 13:59:07,052] [INFO] [30103] Received COMMIT: id:1741323542381, from:30116, delay:0.0000s, distance:145.40m (Euclidean)
[2025-03-07 13:59:07,052] [INFO] [30103] Received COMMIT: id:1741323542381, from:30065, delay:0.0000s, distance:106.32m (Euclidean)
[2025-03-07 13:59:07,052] [INFO] [30103] Received PREPARE: id:1741323542381, from:30199, delay:0.0001s, distance:158.23m (Euclidean)
[2025-03-07 13:59:07,059] [INFO] [30103] Received PREPARE: id:1741323542381, from:30112, delay:0.0001s, distance:185.58m (Euclidean)
[2025-03-07 13:59:07,182] [INFO] [30103] Received COMMIT: id:1741323542381, from:30190, delay:0.0001s, distance:190.63m (Euclidean)
[2025-03-07 13:59:07,184] [INFO] [30103] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:117.82m (Euclidean)
[2025-03-07 13:59:07,184] [INFO] [30103] Received PREPARE: id:1741323542381, from:30076, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:59:07,184] [INFO] [30103] Received PREPARE: id:1741323542381, from:30051, delay:0.0001s, distance:165.08m (Euclidean)
[2025-03-07 13:59:07,184] [INFO] [30103] Received PREPARE: id:1741323542381, from:30098, delay:0.0000s, distance:118.58m (Euclidean)
[2025-03-07 13:59:07,187] [INFO] [30103] Received PREPARE: id:1741323542381, from:30023, delay:0.0001s, distance:179.01m (Euclidean)
[2025-03-07 13:59:07,187] [INFO] [30103] Received COMMIT: id:1741323542381, from:30023, delay:0.0001s, distance:179.01m (Euclidean)
[2025-03-07 13:59:07,192] [INFO] [30103] Received PREPARE: id:1741323542381, from:30191, delay:0.0000s, distance:99.98m (Euclidean)
[2025-03-07 13:59:07,260] [INFO] [30103] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:64.75m (Euclidean)
[2025-03-07 13:59:07,262] [INFO] [30103] Received COMMIT: id:1741323542381, from:30048, delay:0.0000s, distance:17.26m (Euclidean)
[2025-03-07 13:59:07,262] [INFO] [30103] Received COMMIT: id:1741323542381, from:30027, delay:0.0001s, distance:186.51m (Euclidean)
[2025-03-07 13:59:07,263] [INFO] [30103] Received COMMIT: id:1741323542381, from:30080, delay:0.0001s, distance:189.59m (Euclidean)
[2025-03-07 13:59:07,263] [INFO] [30103] Received COMMIT: id:1741323542381, from:30085, delay:0.0000s, distance:121.58m (Euclidean)
[2025-03-07 13:59:07,263] [INFO] [30103] Received PREPARE: id:1741323542381, from:30092, delay:0.0000s, distance:138.06m (Euclidean)
[2025-03-07 13:59:07,325] [INFO] [30103] Received COMMIT: id:1741323542381, from:30107, delay:0.0000s, distance:98.60m (Euclidean)
[2025-03-07 13:59:07,327] [INFO] [30103] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:92.48m (Euclidean)
[2025-03-07 13:59:07,327] [INFO] [30103] Received COMMIT: id:1741323542381, from:30180, delay:0.0000s, distance:96.87m (Euclidean)
[2025-03-07 13:59:07,327] [INFO] [30103] Received COMMIT: id:1741323542381, from:30113, delay:0.0000s, distance:58.26m (Euclidean)
[2025-03-07 13:59:07,327] [INFO] [30103] Received COMMIT: id:1741323542381, from:30095, delay:0.0000s, distance:138.49m (Euclidean)
[2025-03-07 13:59:07,329] [INFO] [30103] Received COMMIT: id:1741323542381, from:30020, delay:0.0000s, distance:92.49m (Euclidean)
[2025-03-07 13:59:07,329] [INFO] [30103] Received COMMIT: id:1741323542381, from:30167, delay:0.0000s, distance:136.11m (Euclidean)
[2025-03-07 13:59:07,329] [INFO] [30103] Received COMMIT: id:1741323542381, from:30196, delay:0.0000s, distance:135.32m (Euclidean)
[2025-03-07 13:59:07,329] [INFO] [30103] Received COMMIT: id:1741323542381, from:30063, delay:0.0000s, distance:106.25m (Euclidean)
[2025-03-07 13:59:07,329] [INFO] [30103] Received COMMIT: id:1741323542381, from:30066, delay:0.0000s, distance:100.34m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30103] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:105.10m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30103] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:48.53m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30103] Received PREPARE: id:1741323542381, from:30062, delay:0.0000s, distance:121.80m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30103] Received PREPARE: id:1741323542381, from:30169, delay:0.0001s, distance:232.69m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30103] Received COMMIT: id:1741323542381, from:30093, delay:0.0000s, distance:134.34m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30103] Received PREPARE: id:1741323542381, from:30106, delay:0.0001s, distance:193.78m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30103] Received PREPARE: id:1741323542381, from:30070, delay:0.0000s, distance:114.79m (Euclidean)
[2025-03-07 13:59:07,809] [INFO] [30103] Received COMMIT: id:1741323542381, from:30062, delay:0.0000s, distance:121.80m (Euclidean)
[2025-03-07 13:59:07,809] [INFO] [30103] Received COMMIT: id:1741323542381, from:30098, delay:0.0000s, distance:118.58m (Euclidean)
[2025-03-07 13:59:07,809] [INFO] [30103] Received COMMIT: id:1741323542381, from:30106, delay:0.0001s, distance:193.78m (Euclidean)
[2025-03-07 13:59:07,811] [INFO] [30103] Received COMMIT: id:1741323542381, from:30136, delay:0.0000s, distance:52.57m (Euclidean)
[2025-03-07 13:59:07,813] [INFO] [30103] Received COMMIT: id:1741323542381, from:30110, delay:0.0000s, distance:94.03m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30103] Received PREPARE: id:1741323542381, from:30056, delay:0.0000s, distance:110.09m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30103] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:117.14m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30103] Received COMMIT: id:1741323542381, from:30092, delay:0.0000s, distance:138.06m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30103] Received PREPARE: id:1741323542381, from:30060, delay:0.0001s, distance:172.23m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30103] Received COMMIT: id:1741323542381, from:30089, delay:0.0001s, distance:173.54m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30103] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:58.86m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30103] Received PREPARE: id:1741323542381, from:30123, delay:0.0001s, distance:174.61m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30103] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:122.03m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30103] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:88.01m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30103] Received PREPARE: id:1741323542381, from:30120, delay:0.0000s, distance:113.10m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30103] Received COMMIT: id:1741323542381, from:30181, delay:0.0001s, distance:156.24m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30103] Received COMMIT: id:1741323542381, from:30051, delay:0.0001s, distance:165.08m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30103] Received COMMIT: id:1741323542381, from:30056, delay:0.0000s, distance:110.09m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30103] Received COMMIT: id:1741323542381, from:30060, delay:0.0001s, distance:172.23m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30103] Received COMMIT: id:1741323542381, from:30169, delay:0.0001s, distance:232.69m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30103] Received COMMIT: id:1741323542381, from:30150, delay:0.0000s, distance:59.84m (Euclidean)
[2025-03-07 13:59:08,131] [INFO] [30103] Received PREPARE: id:1741323542381, from:30040, delay:0.0001s, distance:167.42m (Euclidean)
[2025-03-07 13:59:08,131] [INFO] [30103] Received PREPARE: id:1741323542381, from:30046, delay:0.0000s, distance:122.76m (Euclidean)
[2025-03-07 13:59:08,341] [INFO] [30103] Received COMMIT: id:1741323542381, from:30046, delay:0.0000s, distance:122.76m (Euclidean)
[2025-03-07 13:59:08,341] [INFO] [30103] Received COMMIT: id:1741323542381, from:30123, delay:0.0001s, distance:174.61m (Euclidean)
[2025-03-07 13:59:08,347] [INFO] [30103] Received COMMIT: id:1741323542381, from:30070, delay:0.0000s, distance:114.79m (Euclidean)
[2025-03-07 13:59:08,356] [INFO] [30103] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:64.75m (Euclidean)
[2025-03-07 13:59:08,358] [INFO] [30103] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:70.70m (Euclidean)
[2025-03-07 13:59:08,358] [INFO] [30103] Received COMMIT: id:1741323542381, from:30119, delay:0.0000s, distance:143.72m (Euclidean)
[2025-03-07 13:59:08,358] [INFO] [30103] Received COMMIT: id:1741323542381, from:30199, delay:0.0001s, distance:158.23m (Euclidean)
[2025-03-07 13:59:08,436] [INFO] [30103] Received COMMIT: id:1741323542381, from:30096, delay:0.0000s, distance:120.69m (Euclidean)
[2025-03-07 13:59:08,436] [INFO] [30103] Received COMMIT: id:1741323542381, from:30040, delay:0.0001s, distance:167.42m (Euclidean)
[2025-03-07 13:59:08,477] [INFO] [30103] Received COMMIT: id:1741323542381, from:30109, delay:0.0000s, distance:101.47m (Euclidean)
[2025-03-07 13:59:08,483] [INFO] [30103] Received COMMIT: id:1741323542381, from:30191, delay:0.0000s, distance:99.98m (Euclidean)
[2025-03-07 13:59:08,496] [INFO] [30103] Received COMMIT: id:1741323542381, from:30054, delay:0.0001s, distance:167.04m (Euclidean)
[2025-03-07 13:59:08,496] [INFO] [30103] Received PREPARE: id:1741323542381, from:30054, delay:0.0001s, distance:167.04m (Euclidean)
[2025-03-07 13:59:08,523] [INFO] [30103] Received COMMIT: id:1741323542381, from:30112, delay:0.0001s, distance:185.58m (Euclidean)
[2025-03-07 13:59:08,543] [INFO] [30103] Received COMMIT: id:1741323542381, from:30011, delay:0.0000s, distance:84.39m (Euclidean)
[2025-03-07 13:59:08,543] [INFO] [30103] Received PREPARE: id:1741323542381, from:30090, delay:0.0000s, distance:70.16m (Euclidean)
[2025-03-07 13:59:08,543] [INFO] [30103] Received COMMIT: id:1741323542381, from:30090, delay:0.0000s, distance:70.16m (Euclidean)
[2025-03-07 13:59:08,543] [INFO] [30103] Received PREPARE: id:1741323542381, from:30011, delay:0.0000s, distance:84.39m (Euclidean)
[2025-03-07 13:59:08,593] [INFO] [30103] Received COMMIT: id:1741323542381, from:30120, delay:0.0000s, distance:113.10m (Euclidean)
[2025-03-07 13:59:08,653] [INFO] [30103] Received PREPARE: id:1741323542381, from:30171, delay:0.0000s, distance:119.42m (Euclidean)
[2025-03-07 13:59:08,671] [INFO] [30103] Received COMMIT: id:1741323542381, from:30171, delay:0.0000s, distance:119.42m (Euclidean)
[2025-03-07 13:59:08,673] [INFO] [30103] Received COMMIT: id:1741323542381, from:30076, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:59:08,771] [INFO] [30103] Received COMMIT: id:1741323542381, from:30177, delay:0.0000s, distance:94.62m (Euclidean)
[2025-03-07 13:59:08,798] [INFO] [30103] Received COMMIT: id:1741323542381, from:30174, delay:0.0000s, distance:133.78m (Euclidean)
[2025-03-07 13:59:08,895] [INFO] [30103] Received COMMIT: id:1741323542381, from:30043, delay:0.0000s, distance:80.75m (Euclidean)
[2025-03-07 13:59:08,897] [INFO] [30103] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:105.68m (Euclidean)
[2025-03-07 13:59:08,897] [INFO] [30103] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:105.68m (Euclidean)
[2025-03-07 13:59:09,190] [INFO] [30103] Received COMMIT: id:1741323542381, from:30024, delay:0.0000s, distance:128.60m (Euclidean)
[2025-03-07 13:59:09,783] [INFO] [30103] Received PREPARE: id:1741323542381, from:30154, delay:0.0000s, distance:62.17m (Euclidean)
[2025-03-07 13:59:09,788] [INFO] [30103] Received COMMIT: id:1741323542381, from:30154, delay:0.0000s, distance:62.17m (Euclidean)
[2025-03-07 13:59:10,524] [INFO] [30103] Received PREPARE: id:1741323542381, from:30121, delay:0.0001s, distance:153.61m (Euclidean)
[2025-03-07 13:59:10,524] [INFO] [30103] Received COMMIT: id:1741323542381, from:30121, delay:0.0001s, distance:153.61m (Euclidean)
[2025-03-07 13:59:11,023] [INFO] [30103] Received PREPARE: id:1741323542381, from:30130, delay:0.0001s, distance:166.41m (Euclidean)
[2025-03-07 13:59:11,025] [INFO] [30103] Received COMMIT: id:1741323542381, from:30130, delay:0.0001s, distance:166.41m (Euclidean)
[2025-03-07 13:59:11,096] [INFO] [30103] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:115.87m (Euclidean)
[2025-03-07 13:59:11,096] [INFO] [30103] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:115.87m (Euclidean)
[2025-03-07 13:59:12,054] [INFO] [30103] Received PREPARE: id:1741323542381, from:30059, delay:0.0000s, distance:135.13m (Euclidean)
[2025-03-07 13:59:12,069] [INFO] [30103] Received COMMIT: id:1741323542381, from:30059, delay:0.0000s, distance:135.13m (Euclidean)
[2025-03-07 13:59:12,255] [INFO] [30103] Received PREPARE: id:1741323542381, from:30057, delay:0.0001s, distance:184.46m (Euclidean)
[2025-03-07 13:59:12,255] [INFO] [30103] Received COMMIT: id:1741323542381, from:30057, delay:0.0001s, distance:184.46m (Euclidean)
[2025-03-07 13:59:12,717] [INFO] [30103] Received PREPARE: id:1741323542381, from:30194, delay:0.0000s, distance:108.17m (Euclidean)
[2025-03-07 13:59:12,856] [INFO] [30103] Received PREPARE: id:1741323542381, from:30086, delay:0.0000s, distance:139.40m (Euclidean)
[2025-03-07 13:59:12,992] [INFO] [30103] Received PREPARE: id:1741323542381, from:30134, delay:0.0001s, distance:170.63m (Euclidean)
[2025-03-07 13:59:13,000] [INFO] [30103] Received PREPARE: id:1741323542381, from:30003, delay:0.0000s, distance:150.43m (Euclidean)
[2025-03-07 13:59:13,042] [INFO] [30103] Received COMMIT: id:1741323542381, from:30086, delay:0.0000s, distance:139.40m (Euclidean)
[2025-03-07 13:59:13,527] [INFO] [30103] Received PREPARE: id:1741323542381, from:30006, delay:0.0001s, distance:206.05m (Euclidean)
[2025-03-07 13:59:13,611] [INFO] [30103] Received PREPARE: id:1741323542381, from:30026, delay:0.0001s, distance:213.16m (Euclidean)
[2025-03-07 13:59:13,611] [INFO] [30103] Received COMMIT: id:1741323542381, from:30026, delay:0.0001s, distance:213.16m (Euclidean)
[2025-03-07 13:59:13,749] [INFO] [30103] Received COMMIT: id:1741323542381, from:30134, delay:0.0001s, distance:170.63m (Euclidean)
[2025-03-07 13:59:13,875] [INFO] [30103] Received PREPARE: id:1741323542381, from:30135, delay:0.0001s, distance:219.56m (Euclidean)
[2025-03-07 13:59:14,042] [INFO] [30103] Received COMMIT: id:1741323542381, from:30000, delay:0.0000s, distance:60.87m (Euclidean)
[2025-03-07 13:59:14,069] [INFO] [30103] Received PREPARE: id:1741323542381, from:30064, delay:0.0001s, distance:174.09m (Euclidean)
[2025-03-07 13:59:14,144] [INFO] [30103] Received PREPARE: id:1741323542381, from:30153, delay:0.0000s, distance:99.59m (Euclidean)
[2025-03-07 13:59:14,286] [INFO] [30103] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:135.66m (Euclidean)
[2025-03-07 13:59:14,306] [INFO] [30103] Received PREPARE: id:1741323542381, from:30091, delay:0.0000s, distance:137.85m (Euclidean)
[2025-03-07 13:59:14,306] [INFO] [30103] Received PREPARE: id:1741323542381, from:30061, delay:0.0001s, distance:202.91m (Euclidean)
[2025-03-07 13:59:14,324] [INFO] [30103] Received COMMIT: id:1741323542381, from:30061, delay:0.0001s, distance:202.91m (Euclidean)
[2025-03-07 13:59:14,648] [INFO] [30103] Received PREPARE: id:1741323542381, from:30165, delay:0.0001s, distance:240.13m (Euclidean)
[2025-03-07 13:59:14,652] [INFO] [30103] Received COMMIT: id:1741323542381, from:30165, delay:0.0001s, distance:240.13m (Euclidean)
[2025-03-07 13:59:14,753] [INFO] [30103] Received PREPARE: id:1741323542381, from:30088, delay:0.0001s, distance:176.16m (Euclidean)
[2025-03-07 13:59:14,768] [INFO] [30103] Received PREPARE: id:1741323542381, from:30117, delay:0.0001s, distance:177.47m (Euclidean)
[2025-03-07 13:59:14,799] [INFO] [30103] Received COMMIT: id:1741323542381, from:30194, delay:0.0000s, distance:108.17m (Euclidean)
[2025-03-07 13:59:14,807] [INFO] [30103] Received PREPARE: id:1741323542381, from:30198, delay:0.0001s, distance:203.09m (Euclidean)
[2025-03-07 13:59:14,807] [INFO] [30103] Received COMMIT: id:1741323542381, from:30198, delay:0.0001s, distance:203.09m (Euclidean)
[2025-03-07 13:59:14,839] [INFO] [30103] Received PREPARE: id:1741323542381, from:30146, delay:0.0001s, distance:220.70m (Euclidean)
[2025-03-07 13:59:14,839] [INFO] [30103] Received COMMIT: id:1741323542381, from:30146, delay:0.0001s, distance:220.70m (Euclidean)
[2025-03-07 13:59:14,885] [INFO] [30103] Received PREPARE: id:1741323542381, from:30069, delay:0.0001s, distance:234.13m (Euclidean)
[2025-03-07 13:59:14,902] [INFO] [30103] Received PREPARE: id:1741323542381, from:30140, delay:0.0000s, distance:126.29m (Euclidean)
[2025-03-07 13:59:14,904] [INFO] [30103] Received COMMIT: id:1741323542381, from:30140, delay:0.0000s, distance:126.29m (Euclidean)
[2025-03-07 13:59:14,926] [INFO] [30103] Received PREPARE: id:1741323542381, from:30081, delay:0.0000s, distance:145.54m (Euclidean)
[2025-03-07 13:59:15,011] [INFO] [30103] Received PREPARE: id:1741323542381, from:30068, delay:0.0000s, distance:103.82m (Euclidean)
[2025-03-07 13:59:15,011] [INFO] [30103] Received COMMIT: id:1741323542381, from:30068, delay:0.0000s, distance:103.82m (Euclidean)
[2025-03-07 13:59:15,248] [INFO] [30103] Received PREPARE: id:1741323542381, from:30141, delay:0.0000s, distance:134.36m (Euclidean)
[2025-03-07 13:59:15,485] [INFO] [30103] Received COMMIT: id:1741323542381, from:30153, delay:0.0000s, distance:99.59m (Euclidean)
[2025-03-07 13:59:15,485] [INFO] [30103] Received PREPARE: id:1741323542381, from:30032, delay:0.0001s, distance:222.90m (Euclidean)
[2025-03-07 13:59:15,485] [INFO] [30103] Received COMMIT: id:1741323542381, from:30032, delay:0.0001s, distance:222.90m (Euclidean)
[2025-03-07 13:59:15,501] [INFO] [30103] Received PREPARE: id:1741323542381, from:30010, delay:0.0001s, distance:221.14m (Euclidean)
[2025-03-07 13:59:15,596] [INFO] [30103] Received PREPARE: id:1741323542381, from:30132, delay:0.0001s, distance:222.21m (Euclidean)
[2025-03-07 13:59:15,596] [INFO] [30103] Received COMMIT: id:1741323542381, from:30132, delay:0.0001s, distance:222.21m (Euclidean)
[2025-03-07 13:59:15,659] [INFO] [30103] Received PREPARE: id:1741323542381, from:30188, delay:0.0001s, distance:152.22m (Euclidean)
[2025-03-07 13:59:15,663] [INFO] [30103] Received COMMIT: id:1741323542381, from:30188, delay:0.0001s, distance:152.22m (Euclidean)
[2025-03-07 13:59:15,746] [INFO] [30103] Received COMMIT: id:1741323542381, from:30135, delay:0.0001s, distance:219.56m (Euclidean)
[2025-03-07 13:59:15,820] [INFO] [30103] Received PREPARE: id:1741323542381, from:30160, delay:0.0001s, distance:153.20m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30103] Received PREPARE: id:1741323542381, from:30033, delay:0.0001s, distance:160.03m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30103] Received COMMIT: id:1741323542381, from:30033, delay:0.0001s, distance:160.03m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30103] Received PREPARE: id:1741323542381, from:30055, delay:0.0001s, distance:189.36m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30103] Received PREPARE: id:1741323542381, from:30131, delay:0.0000s, distance:148.56m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30103] Received PREPARE: id:1741323542381, from:30071, delay:0.0001s, distance:212.10m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30103] Received COMMIT: id:1741323542381, from:30055, delay:0.0001s, distance:189.36m (Euclidean)
[2025-03-07 13:59:15,929] [INFO] [30103] Received COMMIT: id:1741323542381, from:30071, delay:0.0001s, distance:212.10m (Euclidean)
[2025-03-07 13:59:15,977] [INFO] [30103] Received COMMIT: id:1741323542381, from:30010, delay:0.0001s, distance:221.14m (Euclidean)
[2025-03-07 13:59:16,102] [INFO] [30103] Received PREPARE: id:1741323542381, from:30016, delay:0.0001s, distance:193.98m (Euclidean)
[2025-03-07 13:59:16,144] [INFO] [30103] Received COMMIT: id:1741323542381, from:30141, delay:0.0000s, distance:134.36m (Euclidean)
[2025-03-07 13:59:16,601] [INFO] [30103] Received PREPARE: id:1741323542381, from:30105, delay:0.0001s, distance:231.91m (Euclidean)
[2025-03-07 13:59:16,622] [INFO] [30103] Received PREPARE: id:1741323542381, from:30151, delay:0.0000s, distance:141.70m (Euclidean)
[2025-03-07 13:59:16,675] [INFO] [30103] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:135.66m (Euclidean)
[2025-03-07 13:59:16,703] [INFO] [30103] Received PREPARE: id:1741323542381, from:30017, delay:0.0000s, distance:116.87m (Euclidean)
[2025-03-07 13:59:16,839] [INFO] [30103] Received PREPARE: id:1741323542381, from:30145, delay:0.0001s, distance:222.31m (Euclidean)
[2025-03-07 13:59:16,860] [INFO] [30103] Received PREPARE: id:1741323542381, from:30042, delay:0.0000s, distance:170.45m (Euclidean)
[2025-03-07 13:59:16,959] [INFO] [30103] Received COMMIT: id:1741323542381, from:30016, delay:0.0001s, distance:193.98m (Euclidean)
[2025-03-07 13:59:17,043] [INFO] [30103] Received PREPARE: id:1741323542381, from:30159, delay:0.0000s, distance:114.59m (Euclidean)
[2025-03-07 13:59:17,043] [INFO] [30103] Received COMMIT: id:1741323542381, from:30159, delay:0.0000s, distance:114.59m (Euclidean)
[2025-03-07 13:59:17,101] [INFO] [30103] Received PREPARE: id:1741323542381, from:30197, delay:0.0001s, distance:162.10m (Euclidean)
[2025-03-07 13:59:17,186] [INFO] [30103] Received PREPARE: id:1741323542381, from:30125, delay:0.0001s, distance:169.24m (Euclidean)
[2025-03-07 13:59:17,188] [INFO] [30103] Received COMMIT: id:1741323542381, from:30125, delay:0.0001s, distance:169.24m (Euclidean)
[2025-03-07 13:59:17,221] [INFO] [30103] Received COMMIT: id:1741323542381, from:30131, delay:0.0000s, distance:148.56m (Euclidean)
[2025-03-07 13:59:17,229] [INFO] [30103] Received COMMIT: id:1741323542381, from:30006, delay:0.0001s, distance:206.05m (Euclidean)
[2025-03-07 13:59:17,271] [INFO] [30103] Received COMMIT: id:1741323542381, from:30160, delay:0.0001s, distance:153.20m (Euclidean)
[2025-03-07 13:59:17,319] [INFO] [30103] Received PREPARE: id:1741323542381, from:30114, delay:0.0002s, distance:257.27m (Euclidean)
[2025-03-07 13:59:17,319] [INFO] [30103] Received COMMIT: id:1741323542381, from:30114, delay:0.0002s, distance:257.27m (Euclidean)
[2025-03-07 13:59:17,328] [INFO] [30103] Received PREPARE: id:1741323542381, from:30067, delay:0.0001s, distance:220.01m (Euclidean)
[2025-03-07 13:59:17,348] [INFO] [30103] Received COMMIT: id:1741323542381, from:30067, delay:0.0001s, distance:220.01m (Euclidean)
[2025-03-07 13:59:17,381] [INFO] [30103] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:195.59m (Euclidean)
[2025-03-07 13:59:17,511] [INFO] [30103] Received COMMIT: id:1741323542381, from:30069, delay:0.0001s, distance:234.13m (Euclidean)
[2025-03-07 13:59:17,521] [INFO] [30103] Received PREPARE: id:1741323542381, from:30122, delay:0.0002s, distance:250.46m (Euclidean)
[2025-03-07 13:59:17,537] [INFO] [30103] Received COMMIT: id:1741323542381, from:30122, delay:0.0002s, distance:250.46m (Euclidean)
[2025-03-07 13:59:17,546] [INFO] [30103] Received PREPARE: id:1741323542381, from:30193, delay:0.0001s, distance:177.01m (Euclidean)
[2025-03-07 13:59:17,553] [INFO] [30103] Received COMMIT: id:1741323542381, from:30193, delay:0.0001s, distance:177.01m (Euclidean)
[2025-03-07 13:59:17,604] [INFO] [30103] Received COMMIT: id:1741323542381, from:30003, delay:0.0000s, distance:150.43m (Euclidean)
[2025-03-07 13:59:17,651] [INFO] [30103] Received COMMIT: id:1741323542381, from:30117, delay:0.0001s, distance:177.47m (Euclidean)
[2025-03-07 13:59:17,697] [INFO] [30103] Received COMMIT: id:1741323542381, from:30088, delay:0.0001s, distance:176.16m (Euclidean)
[2025-03-07 13:59:17,859] [INFO] [30103] Received COMMIT: id:1741323542381, from:30197, delay:0.0001s, distance:162.10m (Euclidean)
[2025-03-07 13:59:17,890] [INFO] [30103] Received PREPARE: id:1741323542381, from:30156, delay:0.0001s, distance:152.33m (Euclidean)
[2025-03-07 13:59:18,138] [INFO] [30103] Received COMMIT: id:1741323542381, from:30091, delay:0.0000s, distance:137.85m (Euclidean)
[2025-03-07 13:59:18,205] [INFO] [30103] Received PREPARE: id:1741323542381, from:30008, delay:0.0000s, distance:157.06m (Euclidean)
[2025-03-07 13:59:18,205] [INFO] [30103] Received COMMIT: id:1741323542381, from:30008, delay:0.0000s, distance:157.06m (Euclidean)
[2025-03-07 13:59:18,290] [INFO] [30103] Received COMMIT: id:1741323542381, from:30064, delay:0.0001s, distance:174.09m (Euclidean)
[2025-03-07 13:59:18,405] [INFO] [30103] Received PREPARE: id:1741323542381, from:30073, delay:0.0001s, distance:188.50m (Euclidean)
[2025-03-07 13:59:18,406] [INFO] [30103] Received COMMIT: id:1741323542381, from:30073, delay:0.0001s, distance:188.50m (Euclidean)
[2025-03-07 13:59:18,544] [INFO] [30103] Received PREPARE: id:1741323542381, from:30104, delay:0.0001s, distance:220.32m (Euclidean)
[2025-03-07 13:59:18,558] [INFO] [30103] Received COMMIT: id:1741323542381, from:30105, delay:0.0001s, distance:231.91m (Euclidean)
[2025-03-07 13:59:19,036] [INFO] [30103] Received PREPARE: id:1741323542381, from:30019, delay:0.0000s, distance:119.38m (Euclidean)
[2025-03-07 13:59:19,036] [INFO] [30103] Received COMMIT: id:1741323542381, from:30019, delay:0.0000s, distance:119.38m (Euclidean)
[2025-03-07 13:59:19,182] [INFO] [30103] Received COMMIT: id:1741323542381, from:30042, delay:0.0000s, distance:170.45m (Euclidean)
[2025-03-07 13:59:19,234] [INFO] [30103] Received PREPARE: id:1741323542381, from:30143, delay:0.0001s, distance:223.03m (Euclidean)
[2025-03-07 13:59:19,236] [INFO] [30103] Received COMMIT: id:1741323542381, from:30143, delay:0.0001s, distance:223.03m (Euclidean)
[2025-03-07 13:59:19,451] [INFO] [30103] Received PREPARE: id:1741323542381, from:30050, delay:0.0001s, distance:245.36m (Euclidean)
[2025-03-07 13:59:19,451] [INFO] [30103] Received PREPARE: id:1741323542381, from:30031, delay:0.0002s, distance:259.48m (Euclidean)
[2025-03-07 13:59:19,451] [INFO] [30103] Received PREPARE: id:1741323542381, from:30087, delay:0.0002s, distance:280.91m (Euclidean)
[2025-03-07 13:59:19,451] [INFO] [30103] Received COMMIT: id:1741323542381, from:30050, delay:0.0001s, distance:245.36m (Euclidean)
[2025-03-07 13:59:19,451] [INFO] [30103] Received COMMIT: id:1741323542381, from:30087, delay:0.0002s, distance:280.91m (Euclidean)
[2025-03-07 13:59:19,453] [INFO] [30103] Received COMMIT: id:1741323542381, from:30031, delay:0.0002s, distance:259.48m (Euclidean)
[2025-03-07 13:59:19,507] [INFO] [30103] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:195.59m (Euclidean)
[2025-03-07 13:59:19,696] [INFO] [30103] Received COMMIT: id:1741323542381, from:30081, delay:0.0000s, distance:145.54m (Euclidean)
[2025-03-07 13:59:19,738] [INFO] [30103] Received COMMIT: id:1741323542381, from:30145, delay:0.0001s, distance:222.31m (Euclidean)
[2025-03-07 13:59:20,200] [INFO] [30103] Received PREPARE: id:1741323542381, from:30152, delay:0.0000s, distance:147.19m (Euclidean)
[2025-03-07 13:59:20,200] [INFO] [30103] Received COMMIT: id:1741323542381, from:30152, delay:0.0000s, distance:147.19m (Euclidean)
[2025-03-07 13:59:20,343] [INFO] [30103] Received COMMIT: id:1741323542381, from:30156, delay:0.0001s, distance:152.33m (Euclidean)
[2025-03-07 13:59:20,515] [INFO] [30103] Received PREPARE: id:1741323542381, from:30142, delay:0.0001s, distance:216.65m (Euclidean)
[2025-03-07 13:59:20,515] [INFO] [30103] Received COMMIT: id:1741323542381, from:30142, delay:0.0001s, distance:216.65m (Euclidean)
[2025-03-07 13:59:20,525] [INFO] [30103] Received PREPARE: id:1741323542381, from:30001, delay:0.0001s, distance:208.32m (Euclidean)
[2025-03-07 13:59:20,541] [INFO] [30103] Received COMMIT: id:1741323542381, from:30001, delay:0.0001s, distance:208.32m (Euclidean)
[2025-03-07 13:59:20,581] [INFO] [30103] Received PREPARE: id:1741323542381, from:30083, delay:0.0001s, distance:185.31m (Euclidean)
[2025-03-07 13:59:20,581] [INFO] [30103] Received COMMIT: id:1741323542381, from:30083, delay:0.0001s, distance:185.31m (Euclidean)
[2025-03-07 13:59:21,132] [INFO] [30103] Received PREPARE: id:1741323542381, from:30036, delay:0.0002s, distance:275.77m (Euclidean)
[2025-03-07 13:59:21,136] [INFO] [30103] Received COMMIT: id:1741323542381, from:30036, delay:0.0002s, distance:275.77m (Euclidean)
[2025-03-07 13:59:21,185] [INFO] [30103] Received PREPARE: id:1741323542381, from:30173, delay:0.0001s, distance:203.50m (Euclidean)
[2025-03-07 13:59:21,188] [INFO] [30103] Received COMMIT: id:1741323542381, from:30173, delay:0.0001s, distance:203.50m (Euclidean)
[2025-03-07 13:59:21,212] [INFO] [30103] Received PREPARE: id:1741323542381, from:30038, delay:0.0001s, distance:206.13m (Euclidean)
[2025-03-07 13:59:21,214] [INFO] [30103] Received COMMIT: id:1741323542381, from:30038, delay:0.0001s, distance:206.13m (Euclidean)
[2025-03-07 13:59:21,214] [INFO] [30103] Received PREPARE: id:1741323542381, from:30137, delay:0.0001s, distance:208.85m (Euclidean)
[2025-03-07 13:59:21,214] [INFO] [30103] Received COMMIT: id:1741323542381, from:30137, delay:0.0001s, distance:208.85m (Euclidean)
[2025-03-07 13:59:21,313] [INFO] [30103] Received COMMIT: id:1741323542381, from:30151, delay:0.0000s, distance:141.70m (Euclidean)
[2025-03-07 13:59:21,451] [INFO] [30103] Received PREPARE: id:1741323542381, from:30052, delay:0.0001s, distance:201.26m (Euclidean)
[2025-03-07 13:59:21,453] [INFO] [30103] Received PREPARE: id:1741323542381, from:30022, delay:0.0000s, distance:138.65m (Euclidean)
[2025-03-07 13:59:21,453] [INFO] [30103] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:129.78m (Euclidean)
[2025-03-07 13:59:21,454] [INFO] [30103] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:129.78m (Euclidean)
[2025-03-07 13:59:21,454] [INFO] [30103] Received COMMIT: id:1741323542381, from:30022, delay:0.0000s, distance:138.65m (Euclidean)
[2025-03-07 13:59:21,485] [INFO] [30103] Received COMMIT: id:1741323542381, from:30052, delay:0.0001s, distance:201.26m (Euclidean)
[2025-03-07 13:59:21,645] [INFO] [30103] Received PREPARE: id:1741323542381, from:30187, delay:0.0001s, distance:226.86m (Euclidean)
[2025-03-07 13:59:22,872] [INFO] [30103] Received COMMIT: id:1741323542381, from:30187, delay:0.0001s, distance:226.86m (Euclidean)
[2025-03-07 13:59:22,873] [INFO] [30103] Received COMMIT: id:1741323542381, from:30075, delay:0.0001s, distance:166.25m (Euclidean)
[2025-03-07 13:59:22,873] [INFO] [30103] Received COMMIT: id:1741323542381, from:30094, delay:0.0001s, distance:169.80m (Euclidean)
[2025-03-07 13:59:22,873] [INFO] [30103] Received PREPARE: id:1741323542381, from:30079, delay:0.0001s, distance:236.47m (Euclidean)
[2025-03-07 13:59:22,873] [INFO] [30103] Received PREPARE: id:1741323542381, from:30058, delay:0.0001s, distance:242.54m (Euclidean)
[2025-03-07 13:59:22,873] [INFO] [30103] Received PREPARE: id:1741323542381, from:30094, delay:0.0001s, distance:169.80m (Euclidean)
[2025-03-07 13:59:22,873] [INFO] [30103] Received PREPARE: id:1741323542381, from:30075, delay:0.0001s, distance:166.25m (Euclidean)
[2025-03-07 13:59:22,876] [INFO] [30103] Received COMMIT: id:1741323542381, from:30079, delay:0.0001s, distance:236.47m (Euclidean)
[2025-03-07 13:59:22,876] [INFO] [30103] Received COMMIT: id:1741323542381, from:30058, delay:0.0001s, distance:242.54m (Euclidean)
[2025-03-07 13:59:23,424] [INFO] [30103] Received PREPARE: id:1741323542381, from:30183, delay:0.0000s, distance:133.02m (Euclidean)
[2025-03-07 13:59:23,711] [INFO] [30103] Received PREPARE: id:1741323542381, from:30138, delay:0.0001s, distance:187.41m (Euclidean)
[2025-03-07 13:59:23,711] [INFO] [30103] Received COMMIT: id:1741323542381, from:30138, delay:0.0001s, distance:187.41m (Euclidean)
[2025-03-07 13:59:23,812] [INFO] [30103] Received PREPARE: id:1741323542381, from:30162, delay:0.0000s, distance:124.61m (Euclidean)
[2025-03-07 13:59:23,818] [INFO] [30103] Received COMMIT: id:1741323542381, from:30162, delay:0.0000s, distance:124.61m (Euclidean)
[2025-03-07 13:59:23,906] [INFO] [30103] Received COMMIT: id:1741323542381, from:30017, delay:0.0000s, distance:116.87m (Euclidean)
[2025-03-07 13:59:24,071] [INFO] [30103] Received PREPARE: id:1741323542381, from:30014, delay:0.0001s, distance:234.37m (Euclidean)
[2025-03-07 13:59:24,073] [INFO] [30103] Received COMMIT: id:1741323542381, from:30014, delay:0.0001s, distance:234.37m (Euclidean)
[2025-03-07 13:59:24,520] [INFO] [30103] Received COMMIT: id:1741323542381, from:30104, delay:0.0001s, distance:220.32m (Euclidean)
[2025-03-07 13:59:24,614] [INFO] [30103] Received PREPARE: id:1741323542381, from:30009, delay:0.0001s, distance:225.30m (Euclidean)
[2025-03-07 13:59:24,909] [INFO] [30103] Received COMMIT: id:1741323542381, from:30009, delay:0.0001s, distance:225.30m (Euclidean)
[2025-03-07 13:59:24,988] [INFO] [30103] Received PREPARE: id:1741323542381, from:30166, delay:0.0001s, distance:194.81m (Euclidean)
[2025-03-07 13:59:24,988] [INFO] [30103] Received COMMIT: id:1741323542381, from:30166, delay:0.0001s, distance:194.81m (Euclidean)
[2025-03-07 13:59:25,494] [INFO] [30103] Received PREPARE: id:1741323542381, from:30039, delay:0.0001s, distance:208.89m (Euclidean)
[2025-03-07 13:59:25,494] [INFO] [30103] Received COMMIT: id:1741323542381, from:30039, delay:0.0001s, distance:208.89m (Euclidean)
[2025-03-07 13:59:26,263] [INFO] [30103] Received PREPARE: id:1741323542381, from:30101, delay:0.0001s, distance:170.65m (Euclidean)
[2025-03-07 13:59:26,263] [INFO] [30103] Received COMMIT: id:1741323542381, from:30101, delay:0.0001s, distance:170.65m (Euclidean)
[2025-03-07 13:59:26,408] [INFO] [30103] Received PREPARE: id:1741323542381, from:30084, delay:0.0001s, distance:182.03m (Euclidean)
[2025-03-07 13:59:26,408] [INFO] [30103] Received COMMIT: id:1741323542381, from:30084, delay:0.0001s, distance:182.03m (Euclidean)
[2025-03-07 13:59:26,572] [INFO] [30103] Received PREPARE: id:1741323542381, from:30045, delay:0.0001s, distance:226.99m (Euclidean)
[2025-03-07 13:59:26,578] [INFO] [30103] Received COMMIT: id:1741323542381, from:30045, delay:0.0001s, distance:226.99m (Euclidean)
[2025-03-07 13:59:27,197] [INFO] [30103] Received PREPARE: id:1741323542381, from:30018, delay:0.0000s, distance:140.13m (Euclidean)
[2025-03-07 13:59:27,528] [INFO] [30103] Received PREPARE: id:1741323542381, from:30139, delay:0.0001s, distance:196.67m (Euclidean)
[2025-03-07 13:59:27,550] [INFO] [30103] Received COMMIT: id:1741323542381, from:30139, delay:0.0001s, distance:196.67m (Euclidean)
[2025-03-07 13:59:27,642] [INFO] [30103] Received PREPARE: id:1741323542381, from:30002, delay:0.0001s, distance:156.56m (Euclidean)
[2025-03-07 13:59:27,642] [INFO] [30103] Received COMMIT: id:1741323542381, from:30002, delay:0.0001s, distance:156.56m (Euclidean)
[2025-03-07 13:59:27,983] [INFO] [30103] Received PREPARE: id:1741323542381, from:30172, delay:0.0001s, distance:174.16m (Euclidean)
[2025-03-07 13:59:27,984] [INFO] [30103] Received COMMIT: id:1741323542381, from:30172, delay:0.0001s, distance:174.16m (Euclidean)
[2025-03-07 13:59:28,089] [INFO] [30103] Received PREPARE: id:1741323542381, from:30082, delay:0.0001s, distance:212.10m (Euclidean)
[2025-03-07 13:59:28,095] [INFO] [30103] Received COMMIT: id:1741323542381, from:30018, delay:0.0000s, distance:140.13m (Euclidean)
[2025-03-07 13:59:28,231] [INFO] [30103] Received COMMIT: id:1741323542381, from:30183, delay:0.0000s, distance:133.02m (Euclidean)
[2025-03-07 13:59:28,238] [INFO] [30103] Received PREPARE: id:1741323542381, from:30148, delay:0.0001s, distance:212.52m (Euclidean)
[2025-03-07 13:59:28,247] [INFO] [30103] Received COMMIT: id:1741323542381, from:30148, delay:0.0001s, distance:212.52m (Euclidean)
[2025-03-07 13:59:28,449] [INFO] [30103] Received PREPARE: id:1741323542381, from:30012, delay:0.0001s, distance:247.40m (Euclidean)
[2025-03-07 13:59:28,494] [INFO] [30103] Received COMMIT: id:1741323542381, from:30012, delay:0.0001s, distance:247.40m (Euclidean)
[2025-03-07 13:59:28,596] [INFO] [30103] Received PREPARE: id:1741323542381, from:30072, delay:0.0002s, distance:255.61m (Euclidean)
[2025-03-07 13:59:28,619] [INFO] [30103] Received COMMIT: id:1741323542381, from:30072, delay:0.0002s, distance:255.61m (Euclidean)
[2025-03-07 13:59:28,864] [INFO] [30103] Received PREPARE: id:1741323542381, from:30030, delay:0.0001s, distance:204.51m (Euclidean)
[2025-03-07 13:59:28,905] [INFO] [30103] Received COMMIT: id:1741323542381, from:30030, delay:0.0001s, distance:204.51m (Euclidean)
[2025-03-07 13:59:33,283] [INFO] [30103] Received PREPARE: id:1741323542381, from:30044, delay:0.0001s, distance:248.98m (Euclidean)
[2025-03-07 13:59:33,307] [INFO] [30103] Received COMMIT: id:1741323542381, from:30082, delay:0.0001s, distance:212.10m (Euclidean)
[2025-03-07 13:59:33,338] [INFO] [30103] Received COMMIT: id:1741323542381, from:30044, delay:0.0001s, distance:248.98m (Euclidean)
[2025-03-07 13:59:37,349] [INFO] [30103] Received PREPARE: id:1741323542381, from:30164, delay:0.0001s, distance:169.30m (Euclidean)
[2025-03-07 13:59:37,502] [INFO] [30103] Received PREPARE: id:1741323542381, from:30047, delay:0.0001s, distance:233.38m (Euclidean)
[2025-03-07 13:59:38,264] [INFO] [30103] Received COMMIT: id:1741323542381, from:30185, delay:0.0001s, distance:213.23m (Euclidean)
[2025-03-07 13:59:38,339] [INFO] [30103] Received PREPARE: id:1741323542381, from:30078, delay:0.0001s, distance:165.69m (Euclidean)
[2025-03-07 13:59:38,355] [INFO] [30103] Received PREPARE: id:1741323542381, from:30097, delay:0.0001s, distance:192.61m (Euclidean)
[2025-03-07 13:59:38,500] [INFO] [30103] Received COMMIT: id:1741323542381, from:30097, delay:0.0001s, distance:192.61m (Euclidean)
[2025-03-07 13:59:38,531] [INFO] [30103] Received PREPARE: id:1741323542381, from:30192, delay:0.0001s, distance:224.08m (Euclidean)
[2025-03-07 13:59:38,538] [INFO] [30103] Received COMMIT: id:1741323542381, from:30078, delay:0.0001s, distance:165.69m (Euclidean)
[2025-03-07 13:59:38,602] [INFO] [30103] Received PREPARE: id:1741323542381, from:30163, delay:0.0001s, distance:213.02m (Euclidean)
[2025-03-07 13:59:38,664] [INFO] [30103] Received COMMIT: id:1741323542381, from:30192, delay:0.0001s, distance:224.08m (Euclidean)
[2025-03-07 13:59:38,709] [INFO] [30103] Received COMMIT: id:1741323542381, from:30164, delay:0.0001s, distance:169.30m (Euclidean)
[2025-03-07 13:59:38,748] [INFO] [30103] Received COMMIT: id:1741323542381, from:30163, delay:0.0001s, distance:213.02m (Euclidean)
