[2025-03-07 13:53:32,884] [INFO] Starting node at localhost:30150 | index=151 | f=1, k=4 | Role: Replica
[2025-03-07 13:53:39,051] [INFO] [30150] Received PREPARE: id:1741323218379, from:30017, delay:0.0000s, distance:200.22m (Euclidean)
[2025-03-07 13:53:39,051] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,255] [INFO] [30150] Received PREPARE: id:1741323218379, from:30061, delay:0.0000s, distance:249.64m (Euclidean)
[2025-03-07 13:53:39,255] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,505] [INFO] [30150] Received COMMIT: id:1741323218379, from:30017, delay:0.0000s, distance:200.22m (Euclidean)
[2025-03-07 13:53:39,560] [INFO] [30150] Received COMMIT: id:1741323218379, from:30061, delay:0.0000s, distance:249.64m (Euclidean)
[2025-03-07 13:53:40,217] [INFO] [30150] Received PREPARE: id:1741323218379, from:30006, delay:0.0000s, distance:52.97m (Euclidean)
[2025-03-07 13:53:40,217] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,545] [INFO] [30150] Received PREPARE: id:1741323218379, from:30092, delay:0.0000s, distance:112.83m (Euclidean)
[2025-03-07 13:53:40,545] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,561] [INFO] [30150] Received PREPARE: id:1741323218379, from:30037, delay:0.0000s, distance:94.48m (Euclidean)
[2025-03-07 13:53:40,561] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,561] [INFO] [30150] Received COMMIT: id:1741323218379, from:30037, delay:0.0000s, distance:94.48m (Euclidean)
[2025-03-07 13:53:40,944] [INFO] [30150] Received COMMIT: id:1741323218379, from:30092, delay:0.0000s, distance:112.83m (Euclidean)
[2025-03-07 13:53:41,073] [INFO] [30150] Received PREPARE: id:1741323218379, from:30058, delay:0.0000s, distance:91.13m (Euclidean)
[2025-03-07 13:53:41,073] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,267] [INFO] [30150] Received COMMIT: id:1741323218379, from:30006, delay:0.0000s, distance:52.97m (Euclidean)
[2025-03-07 13:53:41,267] [INFO] [30150] Received PREPARE: id:1741323218379, from:30013, delay:0.0001s, distance:151.96m (Euclidean)
[2025-03-07 13:53:41,267] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,273] [INFO] [30150] Received COMMIT: id:1741323218379, from:30013, delay:0.0001s, distance:151.96m (Euclidean)
[2025-03-07 13:53:41,338] [INFO] [30150] Received PREPARE: id:1741323218379, from:30021, delay:0.0002s, distance:295.83m (Euclidean)
[2025-03-07 13:53:41,338] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,338] [INFO] [30150] Received COMMIT: id:1741323218379, from:30021, delay:0.0002s, distance:295.83m (Euclidean)
[2025-03-07 13:53:41,448] [INFO] [30150] Received PREPARE: id:1741323218379, from:30062, delay:0.0000s, distance:120.09m (Euclidean)
[2025-03-07 13:53:41,448] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,450] [INFO] [30150] Received COMMIT: id:1741323218379, from:30062, delay:0.0000s, distance:120.09m (Euclidean)
[2025-03-07 13:53:41,498] [INFO] [30150] Received PREPARE: id:1741323218379, from:30072, delay:0.0000s, distance:144.98m (Euclidean)
[2025-03-07 13:53:41,498] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,703] [INFO] [30150] Received PREPARE: id:1741323218379, from:30026, delay:0.0001s, distance:182.88m (Euclidean)
[2025-03-07 13:53:41,703] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,731] [INFO] [30150] Received PREPARE: id:1741323218379, from:30081, delay:0.0000s, distance:143.40m (Euclidean)
[2025-03-07 13:53:41,731] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,731] [INFO] [30150] Received COMMIT: id:1741323218379, from:30081, delay:0.0000s, distance:143.40m (Euclidean)
[2025-03-07 13:53:41,842] [INFO] [30150] Received PREPARE: id:1741323218379, from:30039, delay:0.0001s, distance:218.61m (Euclidean)
[2025-03-07 13:53:41,842] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,842] [INFO] [30150] Received COMMIT: id:1741323218379, from:30039, delay:0.0001s, distance:218.61m (Euclidean)
[2025-03-07 13:53:41,842] [INFO] [30150] Received PREPARE: id:1741323218379, from:30012, delay:0.0002s, distance:266.11m (Euclidean)
[2025-03-07 13:53:41,842] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,842] [INFO] [30150] Received COMMIT: id:1741323218379, from:30012, delay:0.0002s, distance:266.11m (Euclidean)
[2025-03-07 13:53:42,143] [INFO] [30150] Received COMMIT: id:1741323218379, from:30058, delay:0.0000s, distance:91.13m (Euclidean)
[2025-03-07 13:53:42,143] [INFO] [30150] Received PREPARE: id:1741323218379, from:30086, delay:0.0002s, distance:276.79m (Euclidean)
[2025-03-07 13:53:42,143] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,143] [INFO] [30150] Received COMMIT: id:1741323218379, from:30086, delay:0.0002s, distance:276.79m (Euclidean)
[2025-03-07 13:53:42,664] [INFO] [30150] Received PREPARE: id:1741323218379, from:30020, delay:0.0000s, distance:54.72m (Euclidean)
[2025-03-07 13:53:42,664] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,759] [INFO] [30150] Received COMMIT: id:1741323218379, from:30020, delay:0.0000s, distance:54.72m (Euclidean)
[2025-03-07 13:53:42,932] [INFO] [30150] Received PREPARE: id:1741323218379, from:30087, delay:0.0001s, distance:152.93m (Euclidean)
[2025-03-07 13:53:42,932] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,932] [INFO] [30150] Received COMMIT: id:1741323218379, from:30087, delay:0.0001s, distance:152.93m (Euclidean)
[2025-03-07 13:53:42,932] [INFO] [30150] Received PREPARE: id:1741323218379, from:30096, delay:0.0002s, distance:291.65m (Euclidean)
[2025-03-07 13:53:42,932] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,932] [INFO] [30150] Received COMMIT: id:1741323218379, from:30096, delay:0.0002s, distance:291.65m (Euclidean)
[2025-03-07 13:53:42,976] [INFO] [30150] Received COMMIT: id:1741323218379, from:30026, delay:0.0001s, distance:182.88m (Euclidean)
[2025-03-07 13:53:43,066] [INFO] [30150] Received PREPARE: id:1741323218379, from:30036, delay:0.0001s, distance:215.26m (Euclidean)
[2025-03-07 13:53:43,066] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,075] [INFO] [30150] Received COMMIT: id:1741323218379, from:30036, delay:0.0001s, distance:215.26m (Euclidean)
[2025-03-07 13:53:43,075] [INFO] [30150] Received COMMIT: id:1741323218379, from:30097, delay:0.0000s, distance:125.33m (Euclidean)
[2025-03-07 13:53:43,075] [INFO] [30150] Received PREPARE: id:1741323218379, from:30097, delay:0.0000s, distance:125.33m (Euclidean)
[2025-03-07 13:53:43,075] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,371] [INFO] [30150] Received PREPARE: id:1741323218379, from:30090, delay:0.0001s, distance:206.14m (Euclidean)
[2025-03-07 13:53:43,371] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,371] [INFO] [30150] Received PREPARE: id:1741323218379, from:30033, delay:0.0002s, distance:261.29m (Euclidean)
[2025-03-07 13:53:43,371] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,371] [INFO] [30150] Received COMMIT: id:1741323218379, from:30033, delay:0.0002s, distance:261.29m (Euclidean)
[2025-03-07 13:53:43,371] [INFO] [30150] Received COMMIT: id:1741323218379, from:30090, delay:0.0001s, distance:206.14m (Euclidean)
[2025-03-07 13:53:43,643] [INFO] [30150] Received COMMIT: id:1741323218379, from:30072, delay:0.0000s, distance:144.98m (Euclidean)
[2025-03-07 13:53:43,648] [INFO] [30150] Received PREPARE: id:1741323218379, from:30001, delay:0.0001s, distance:218.30m (Euclidean)
[2025-03-07 13:53:43,648] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,648] [INFO] [30150] Received COMMIT: id:1741323218379, from:30001, delay:0.0001s, distance:218.30m (Euclidean)
[2025-03-07 13:53:43,723] [INFO] [30150] Received PREPARE: id:1741323218379, from:30034, delay:0.0001s, distance:225.94m (Euclidean)
[2025-03-07 13:53:43,723] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,754] [INFO] [30150] Received PREPARE: id:1741323218379, from:30044, delay:0.0001s, distance:201.08m (Euclidean)
[2025-03-07 13:53:43,754] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,754] [INFO] [30150] Received COMMIT: id:1741323218379, from:30044, delay:0.0001s, distance:201.08m (Euclidean)
[2025-03-07 13:53:43,922] [INFO] [30150] Received PREPARE: id:1741323218379, from:30055, delay:0.0001s, distance:193.65m (Euclidean)
[2025-03-07 13:53:43,922] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,039] [INFO] [30150] Received COMMIT: id:1741323218379, from:30034, delay:0.0001s, distance:225.94m (Euclidean)
[2025-03-07 13:53:44,080] [INFO] [30150] Received PREPARE: id:1741323218379, from:30047, delay:0.0002s, distance:269.91m (Euclidean)
[2025-03-07 13:53:44,080] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,080] [INFO] [30150] Received COMMIT: id:1741323218379, from:30047, delay:0.0002s, distance:269.91m (Euclidean)
[2025-03-07 13:53:44,260] [INFO] [30150] Received PREPARE: id:1741323218379, from:30078, delay:0.0001s, distance:192.29m (Euclidean)
[2025-03-07 13:53:44,260] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,260] [INFO] [30150] Received COMMIT: id:1741323218379, from:30078, delay:0.0001s, distance:192.29m (Euclidean)
[2025-03-07 13:53:44,276] [INFO] [30150] Received PREPARE: id:1741323218379, from:30004, delay:0.0001s, distance:215.78m (Euclidean)
[2025-03-07 13:53:44,276] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,276] [INFO] [30150] Received COMMIT: id:1741323218379, from:30004, delay:0.0001s, distance:215.78m (Euclidean)
[2025-03-07 13:53:44,276] [INFO] [30150] Received PREPARE: id:1741323218379, from:30005, delay:0.0002s, distance:265.35m (Euclidean)
[2025-03-07 13:53:44,291] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,291] [INFO] [30150] Received COMMIT: id:1741323218379, from:30005, delay:0.0002s, distance:265.35m (Euclidean)
[2025-03-07 13:53:44,307] [INFO] [30150] Received COMMIT: id:1741323218379, from:30055, delay:0.0001s, distance:193.65m (Euclidean)
[2025-03-07 13:53:44,434] [INFO] [30150] Received PREPARE: id:1741323218379, from:30043, delay:0.0002s, distance:292.80m (Euclidean)
[2025-03-07 13:53:44,434] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,434] [INFO] [30150] Received COMMIT: id:1741323218379, from:30043, delay:0.0002s, distance:292.80m (Euclidean)
[2025-03-07 13:53:44,545] [INFO] [30150] Received PREPARE: id:1741323218379, from:30053, delay:0.0001s, distance:199.94m (Euclidean)
[2025-03-07 13:53:44,545] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,545] [INFO] [30150] Received COMMIT: id:1741323218379, from:30053, delay:0.0001s, distance:199.94m (Euclidean)
[2025-03-07 13:53:44,604] [INFO] [30150] Received PREPARE: id:1741323218379, from:30048, delay:0.0002s, distance:281.99m (Euclidean)
[2025-03-07 13:53:44,604] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,604] [INFO] [30150] Received COMMIT: id:1741323218379, from:30048, delay:0.0002s, distance:281.99m (Euclidean)
[2025-03-07 13:53:44,726] [INFO] [30150] Received PREPARE: id:1741323218379, from:30099, delay:0.0001s, distance:228.03m (Euclidean)
[2025-03-07 13:53:44,726] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,726] [INFO] [30150] Received COMMIT: id:1741323218379, from:30099, delay:0.0001s, distance:228.03m (Euclidean)
[2025-03-07 13:53:44,740] [INFO] [30150] Received PREPARE: id:1741323218379, from:30104, delay:0.0002s, distance:276.69m (Euclidean)
[2025-03-07 13:53:44,740] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,752] [INFO] [30150] Received COMMIT: id:1741323218379, from:30104, delay:0.0002s, distance:276.69m (Euclidean)
[2025-03-07 13:53:44,914] [INFO] [30150] Received PREPARE: id:1741323218379, from:30094, delay:0.0002s, distance:252.84m (Euclidean)
[2025-03-07 13:53:44,914] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,924] [INFO] [30150] Received COMMIT: id:1741323218379, from:30094, delay:0.0002s, distance:252.84m (Euclidean)
[2025-03-07 13:53:45,021] [INFO] [30150] Received PREPARE: id:1741323218379, from:30088, delay:0.0001s, distance:196.62m (Euclidean)
[2025-03-07 13:53:45,021] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,021] [INFO] [30150] Received COMMIT: id:1741323218379, from:30088, delay:0.0001s, distance:196.62m (Euclidean)
[2025-03-07 13:53:45,021] [INFO] [30150] Received PREPARE: id:1741323218379, from:30024, delay:0.0002s, distance:268.22m (Euclidean)
[2025-03-07 13:53:45,021] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,021] [INFO] [30150] Received COMMIT: id:1741323218379, from:30024, delay:0.0002s, distance:268.22m (Euclidean)
[2025-03-07 13:53:45,035] [INFO] [30150] Received PREPARE: id:1741323218379, from:30042, delay:0.0001s, distance:164.53m (Euclidean)
[2025-03-07 13:53:45,035] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,035] [INFO] [30150] Received COMMIT: id:1741323218379, from:30042, delay:0.0001s, distance:164.53m (Euclidean)
[2025-03-07 13:53:45,056] [INFO] [30150] Received PREPARE: id:1741323218379, from:30091, delay:0.0001s, distance:240.28m (Euclidean)
[2025-03-07 13:53:45,056] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,066] [INFO] [30150] Received PREPARE: id:1741323218379, from:30019, delay:0.0001s, distance:172.51m (Euclidean)
[2025-03-07 13:53:45,066] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,066] [INFO] [30150] Received COMMIT: id:1741323218379, from:30019, delay:0.0001s, distance:172.51m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30150] Received PREPARE: id:1741323218379, from:30049, delay:0.0001s, distance:181.11m (Euclidean)
[2025-03-07 13:53:45,196] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,196] [INFO] [30150] Received COMMIT: id:1741323218379, from:30049, delay:0.0001s, distance:181.11m (Euclidean)
[2025-03-07 13:53:45,225] [INFO] [30150] Received COMMIT: id:1741323218379, from:30091, delay:0.0001s, distance:240.28m (Euclidean)
[2025-03-07 13:53:45,241] [INFO] [30150] Received PREPARE: id:1741323218379, from:30046, delay:0.0002s, distance:292.15m (Euclidean)
[2025-03-07 13:53:45,241] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,241] [INFO] [30150] Received COMMIT: id:1741323218379, from:30046, delay:0.0002s, distance:292.15m (Euclidean)
[2025-03-07 13:53:45,309] [INFO] [30150] Received PREPARE: id:1741323218379, from:30102, delay:0.0001s, distance:197.39m (Euclidean)
[2025-03-07 13:53:45,309] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,309] [INFO] [30150] Received COMMIT: id:1741323218379, from:30102, delay:0.0001s, distance:197.39m (Euclidean)
[2025-03-07 13:53:45,351] [INFO] [30150] Received PREPARE: id:1741323218379, from:30009, delay:0.0002s, distance:276.29m (Euclidean)
[2025-03-07 13:53:45,351] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,351] [INFO] [30150] Received COMMIT: id:1741323218379, from:30009, delay:0.0002s, distance:276.29m (Euclidean)
[2025-03-07 13:53:45,449] [INFO] [30150] Received PREPARE: id:1741323218379, from:30010, delay:0.0001s, distance:242.52m (Euclidean)
[2025-03-07 13:53:45,449] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,449] [INFO] [30150] Received COMMIT: id:1741323218379, from:30010, delay:0.0001s, distance:242.52m (Euclidean)
[2025-03-07 13:53:45,541] [INFO] [30150] Received PREPARE: id:1741323218379, from:30035, delay:0.0001s, distance:179.81m (Euclidean)
[2025-03-07 13:53:45,541] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,541] [INFO] [30150] Received COMMIT: id:1741323218379, from:30035, delay:0.0001s, distance:179.81m (Euclidean)
[2025-03-07 13:53:45,603] [INFO] [30150] Received PREPARE: id:1741323218379, from:30040, delay:0.0001s, distance:187.59m (Euclidean)
[2025-03-07 13:53:45,603] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,603] [INFO] [30150] Received COMMIT: id:1741323218379, from:30040, delay:0.0001s, distance:187.59m (Euclidean)
[2025-03-07 13:53:45,652] [INFO] [30150] Received PREPARE: id:1741323218379, from:30002, delay:0.0001s, distance:219.25m (Euclidean)
[2025-03-07 13:53:45,652] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,652] [INFO] [30150] Received COMMIT: id:1741323218379, from:30002, delay:0.0001s, distance:219.25m (Euclidean)
[2025-03-07 13:53:45,715] [INFO] [30150] Received PREPARE: id:1741323218379, from:30083, delay:0.0002s, distance:260.75m (Euclidean)
[2025-03-07 13:53:45,715] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,715] [INFO] [30150] Received COMMIT: id:1741323218379, from:30083, delay:0.0002s, distance:260.75m (Euclidean)
[2025-03-07 13:53:45,747] [INFO] [30150] Received PREPARE: id:1741323218379, from:30098, delay:0.0002s, distance:278.33m (Euclidean)
[2025-03-07 13:53:45,747] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,747] [INFO] [30150] Received COMMIT: id:1741323218379, from:30098, delay:0.0002s, distance:278.33m (Euclidean)
[2025-03-07 13:53:45,778] [INFO] [30150] Received PREPARE: id:1741323218379, from:30041, delay:0.0001s, distance:262.89m (Euclidean)
[2025-03-07 13:53:45,778] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,778] [INFO] [30150] Received COMMIT: id:1741323218379, from:30041, delay:0.0001s, distance:262.89m (Euclidean)
[2025-03-07 13:53:45,778] [INFO] [30150] Received PREPARE: id:1741323218379, from:30016, delay:0.0001s, distance:161.91m (Euclidean)
[2025-03-07 13:53:45,778] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,778] [INFO] [30150] Received COMMIT: id:1741323218379, from:30016, delay:0.0001s, distance:161.91m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30150] Received COMMIT: id:1741323218379, from:30089, delay:0.0002s, distance:276.22m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30150] Received PREPARE: id:1741323218379, from:30089, delay:0.0002s, distance:276.22m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,810] [INFO] [30150] Received PREPARE: id:1741323218379, from:30135, delay:0.0000s, distance:78.05m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,810] [INFO] [30150] Received COMMIT: id:1741323218379, from:30135, delay:0.0000s, distance:78.05m (Euclidean)
[2025-03-07 13:53:46,019] [INFO] [30150] Received PREPARE: id:1741323218379, from:30011, delay:0.0001s, distance:201.35m (Euclidean)
[2025-03-07 13:53:46,028] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,028] [INFO] [30150] Received COMMIT: id:1741323218379, from:30011, delay:0.0001s, distance:201.35m (Euclidean)
[2025-03-07 13:53:46,063] [INFO] [30150] Received PREPARE: id:1741323218379, from:30014, delay:0.0000s, distance:99.94m (Euclidean)
[2025-03-07 13:53:46,063] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,063] [INFO] [30150] Received COMMIT: id:1741323218379, from:30014, delay:0.0000s, distance:99.94m (Euclidean)
[2025-03-07 13:53:46,116] [INFO] [30150] Received PREPARE: id:1741323218379, from:30032, delay:0.0001s, distance:260.03m (Euclidean)
[2025-03-07 13:53:46,116] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,116] [INFO] [30150] Received COMMIT: id:1741323218379, from:30032, delay:0.0001s, distance:260.03m (Euclidean)
[2025-03-07 13:53:46,333] [INFO] [30150] Received PREPARE: id:1741323218379, from:30031, delay:0.0000s, distance:141.12m (Euclidean)
[2025-03-07 13:53:46,333] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,333] [INFO] [30150] Received COMMIT: id:1741323218379, from:30031, delay:0.0000s, distance:141.12m (Euclidean)
[2025-03-07 13:53:46,482] [INFO] [30150] Received PREPARE: id:1741323218379, from:30070, delay:0.0001s, distance:198.95m (Euclidean)
[2025-03-07 13:53:46,482] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,482] [INFO] [30150] Received COMMIT: id:1741323218379, from:30070, delay:0.0001s, distance:198.95m (Euclidean)
[2025-03-07 13:53:46,557] [INFO] [30150] Received PREPARE: id:1741323218379, from:30028, delay:0.0001s, distance:183.83m (Euclidean)
[2025-03-07 13:53:46,557] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,557] [INFO] [30150] Received COMMIT: id:1741323218379, from:30028, delay:0.0001s, distance:183.83m (Euclidean)
[2025-03-07 13:53:46,900] [INFO] [30150] Received PREPARE: id:1741323218379, from:30003, delay:0.0001s, distance:281.12m (Euclidean)
[2025-03-07 13:53:46,902] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,902] [INFO] [30150] Received COMMIT: id:1741323218379, from:30003, delay:0.0001s, distance:281.12m (Euclidean)
[2025-03-07 13:53:47,645] [INFO] [30150] Received PREPARE: id:1741323218379, from:30134, delay:0.0002s, distance:287.90m (Euclidean)
[2025-03-07 13:53:47,645] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,655] [INFO] [30150] Received COMMIT: id:1741323218379, from:30134, delay:0.0002s, distance:287.90m (Euclidean)
[2025-03-07 13:53:47,834] [INFO] [30150] Received PREPARE: id:1741323218379, from:30147, delay:0.0002s, distance:277.87m (Euclidean)
[2025-03-07 13:53:47,834] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,976] [INFO] [30150] Received PREPARE: id:1741323218379, from:30153, delay:0.0002s, distance:297.89m (Euclidean)
[2025-03-07 13:53:47,976] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,976] [INFO] [30150] Received COMMIT: id:1741323218379, from:30153, delay:0.0002s, distance:297.89m (Euclidean)
[2025-03-07 13:53:48,048] [INFO] [30150] Received COMMIT: id:1741323218379, from:30147, delay:0.0002s, distance:277.87m (Euclidean)
[2025-03-07 13:53:48,169] [INFO] [30150] Received PREPARE: id:1741323218379, from:30158, delay:0.0002s, distance:275.99m (Euclidean)
[2025-03-07 13:53:48,169] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,169] [INFO] [30150] Received COMMIT: id:1741323218379, from:30158, delay:0.0002s, distance:275.99m (Euclidean)
[2025-03-07 13:53:48,182] [INFO] [30150] Received PREPARE: id:1741323218379, from:30154, delay:0.0001s, distance:176.15m (Euclidean)
[2025-03-07 13:53:48,182] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,182] [INFO] [30150] Received COMMIT: id:1741323218379, from:30154, delay:0.0001s, distance:176.15m (Euclidean)
[2025-03-07 13:53:48,228] [INFO] [30150] Received PREPARE: id:1741323218379, from:30122, delay:0.0002s, distance:275.44m (Euclidean)
[2025-03-07 13:53:48,228] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,228] [INFO] [30150] Received COMMIT: id:1741323218379, from:30122, delay:0.0002s, distance:275.44m (Euclidean)
[2025-03-07 13:53:48,249] [INFO] [30150] Received PREPARE: id:1741323218379, from:30136, delay:0.0000s, distance:108.51m (Euclidean)
[2025-03-07 13:53:48,249] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,249] [INFO] [30150] Received COMMIT: id:1741323218379, from:30136, delay:0.0000s, distance:108.51m (Euclidean)
[2025-03-07 13:53:48,593] [INFO] [30150] Received PREPARE: id:1741323218379, from:30131, delay:0.0001s, distance:215.36m (Euclidean)
[2025-03-07 13:53:48,593] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,593] [INFO] [30150] Received COMMIT: id:1741323218379, from:30131, delay:0.0001s, distance:215.36m (Euclidean)
[2025-03-07 13:53:48,599] [INFO] [30150] Received PREPARE: id:1741323218379, from:30139, delay:0.0002s, distance:296.51m (Euclidean)
[2025-03-07 13:53:48,599] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,609] [INFO] [30150] Received COMMIT: id:1741323218379, from:30139, delay:0.0002s, distance:296.51m (Euclidean)
[2025-03-07 13:53:48,657] [INFO] [30150] Received PREPARE: id:1741323218379, from:30157, delay:0.0001s, distance:232.43m (Euclidean)
[2025-03-07 13:53:48,657] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,657] [INFO] [30150] Received COMMIT: id:1741323218379, from:30157, delay:0.0001s, distance:232.43m (Euclidean)
[2025-03-07 13:53:48,766] [INFO] [30150] Received PREPARE: id:1741323218379, from:30128, delay:0.0001s, distance:196.41m (Euclidean)
[2025-03-07 13:53:48,766] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,771] [INFO] [30150] Received COMMIT: id:1741323218379, from:30128, delay:0.0001s, distance:196.41m (Euclidean)
[2025-03-07 13:53:49,004] [INFO] [30150] Received PREPARE: id:1741323218379, from:30107, delay:0.0001s, distance:191.18m (Euclidean)
[2025-03-07 13:53:49,012] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:49,051] [INFO] [30150] Received COMMIT: id:1741323218379, from:30107, delay:0.0001s, distance:191.18m (Euclidean)
[2025-03-07 13:53:49,391] [INFO] [30150] Received PREPARE: id:1741323218379, from:30151, delay:0.0002s, distance:269.70m (Euclidean)
[2025-03-07 13:53:49,391] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:49,399] [INFO] [30150] Received COMMIT: id:1741323218379, from:30151, delay:0.0002s, distance:269.70m (Euclidean)
[2025-03-07 13:53:50,269] [INFO] [30150] Received PREPARE: id:1741323218379, from:30119, delay:0.0000s, distance:84.04m (Euclidean)
[2025-03-07 13:53:50,269] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:50,303] [INFO] [30150] Received COMMIT: id:1741323218379, from:30119, delay:0.0000s, distance:84.04m (Euclidean)
[2025-03-07 13:53:50,507] [INFO] [30150] Received PREPARE: id:1741323218379, from:30126, delay:0.0002s, distance:289.66m (Euclidean)
[2025-03-07 13:53:50,507] [INFO] [30150] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:50,507] [INFO] [30150] Received COMMIT: id:1741323218379, from:30126, delay:0.0002s, distance:289.66m (Euclidean)
[2025-03-07 13:53:50,807] [INFO] [30150] Received PRE-PREPARE: id:1741323218379, from:Leader(30000), delay:0.0000s, distance:186.68m (Euclidean)
[2025-03-07 13:53:50,807] [INFO] [30150] Broadcasting PREPARE for REQUEST 1741323218379
[2025-03-07 13:53:50,905] [INFO] [30150] Received COMMIT: id:1741323218379, from:30000, delay:0.0000s, distance:186.68m (Euclidean)
[2025-03-07 13:53:50,990] [INFO] [30150] Received PREPARE: id:1741323218379, from:30159, delay:0.0000s, distance:249.18m (Euclidean)
[2025-03-07 13:53:50,990] [INFO] [30150] Broadcasting COMMIT for REQUEST 1741323218379
[2025-03-07 13:53:51,630] [INFO] [30150] Received PREPARE: id:1741323218379, from:30127, delay:0.0000s, distance:10.56m (Euclidean)
[2025-03-07 13:53:51,902] [INFO] [30150] Received PREPARE: id:1741323218379, from:30116, delay:0.0001s, distance:214.87m (Euclidean)
[2025-03-07 13:53:51,902] [INFO] [30150] Received COMMIT: id:1741323218379, from:30116, delay:0.0001s, distance:214.87m (Euclidean)
[2025-03-07 13:53:51,914] [INFO] [30150] Received COMMIT: id:1741323218379, from:30127, delay:0.0000s, distance:10.56m (Euclidean)
[2025-03-07 13:53:52,261] [INFO] [30150] Received PREPARE: id:1741323218379, from:30118, delay:0.0000s, distance:157.52m (Euclidean)
[2025-03-07 13:53:52,343] [INFO] [30150] Received COMMIT: id:1741323218379, from:30118, delay:0.0000s, distance:157.52m (Euclidean)
[2025-03-07 13:53:53,084] [INFO] [30150] Received COMMIT: id:1741323218379, from:30159, delay:0.0000s, distance:249.18m (Euclidean)
[2025-03-07 13:53:53,147] [INFO] [30150] Received PREPARE: id:1741323218379, from:30121, delay:0.0001s, distance:235.14m (Euclidean)
[2025-03-07 13:53:53,147] [INFO] [30150] Received COMMIT: id:1741323218379, from:30121, delay:0.0001s, distance:235.14m (Euclidean)
[2025-03-07 13:53:53,341] [INFO] [30150] Received PREPARE: id:1741323218379, from:30129, delay:0.0001s, distance:273.05m (Euclidean)
[2025-03-07 13:53:53,341] [INFO] [30150] Received PREPARE: id:1741323218379, from:30113, delay:0.0001s, distance:254.12m (Euclidean)
[2025-03-07 13:53:53,341] [INFO] [30150] Received COMMIT: id:1741323218379, from:30129, delay:0.0001s, distance:273.05m (Euclidean)
[2025-03-07 13:53:53,341] [INFO] [30150] Received COMMIT: id:1741323218379, from:30113, delay:0.0001s, distance:254.12m (Euclidean)
[2025-03-07 13:53:53,543] [INFO] [30150] Received PREPARE: id:1741323218379, from:30123, delay:0.0000s, distance:140.08m (Euclidean)
[2025-03-07 13:53:53,543] [INFO] [30150] Received COMMIT: id:1741323218379, from:30123, delay:0.0000s, distance:140.08m (Euclidean)
[2025-03-07 13:53:54,081] [INFO] [30150] Received PREPARE: id:1741323218379, from:30149, delay:0.0002s, distance:285.24m (Euclidean)
[2025-03-07 13:53:54,097] [INFO] [30150] Received COMMIT: id:1741323218379, from:30149, delay:0.0002s, distance:285.24m (Euclidean)
[2025-03-07 13:53:54,271] [INFO] [30150] Received PREPARE: id:1741323218379, from:30156, delay:0.0001s, distance:247.46m (Euclidean)
[2025-03-07 13:53:54,356] [INFO] [30150] Received PREPARE: id:1741323218379, from:30146, delay:0.0000s, distance:129.63m (Euclidean)
[2025-03-07 13:53:54,397] [INFO] [30150] Received COMMIT: id:1741323218379, from:30146, delay:0.0000s, distance:129.63m (Euclidean)
[2025-03-07 13:53:54,397] [INFO] [30150] Received PREPARE: id:1741323218379, from:30108, delay:0.0001s, distance:188.31m (Euclidean)
[2025-03-07 13:53:54,405] [INFO] [30150] Received PREPARE: id:1741323218379, from:30106, delay:0.0001s, distance:214.94m (Euclidean)
[2025-03-07 13:53:54,424] [INFO] [30150] Received COMMIT: id:1741323218379, from:30106, delay:0.0001s, distance:214.94m (Euclidean)
[2025-03-07 13:53:54,458] [INFO] [30150] Received COMMIT: id:1741323218379, from:30108, delay:0.0001s, distance:188.31m (Euclidean)
[2025-03-07 13:53:54,466] [INFO] [30150] Received PREPARE: id:1741323218379, from:30152, delay:0.0001s, distance:178.35m (Euclidean)
[2025-03-07 13:53:54,499] [INFO] [30150] Received COMMIT: id:1741323218379, from:30152, delay:0.0001s, distance:178.35m (Euclidean)
[2025-03-07 13:53:55,402] [ERROR] [30150] Error sending to http://localhost:30141/prepare: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('127.0.0.1', 30141)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30141)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('127.0.0.1', 30141)]
[2025-03-07 13:53:55,490] [ERROR] [30150] Error sending to http://localhost:30141/commit: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('::1', 30141, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30141, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('::1', 30141, 0, 0)]
[2025-03-07 13:53:55,498] [INFO] [30150] Received PREPARE: id:1741323218379, from:30111, delay:0.0000s, distance:151.04m (Euclidean)
[2025-03-07 13:53:55,498] [INFO] [30150] Received PREPARE: id:1741323218379, from:30115, delay:0.0001s, distance:268.29m (Euclidean)
[2025-03-07 13:53:55,498] [INFO] [30150] Received COMMIT: id:1741323218379, from:30115, delay:0.0001s, distance:268.29m (Euclidean)
[2025-03-07 13:53:55,503] [INFO] [30150] Received COMMIT: id:1741323218379, from:30156, delay:0.0001s, distance:247.46m (Euclidean)
[2025-03-07 13:53:55,503] [ERROR] [30150] Error sending to http://localhost:30029/prepare: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30029)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
[2025-03-07 13:53:55,503] [INFO] [30150] Received COMMIT: id:1741323218379, from:30111, delay:0.0000s, distance:151.04m (Euclidean)
[2025-03-07 13:53:55,660] [INFO] [30150] Received PREPARE: id:1741323218379, from:30022, delay:0.0002s, distance:292.09m (Euclidean)
[2025-03-07 13:53:55,676] [INFO] [30150] Received COMMIT: id:1741323218379, from:30022, delay:0.0002s, distance:292.09m (Euclidean)
[2025-03-07 13:53:55,771] [ERROR] [30150] Error sending to http://localhost:30027/prepare: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30027)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
[2025-03-07 13:53:56,105] [ERROR] [30150] Error sending to http://localhost:30023/commit: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30023, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
[2025-03-07 13:53:56,121] [ERROR] [30150] Error sending to http://localhost:30023/prepare: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30023)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
[2025-03-07 13:53:56,312] [ERROR] [30150] Error sending to http://localhost:30025/prepare: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('127.0.0.1', 30025)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30025)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('127.0.0.1', 30025)]
[2025-03-07 13:53:56,425] [ERROR] [30150] Error sending to http://localhost:30027/commit: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30027, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
[2025-03-07 13:53:57,444] [ERROR] [30150] Error sending to http://localhost:30075/commit: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30075, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
[2025-03-07 13:53:57,458] [ERROR] [30150] Error sending to http://localhost:30065/prepare: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('127.0.0.1', 30065)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30065)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('127.0.0.1', 30065)]
[2025-03-07 13:53:57,490] [ERROR] [30150] Error sending to http://localhost:30008/prepare: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30008)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
[2025-03-07 13:53:57,490] [ERROR] [30150] Error sending to http://localhost:30065/commit: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('::1', 30065, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30065, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('::1', 30065, 0, 0)]
[2025-03-07 13:53:57,506] [ERROR] [30150] Error sending to http://localhost:30143/prepare: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('127.0.0.1', 30143)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30143)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('127.0.0.1', 30143)]
[2025-03-07 13:53:57,521] [ERROR] [30150] Error sending to http://localhost:30063/commit: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30063, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
[2025-03-07 13:53:57,523] [ERROR] [30150] Error sending to http://localhost:30143/commit: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('::1', 30143, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30143, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('::1', 30143, 0, 0)]
[2025-03-07 13:53:57,523] [ERROR] [30150] Error sending to http://localhost:30075/prepare: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30075)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
[2025-03-07 13:53:57,523] [ERROR] [30150] Error sending to http://localhost:30008/commit: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30008, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
[2025-03-07 13:53:57,523] [ERROR] [30150] Error sending to http://localhost:30029/commit: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30029, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
[2025-03-07 13:53:57,537] [ERROR] [30150] Error sending to http://localhost:30063/prepare: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30063)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
[2025-03-07 13:53:57,537] [ERROR] [30150] Error sending to http://localhost:30137/prepare: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30137)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
[2025-03-07 13:53:57,569] [ERROR] [30150] Error sending to http://localhost:30124/commit: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30124, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
[2025-03-07 13:53:57,569] [ERROR] [30150] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:53:57,585] [ERROR] [30150] Error sending to http://localhost:30124/prepare: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
[2025-03-07 13:53:57,585] [ERROR] [30150] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:53:57,663] [ERROR] [30150] Error sending to http://localhost:30093/prepare: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30093)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
[2025-03-07 13:53:57,663] [ERROR] [30150] Error sending to http://localhost:30093/commit: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30093, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
[2025-03-07 13:53:57,663] [ERROR] [30150] Error sending to http://localhost:30137/commit: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30137, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
[2025-03-07 13:53:57,713] [ERROR] [30150] Error sending to http://localhost:30025/commit: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('::1', 30025, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30025, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('::1', 30025, 0, 0)]
[2025-03-07 13:53:57,759] [ERROR] [30150] Error sending to http://localhost:30085/prepare: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30085)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
[2025-03-07 13:53:57,791] [ERROR] [30150] Error sending to http://localhost:30085/commit: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30085, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
[2025-03-07 13:53:58,203] [ERROR] [30150] Error sending to http://localhost:30064/commit: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30064, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
[2025-03-07 13:53:58,203] [ERROR] [30150] Error sending to http://localhost:30064/prepare: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30064)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
[2025-03-07 13:53:58,362] [ERROR] [30150] Error sending to http://localhost:30076/commit: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30076, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
[2025-03-07 13:53:58,364] [ERROR] [30150] Error sending to http://localhost:30076/prepare: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
[2025-03-07 13:53:58,425] [ERROR] [30150] Error sending to http://localhost:30100/prepare: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('127.0.0.1', 30100)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30100)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('127.0.0.1', 30100)]
[2025-03-07 13:53:58,425] [ERROR] [30150] Error sending to http://localhost:30138/prepare: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30138)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
[2025-03-07 13:53:58,441] [ERROR] [30150] Error sending to http://localhost:30100/commit: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('::1', 30100, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30100, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('::1', 30100, 0, 0)]
[2025-03-07 13:53:58,457] [ERROR] [30150] Error sending to http://localhost:30138/commit: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30138, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
[2025-03-07 13:54:57,881] [INFO] Starting node at localhost:30150 | index=151 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:44,319] [INFO] Starting node at localhost:30150 | index=151 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:46,740] [INFO] Starting node at localhost:30150 | index=151 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:02,502] [INFO] [30150] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0000s, distance:92.69m (Euclidean)
[2025-03-07 13:59:02,502] [INFO] [30150] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:02,514] [INFO] [30150] Not broadcasting to fault node: 30077
[2025-03-07 13:59:02,530] [INFO] [30150] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,130] [INFO] [30150] Received PREPARE: id:1741323542381, from:30169, delay:0.0000s, distance:200.31m (Euclidean)
[2025-03-07 13:59:03,244] [INFO] [30150] Received PREPARE: id:1741323542381, from:30189, delay:0.0000s, distance:200.60m (Euclidean)
[2025-03-07 13:59:03,244] [INFO] [30150] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:03,257] [INFO] [30150] Not broadcasting to fault node: 30077
[2025-03-07 13:59:03,339] [INFO] [30150] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,554] [INFO] [30150] Received COMMIT: id:1741323542381, from:30169, delay:0.0000s, distance:200.31m (Euclidean)
[2025-03-07 13:59:03,817] [INFO] [30150] Received PREPARE: id:1741323542381, from:30120, delay:0.0000s, distance:145.28m (Euclidean)
[2025-03-07 13:59:03,839] [INFO] [30150] Received COMMIT: id:1741323542381, from:30189, delay:0.0000s, distance:200.60m (Euclidean)
[2025-03-07 13:59:03,839] [INFO] [LEADER 30150] Sending REPLY for REQUEST 1741323542381 to CLIENT
[2025-03-07 13:59:03,842] [INFO] [30150] Received PREPARE: id:1741323542381, from:30070, delay:0.0000s, distance:150.65m (Euclidean)
[2025-03-07 13:59:04,100] [INFO] [30150] Received PREPARE: id:1741323542381, from:30155, delay:0.0001s, distance:171.20m (Euclidean)
[2025-03-07 13:59:04,100] [INFO] [30150] Received PREPARE: id:1741323542381, from:30126, delay:0.0000s, distance:91.00m (Euclidean)
[2025-03-07 13:59:04,100] [INFO] [30150] Received PREPARE: id:1741323542381, from:30128, delay:0.0000s, distance:123.35m (Euclidean)
[2025-03-07 13:59:04,113] [INFO] [30150] Received COMMIT: id:1741323542381, from:30155, delay:0.0001s, distance:171.20m (Euclidean)
[2025-03-07 13:59:04,170] [INFO] [30150] Received PREPARE: id:1741323542381, from:30170, delay:0.0000s, distance:38.89m (Euclidean)
[2025-03-07 13:59:04,170] [INFO] [30150] Received PREPARE: id:1741323542381, from:30037, delay:0.0000s, distance:106.05m (Euclidean)
[2025-03-07 13:59:04,225] [INFO] [30150] Received COMMIT: id:1741323542381, from:30128, delay:0.0000s, distance:123.35m (Euclidean)
[2025-03-07 13:59:04,374] [INFO] [30150] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:46.35m (Euclidean)
[2025-03-07 13:59:04,425] [INFO] [30150] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:104.88m (Euclidean)
[2025-03-07 13:59:04,449] [INFO] [30150] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:104.88m (Euclidean)
[2025-03-07 13:59:04,485] [INFO] [30150] Received PREPARE: id:1741323542381, from:30157, delay:0.0001s, distance:154.50m (Euclidean)
[2025-03-07 13:59:04,494] [INFO] [30150] Received PREPARE: id:1741323542381, from:30098, delay:0.0000s, distance:63.98m (Euclidean)
[2025-03-07 13:59:04,530] [INFO] [30150] Received PREPARE: id:1741323542381, from:30013, delay:0.0000s, distance:132.42m (Euclidean)
[2025-03-07 13:59:04,717] [INFO] [30150] Received PREPARE: id:1741323542381, from:30119, delay:0.0001s, distance:189.09m (Euclidean)
[2025-03-07 13:59:04,772] [INFO] [30150] Received COMMIT: id:1741323542381, from:30037, delay:0.0000s, distance:106.05m (Euclidean)
[2025-03-07 13:59:05,749] [INFO] [30150] Received COMMIT: id:1741323542381, from:30119, delay:0.0001s, distance:189.09m (Euclidean)
[2025-03-07 13:59:05,933] [INFO] [30150] Received PREPARE: id:1741323542381, from:30029, delay:0.0001s, distance:168.12m (Euclidean)
[2025-03-07 13:59:05,933] [INFO] [30150] Received COMMIT: id:1741323542381, from:30126, delay:0.0000s, distance:91.00m (Euclidean)
[2025-03-07 13:59:06,331] [INFO] [30150] Received PREPARE: id:1741323542381, from:30199, delay:0.0000s, distance:129.21m (Euclidean)
[2025-03-07 13:59:06,333] [INFO] [30150] Received COMMIT: id:1741323542381, from:30167, delay:0.0001s, distance:170.65m (Euclidean)
[2025-03-07 13:59:06,333] [INFO] [30150] Received PREPARE: id:1741323542381, from:30167, delay:0.0001s, distance:170.65m (Euclidean)
[2025-03-07 13:59:06,335] [INFO] [30150] Received PREPARE: id:1741323542381, from:30144, delay:0.0000s, distance:117.69m (Euclidean)
[2025-03-07 13:59:06,426] [INFO] [30150] Received PREPARE: id:1741323542381, from:30043, delay:0.0000s, distance:118.72m (Euclidean)
[2025-03-07 13:59:06,426] [INFO] [30150] Received PREPARE: id:1741323542381, from:30080, delay:0.0001s, distance:179.90m (Euclidean)
[2025-03-07 13:59:06,428] [INFO] [30150] Received PREPARE: id:1741323542381, from:30154, delay:0.0000s, distance:101.31m (Euclidean)
[2025-03-07 13:59:06,428] [INFO] [30150] Received PREPARE: id:1741323542381, from:30093, delay:0.0000s, distance:129.50m (Euclidean)
[2025-03-07 13:59:06,428] [INFO] [30150] Received PREPARE: id:1741323542381, from:30095, delay:0.0000s, distance:89.91m (Euclidean)
[2025-03-07 13:59:06,428] [INFO] [30150] Received COMMIT: id:1741323542381, from:30157, delay:0.0001s, distance:154.50m (Euclidean)
[2025-03-07 13:59:06,428] [INFO] [30150] Received PREPARE: id:1741323542381, from:30065, delay:0.0001s, distance:157.06m (Euclidean)
[2025-03-07 13:59:06,431] [INFO] [30150] Received PREPARE: id:1741323542381, from:30136, delay:0.0000s, distance:96.35m (Euclidean)
[2025-03-07 13:59:06,431] [INFO] [30150] Received PREPARE: id:1741323542381, from:30147, delay:0.0000s, distance:90.62m (Euclidean)
[2025-03-07 13:59:06,791] [INFO] [30150] Received COMMIT: id:1741323542381, from:30080, delay:0.0001s, distance:179.90m (Euclidean)
[2025-03-07 13:59:06,791] [INFO] [30150] Received COMMIT: id:1741323542381, from:30070, delay:0.0000s, distance:150.65m (Euclidean)
[2025-03-07 13:59:06,791] [INFO] [30150] Received COMMIT: id:1741323542381, from:30029, delay:0.0001s, distance:168.12m (Euclidean)
[2025-03-07 13:59:06,791] [INFO] [30150] Received COMMIT: id:1741323542381, from:30144, delay:0.0000s, distance:117.69m (Euclidean)
[2025-03-07 13:59:06,791] [INFO] [30150] Received COMMIT: id:1741323542381, from:30095, delay:0.0000s, distance:89.91m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30174, delay:0.0001s, distance:184.63m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30059, delay:0.0000s, distance:91.62m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30011, delay:0.0000s, distance:32.55m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30100, delay:0.0000s, distance:75.57m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30181, delay:0.0001s, distance:182.65m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30110, delay:0.0000s, distance:39.12m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30115, delay:0.0001s, distance:151.32m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received COMMIT: id:1741323542381, from:30013, delay:0.0000s, distance:132.42m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:139.89m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30150] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:134.79m (Euclidean)
[2025-03-07 13:59:07,216] [INFO] [30150] Received COMMIT: id:1741323542381, from:30100, delay:0.0000s, distance:75.57m (Euclidean)
[2025-03-07 13:59:07,216] [INFO] [30150] Received COMMIT: id:1741323542381, from:30195, delay:0.0000s, distance:145.98m (Euclidean)
[2025-03-07 13:59:07,216] [INFO] [30150] Received PREPARE: id:1741323542381, from:30056, delay:0.0000s, distance:79.97m (Euclidean)
[2025-03-07 13:59:07,216] [INFO] [30150] Received COMMIT: id:1741323542381, from:30115, delay:0.0001s, distance:151.32m (Euclidean)
[2025-03-07 13:59:07,216] [INFO] [30150] Received COMMIT: id:1741323542381, from:30098, delay:0.0000s, distance:63.98m (Euclidean)
[2025-03-07 13:59:07,216] [INFO] [30150] Received COMMIT: id:1741323542381, from:30170, delay:0.0000s, distance:38.89m (Euclidean)
[2025-03-07 13:59:07,216] [INFO] [30150] Received PREPARE: id:1741323542381, from:30182, delay:0.0001s, distance:156.96m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received COMMIT: id:1741323542381, from:30056, delay:0.0000s, distance:79.97m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received PREPARE: id:1741323542381, from:30051, delay:0.0001s, distance:185.23m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received PREPARE: id:1741323542381, from:30102, delay:0.0000s, distance:43.53m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received PREPARE: id:1741323542381, from:30195, delay:0.0000s, distance:145.98m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received PREPARE: id:1741323542381, from:30060, delay:0.0001s, distance:170.47m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received PREPARE: id:1741323542381, from:30096, delay:0.0000s, distance:64.67m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received PREPARE: id:1741323542381, from:30023, delay:0.0001s, distance:198.30m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received COMMIT: id:1741323542381, from:30065, delay:0.0001s, distance:157.06m (Euclidean)
[2025-03-07 13:59:07,305] [INFO] [30150] Received PREPARE: id:1741323542381, from:30092, delay:0.0000s, distance:136.22m (Euclidean)
[2025-03-07 13:59:07,309] [INFO] [30150] Received PREPARE: id:1741323542381, from:30158, delay:0.0000s, distance:64.50m (Euclidean)
[2025-03-07 13:59:07,431] [INFO] [30150] Received COMMIT: id:1741323542381, from:30060, delay:0.0001s, distance:170.47m (Euclidean)
[2025-03-07 13:59:07,439] [INFO] [30150] Received COMMIT: id:1741323542381, from:30154, delay:0.0000s, distance:101.31m (Euclidean)
[2025-03-07 13:59:07,439] [INFO] [30150] Received COMMIT: id:1741323542381, from:30093, delay:0.0000s, distance:129.50m (Euclidean)
[2025-03-07 13:59:07,567] [INFO] [30150] Received COMMIT: id:1741323542381, from:30199, delay:0.0000s, distance:129.21m (Euclidean)
[2025-03-07 13:59:07,567] [INFO] [30150] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:139.89m (Euclidean)
[2025-03-07 13:59:07,569] [INFO] [30150] Received PREPARE: id:1741323542381, from:30089, delay:0.0001s, distance:185.71m (Euclidean)
[2025-03-07 13:59:07,750] [INFO] [30150] Received COMMIT: id:1741323542381, from:30113, delay:0.0000s, distance:96.01m (Euclidean)
[2025-03-07 13:59:07,752] [INFO] [30150] Received COMMIT: id:1741323542381, from:30023, delay:0.0001s, distance:198.30m (Euclidean)
[2025-03-07 13:59:07,752] [INFO] [30150] Received COMMIT: id:1741323542381, from:30011, delay:0.0000s, distance:32.55m (Euclidean)
[2025-03-07 13:59:07,752] [INFO] [30150] Received COMMIT: id:1741323542381, from:30147, delay:0.0000s, distance:90.62m (Euclidean)
[2025-03-07 13:59:07,752] [INFO] [30150] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:134.79m (Euclidean)
[2025-03-07 13:59:07,752] [INFO] [30150] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:128.20m (Euclidean)
[2025-03-07 13:59:07,841] [INFO] [30150] Received PREPARE: id:1741323542381, from:30171, delay:0.0000s, distance:144.11m (Euclidean)
[2025-03-07 13:59:07,841] [INFO] [30150] Received PREPARE: id:1741323542381, from:30113, delay:0.0000s, distance:96.01m (Euclidean)
[2025-03-07 13:59:07,841] [INFO] [30150] Received COMMIT: id:1741323542381, from:30096, delay:0.0000s, distance:64.67m (Euclidean)
[2025-03-07 13:59:07,841] [INFO] [30150] Received COMMIT: id:1741323542381, from:30136, delay:0.0000s, distance:96.35m (Euclidean)
[2025-03-07 13:59:07,841] [INFO] [30150] Received COMMIT: id:1741323542381, from:30092, delay:0.0000s, distance:136.22m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30150] Received COMMIT: id:1741323542381, from:30110, delay:0.0000s, distance:39.12m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30150] Received COMMIT: id:1741323542381, from:30051, delay:0.0001s, distance:185.23m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30150] Received COMMIT: id:1741323542381, from:30171, delay:0.0000s, distance:144.11m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30150] Received COMMIT: id:1741323542381, from:30181, delay:0.0001s, distance:182.65m (Euclidean)
[2025-03-07 13:59:07,949] [INFO] [30150] Received PREPARE: id:1741323542381, from:30107, delay:0.0000s, distance:136.29m (Euclidean)
[2025-03-07 13:59:07,949] [INFO] [30150] Received COMMIT: id:1741323542381, from:30120, delay:0.0000s, distance:145.28m (Euclidean)
[2025-03-07 13:59:07,949] [INFO] [30150] Received PREPARE: id:1741323542381, from:30179, delay:0.0001s, distance:165.22m (Euclidean)
[2025-03-07 13:59:07,951] [INFO] [30150] Received COMMIT: id:1741323542381, from:30102, delay:0.0000s, distance:43.53m (Euclidean)
[2025-03-07 13:59:08,040] [INFO] [30150] Received COMMIT: id:1741323542381, from:30059, delay:0.0000s, distance:91.62m (Euclidean)
[2025-03-07 13:59:08,040] [INFO] [30150] Received COMMIT: id:1741323542381, from:30107, delay:0.0000s, distance:136.29m (Euclidean)
[2025-03-07 13:59:08,042] [INFO] [30150] Received COMMIT: id:1741323542381, from:30180, delay:0.0000s, distance:140.57m (Euclidean)
[2025-03-07 13:59:08,201] [INFO] [30150] Received COMMIT: id:1741323542381, from:30179, delay:0.0001s, distance:165.22m (Euclidean)
[2025-03-07 13:59:08,201] [INFO] [30150] Received PREPARE: id:1741323542381, from:30180, delay:0.0000s, distance:140.57m (Euclidean)
[2025-03-07 13:59:08,201] [INFO] [30150] Received PREPARE: id:1741323542381, from:30106, delay:0.0001s, distance:196.30m (Euclidean)
[2025-03-07 13:59:08,203] [INFO] [30150] Received PREPARE: id:1741323542381, from:30168, delay:0.0001s, distance:205.98m (Euclidean)
[2025-03-07 13:59:08,333] [INFO] [30150] Received COMMIT: id:1741323542381, from:30106, delay:0.0001s, distance:196.30m (Euclidean)
[2025-03-07 13:59:08,335] [INFO] [30150] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:128.20m (Euclidean)
[2025-03-07 13:59:08,335] [INFO] [30150] Received PREPARE: id:1741323542381, from:30133, delay:0.0001s, distance:152.10m (Euclidean)
[2025-03-07 13:59:08,337] [INFO] [30150] Received PREPARE: id:1741323542381, from:30112, delay:0.0001s, distance:175.12m (Euclidean)
[2025-03-07 13:59:08,420] [INFO] [30150] Received COMMIT: id:1741323542381, from:30174, delay:0.0001s, distance:184.63m (Euclidean)
[2025-03-07 13:59:08,425] [INFO] [30150] Received COMMIT: id:1741323542381, from:30089, delay:0.0001s, distance:185.71m (Euclidean)
[2025-03-07 13:59:08,427] [INFO] [30150] Received PREPARE: id:1741323542381, from:30124, delay:0.0000s, distance:64.10m (Euclidean)
[2025-03-07 13:59:08,517] [INFO] [30150] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:46.35m (Euclidean)
[2025-03-07 13:59:08,517] [INFO] [30150] Received PREPARE: id:1741323542381, from:30048, delay:0.0000s, distance:58.43m (Euclidean)
[2025-03-07 13:59:08,600] [INFO] [30150] Received COMMIT: id:1741323542381, from:30158, delay:0.0000s, distance:64.50m (Euclidean)
[2025-03-07 13:59:08,600] [INFO] [30150] Received COMMIT: id:1741323542381, from:30048, delay:0.0000s, distance:58.43m (Euclidean)
[2025-03-07 13:59:08,600] [INFO] [30150] Received PREPARE: id:1741323542381, from:30103, delay:0.0000s, distance:59.84m (Euclidean)
[2025-03-07 13:59:08,635] [INFO] [30150] Received COMMIT: id:1741323542381, from:30043, delay:0.0000s, distance:118.72m (Euclidean)
[2025-03-07 13:59:08,635] [INFO] [30150] Received PREPARE: id:1741323542381, from:30123, delay:0.0001s, distance:193.59m (Euclidean)
[2025-03-07 13:59:08,635] [INFO] [30150] Received COMMIT: id:1741323542381, from:30103, delay:0.0000s, distance:59.84m (Euclidean)
[2025-03-07 13:59:08,635] [INFO] [30150] Received PREPARE: id:1741323542381, from:30130, delay:0.0001s, distance:176.98m (Euclidean)
[2025-03-07 13:59:08,665] [INFO] [30150] Received COMMIT: id:1741323542381, from:30130, delay:0.0001s, distance:176.98m (Euclidean)
[2025-03-07 13:59:08,665] [INFO] [30150] Received COMMIT: id:1741323542381, from:30063, delay:0.0000s, distance:78.58m (Euclidean)
[2025-03-07 13:59:08,665] [INFO] [30150] Received COMMIT: id:1741323542381, from:30020, delay:0.0000s, distance:130.26m (Euclidean)
[2025-03-07 13:59:08,665] [INFO] [30150] Received COMMIT: id:1741323542381, from:30190, delay:0.0001s, distance:173.79m (Euclidean)
[2025-03-07 13:59:08,683] [INFO] [30150] Received PREPARE: id:1741323542381, from:30020, delay:0.0000s, distance:130.26m (Euclidean)
[2025-03-07 13:59:08,683] [INFO] [30150] Received PREPARE: id:1741323542381, from:30190, delay:0.0001s, distance:173.79m (Euclidean)
[2025-03-07 13:59:08,683] [INFO] [30150] Received PREPARE: id:1741323542381, from:30063, delay:0.0000s, distance:78.58m (Euclidean)
[2025-03-07 13:59:08,683] [INFO] [30150] Received COMMIT: id:1741323542381, from:30112, delay:0.0001s, distance:175.12m (Euclidean)
[2025-03-07 13:59:08,713] [INFO] [30150] Received COMMIT: id:1741323542381, from:30124, delay:0.0000s, distance:64.10m (Euclidean)
[2025-03-07 13:59:08,713] [INFO] [30150] Received COMMIT: id:1741323542381, from:30123, delay:0.0001s, distance:193.59m (Euclidean)
[2025-03-07 13:59:08,812] [INFO] [30150] Received COMMIT: id:1741323542381, from:30133, delay:0.0001s, distance:152.10m (Euclidean)
[2025-03-07 13:59:08,859] [INFO] [30150] Received PREPARE: id:1741323542381, from:30121, delay:0.0000s, distance:118.40m (Euclidean)
[2025-03-07 13:59:08,885] [INFO] [30150] Received COMMIT: id:1741323542381, from:30121, delay:0.0000s, distance:118.40m (Euclidean)
[2025-03-07 13:59:08,885] [INFO] [30150] Received COMMIT: id:1741323542381, from:30168, delay:0.0001s, distance:205.98m (Euclidean)
[2025-03-07 13:59:08,989] [INFO] [30150] Received COMMIT: id:1741323542381, from:30028, delay:0.0001s, distance:223.44m (Euclidean)
[2025-03-07 13:59:08,989] [INFO] [30150] Received PREPARE: id:1741323542381, from:30028, delay:0.0001s, distance:223.44m (Euclidean)
[2025-03-07 13:59:08,989] [INFO] [30150] Received PREPARE: id:1741323542381, from:30062, delay:0.0001s, distance:152.06m (Euclidean)
[2025-03-07 13:59:08,989] [INFO] [30150] Received PREPARE: id:1741323542381, from:30196, delay:0.0000s, distance:111.78m (Euclidean)
[2025-03-07 13:59:08,991] [INFO] [30150] Received PREPARE: id:1741323542381, from:30027, delay:0.0001s, distance:222.82m (Euclidean)
[2025-03-07 13:59:09,022] [INFO] [30150] Received COMMIT: id:1741323542381, from:30062, delay:0.0001s, distance:152.06m (Euclidean)
[2025-03-07 13:59:09,022] [INFO] [30150] Received COMMIT: id:1741323542381, from:30196, delay:0.0000s, distance:111.78m (Euclidean)
[2025-03-07 13:59:09,022] [INFO] [30150] Received COMMIT: id:1741323542381, from:30027, delay:0.0001s, distance:222.82m (Euclidean)
[2025-03-07 13:59:09,027] [INFO] [30150] Received PREPARE: id:1741323542381, from:30118, delay:0.0000s, distance:132.87m (Euclidean)
[2025-03-07 13:59:09,081] [INFO] [30150] Received COMMIT: id:1741323542381, from:30118, delay:0.0000s, distance:132.87m (Euclidean)
[2025-03-07 13:59:09,142] [INFO] [30150] Received COMMIT: id:1741323542381, from:30191, delay:0.0001s, distance:159.36m (Euclidean)
[2025-03-07 13:59:09,142] [INFO] [30150] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:137.85m (Euclidean)
[2025-03-07 13:59:09,142] [INFO] [30150] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:137.85m (Euclidean)
[2025-03-07 13:59:09,144] [INFO] [30150] Received PREPARE: id:1741323542381, from:30191, delay:0.0001s, distance:159.36m (Euclidean)
[2025-03-07 13:59:09,167] [INFO] [30150] Received PREPARE: id:1741323542381, from:30074, delay:0.0000s, distance:99.94m (Euclidean)
[2025-03-07 13:59:09,167] [INFO] [30150] Received COMMIT: id:1741323542381, from:30074, delay:0.0000s, distance:99.94m (Euclidean)
[2025-03-07 13:59:09,347] [INFO] [30150] Received COMMIT: id:1741323542381, from:30182, delay:0.0001s, distance:156.96m (Euclidean)
[2025-03-07 13:59:09,521] [INFO] [30150] Received PREPARE: id:1741323542381, from:30015, delay:0.0000s, distance:105.19m (Euclidean)
[2025-03-07 13:59:09,541] [INFO] [30150] Received COMMIT: id:1741323542381, from:30015, delay:0.0000s, distance:105.19m (Euclidean)
[2025-03-07 13:59:09,594] [INFO] [30150] Received PREPARE: id:1741323542381, from:30046, delay:0.0001s, distance:155.32m (Euclidean)
[2025-03-07 13:59:09,594] [INFO] [30150] Received COMMIT: id:1741323542381, from:30046, delay:0.0001s, distance:155.32m (Euclidean)
[2025-03-07 13:59:09,743] [INFO] [30150] Received PREPARE: id:1741323542381, from:30127, delay:0.0001s, distance:177.38m (Euclidean)
[2025-03-07 13:59:09,743] [INFO] [30150] Received COMMIT: id:1741323542381, from:30127, delay:0.0001s, distance:177.38m (Euclidean)
[2025-03-07 13:59:09,886] [INFO] [30150] Received PREPARE: id:1741323542381, from:30005, delay:0.0001s, distance:177.29m (Euclidean)
[2025-03-07 13:59:09,917] [INFO] [30150] Received COMMIT: id:1741323542381, from:30005, delay:0.0001s, distance:177.29m (Euclidean)
[2025-03-07 13:59:09,929] [INFO] [30150] Received PREPARE: id:1741323542381, from:30090, delay:0.0000s, distance:60.20m (Euclidean)
[2025-03-07 13:59:09,931] [INFO] [30150] Received COMMIT: id:1741323542381, from:30090, delay:0.0000s, distance:60.20m (Euclidean)
[2025-03-07 13:59:10,035] [INFO] [30150] Received PREPARE: id:1741323542381, from:30116, delay:0.0000s, distance:109.81m (Euclidean)
[2025-03-07 13:59:10,040] [INFO] [30150] Received COMMIT: id:1741323542381, from:30116, delay:0.0000s, distance:109.81m (Euclidean)
[2025-03-07 13:59:10,168] [INFO] [30150] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:103.49m (Euclidean)
[2025-03-07 13:59:10,184] [INFO] [30150] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:103.49m (Euclidean)
[2025-03-07 13:59:10,303] [INFO] [30150] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:104.98m (Euclidean)
[2025-03-07 13:59:10,308] [INFO] [30150] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:104.98m (Euclidean)
[2025-03-07 13:59:10,389] [INFO] [30150] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:83.44m (Euclidean)
[2025-03-07 13:59:10,389] [INFO] [30150] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:83.44m (Euclidean)
[2025-03-07 13:59:10,673] [INFO] [30150] Received PREPARE: id:1741323542381, from:30109, delay:0.0000s, distance:79.47m (Euclidean)
[2025-03-07 13:59:10,673] [INFO] [30150] Received COMMIT: id:1741323542381, from:30109, delay:0.0000s, distance:79.47m (Euclidean)
[2025-03-07 13:59:10,761] [INFO] [30150] Received PREPARE: id:1741323542381, from:30066, delay:0.0000s, distance:60.68m (Euclidean)
[2025-03-07 13:59:10,763] [INFO] [30150] Received COMMIT: id:1741323542381, from:30066, delay:0.0000s, distance:60.68m (Euclidean)
[2025-03-07 13:59:11,009] [INFO] [30150] Received PREPARE: id:1741323542381, from:30025, delay:0.0000s, distance:109.92m (Euclidean)
[2025-03-07 13:59:11,009] [INFO] [30150] Received COMMIT: id:1741323542381, from:30025, delay:0.0000s, distance:109.92m (Euclidean)
[2025-03-07 13:59:11,009] [INFO] [30150] Received PREPARE: id:1741323542381, from:30054, delay:0.0001s, distance:192.36m (Euclidean)
[2025-03-07 13:59:11,015] [INFO] [30150] Received COMMIT: id:1741323542381, from:30054, delay:0.0001s, distance:192.36m (Euclidean)
[2025-03-07 13:59:11,109] [INFO] [30150] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:148.88m (Euclidean)
[2025-03-07 13:59:11,109] [INFO] [30150] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:148.88m (Euclidean)
[2025-03-07 13:59:11,269] [INFO] [30150] Received PREPARE: id:1741323542381, from:30024, delay:0.0001s, distance:181.66m (Euclidean)
[2025-03-07 13:59:11,269] [INFO] [30150] Received COMMIT: id:1741323542381, from:30024, delay:0.0001s, distance:181.66m (Euclidean)
[2025-03-07 13:59:11,488] [INFO] [30150] Received PREPARE: id:1741323542381, from:30085, delay:0.0000s, distance:83.74m (Euclidean)
[2025-03-07 13:59:11,522] [INFO] [30150] Received PREPARE: id:1741323542381, from:30057, delay:0.0001s, distance:176.89m (Euclidean)
[2025-03-07 13:59:11,524] [INFO] [30150] Received COMMIT: id:1741323542381, from:30085, delay:0.0000s, distance:83.74m (Euclidean)
[2025-03-07 13:59:11,524] [INFO] [30150] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:125.05m (Euclidean)
[2025-03-07 13:59:11,531] [INFO] [30150] Received COMMIT: id:1741323542381, from:30057, delay:0.0001s, distance:176.89m (Euclidean)
[2025-03-07 13:59:11,531] [INFO] [30150] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:125.05m (Euclidean)
[2025-03-07 13:59:11,655] [INFO] [30150] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:36.64m (Euclidean)
[2025-03-07 13:59:11,671] [INFO] [30150] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:36.64m (Euclidean)
[2025-03-07 13:59:11,749] [INFO] [30150] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:136.11m (Euclidean)
[2025-03-07 13:59:11,752] [INFO] [30150] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:136.11m (Euclidean)
[2025-03-07 13:59:11,808] [INFO] [30150] Received PREPARE: id:1741323542381, from:30076, delay:0.0001s, distance:197.03m (Euclidean)
[2025-03-07 13:59:11,808] [INFO] [30150] Received COMMIT: id:1741323542381, from:30076, delay:0.0001s, distance:197.03m (Euclidean)
[2025-03-07 13:59:11,965] [INFO] [30150] Received PREPARE: id:1741323542381, from:30040, delay:0.0001s, distance:205.46m (Euclidean)
[2025-03-07 13:59:11,967] [INFO] [30150] Received COMMIT: id:1741323542381, from:30040, delay:0.0001s, distance:205.46m (Euclidean)
[2025-03-07 13:59:12,160] [INFO] [30150] Received PREPARE: id:1741323542381, from:30177, delay:0.0000s, distance:141.25m (Euclidean)
[2025-03-07 13:59:12,160] [INFO] [30150] Received COMMIT: id:1741323542381, from:30177, delay:0.0000s, distance:141.25m (Euclidean)
[2025-03-07 13:59:12,207] [INFO] [30150] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:74.80m (Euclidean)
[2025-03-07 13:59:12,207] [INFO] [30150] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:74.80m (Euclidean)
[2025-03-07 13:59:12,623] [INFO] [30150] Received PREPARE: id:1741323542381, from:30079, delay:0.0000s, distance:200.71m (Euclidean)
[2025-03-07 13:59:12,676] [INFO] [30150] Received PREPARE: id:1741323542381, from:30035, delay:0.0000s, distance:132.72m (Euclidean)
[2025-03-07 13:59:12,676] [INFO] [30150] Received COMMIT: id:1741323542381, from:30035, delay:0.0000s, distance:132.72m (Euclidean)
[2025-03-07 13:59:13,005] [INFO] [30150] Received PREPARE: id:1741323542381, from:30086, delay:0.0001s, distance:177.19m (Euclidean)
[2025-03-07 13:59:13,036] [INFO] [30150] Received PREPARE: id:1741323542381, from:30138, delay:0.0000s, distance:150.28m (Euclidean)
[2025-03-07 13:59:13,275] [INFO] [30150] Received COMMIT: id:1741323542381, from:30086, delay:0.0001s, distance:177.19m (Euclidean)
[2025-03-07 13:59:13,862] [INFO] [30150] Received PREPARE: id:1741323542381, from:30146, delay:0.0001s, distance:186.48m (Euclidean)
[2025-03-07 13:59:13,875] [INFO] [30150] Received COMMIT: id:1741323542381, from:30000, delay:0.0000s, distance:92.69m (Euclidean)
[2025-03-07 13:59:14,051] [INFO] [30150] Received COMMIT: id:1741323542381, from:30146, delay:0.0001s, distance:186.48m (Euclidean)
[2025-03-07 13:59:14,326] [INFO] [30150] Received PREPARE: id:1741323542381, from:30088, delay:0.0000s, distance:118.33m (Euclidean)
[2025-03-07 13:59:14,326] [INFO] [30150] Received COMMIT: id:1741323542381, from:30088, delay:0.0000s, distance:118.33m (Euclidean)
[2025-03-07 13:59:14,635] [INFO] [30150] Received PREPARE: id:1741323542381, from:30153, delay:0.0000s, distance:127.52m (Euclidean)
[2025-03-07 13:59:14,656] [INFO] [30150] Received PREPARE: id:1741323542381, from:30026, delay:0.0002s, distance:261.92m (Euclidean)
[2025-03-07 13:59:14,656] [INFO] [30150] Received COMMIT: id:1741323542381, from:30026, delay:0.0002s, distance:261.92m (Euclidean)
[2025-03-07 13:59:15,339] [INFO] [30150] Received PREPARE: id:1741323542381, from:30091, delay:0.0000s, distance:107.66m (Euclidean)
[2025-03-07 13:59:15,452] [INFO] [30150] Received PREPARE: id:1741323542381, from:30010, delay:0.0001s, distance:238.99m (Euclidean)
[2025-03-07 13:59:15,456] [INFO] [30150] Received COMMIT: id:1741323542381, from:30010, delay:0.0001s, distance:238.99m (Euclidean)
[2025-03-07 13:59:15,571] [INFO] [30150] Received PREPARE: id:1741323542381, from:30140, delay:0.0000s, distance:114.38m (Euclidean)
[2025-03-07 13:59:15,601] [INFO] [30150] Received COMMIT: id:1741323542381, from:30140, delay:0.0000s, distance:114.38m (Euclidean)
[2025-03-07 13:59:15,611] [INFO] [30150] Received COMMIT: id:1741323542381, from:30138, delay:0.0000s, distance:150.28m (Euclidean)
[2025-03-07 13:59:15,833] [INFO] [30150] Received PREPARE: id:1741323542381, from:30165, delay:0.0001s, distance:217.48m (Euclidean)
[2025-03-07 13:59:15,837] [INFO] [30150] Received COMMIT: id:1741323542381, from:30165, delay:0.0001s, distance:217.48m (Euclidean)
[2025-03-07 13:59:15,891] [INFO] [30150] Received PREPARE: id:1741323542381, from:30125, delay:0.0001s, distance:158.29m (Euclidean)
[2025-03-07 13:59:15,908] [INFO] [30150] Received COMMIT: id:1741323542381, from:30125, delay:0.0001s, distance:158.29m (Euclidean)
[2025-03-07 13:59:15,944] [INFO] [30150] Received PREPARE: id:1741323542381, from:30135, delay:0.0001s, distance:179.06m (Euclidean)
[2025-03-07 13:59:15,944] [INFO] [30150] Received COMMIT: id:1741323542381, from:30135, delay:0.0001s, distance:179.06m (Euclidean)
[2025-03-07 13:59:15,946] [INFO] [30150] Received COMMIT: id:1741323542381, from:30079, delay:0.0000s, distance:200.71m (Euclidean)
[2025-03-07 13:59:16,016] [INFO] [30150] Received PREPARE: id:1741323542381, from:30003, delay:0.0001s, distance:167.20m (Euclidean)
[2025-03-07 13:59:16,148] [INFO] [30150] Received PREPARE: id:1741323542381, from:30052, delay:0.0001s, distance:164.24m (Euclidean)
[2025-03-07 13:59:16,148] [INFO] [30150] Received COMMIT: id:1741323542381, from:30052, delay:0.0001s, distance:164.24m (Euclidean)
[2025-03-07 13:59:16,302] [INFO] [30150] Received PREPARE: id:1741323542381, from:30145, delay:0.0001s, distance:167.01m (Euclidean)
[2025-03-07 13:59:16,615] [INFO] [30150] Received COMMIT: id:1741323542381, from:30091, delay:0.0000s, distance:107.66m (Euclidean)
[2025-03-07 13:59:16,856] [INFO] [30150] Received PREPARE: id:1741323542381, from:30031, delay:0.0002s, distance:255.52m (Euclidean)
[2025-03-07 13:59:16,856] [INFO] [30150] Received COMMIT: id:1741323542381, from:30031, delay:0.0002s, distance:255.52m (Euclidean)
[2025-03-07 13:59:16,981] [INFO] [30150] Received PREPARE: id:1741323542381, from:30019, delay:0.0000s, distance:143.06m (Euclidean)
[2025-03-07 13:59:16,981] [INFO] [30150] Received COMMIT: id:1741323542381, from:30019, delay:0.0000s, distance:143.06m (Euclidean)
[2025-03-07 13:59:17,003] [INFO] [30150] Received PREPARE: id:1741323542381, from:30194, delay:0.0000s, distance:143.37m (Euclidean)
[2025-03-07 13:59:17,003] [INFO] [30150] Received COMMIT: id:1741323542381, from:30194, delay:0.0000s, distance:143.37m (Euclidean)
[2025-03-07 13:59:17,176] [INFO] [30150] Received PREPARE: id:1741323542381, from:30050, delay:0.0001s, distance:246.18m (Euclidean)
[2025-03-07 13:59:17,176] [INFO] [30150] Received COMMIT: id:1741323542381, from:30050, delay:0.0001s, distance:246.18m (Euclidean)
[2025-03-07 13:59:17,217] [INFO] [30150] Received PREPARE: id:1741323542381, from:30198, delay:0.0001s, distance:236.55m (Euclidean)
[2025-03-07 13:59:17,217] [INFO] [30150] Received COMMIT: id:1741323542381, from:30198, delay:0.0001s, distance:236.55m (Euclidean)
[2025-03-07 13:59:17,259] [INFO] [30150] Received PREPARE: id:1741323542381, from:30143, delay:0.0001s, distance:206.58m (Euclidean)
[2025-03-07 13:59:17,665] [INFO] [30150] Received PREPARE: id:1741323542381, from:30131, delay:0.0000s, distance:92.34m (Euclidean)
[2025-03-07 13:59:17,665] [INFO] [30150] Received COMMIT: id:1741323542381, from:30131, delay:0.0000s, distance:92.34m (Euclidean)
[2025-03-07 13:59:17,697] [INFO] [30150] Received COMMIT: id:1741323542381, from:30003, delay:0.0001s, distance:167.20m (Euclidean)
[2025-03-07 13:59:17,896] [INFO] [30150] Received PREPARE: id:1741323542381, from:30193, delay:0.0001s, distance:154.59m (Euclidean)
[2025-03-07 13:59:17,896] [INFO] [30150] Received COMMIT: id:1741323542381, from:30193, delay:0.0001s, distance:154.59m (Euclidean)
[2025-03-07 13:59:17,975] [INFO] [30150] Received PREPARE: id:1741323542381, from:30073, delay:0.0000s, distance:131.00m (Euclidean)
[2025-03-07 13:59:17,976] [INFO] [30150] Received COMMIT: id:1741323542381, from:30073, delay:0.0000s, distance:131.00m (Euclidean)
[2025-03-07 13:59:18,065] [INFO] [30150] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:144.33m (Euclidean)
[2025-03-07 13:59:18,067] [INFO] [30150] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:144.33m (Euclidean)
[2025-03-07 13:59:18,209] [INFO] [30150] Received PREPARE: id:1741323542381, from:30016, delay:0.0001s, distance:211.69m (Euclidean)
[2025-03-07 13:59:18,209] [INFO] [30150] Received PREPARE: id:1741323542381, from:30033, delay:0.0001s, distance:159.76m (Euclidean)
[2025-03-07 13:59:18,209] [INFO] [30150] Received COMMIT: id:1741323542381, from:30016, delay:0.0001s, distance:211.69m (Euclidean)
[2025-03-07 13:59:18,211] [INFO] [30150] Received COMMIT: id:1741323542381, from:30033, delay:0.0001s, distance:159.76m (Euclidean)
[2025-03-07 13:59:18,243] [INFO] [30150] Received COMMIT: id:1741323542381, from:30153, delay:0.0000s, distance:127.52m (Euclidean)
[2025-03-07 13:59:18,438] [INFO] [30150] Received COMMIT: id:1741323542381, from:30143, delay:0.0001s, distance:206.58m (Euclidean)
[2025-03-07 13:59:18,493] [INFO] [30150] Received PREPARE: id:1741323542381, from:30160, delay:0.0001s, distance:180.18m (Euclidean)
[2025-03-07 13:59:18,494] [INFO] [30150] Received COMMIT: id:1741323542381, from:30160, delay:0.0001s, distance:180.18m (Euclidean)
[2025-03-07 13:59:18,546] [INFO] [30150] Received COMMIT: id:1741323542381, from:30145, delay:0.0001s, distance:167.01m (Euclidean)
[2025-03-07 13:59:18,727] [INFO] [30150] Received PREPARE: id:1741323542381, from:30114, delay:0.0001s, distance:235.43m (Euclidean)
[2025-03-07 13:59:18,744] [INFO] [30150] Received COMMIT: id:1741323542381, from:30114, delay:0.0001s, distance:235.43m (Euclidean)
[2025-03-07 13:59:19,157] [INFO] [30150] Received PREPARE: id:1741323542381, from:30173, delay:0.0001s, distance:185.15m (Euclidean)
[2025-03-07 13:59:19,157] [INFO] [30150] Received PREPARE: id:1741323542381, from:30008, delay:0.0000s, distance:154.36m (Euclidean)
[2025-03-07 13:59:19,242] [INFO] [30150] Received COMMIT: id:1741323542381, from:30173, delay:0.0001s, distance:185.15m (Euclidean)
[2025-03-07 13:59:19,258] [INFO] [30150] Received PREPARE: id:1741323542381, from:30067, delay:0.0001s, distance:190.79m (Euclidean)
[2025-03-07 13:59:19,258] [INFO] [30150] Received COMMIT: id:1741323542381, from:30067, delay:0.0001s, distance:190.79m (Euclidean)
[2025-03-07 13:59:19,327] [INFO] [30150] Received PREPARE: id:1741323542381, from:30132, delay:0.0001s, distance:215.55m (Euclidean)
[2025-03-07 13:59:19,327] [INFO] [30150] Received COMMIT: id:1741323542381, from:30132, delay:0.0001s, distance:215.55m (Euclidean)
[2025-03-07 13:59:19,654] [INFO] [30150] Received PREPARE: id:1741323542381, from:30064, delay:0.0001s, distance:205.53m (Euclidean)
[2025-03-07 13:59:19,656] [INFO] [30150] Received COMMIT: id:1741323542381, from:30064, delay:0.0001s, distance:205.53m (Euclidean)
[2025-03-07 13:59:19,656] [INFO] [30150] Received COMMIT: id:1741323542381, from:30071, delay:0.0001s, distance:199.26m (Euclidean)
[2025-03-07 13:59:19,656] [INFO] [30150] Received PREPARE: id:1741323542381, from:30071, delay:0.0001s, distance:199.26m (Euclidean)
[2025-03-07 13:59:19,679] [INFO] [30150] Received PREPARE: id:1741323542381, from:30152, delay:0.0000s, distance:109.05m (Euclidean)
[2025-03-07 13:59:19,734] [INFO] [30150] Received PREPARE: id:1741323542381, from:30105, delay:0.0001s, distance:233.84m (Euclidean)
[2025-03-07 13:59:19,734] [INFO] [30150] Received COMMIT: id:1741323542381, from:30105, delay:0.0001s, distance:233.84m (Euclidean)
[2025-03-07 13:59:19,775] [INFO] [30150] Received PREPARE: id:1741323542381, from:30006, delay:0.0001s, distance:153.55m (Euclidean)
[2025-03-07 13:59:19,775] [INFO] [30150] Received COMMIT: id:1741323542381, from:30006, delay:0.0001s, distance:153.55m (Euclidean)
[2025-03-07 13:59:19,798] [INFO] [30150] Received PREPARE: id:1741323542381, from:30087, delay:0.0002s, distance:254.52m (Euclidean)
[2025-03-07 13:59:19,836] [INFO] [30150] Received COMMIT: id:1741323542381, from:30087, delay:0.0002s, distance:254.52m (Euclidean)
[2025-03-07 13:59:19,908] [INFO] [30150] Received PREPARE: id:1741323542381, from:30061, delay:0.0001s, distance:207.88m (Euclidean)
[2025-03-07 13:59:19,908] [INFO] [30150] Received COMMIT: id:1741323542381, from:30061, delay:0.0001s, distance:207.88m (Euclidean)
[2025-03-07 13:59:20,060] [INFO] [30150] Received COMMIT: id:1741323542381, from:30152, delay:0.0000s, distance:109.05m (Euclidean)
[2025-03-07 13:59:20,341] [INFO] [30150] Received PREPARE: id:1741323542381, from:30156, delay:0.0001s, distance:166.24m (Euclidean)
[2025-03-07 13:59:20,341] [INFO] [30150] Received COMMIT: id:1741323542381, from:30156, delay:0.0001s, distance:166.24m (Euclidean)
[2025-03-07 13:59:20,596] [INFO] [30150] Received PREPARE: id:1741323542381, from:30001, delay:0.0001s, distance:175.81m (Euclidean)
[2025-03-07 13:59:20,596] [INFO] [30150] Received COMMIT: id:1741323542381, from:30001, delay:0.0001s, distance:175.81m (Euclidean)
[2025-03-07 13:59:20,606] [INFO] [30150] Received PREPARE: id:1741323542381, from:30134, delay:0.0001s, distance:223.90m (Euclidean)
[2025-03-07 13:59:20,606] [INFO] [30150] Received COMMIT: id:1741323542381, from:30134, delay:0.0001s, distance:223.90m (Euclidean)
[2025-03-07 13:59:20,644] [INFO] [30150] Received PREPARE: id:1741323542381, from:30151, delay:0.0000s, distance:104.68m (Euclidean)
[2025-03-07 13:59:20,644] [INFO] [30150] Received COMMIT: id:1741323542381, from:30151, delay:0.0000s, distance:104.68m (Euclidean)
[2025-03-07 13:59:20,768] [INFO] [30150] Received PREPARE: id:1741323542381, from:30042, delay:0.0000s, distance:144.92m (Euclidean)
[2025-03-07 13:59:20,768] [INFO] [30150] Received COMMIT: id:1741323542381, from:30042, delay:0.0000s, distance:144.92m (Euclidean)
[2025-03-07 13:59:21,190] [INFO] [30150] Received PREPARE: id:1741323542381, from:30141, delay:0.0001s, distance:184.43m (Euclidean)
[2025-03-07 13:59:21,190] [INFO] [30150] Received PREPARE: id:1741323542381, from:30094, delay:0.0000s, distance:130.60m (Euclidean)
[2025-03-07 13:59:21,190] [INFO] [30150] Received COMMIT: id:1741323542381, from:30094, delay:0.0000s, distance:130.60m (Euclidean)
[2025-03-07 13:59:21,190] [INFO] [30150] Received COMMIT: id:1741323542381, from:30141, delay:0.0001s, distance:184.43m (Euclidean)
[2025-03-07 13:59:21,221] [INFO] [30150] Received PREPARE: id:1741323542381, from:30075, delay:0.0000s, distance:114.49m (Euclidean)
[2025-03-07 13:59:21,221] [INFO] [30150] Received COMMIT: id:1741323542381, from:30075, delay:0.0000s, distance:114.49m (Euclidean)
[2025-03-07 13:59:21,292] [INFO] [30150] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:214.80m (Euclidean)
[2025-03-07 13:59:21,294] [INFO] [30150] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:214.80m (Euclidean)
[2025-03-07 13:59:21,471] [INFO] [30150] Received PREPARE: id:1741323542381, from:30137, delay:0.0001s, distance:219.96m (Euclidean)
[2025-03-07 13:59:21,471] [INFO] [30150] Received COMMIT: id:1741323542381, from:30137, delay:0.0001s, distance:219.96m (Euclidean)
[2025-03-07 13:59:21,761] [INFO] [30150] Received PREPARE: id:1741323542381, from:30068, delay:0.0000s, distance:121.23m (Euclidean)
[2025-03-07 13:59:21,763] [INFO] [30150] Received COMMIT: id:1741323542381, from:30068, delay:0.0000s, distance:121.23m (Euclidean)
[2025-03-07 13:59:21,933] [INFO] [30150] Received COMMIT: id:1741323542381, from:30008, delay:0.0000s, distance:154.36m (Euclidean)
[2025-03-07 13:59:21,983] [INFO] [30150] Received PREPARE: id:1741323542381, from:30162, delay:0.0000s, distance:72.77m (Euclidean)
[2025-03-07 13:59:22,008] [INFO] [30150] Received COMMIT: id:1741323542381, from:30162, delay:0.0000s, distance:72.77m (Euclidean)
[2025-03-07 13:59:22,018] [INFO] [30150] Received PREPARE: id:1741323542381, from:30104, delay:0.0001s, distance:229.26m (Euclidean)
[2025-03-07 13:59:22,020] [INFO] [30150] Received COMMIT: id:1741323542381, from:30104, delay:0.0001s, distance:229.26m (Euclidean)
[2025-03-07 13:59:22,179] [INFO] [30150] Received PREPARE: id:1741323542381, from:30084, delay:0.0000s, distance:142.11m (Euclidean)
[2025-03-07 13:59:22,179] [INFO] [30150] Received COMMIT: id:1741323542381, from:30084, delay:0.0000s, distance:142.11m (Euclidean)
[2025-03-07 13:59:22,590] [INFO] [30150] Received PREPARE: id:1741323542381, from:30022, delay:0.0000s, distance:140.31m (Euclidean)
[2025-03-07 13:59:22,592] [INFO] [30150] Received COMMIT: id:1741323542381, from:30022, delay:0.0000s, distance:140.31m (Euclidean)
[2025-03-07 13:59:22,685] [INFO] [30150] Received PREPARE: id:1741323542381, from:30188, delay:0.0000s, distance:115.47m (Euclidean)
[2025-03-07 13:59:22,685] [INFO] [30150] Received COMMIT: id:1741323542381, from:30188, delay:0.0000s, distance:115.47m (Euclidean)
[2025-03-07 13:59:22,705] [INFO] [30150] Received PREPARE: id:1741323542381, from:30081, delay:0.0001s, distance:189.47m (Euclidean)
[2025-03-07 13:59:22,713] [INFO] [30150] Received COMMIT: id:1741323542381, from:30081, delay:0.0001s, distance:189.47m (Euclidean)
[2025-03-07 13:59:23,016] [INFO] [30150] Received PREPARE: id:1741323542381, from:30117, delay:0.0001s, distance:206.51m (Euclidean)
[2025-03-07 13:59:23,016] [INFO] [30150] Received COMMIT: id:1741323542381, from:30117, delay:0.0001s, distance:206.51m (Euclidean)
[2025-03-07 13:59:23,197] [INFO] [30150] Received COMMIT: id:1741323542381, from:30032, delay:0.0001s, distance:189.27m (Euclidean)
[2025-03-07 13:59:23,197] [INFO] [30150] Received PREPARE: id:1741323542381, from:30032, delay:0.0001s, distance:189.27m (Euclidean)
[2025-03-07 13:59:23,225] [INFO] [30150] Received PREPARE: id:1741323542381, from:30197, delay:0.0001s, distance:179.22m (Euclidean)
[2025-03-07 13:59:23,225] [INFO] [30150] Received COMMIT: id:1741323542381, from:30197, delay:0.0001s, distance:179.22m (Euclidean)
[2025-03-07 13:59:23,484] [INFO] [30150] Received PREPARE: id:1741323542381, from:30036, delay:0.0002s, distance:263.30m (Euclidean)
[2025-03-07 13:59:23,484] [INFO] [30150] Received COMMIT: id:1741323542381, from:30036, delay:0.0002s, distance:263.30m (Euclidean)
[2025-03-07 13:59:23,832] [INFO] [30150] Received PREPARE: id:1741323542381, from:30159, delay:0.0001s, distance:154.10m (Euclidean)
[2025-03-07 13:59:23,832] [INFO] [30150] Received COMMIT: id:1741323542381, from:30159, delay:0.0001s, distance:154.10m (Euclidean)
[2025-03-07 13:59:23,962] [INFO] [30150] Received PREPARE: id:1741323542381, from:30069, delay:0.0001s, distance:238.10m (Euclidean)
[2025-03-07 13:59:23,962] [INFO] [30150] Received COMMIT: id:1741323542381, from:30069, delay:0.0001s, distance:238.10m (Euclidean)
[2025-03-07 13:59:24,308] [INFO] [30150] Received PREPARE: id:1741323542381, from:30122, delay:0.0001s, distance:223.54m (Euclidean)
[2025-03-07 13:59:24,308] [INFO] [30150] Received COMMIT: id:1741323542381, from:30122, delay:0.0001s, distance:223.54m (Euclidean)
[2025-03-07 13:59:24,354] [INFO] [30150] Received PREPARE: id:1741323542381, from:30014, delay:0.0001s, distance:190.18m (Euclidean)
[2025-03-07 13:59:24,354] [INFO] [30150] Received COMMIT: id:1741323542381, from:30014, delay:0.0001s, distance:190.18m (Euclidean)
[2025-03-07 13:59:24,940] [INFO] [30150] Received PREPARE: id:1741323542381, from:30038, delay:0.0001s, distance:212.27m (Euclidean)
[2025-03-07 13:59:24,940] [INFO] [30150] Received COMMIT: id:1741323542381, from:30038, delay:0.0001s, distance:212.27m (Euclidean)
[2025-03-07 13:59:24,972] [INFO] [30150] Received PREPARE: id:1741323542381, from:30058, delay:0.0001s, distance:233.54m (Euclidean)
[2025-03-07 13:59:24,972] [INFO] [30150] Received COMMIT: id:1741323542381, from:30058, delay:0.0001s, distance:233.54m (Euclidean)
[2025-03-07 13:59:25,049] [INFO] [30150] Received PREPARE: id:1741323542381, from:30187, delay:0.0001s, distance:207.60m (Euclidean)
[2025-03-07 13:59:25,049] [INFO] [30150] Received COMMIT: id:1741323542381, from:30187, delay:0.0001s, distance:207.60m (Euclidean)
[2025-03-07 13:59:25,993] [INFO] [30150] Received PREPARE: id:1741323542381, from:30083, delay:0.0001s, distance:224.61m (Euclidean)
[2025-03-07 13:59:25,994] [INFO] [30150] Received COMMIT: id:1741323542381, from:30083, delay:0.0001s, distance:224.61m (Euclidean)
[2025-03-07 13:59:26,047] [INFO] [30150] Received PREPARE: id:1741323542381, from:30055, delay:0.0001s, distance:210.49m (Euclidean)
[2025-03-07 13:59:26,063] [INFO] [30150] Received COMMIT: id:1741323542381, from:30055, delay:0.0001s, distance:210.49m (Euclidean)
[2025-03-07 13:59:26,139] [INFO] [30150] Received PREPARE: id:1741323542381, from:30166, delay:0.0001s, distance:163.87m (Euclidean)
[2025-03-07 13:59:26,143] [INFO] [30150] Received COMMIT: id:1741323542381, from:30166, delay:0.0001s, distance:163.87m (Euclidean)
[2025-03-07 13:59:26,251] [INFO] [30150] Received PREPARE: id:1741323542381, from:30148, delay:0.0001s, distance:185.36m (Euclidean)
[2025-03-07 13:59:26,251] [INFO] [30150] Received COMMIT: id:1741323542381, from:30148, delay:0.0001s, distance:185.36m (Euclidean)
[2025-03-07 13:59:26,397] [INFO] [30150] Received PREPARE: id:1741323542381, from:30039, delay:0.0001s, distance:188.19m (Euclidean)
[2025-03-07 13:59:26,397] [INFO] [30150] Received COMMIT: id:1741323542381, from:30039, delay:0.0001s, distance:188.19m (Euclidean)
[2025-03-07 13:59:26,397] [INFO] [30150] Received PREPARE: id:1741323542381, from:30017, delay:0.0000s, distance:83.10m (Euclidean)
[2025-03-07 13:59:26,397] [INFO] [30150] Received COMMIT: id:1741323542381, from:30017, delay:0.0000s, distance:83.10m (Euclidean)
[2025-03-07 13:59:26,482] [INFO] [30150] Received PREPARE: id:1741323542381, from:30045, delay:0.0001s, distance:230.68m (Euclidean)
[2025-03-07 13:59:26,482] [INFO] [30150] Received COMMIT: id:1741323542381, from:30045, delay:0.0001s, distance:230.68m (Euclidean)
[2025-03-07 13:59:26,767] [INFO] [30150] Received PREPARE: id:1741323542381, from:30142, delay:0.0001s, distance:185.93m (Euclidean)
[2025-03-07 13:59:26,791] [INFO] [30150] Received COMMIT: id:1741323542381, from:30142, delay:0.0001s, distance:185.93m (Euclidean)
[2025-03-07 13:59:26,806] [INFO] [30150] Received PREPARE: id:1741323542381, from:30172, delay:0.0000s, distance:116.59m (Euclidean)
[2025-03-07 13:59:26,806] [INFO] [30150] Received COMMIT: id:1741323542381, from:30172, delay:0.0000s, distance:116.59m (Euclidean)
[2025-03-07 13:59:26,914] [INFO] [30150] Received PREPARE: id:1741323542381, from:30101, delay:0.0001s, distance:216.43m (Euclidean)
[2025-03-07 13:59:26,914] [INFO] [30150] Received COMMIT: id:1741323542381, from:30101, delay:0.0001s, distance:216.43m (Euclidean)
[2025-03-07 13:59:27,439] [INFO] [30150] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:151.00m (Euclidean)
[2025-03-07 13:59:27,441] [INFO] [30150] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:151.00m (Euclidean)
[2025-03-07 13:59:27,526] [INFO] [30150] Received PREPARE: id:1741323542381, from:30139, delay:0.0001s, distance:173.95m (Euclidean)
[2025-03-07 13:59:27,548] [INFO] [30150] Received COMMIT: id:1741323542381, from:30139, delay:0.0001s, distance:173.95m (Euclidean)
[2025-03-07 13:59:27,774] [INFO] [30150] Received PREPARE: id:1741323542381, from:30009, delay:0.0002s, distance:256.72m (Euclidean)
[2025-03-07 13:59:27,774] [INFO] [30150] Received COMMIT: id:1741323542381, from:30009, delay:0.0002s, distance:256.72m (Euclidean)
[2025-03-07 13:59:27,920] [INFO] [30150] Received PREPARE: id:1741323542381, from:30072, delay:0.0001s, distance:196.70m (Euclidean)
[2025-03-07 13:59:27,922] [INFO] [30150] Received COMMIT: id:1741323542381, from:30072, delay:0.0001s, distance:196.70m (Euclidean)
[2025-03-07 13:59:27,932] [INFO] [30150] Received PREPARE: id:1741323542381, from:30047, delay:0.0001s, distance:194.16m (Euclidean)
[2025-03-07 13:59:27,943] [INFO] [30150] Received COMMIT: id:1741323542381, from:30047, delay:0.0001s, distance:194.16m (Euclidean)
[2025-03-07 13:59:28,247] [INFO] [30150] Received PREPARE: id:1741323542381, from:30012, delay:0.0001s, distance:191.12m (Euclidean)
[2025-03-07 13:59:28,247] [INFO] [30150] Received COMMIT: id:1741323542381, from:30012, delay:0.0001s, distance:191.12m (Euclidean)
[2025-03-07 13:59:28,628] [INFO] [30150] Received PREPARE: id:1741323542381, from:30030, delay:0.0001s, distance:214.90m (Euclidean)
[2025-03-07 13:59:28,656] [INFO] [30150] Received PREPARE: id:1741323542381, from:30044, delay:0.0001s, distance:237.34m (Euclidean)
[2025-03-07 13:59:28,660] [INFO] [30150] Received COMMIT: id:1741323542381, from:30044, delay:0.0001s, distance:237.34m (Euclidean)
[2025-03-07 13:59:28,717] [INFO] [30150] Received PREPARE: id:1741323542381, from:30183, delay:0.0000s, distance:81.22m (Euclidean)
[2025-03-07 13:59:28,747] [INFO] [30150] Received COMMIT: id:1741323542381, from:30183, delay:0.0000s, distance:81.22m (Euclidean)
[2025-03-07 13:59:33,236] [INFO] [30150] Received COMMIT: id:1741323542381, from:30030, delay:0.0001s, distance:214.90m (Euclidean)
[2025-03-07 13:59:33,327] [INFO] [30150] Received PREPARE: id:1741323542381, from:30163, delay:0.0001s, distance:210.42m (Euclidean)
[2025-03-07 13:59:33,342] [INFO] [30150] Received PREPARE: id:1741323542381, from:30002, delay:0.0001s, distance:202.08m (Euclidean)
[2025-03-07 13:59:37,131] [INFO] [30150] Received COMMIT: id:1741323542381, from:30163, delay:0.0001s, distance:210.42m (Euclidean)
[2025-03-07 13:59:37,310] [INFO] [30150] Received COMMIT: id:1741323542381, from:30002, delay:0.0001s, distance:202.08m (Euclidean)
[2025-03-07 13:59:37,965] [INFO] [30150] Received COMMIT: id:1741323542381, from:30018, delay:0.0000s, distance:109.31m (Euclidean)
[2025-03-07 13:59:38,190] [INFO] [30150] Received PREPARE: id:1741323542381, from:30082, delay:0.0001s, distance:202.55m (Euclidean)
[2025-03-07 13:59:38,202] [INFO] [30150] Received COMMIT: id:1741323542381, from:30082, delay:0.0001s, distance:202.55m (Euclidean)
[2025-03-07 13:59:38,264] [INFO] [30150] Received COMMIT: id:1741323542381, from:30185, delay:0.0001s, distance:203.31m (Euclidean)
[2025-03-07 13:59:38,337] [INFO] [30150] Received PREPARE: id:1741323542381, from:30078, delay:0.0000s, distance:109.61m (Euclidean)
[2025-03-07 13:59:38,461] [INFO] [30150] Received COMMIT: id:1741323542381, from:30078, delay:0.0000s, distance:109.61m (Euclidean)
[2025-03-07 13:59:38,529] [INFO] [30150] Received PREPARE: id:1741323542381, from:30192, delay:0.0001s, distance:214.68m (Euclidean)
[2025-03-07 13:59:38,543] [INFO] [30150] Received PREPARE: id:1741323542381, from:30164, delay:0.0000s, distance:129.57m (Euclidean)
[2025-03-07 13:59:38,664] [INFO] [30150] Received COMMIT: id:1741323542381, from:30192, delay:0.0001s, distance:214.68m (Euclidean)
[2025-03-07 13:59:38,675] [INFO] [30150] Received COMMIT: id:1741323542381, from:30164, delay:0.0000s, distance:129.57m (Euclidean)
