[2025-03-07 13:53:31,682] [INFO] Starting node at localhost:30144 | index=145 | f=1, k=4 | Role: Replica
[2025-03-07 13:53:39,043] [INFO] [30144] Received PREPARE: id:1741323218379, from:30073, delay:0.0000s, distance:50.00m (Euclidean)
[2025-03-07 13:53:39,043] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,255] [INFO] [30144] Received PREPARE: id:1741323218379, from:30061, delay:0.0000s, distance:100.94m (Euclidean)
[2025-03-07 13:53:39,255] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,356] [INFO] [30144] Received COMMIT: id:1741323218379, from:30061, delay:0.0000s, distance:100.94m (Euclidean)
[2025-03-07 13:53:39,381] [INFO] [30144] Received COMMIT: id:1741323218379, from:30073, delay:0.0000s, distance:50.00m (Euclidean)
[2025-03-07 13:53:39,537] [INFO] [30144] Received PREPARE: id:1741323218379, from:30005, delay:0.0000s, distance:81.92m (Euclidean)
[2025-03-07 13:53:39,537] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,578] [INFO] [30144] Received PREPARE: id:1741323218379, from:30090, delay:0.0000s, distance:150.44m (Euclidean)
[2025-03-07 13:53:39,578] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,690] [INFO] [30144] Received COMMIT: id:1741323218379, from:30090, delay:0.0000s, distance:150.44m (Euclidean)
[2025-03-07 13:53:39,690] [INFO] [30144] Received PREPARE: id:1741323218379, from:30086, delay:0.0000s, distance:79.15m (Euclidean)
[2025-03-07 13:53:39,690] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,690] [INFO] [30144] Received COMMIT: id:1741323218379, from:30086, delay:0.0000s, distance:79.15m (Euclidean)
[2025-03-07 13:53:39,800] [INFO] [30144] Received COMMIT: id:1741323218379, from:30005, delay:0.0000s, distance:81.92m (Euclidean)
[2025-03-07 13:53:40,180] [INFO] [30144] Received PREPARE: id:1741323218379, from:30083, delay:0.0000s, distance:77.36m (Euclidean)
[2025-03-07 13:53:40,180] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,829] [INFO] [30144] Received PREPARE: id:1741323218379, from:30002, delay:0.0000s, distance:114.82m (Euclidean)
[2025-03-07 13:53:40,829] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,829] [INFO] [30144] Received COMMIT: id:1741323218379, from:30002, delay:0.0000s, distance:114.82m (Euclidean)
[2025-03-07 13:53:41,114] [INFO] [30144] Received PREPARE: id:1741323218379, from:30088, delay:0.0001s, distance:151.69m (Euclidean)
[2025-03-07 13:53:41,114] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,116] [INFO] [30144] Received COMMIT: id:1741323218379, from:30088, delay:0.0001s, distance:151.69m (Euclidean)
[2025-03-07 13:53:41,116] [INFO] [30144] Received PREPARE: id:1741323218379, from:30026, delay:0.0001s, distance:191.86m (Euclidean)
[2025-03-07 13:53:41,116] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,116] [INFO] [30144] Received COMMIT: id:1741323218379, from:30026, delay:0.0001s, distance:191.86m (Euclidean)
[2025-03-07 13:53:41,541] [INFO] [30144] Received PREPARE: id:1741323218379, from:30096, delay:0.0001s, distance:236.69m (Euclidean)
[2025-03-07 13:53:41,541] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,596] [INFO] [30144] Received PREPARE: id:1741323218379, from:30060, delay:0.0001s, distance:218.93m (Euclidean)
[2025-03-07 13:53:41,596] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,596] [INFO] [30144] Received COMMIT: id:1741323218379, from:30060, delay:0.0001s, distance:218.93m (Euclidean)
[2025-03-07 13:53:41,636] [INFO] [30144] Received COMMIT: id:1741323218379, from:30096, delay:0.0001s, distance:236.69m (Euclidean)
[2025-03-07 13:53:41,873] [INFO] [30144] Received PREPARE: id:1741323218379, from:30097, delay:0.0001s, distance:216.04m (Euclidean)
[2025-03-07 13:53:41,873] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,873] [INFO] [30144] Received COMMIT: id:1741323218379, from:30097, delay:0.0001s, distance:216.04m (Euclidean)
[2025-03-07 13:53:41,921] [INFO] [30144] Received PREPARE: id:1741323218379, from:30049, delay:0.0000s, distance:131.83m (Euclidean)
[2025-03-07 13:53:41,978] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,371] [INFO] [30144] Received PREPARE: id:1741323218379, from:30016, delay:0.0001s, distance:208.95m (Euclidean)
[2025-03-07 13:53:42,371] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,371] [INFO] [30144] Received COMMIT: id:1741323218379, from:30016, delay:0.0001s, distance:208.95m (Euclidean)
[2025-03-07 13:53:42,553] [INFO] [30144] Received PREPARE: id:1741323218379, from:30117, delay:0.0001s, distance:224.73m (Euclidean)
[2025-03-07 13:53:42,553] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,569] [INFO] [30144] Received COMMIT: id:1741323218379, from:30117, delay:0.0001s, distance:224.73m (Euclidean)
[2025-03-07 13:53:42,590] [INFO] [30144] Received PREPARE: id:1741323218379, from:30001, delay:0.0001s, distance:189.54m (Euclidean)
[2025-03-07 13:53:42,590] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,644] [INFO] [30144] Received PREPARE: id:1741323218379, from:30017, delay:0.0000s, distance:198.18m (Euclidean)
[2025-03-07 13:53:42,644] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,644] [INFO] [30144] Received COMMIT: id:1741323218379, from:30017, delay:0.0000s, distance:198.18m (Euclidean)
[2025-03-07 13:53:42,711] [INFO] [30144] Received COMMIT: id:1741323218379, from:30083, delay:0.0000s, distance:77.36m (Euclidean)
[2025-03-07 13:53:42,711] [INFO] [30144] Received COMMIT: id:1741323218379, from:30001, delay:0.0001s, distance:189.54m (Euclidean)
[2025-03-07 13:53:42,821] [INFO] [30144] Received COMMIT: id:1741323218379, from:30049, delay:0.0000s, distance:131.83m (Euclidean)
[2025-03-07 13:53:42,821] [INFO] [30144] Received PREPARE: id:1741323218379, from:30040, delay:0.0001s, distance:247.93m (Euclidean)
[2025-03-07 13:53:42,821] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,824] [INFO] [30144] Received COMMIT: id:1741323218379, from:30040, delay:0.0001s, distance:247.93m (Euclidean)
[2025-03-07 13:53:42,884] [INFO] [30144] Received PREPARE: id:1741323218379, from:30053, delay:0.0002s, distance:266.27m (Euclidean)
[2025-03-07 13:53:42,884] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,891] [INFO] [30144] Received COMMIT: id:1741323218379, from:30053, delay:0.0002s, distance:266.27m (Euclidean)
[2025-03-07 13:53:42,932] [INFO] [30144] Received PREPARE: id:1741323218379, from:30087, delay:0.0001s, distance:197.29m (Euclidean)
[2025-03-07 13:53:42,932] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,932] [INFO] [30144] Received COMMIT: id:1741323218379, from:30087, delay:0.0001s, distance:197.29m (Euclidean)
[2025-03-07 13:53:43,075] [INFO] [30144] Received PREPARE: id:1741323218379, from:30081, delay:0.0002s, distance:293.20m (Euclidean)
[2025-03-07 13:53:43,075] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,075] [INFO] [30144] Received COMMIT: id:1741323218379, from:30081, delay:0.0002s, distance:293.20m (Euclidean)
[2025-03-07 13:53:43,185] [INFO] [30144] Received PREPARE: id:1741323218379, from:30070, delay:0.0000s, distance:131.76m (Euclidean)
[2025-03-07 13:53:43,185] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,187] [INFO] [30144] Received COMMIT: id:1741323218379, from:30070, delay:0.0000s, distance:131.76m (Euclidean)
[2025-03-07 13:53:43,343] [INFO] [30144] Received PREPARE: id:1741323218379, from:30024, delay:0.0001s, distance:220.99m (Euclidean)
[2025-03-07 13:53:43,343] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,343] [INFO] [30144] Received PREPARE: id:1741323218379, from:30089, delay:0.0001s, distance:243.98m (Euclidean)
[2025-03-07 13:53:43,343] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,345] [INFO] [30144] Received PREPARE: id:1741323218379, from:30055, delay:0.0000s, distance:141.91m (Euclidean)
[2025-03-07 13:53:43,345] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,345] [INFO] [30144] Received COMMIT: id:1741323218379, from:30024, delay:0.0001s, distance:220.99m (Euclidean)
[2025-03-07 13:53:43,345] [INFO] [30144] Received COMMIT: id:1741323218379, from:30089, delay:0.0001s, distance:243.98m (Euclidean)
[2025-03-07 13:53:43,375] [INFO] [30144] Received COMMIT: id:1741323218379, from:30055, delay:0.0000s, distance:141.91m (Euclidean)
[2025-03-07 13:53:43,596] [INFO] [30144] Received PREPARE: id:1741323218379, from:30043, delay:0.0002s, distance:271.23m (Euclidean)
[2025-03-07 13:53:43,596] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,596] [INFO] [30144] Received PREPARE: id:1741323218379, from:30041, delay:0.0001s, distance:219.79m (Euclidean)
[2025-03-07 13:53:43,596] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,596] [INFO] [30144] Received COMMIT: id:1741323218379, from:30043, delay:0.0002s, distance:271.23m (Euclidean)
[2025-03-07 13:53:43,596] [INFO] [30144] Received COMMIT: id:1741323218379, from:30041, delay:0.0001s, distance:219.79m (Euclidean)
[2025-03-07 13:53:43,648] [INFO] [30144] Received PREPARE: id:1741323218379, from:30047, delay:0.0001s, distance:201.44m (Euclidean)
[2025-03-07 13:53:43,648] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,661] [INFO] [30144] Received COMMIT: id:1741323218379, from:30047, delay:0.0001s, distance:201.44m (Euclidean)
[2025-03-07 13:53:43,663] [INFO] [30144] Received PREPARE: id:1741323218379, from:30037, delay:0.0002s, distance:252.92m (Euclidean)
[2025-03-07 13:53:43,663] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,671] [INFO] [30144] Received COMMIT: id:1741323218379, from:30037, delay:0.0002s, distance:252.92m (Euclidean)
[2025-03-07 13:53:44,228] [INFO] [30144] Received PREPARE: id:1741323218379, from:30011, delay:0.0001s, distance:177.05m (Euclidean)
[2025-03-07 13:53:44,228] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,228] [INFO] [30144] Received COMMIT: id:1741323218379, from:30011, delay:0.0001s, distance:177.05m (Euclidean)
[2025-03-07 13:53:44,231] [INFO] [30144] Received PREPARE: id:1741323218379, from:30013, delay:0.0001s, distance:248.13m (Euclidean)
[2025-03-07 13:53:44,231] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,231] [INFO] [30144] Received COMMIT: id:1741323218379, from:30013, delay:0.0001s, distance:248.13m (Euclidean)
[2025-03-07 13:53:44,513] [INFO] [30144] Received PREPARE: id:1741323218379, from:30052, delay:0.0001s, distance:204.06m (Euclidean)
[2025-03-07 13:53:44,513] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,513] [INFO] [30144] Received COMMIT: id:1741323218379, from:30052, delay:0.0001s, distance:204.06m (Euclidean)
[2025-03-07 13:53:44,740] [INFO] [30144] Received PREPARE: id:1741323218379, from:30104, delay:0.0000s, distance:133.30m (Euclidean)
[2025-03-07 13:53:44,740] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,752] [INFO] [30144] Received COMMIT: id:1741323218379, from:30104, delay:0.0000s, distance:133.30m (Euclidean)
[2025-03-07 13:53:44,869] [INFO] [30144] Received PREPARE: id:1741323218379, from:30035, delay:0.0001s, distance:171.27m (Euclidean)
[2025-03-07 13:53:44,869] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,869] [INFO] [30144] Received COMMIT: id:1741323218379, from:30035, delay:0.0001s, distance:171.27m (Euclidean)
[2025-03-07 13:53:44,972] [INFO] [30144] Received PREPARE: id:1741323218379, from:30034, delay:0.0002s, distance:297.91m (Euclidean)
[2025-03-07 13:53:44,972] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,972] [INFO] [30144] Received COMMIT: id:1741323218379, from:30034, delay:0.0002s, distance:297.91m (Euclidean)
[2025-03-07 13:53:45,027] [INFO] [30144] Received PREPARE: id:1741323218379, from:30018, delay:0.0002s, distance:258.78m (Euclidean)
[2025-03-07 13:53:45,027] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,027] [INFO] [30144] Received COMMIT: id:1741323218379, from:30018, delay:0.0002s, distance:258.78m (Euclidean)
[2025-03-07 13:53:45,089] [INFO] [30144] Received PREPARE: id:1741323218379, from:30099, delay:0.0001s, distance:230.25m (Euclidean)
[2025-03-07 13:53:45,089] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,089] [INFO] [30144] Received COMMIT: id:1741323218379, from:30099, delay:0.0001s, distance:230.25m (Euclidean)
[2025-03-07 13:53:45,209] [INFO] [30144] Received PREPARE: id:1741323218379, from:30032, delay:0.0000s, distance:131.74m (Euclidean)
[2025-03-07 13:53:45,209] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,209] [INFO] [30144] Received COMMIT: id:1741323218379, from:30032, delay:0.0000s, distance:131.74m (Euclidean)
[2025-03-07 13:53:45,309] [INFO] [30144] Received PREPARE: id:1741323218379, from:30036, delay:0.0002s, distance:289.54m (Euclidean)
[2025-03-07 13:53:45,309] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,309] [INFO] [30144] Received COMMIT: id:1741323218379, from:30036, delay:0.0002s, distance:289.54m (Euclidean)
[2025-03-07 13:53:45,351] [INFO] [30144] Received PREPARE: id:1741323218379, from:30030, delay:0.0001s, distance:203.49m (Euclidean)
[2025-03-07 13:53:45,351] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,351] [INFO] [30144] Received COMMIT: id:1741323218379, from:30030, delay:0.0001s, distance:203.49m (Euclidean)
[2025-03-07 13:53:45,360] [INFO] [30144] Received PREPARE: id:1741323218379, from:30048, delay:0.0000s, distance:124.53m (Euclidean)
[2025-03-07 13:53:45,360] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,360] [INFO] [30144] Received COMMIT: id:1741323218379, from:30048, delay:0.0000s, distance:124.53m (Euclidean)
[2025-03-07 13:53:45,434] [INFO] [30144] Received PREPARE: id:1741323218379, from:30033, delay:0.0001s, distance:207.50m (Euclidean)
[2025-03-07 13:53:45,434] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,434] [INFO] [30144] Received COMMIT: id:1741323218379, from:30033, delay:0.0001s, distance:207.50m (Euclidean)
[2025-03-07 13:53:45,527] [INFO] [30144] Received PREPARE: id:1741323218379, from:30062, delay:0.0001s, distance:211.69m (Euclidean)
[2025-03-07 13:53:45,527] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,527] [INFO] [30144] Received COMMIT: id:1741323218379, from:30062, delay:0.0001s, distance:211.69m (Euclidean)
[2025-03-07 13:53:45,527] [INFO] [30144] Received COMMIT: id:1741323218379, from:30006, delay:0.0002s, distance:290.61m (Euclidean)
[2025-03-07 13:53:45,527] [INFO] [30144] Received PREPARE: id:1741323218379, from:30006, delay:0.0002s, distance:290.61m (Euclidean)
[2025-03-07 13:53:45,527] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,668] [INFO] [30144] Received PREPARE: id:1741323218379, from:30039, delay:0.0002s, distance:255.21m (Euclidean)
[2025-03-07 13:53:45,668] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,668] [INFO] [30144] Received COMMIT: id:1741323218379, from:30039, delay:0.0002s, distance:255.21m (Euclidean)
[2025-03-07 13:53:45,739] [INFO] [30144] Received PREPARE: id:1741323218379, from:30091, delay:0.0000s, distance:113.37m (Euclidean)
[2025-03-07 13:53:45,739] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,739] [INFO] [30144] Received COMMIT: id:1741323218379, from:30091, delay:0.0000s, distance:113.37m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30144] Received PREPARE: id:1741323218379, from:30046, delay:0.0001s, distance:158.96m (Euclidean)
[2025-03-07 13:53:45,810] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,810] [INFO] [30144] Received COMMIT: id:1741323218379, from:30046, delay:0.0001s, distance:158.96m (Euclidean)
[2025-03-07 13:53:45,905] [INFO] [30144] Received PREPARE: id:1741323218379, from:30058, delay:0.0002s, distance:253.86m (Euclidean)
[2025-03-07 13:53:45,905] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,905] [INFO] [30144] Received COMMIT: id:1741323218379, from:30058, delay:0.0002s, distance:253.86m (Euclidean)
[2025-03-07 13:53:45,952] [INFO] [30144] Received PREPARE: id:1741323218379, from:30014, delay:0.0002s, distance:295.26m (Euclidean)
[2025-03-07 13:53:45,952] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,952] [INFO] [30144] Received COMMIT: id:1741323218379, from:30014, delay:0.0002s, distance:295.26m (Euclidean)
[2025-03-07 13:53:45,968] [INFO] [30144] Received PREPARE: id:1741323218379, from:30003, delay:0.0000s, distance:113.73m (Euclidean)
[2025-03-07 13:53:45,968] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,968] [INFO] [30144] Received COMMIT: id:1741323218379, from:30003, delay:0.0000s, distance:113.73m (Euclidean)
[2025-03-07 13:53:46,174] [INFO] [30144] Received PREPARE: id:1741323218379, from:30004, delay:0.0002s, distance:262.68m (Euclidean)
[2025-03-07 13:53:46,174] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,174] [INFO] [30144] Received COMMIT: id:1741323218379, from:30004, delay:0.0002s, distance:262.68m (Euclidean)
[2025-03-07 13:53:46,398] [INFO] [30144] Received PREPARE: id:1741323218379, from:30028, delay:0.0001s, distance:160.69m (Euclidean)
[2025-03-07 13:53:46,398] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,398] [INFO] [30144] Received COMMIT: id:1741323218379, from:30028, delay:0.0001s, distance:160.69m (Euclidean)
[2025-03-07 13:53:46,586] [INFO] [30144] Received PREPARE: id:1741323218379, from:30102, delay:0.0002s, distance:269.22m (Euclidean)
[2025-03-07 13:53:46,586] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,586] [INFO] [30144] Received COMMIT: id:1741323218379, from:30102, delay:0.0002s, distance:269.22m (Euclidean)
[2025-03-07 13:53:46,649] [INFO] [30144] Received PREPARE: id:1741323218379, from:30010, delay:0.0000s, distance:152.03m (Euclidean)
[2025-03-07 13:53:46,649] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,649] [INFO] [30144] Received COMMIT: id:1741323218379, from:30010, delay:0.0000s, distance:152.03m (Euclidean)
[2025-03-07 13:53:46,791] [INFO] [30144] Received PREPARE: id:1741323218379, from:30110, delay:0.0000s, distance:36.94m (Euclidean)
[2025-03-07 13:53:46,791] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,854] [INFO] [30144] Received PREPARE: id:1741323218379, from:30095, delay:0.0000s, distance:145.80m (Euclidean)
[2025-03-07 13:53:46,871] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,871] [INFO] [30144] Received COMMIT: id:1741323218379, from:30095, delay:0.0000s, distance:145.80m (Euclidean)
[2025-03-07 13:53:47,076] [INFO] [30144] Received PREPARE: id:1741323218379, from:30134, delay:0.0000s, distance:82.08m (Euclidean)
[2025-03-07 13:53:47,076] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,076] [INFO] [30144] Received COMMIT: id:1741323218379, from:30134, delay:0.0000s, distance:82.08m (Euclidean)
[2025-03-07 13:53:47,377] [INFO] [30144] Received COMMIT: id:1741323218379, from:30110, delay:0.0000s, distance:36.94m (Euclidean)
[2025-03-07 13:53:47,469] [INFO] [30144] Received PREPARE: id:1741323218379, from:30158, delay:0.0000s, distance:60.91m (Euclidean)
[2025-03-07 13:53:47,469] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,502] [INFO] [30144] Received PREPARE: id:1741323218379, from:30147, delay:0.0000s, distance:82.65m (Euclidean)
[2025-03-07 13:53:47,502] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,502] [INFO] [30144] Received COMMIT: id:1741323218379, from:30147, delay:0.0000s, distance:82.65m (Euclidean)
[2025-03-07 13:53:47,615] [INFO] [30144] Received COMMIT: id:1741323218379, from:30158, delay:0.0000s, distance:60.91m (Euclidean)
[2025-03-07 13:53:47,693] [INFO] [30144] Received PREPARE: id:1741323218379, from:30122, delay:0.0002s, distance:272.75m (Euclidean)
[2025-03-07 13:53:47,693] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,710] [INFO] [30144] Received COMMIT: id:1741323218379, from:30122, delay:0.0002s, distance:272.75m (Euclidean)
[2025-03-07 13:53:48,027] [INFO] [30144] Received PREPARE: id:1741323218379, from:30154, delay:0.0001s, distance:160.92m (Euclidean)
[2025-03-07 13:53:48,027] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,027] [INFO] [30144] Received COMMIT: id:1741323218379, from:30154, delay:0.0001s, distance:160.92m (Euclidean)
[2025-03-07 13:53:48,071] [INFO] [30144] Received PREPARE: id:1741323218379, from:30105, delay:0.0001s, distance:219.77m (Euclidean)
[2025-03-07 13:53:48,071] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,077] [INFO] [30144] Received COMMIT: id:1741323218379, from:30135, delay:0.0002s, distance:277.10m (Euclidean)
[2025-03-07 13:53:48,077] [INFO] [30144] Received COMMIT: id:1741323218379, from:30105, delay:0.0001s, distance:219.77m (Euclidean)
[2025-03-07 13:53:48,077] [INFO] [30144] Received PREPARE: id:1741323218379, from:30135, delay:0.0002s, distance:277.10m (Euclidean)
[2025-03-07 13:53:48,077] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,214] [INFO] [30144] Received PREPARE: id:1741323218379, from:30157, delay:0.0000s, distance:130.81m (Euclidean)
[2025-03-07 13:53:48,214] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,222] [INFO] [30144] Received COMMIT: id:1741323218379, from:30157, delay:0.0000s, distance:130.81m (Euclidean)
[2025-03-07 13:53:48,249] [INFO] [30144] Received PREPARE: id:1741323218379, from:30153, delay:0.0000s, distance:118.37m (Euclidean)
[2025-03-07 13:53:48,249] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,261] [INFO] [30144] Received COMMIT: id:1741323218379, from:30153, delay:0.0000s, distance:118.37m (Euclidean)
[2025-03-07 13:53:48,311] [INFO] [30144] Received PREPARE: id:1741323218379, from:30136, delay:0.0002s, distance:260.41m (Euclidean)
[2025-03-07 13:53:48,311] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,311] [INFO] [30144] Received COMMIT: id:1741323218379, from:30136, delay:0.0002s, distance:260.41m (Euclidean)
[2025-03-07 13:53:48,462] [INFO] [30144] Received PREPARE: id:1741323218379, from:30128, delay:0.0000s, distance:145.33m (Euclidean)
[2025-03-07 13:53:48,462] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,462] [INFO] [30144] Received COMMIT: id:1741323218379, from:30128, delay:0.0000s, distance:145.33m (Euclidean)
[2025-03-07 13:53:48,532] [INFO] [30144] Received PREPARE: id:1741323218379, from:30139, delay:0.0002s, distance:254.76m (Euclidean)
[2025-03-07 13:53:48,532] [INFO] [30144] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,532] [INFO] [30144] Received COMMIT: id:1741323218379, from:30139, delay:0.0002s, distance:254.76m (Euclidean)
[2025-03-07 13:53:48,693] [INFO] [30144] Received PRE-PREPARE: id:1741323218379, from:Leader(30000), delay:0.0000s, distance:197.58m (Euclidean)
[2025-03-07 13:53:48,693] [INFO] [30144] Broadcasting PREPARE for REQUEST 1741323218379
[2025-03-07 13:53:48,735] [INFO] [30144] Received PREPARE: id:1741323218379, from:30109, delay:0.0001s, distance:229.32m (Euclidean)
[2025-03-07 13:53:48,735] [INFO] [30144] Broadcasting COMMIT for REQUEST 1741323218379
[2025-03-07 13:53:48,750] [INFO] [30144] Received COMMIT: id:1741323218379, from:30109, delay:0.0001s, distance:229.32m (Euclidean)
[2025-03-07 13:53:48,861] [INFO] [30144] Received COMMIT: id:1741323218379, from:30131, delay:0.0000s, distance:191.32m (Euclidean)
[2025-03-07 13:53:48,861] [INFO] [30144] Received PREPARE: id:1741323218379, from:30131, delay:0.0000s, distance:191.32m (Euclidean)
[2025-03-07 13:53:49,062] [INFO] [30144] Received PREPARE: id:1741323218379, from:30133, delay:0.0000s, distance:108.99m (Euclidean)
[2025-03-07 13:53:49,062] [INFO] [30144] Received COMMIT: id:1741323218379, from:30133, delay:0.0000s, distance:108.99m (Euclidean)
[2025-03-07 13:53:49,110] [INFO] [30144] Received PREPARE: id:1741323218379, from:30107, delay:0.0002s, distance:277.02m (Euclidean)
[2025-03-07 13:53:49,114] [INFO] [30144] Received COMMIT: id:1741323218379, from:30107, delay:0.0002s, distance:277.02m (Euclidean)
[2025-03-07 13:53:49,184] [INFO] [30144] Received COMMIT: id:1741323218379, from:30112, delay:0.0000s, distance:81.65m (Euclidean)
[2025-03-07 13:53:49,184] [INFO] [30144] Received PREPARE: id:1741323218379, from:30112, delay:0.0000s, distance:81.65m (Euclidean)
[2025-03-07 13:53:49,388] [INFO] [30144] Received PREPARE: id:1741323218379, from:30151, delay:0.0002s, distance:298.59m (Euclidean)
[2025-03-07 13:53:49,431] [INFO] [30144] Received COMMIT: id:1741323218379, from:30151, delay:0.0002s, distance:298.59m (Euclidean)
[2025-03-07 13:53:49,589] [INFO] [30144] Received PREPARE: id:1741323218379, from:30148, delay:0.0001s, distance:230.78m (Euclidean)
[2025-03-07 13:53:49,745] [INFO] [30144] Received COMMIT: id:1741323218379, from:30148, delay:0.0001s, distance:230.78m (Euclidean)
[2025-03-07 13:53:50,129] [INFO] [30144] Received PREPARE: id:1741323218379, from:30114, delay:0.0002s, distance:273.17m (Euclidean)
[2025-03-07 13:53:50,136] [INFO] [30144] Received COMMIT: id:1741323218379, from:30114, delay:0.0002s, distance:273.17m (Euclidean)
[2025-03-07 13:53:50,232] [INFO] [30144] Received PREPARE: id:1741323218379, from:30126, delay:0.0001s, distance:198.77m (Euclidean)
[2025-03-07 13:53:50,232] [INFO] [30144] Received COMMIT: id:1741323218379, from:30126, delay:0.0001s, distance:198.77m (Euclidean)
[2025-03-07 13:53:50,269] [INFO] [30144] Received PREPARE: id:1741323218379, from:30130, delay:0.0000s, distance:57.58m (Euclidean)
[2025-03-07 13:53:50,316] [INFO] [30144] Received PREPARE: id:1741323218379, from:30015, delay:0.0000s, distance:137.34m (Euclidean)
[2025-03-07 13:53:50,554] [INFO] [30144] Received COMMIT: id:1741323218379, from:30015, delay:0.0000s, distance:137.34m (Euclidean)
[2025-03-07 13:53:50,598] [INFO] [30144] Received COMMIT: id:1741323218379, from:30130, delay:0.0000s, distance:57.58m (Euclidean)
[2025-03-07 13:53:51,012] [INFO] [30144] Received COMMIT: id:1741323218379, from:30000, delay:0.0000s, distance:197.58m (Euclidean)
[2025-03-07 13:53:51,803] [INFO] [30144] Received PREPARE: id:1741323218379, from:30129, delay:0.0000s, distance:176.62m (Euclidean)
[2025-03-07 13:53:51,803] [INFO] [30144] Received COMMIT: id:1741323218379, from:30129, delay:0.0000s, distance:176.62m (Euclidean)
[2025-03-07 13:53:52,655] [INFO] [30144] Received PREPARE: id:1741323218379, from:30121, delay:0.0001s, distance:208.78m (Euclidean)
[2025-03-07 13:53:52,767] [INFO] [30144] Received COMMIT: id:1741323218379, from:30121, delay:0.0001s, distance:208.78m (Euclidean)
[2025-03-07 13:53:52,909] [ERROR] [30144] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:53:52,957] [ERROR] [30144] Error sending to http://localhost:30125/prepare: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('127.0.0.1', 30125)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30125)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('127.0.0.1', 30125)]
[2025-03-07 13:53:52,973] [ERROR] [30144] Error sending to http://localhost:30140/prepare: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('127.0.0.1', 30140)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30140)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('127.0.0.1', 30140)]
[2025-03-07 13:53:53,005] [ERROR] [30144] Error sending to http://localhost:30076/prepare: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
[2025-03-07 13:53:53,005] [ERROR] [30144] Error sending to http://localhost:30138/prepare: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30138)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
[2025-03-07 13:53:53,020] [ERROR] [30144] Error sending to http://localhost:30137/prepare: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30137)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
[2025-03-07 13:53:53,020] [ERROR] [30144] Error sending to http://localhost:30124/prepare: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
[2025-03-07 13:53:53,023] [ERROR] [30144] Error sending to http://localhost:30125/commit: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('::1', 30125, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30125, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('::1', 30125, 0, 0)]
[2025-03-07 13:53:53,052] [ERROR] [30144] Error sending to http://localhost:30075/prepare: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30075)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
[2025-03-07 13:53:53,068] [ERROR] [30144] Error sending to http://localhost:30023/prepare: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30023)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
[2025-03-07 13:53:53,116] [ERROR] [30144] Error sending to http://localhost:30085/prepare: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30085)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
[2025-03-07 13:53:53,116] [ERROR] [30144] Error sending to http://localhost:30138/commit: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30138, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
[2025-03-07 13:53:53,127] [INFO] [30144] Received PREPARE: id:1741323218379, from:30123, delay:0.0001s, distance:185.57m (Euclidean)
[2025-03-07 13:53:53,127] [INFO] [30144] Received COMMIT: id:1741323218379, from:30123, delay:0.0001s, distance:185.57m (Euclidean)
[2025-03-07 13:53:53,131] [ERROR] [30144] Error sending to http://localhost:30023/commit: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30023, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
[2025-03-07 13:53:53,147] [ERROR] [30144] Error sending to http://localhost:30066/commit: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30066, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
[2025-03-07 13:53:53,147] [ERROR] [30144] Error sending to http://localhost:30093/prepare: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30093)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
[2025-03-07 13:53:53,178] [ERROR] [30144] Error sending to http://localhost:30066/prepare: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30066)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
[2025-03-07 13:53:53,194] [ERROR] [30144] Error sending to http://localhost:30027/prepare: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30027)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
[2025-03-07 13:53:53,210] [ERROR] [30144] Error sending to http://localhost:30025/prepare: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('127.0.0.1', 30025)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30025)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('127.0.0.1', 30025)]
[2025-03-07 13:53:53,210] [ERROR] [30144] Error sending to http://localhost:30029/prepare: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30029)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
[2025-03-07 13:53:53,226] [ERROR] [30144] Error sending to http://localhost:30025/commit: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('::1', 30025, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30025, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('::1', 30025, 0, 0)]
[2025-03-07 13:53:53,242] [ERROR] [30144] Error sending to http://localhost:30027/commit: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30027, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
[2025-03-07 13:53:53,242] [ERROR] [30144] Error sending to http://localhost:30093/commit: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30093, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
[2025-03-07 13:53:53,274] [ERROR] [30144] Error sending to http://localhost:30101/prepare: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30101)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
[2025-03-07 13:53:53,276] [ERROR] [30144] Error sending to http://localhost:30100/prepare: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('127.0.0.1', 30100)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30100)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('127.0.0.1', 30100)]
[2025-03-07 13:53:53,276] [ERROR] [30144] Error sending to http://localhost:30101/commit: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30101, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
[2025-03-07 13:53:53,290] [ERROR] [30144] Error sending to http://localhost:30029/commit: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30029, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
[2025-03-07 13:53:53,305] [ERROR] [30144] Error sending to http://localhost:30100/commit: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('::1', 30100, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30100, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('::1', 30100, 0, 0)]
[2025-03-07 13:53:53,321] [ERROR] [30144] Error sending to http://localhost:30124/commit: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30124, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
[2025-03-07 13:53:53,341] [INFO] [30144] Received PREPARE: id:1741323218379, from:30142, delay:0.0000s, distance:136.41m (Euclidean)
[2025-03-07 13:53:53,341] [INFO] [30144] Received COMMIT: id:1741323218379, from:30142, delay:0.0000s, distance:136.41m (Euclidean)
[2025-03-07 13:53:53,352] [ERROR] [30144] Error sending to http://localhost:30137/commit: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30137, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
[2025-03-07 13:53:53,368] [ERROR] [30144] Error sending to http://localhost:30141/prepare: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('127.0.0.1', 30141)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30141)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('127.0.0.1', 30141)]
[2025-03-07 13:53:53,400] [ERROR] [30144] Error sending to http://localhost:30085/commit: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30085, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
[2025-03-07 13:53:53,416] [ERROR] [30144] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:53:53,416] [INFO] [30144] Received PREPARE: id:1741323218379, from:30118, delay:0.0001s, distance:223.69m (Euclidean)
[2025-03-07 13:53:53,416] [INFO] [30144] Received COMMIT: id:1741323218379, from:30118, delay:0.0001s, distance:223.69m (Euclidean)
[2025-03-07 13:53:53,432] [ERROR] [30144] Error sending to http://localhost:30076/commit: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30076, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
[2025-03-07 13:53:53,448] [ERROR] [30144] Error sending to http://localhost:30065/prepare: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('127.0.0.1', 30065)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30065)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('127.0.0.1', 30065)]
[2025-03-07 13:53:53,480] [ERROR] [30144] Error sending to http://localhost:30065/commit: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('::1', 30065, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30065, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('::1', 30065, 0, 0)]
[2025-03-07 13:53:53,496] [ERROR] [30144] Error sending to http://localhost:30103/prepare: Cannot connect to host localhost:30103 ssl:default [Connect call failed ('127.0.0.1', 30103)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30103)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30103 ssl:default [Connect call failed ('127.0.0.1', 30103)]
[2025-03-07 13:53:53,496] [ERROR] [30144] Error sending to http://localhost:30103/commit: Cannot connect to host localhost:30103 ssl:default [Connect call failed ('::1', 30103, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30103, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30103 ssl:default [Connect call failed ('::1', 30103, 0, 0)]
[2025-03-07 13:53:53,527] [ERROR] [30144] Error sending to http://localhost:30140/commit: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('::1', 30140, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30140, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('::1', 30140, 0, 0)]
[2025-03-07 13:53:53,559] [ERROR] [30144] Error sending to http://localhost:30141/commit: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('::1', 30141, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30141, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('::1', 30141, 0, 0)]
[2025-03-07 13:53:53,574] [ERROR] [30144] Error sending to http://localhost:30075/commit: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30075, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
[2025-03-07 13:53:53,590] [ERROR] [30144] Error sending to http://localhost:30038/prepare: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('127.0.0.1', 30038)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30038)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('127.0.0.1', 30038)]
[2025-03-07 13:53:53,590] [ERROR] [30144] Error sending to http://localhost:30038/commit: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('::1', 30038, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30038, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('::1', 30038, 0, 0)]
[2025-03-07 13:53:53,627] [INFO] [30144] Received PREPARE: id:1741323218379, from:30113, delay:0.0000s, distance:120.16m (Euclidean)
[2025-03-07 13:53:53,627] [INFO] [30144] Received COMMIT: id:1741323218379, from:30113, delay:0.0000s, distance:120.16m (Euclidean)
[2025-03-07 13:53:53,970] [INFO] [30144] Received PREPARE: id:1741323218379, from:30120, delay:0.0001s, distance:164.57m (Euclidean)
[2025-03-07 13:53:53,986] [INFO] [30144] Received COMMIT: id:1741323218379, from:30120, delay:0.0001s, distance:164.57m (Euclidean)
[2025-03-07 13:53:54,002] [INFO] [30144] Received PREPARE: id:1741323218379, from:30149, delay:0.0001s, distance:154.04m (Euclidean)
[2025-03-07 13:53:54,002] [INFO] [30144] Received COMMIT: id:1741323218379, from:30149, delay:0.0001s, distance:154.04m (Euclidean)
[2025-03-07 13:53:54,041] [INFO] [30144] Received PREPARE: id:1741323218379, from:30106, delay:0.0002s, distance:296.60m (Euclidean)
[2025-03-07 13:53:54,041] [INFO] [30144] Received COMMIT: id:1741323218379, from:30106, delay:0.0002s, distance:296.60m (Euclidean)
[2025-03-07 13:53:54,195] [INFO] [30144] Received PREPARE: id:1741323218379, from:30132, delay:0.0002s, distance:260.17m (Euclidean)
[2025-03-07 13:53:54,195] [INFO] [30144] Received COMMIT: id:1741323218379, from:30132, delay:0.0002s, distance:260.17m (Euclidean)
[2025-03-07 13:53:54,224] [INFO] [30144] Received PREPARE: id:1741323218379, from:30111, delay:0.0000s, distance:180.04m (Euclidean)
[2025-03-07 13:53:54,224] [INFO] [30144] Received COMMIT: id:1741323218379, from:30111, delay:0.0000s, distance:180.04m (Euclidean)
[2025-03-07 13:53:54,261] [INFO] [30144] Received PREPARE: id:1741323218379, from:30145, delay:0.0001s, distance:245.18m (Euclidean)
[2025-03-07 13:53:54,265] [INFO] [30144] Received PREPARE: id:1741323218379, from:30146, delay:0.0001s, distance:232.83m (Euclidean)
[2025-03-07 13:53:54,265] [INFO] [30144] Received COMMIT: id:1741323218379, from:30145, delay:0.0001s, distance:245.18m (Euclidean)
[2025-03-07 13:53:54,271] [INFO] [30144] Received PREPARE: id:1741323218379, from:30108, delay:0.0002s, distance:253.34m (Euclidean)
[2025-03-07 13:53:54,271] [INFO] [30144] Received COMMIT: id:1741323218379, from:30108, delay:0.0002s, distance:253.34m (Euclidean)
[2025-03-07 13:53:54,334] [INFO] [30144] Received PREPARE: id:1741323218379, from:30115, delay:0.0001s, distance:211.14m (Euclidean)
[2025-03-07 13:53:54,356] [INFO] [30144] Received COMMIT: id:1741323218379, from:30115, delay:0.0001s, distance:211.14m (Euclidean)
[2025-03-07 13:53:54,499] [INFO] [30144] Received PREPARE: id:1741323218379, from:30152, delay:0.0002s, distance:267.69m (Euclidean)
[2025-03-07 13:53:54,511] [INFO] [30144] Received COMMIT: id:1741323218379, from:30152, delay:0.0002s, distance:267.69m (Euclidean)
[2025-03-07 13:53:54,511] [INFO] [30144] Received PREPARE: id:1741323218379, from:30156, delay:0.0001s, distance:244.01m (Euclidean)
[2025-03-07 13:53:54,524] [INFO] [30144] Received COMMIT: id:1741323218379, from:30146, delay:0.0001s, distance:232.83m (Euclidean)
[2025-03-07 13:53:54,581] [INFO] [30144] Received COMMIT: id:1741323218379, from:30156, delay:0.0001s, distance:244.01m (Euclidean)
[2025-03-07 13:53:55,692] [INFO] [30144] Received PREPARE: id:1741323218379, from:30155, delay:0.0001s, distance:239.10m (Euclidean)
[2025-03-07 13:53:55,692] [INFO] [30144] Received COMMIT: id:1741323218379, from:30155, delay:0.0001s, distance:239.10m (Euclidean)
[2025-03-07 13:54:56,669] [INFO] Starting node at localhost:30144 | index=145 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:43,105] [INFO] Starting node at localhost:30144 | index=145 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:45,537] [INFO] Starting node at localhost:30144 | index=145 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:02,502] [INFO] [30144] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0000s, distance:86.65m (Euclidean)
[2025-03-07 13:59:02,502] [INFO] [30144] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:02,514] [INFO] [30144] Not broadcasting to fault node: 30077
[2025-03-07 13:59:02,530] [INFO] [30144] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,090] [INFO] [30144] Received PREPARE: id:1741323542381, from:30171, delay:0.0000s, distance:150.37m (Euclidean)
[2025-03-07 13:59:03,509] [INFO] [30144] Received COMMIT: id:1741323542381, from:30171, delay:0.0000s, distance:150.37m (Euclidean)
[2025-03-07 13:59:03,677] [INFO] [30144] Received PREPARE: id:1741323542381, from:30155, delay:0.0000s, distance:95.46m (Euclidean)
[2025-03-07 13:59:03,677] [INFO] [30144] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:03,689] [INFO] [30144] Not broadcasting to fault node: 30077
[2025-03-07 13:59:03,712] [INFO] [30144] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,839] [INFO] [30144] Received PREPARE: id:1741323542381, from:30136, delay:0.0000s, distance:28.84m (Euclidean)
[2025-03-07 13:59:03,840] [INFO] [30144] Received PREPARE: id:1741323542381, from:30119, delay:0.0000s, distance:123.99m (Euclidean)
[2025-03-07 13:59:03,840] [INFO] [30144] Received PREPARE: id:1741323542381, from:30128, delay:0.0000s, distance:113.06m (Euclidean)
[2025-03-07 13:59:03,869] [INFO] [30144] Received COMMIT: id:1741323542381, from:30155, delay:0.0000s, distance:95.46m (Euclidean)
[2025-03-07 13:59:03,869] [INFO] [LEADER 30144] Sending REPLY for REQUEST 1741323542381 to CLIENT
[2025-03-07 13:59:04,118] [INFO] [30144] Received PREPARE: id:1741323542381, from:30182, delay:0.0000s, distance:86.17m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30144] Received PREPARE: id:1741323542381, from:30180, delay:0.0000s, distance:59.24m (Euclidean)
[2025-03-07 13:59:04,297] [INFO] [30144] Received PREPARE: id:1741323542381, from:30126, delay:0.0001s, distance:198.73m (Euclidean)
[2025-03-07 13:59:04,340] [INFO] [30144] Received PREPARE: id:1741323542381, from:30005, delay:0.0000s, distance:83.77m (Euclidean)
[2025-03-07 13:59:04,352] [INFO] [30144] Received COMMIT: id:1741323542381, from:30005, delay:0.0000s, distance:83.77m (Euclidean)
[2025-03-07 13:59:04,371] [INFO] [30144] Received PREPARE: id:1741323542381, from:30167, delay:0.0000s, distance:96.69m (Euclidean)
[2025-03-07 13:59:04,485] [INFO] [30144] Received PREPARE: id:1741323542381, from:30037, delay:0.0001s, distance:173.39m (Euclidean)
[2025-03-07 13:59:04,501] [INFO] [30144] Received PREPARE: id:1741323542381, from:30035, delay:0.0000s, distance:89.29m (Euclidean)
[2025-03-07 13:59:04,507] [INFO] [30144] Received PREPARE: id:1741323542381, from:30100, delay:0.0000s, distance:132.29m (Euclidean)
[2025-03-07 13:59:04,568] [INFO] [30144] Received PREPARE: id:1741323542381, from:30107, delay:0.0000s, distance:51.34m (Euclidean)
[2025-03-07 13:59:04,568] [INFO] [30144] Received COMMIT: id:1741323542381, from:30167, delay:0.0000s, distance:96.69m (Euclidean)
[2025-03-07 13:59:04,626] [INFO] [30144] Received PREPARE: id:1741323542381, from:30080, delay:0.0001s, distance:204.08m (Euclidean)
[2025-03-07 13:59:04,683] [INFO] [30144] Received PREPARE: id:1741323542381, from:30124, delay:0.0001s, distance:163.50m (Euclidean)
[2025-03-07 13:59:04,697] [INFO] [30144] Received COMMIT: id:1741323542381, from:30124, delay:0.0001s, distance:163.50m (Euclidean)
[2025-03-07 13:59:04,697] [INFO] [30144] Received PREPARE: id:1741323542381, from:30168, delay:0.0001s, distance:188.54m (Euclidean)
[2025-03-07 13:59:04,699] [INFO] [30144] Received COMMIT: id:1741323542381, from:30168, delay:0.0001s, distance:188.54m (Euclidean)
[2025-03-07 13:59:04,762] [INFO] [30144] Received COMMIT: id:1741323542381, from:30128, delay:0.0000s, distance:113.06m (Euclidean)
[2025-03-07 13:59:04,847] [INFO] [30144] Received PREPARE: id:1741323542381, from:30147, delay:0.0000s, distance:113.07m (Euclidean)
[2025-03-07 13:59:04,849] [INFO] [30144] Received COMMIT: id:1741323542381, from:30136, delay:0.0000s, distance:28.84m (Euclidean)
[2025-03-07 13:59:04,850] [INFO] [30144] Received COMMIT: id:1741323542381, from:30147, delay:0.0000s, distance:113.07m (Euclidean)
[2025-03-07 13:59:04,853] [INFO] [30144] Received COMMIT: id:1741323542381, from:30100, delay:0.0000s, distance:132.29m (Euclidean)
[2025-03-07 13:59:04,898] [INFO] [30144] Received COMMIT: id:1741323542381, from:30180, delay:0.0000s, distance:59.24m (Euclidean)
[2025-03-07 13:59:04,944] [INFO] [30144] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:106.97m (Euclidean)
[2025-03-07 13:59:04,993] [INFO] [30144] Received PREPARE: id:1741323542381, from:30195, delay:0.0000s, distance:115.37m (Euclidean)
[2025-03-07 13:59:05,046] [INFO] [30144] Received PREPARE: id:1741323542381, from:30095, delay:0.0001s, distance:201.60m (Euclidean)
[2025-03-07 13:59:05,328] [INFO] [30144] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:147.06m (Euclidean)
[2025-03-07 13:59:05,366] [INFO] [30144] Received COMMIT: id:1741323542381, from:30126, delay:0.0001s, distance:198.73m (Euclidean)
[2025-03-07 13:59:05,389] [INFO] [30144] Received PREPARE: id:1741323542381, from:30048, delay:0.0000s, distance:61.04m (Euclidean)
[2025-03-07 13:59:05,495] [INFO] [30144] Received COMMIT: id:1741323542381, from:30095, delay:0.0001s, distance:201.60m (Euclidean)
[2025-03-07 13:59:05,537] [INFO] [30144] Received PREPARE: id:1741323542381, from:30154, delay:0.0000s, distance:79.75m (Euclidean)
[2025-03-07 13:59:05,576] [INFO] [30144] Received COMMIT: id:1741323542381, from:30154, delay:0.0000s, distance:79.75m (Euclidean)
[2025-03-07 13:59:05,712] [INFO] [30144] Received COMMIT: id:1741323542381, from:30195, delay:0.0000s, distance:115.37m (Euclidean)
[2025-03-07 13:59:05,737] [INFO] [30144] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:147.06m (Euclidean)
[2025-03-07 13:59:05,854] [INFO] [30144] Received PREPARE: id:1741323542381, from:30199, delay:0.0001s, distance:192.48m (Euclidean)
[2025-03-07 13:59:05,892] [INFO] [30144] Received PREPARE: id:1741323542381, from:30190, delay:0.0001s, distance:221.18m (Euclidean)
[2025-03-07 13:59:06,058] [INFO] [30144] Received COMMIT: id:1741323542381, from:30080, delay:0.0001s, distance:204.08m (Euclidean)
[2025-03-07 13:59:06,058] [INFO] [30144] Received COMMIT: id:1741323542381, from:30048, delay:0.0000s, distance:61.04m (Euclidean)
[2025-03-07 13:59:06,098] [INFO] [30144] Received COMMIT: id:1741323542381, from:30037, delay:0.0001s, distance:173.39m (Euclidean)
[2025-03-07 13:59:06,179] [INFO] [30144] Received PREPARE: id:1741323542381, from:30027, delay:0.0001s, distance:202.75m (Euclidean)
[2025-03-07 13:59:06,194] [INFO] [30144] Received PREPARE: id:1741323542381, from:30013, delay:0.0001s, distance:225.93m (Euclidean)
[2025-03-07 13:59:06,246] [INFO] [30144] Received PREPARE: id:1741323542381, from:30028, delay:0.0001s, distance:155.63m (Euclidean)
[2025-03-07 13:59:06,310] [INFO] [30144] Received COMMIT: id:1741323542381, from:30027, delay:0.0001s, distance:202.75m (Euclidean)
[2025-03-07 13:59:06,312] [INFO] [30144] Received COMMIT: id:1741323542381, from:30028, delay:0.0001s, distance:155.63m (Euclidean)
[2025-03-07 13:59:06,316] [INFO] [30144] Received PREPARE: id:1741323542381, from:30025, delay:0.0001s, distance:189.54m (Euclidean)
[2025-03-07 13:59:06,331] [INFO] [30144] Received COMMIT: id:1741323542381, from:30190, delay:0.0001s, distance:221.18m (Euclidean)
[2025-03-07 13:59:06,357] [INFO] [30144] Received PREPARE: id:1741323542381, from:30170, delay:0.0000s, distance:156.47m (Euclidean)
[2025-03-07 13:59:06,415] [INFO] [30144] Received PREPARE: id:1741323542381, from:30098, delay:0.0001s, distance:180.26m (Euclidean)
[2025-03-07 13:59:06,420] [INFO] [30144] Received COMMIT: id:1741323542381, from:30170, delay:0.0000s, distance:156.47m (Euclidean)
[2025-03-07 13:59:06,450] [INFO] [30144] Received PREPARE: id:1741323542381, from:30127, delay:0.0001s, distance:220.58m (Euclidean)
[2025-03-07 13:59:06,470] [INFO] [30144] Received COMMIT: id:1741323542381, from:30023, delay:0.0001s, distance:213.06m (Euclidean)
[2025-03-07 13:59:06,472] [INFO] [30144] Received PREPARE: id:1741323542381, from:30023, delay:0.0001s, distance:213.06m (Euclidean)
[2025-03-07 13:59:06,486] [INFO] [30144] Received COMMIT: id:1741323542381, from:30098, delay:0.0001s, distance:180.26m (Euclidean)
[2025-03-07 13:59:06,496] [INFO] [30144] Received COMMIT: id:1741323542381, from:30025, delay:0.0001s, distance:189.54m (Euclidean)
[2025-03-07 13:59:06,588] [INFO] [30144] Received COMMIT: id:1741323542381, from:30107, delay:0.0000s, distance:51.34m (Euclidean)
[2025-03-07 13:59:06,645] [INFO] [30144] Received COMMIT: id:1741323542381, from:30013, delay:0.0001s, distance:225.93m (Euclidean)
[2025-03-07 13:59:06,710] [INFO] [30144] Received PREPARE: id:1741323542381, from:30092, delay:0.0001s, distance:169.31m (Euclidean)
[2025-03-07 13:59:06,710] [INFO] [30144] Received COMMIT: id:1741323542381, from:30127, delay:0.0001s, distance:220.58m (Euclidean)
[2025-03-07 13:59:06,789] [INFO] [30144] Received PREPARE: id:1741323542381, from:30196, delay:0.0001s, distance:183.64m (Euclidean)
[2025-03-07 13:59:06,847] [INFO] [30144] Received PREPARE: id:1741323542381, from:30066, delay:0.0000s, distance:162.21m (Euclidean)
[2025-03-07 13:59:06,849] [INFO] [30144] Received COMMIT: id:1741323542381, from:30066, delay:0.0000s, distance:162.21m (Euclidean)
[2025-03-07 13:59:06,856] [INFO] [30144] Received PREPARE: id:1741323542381, from:30110, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:59:06,862] [INFO] [30144] Received PREPARE: id:1741323542381, from:30150, delay:0.0000s, distance:117.69m (Euclidean)
[2025-03-07 13:59:06,878] [INFO] [30144] Received PREPARE: id:1741323542381, from:30076, delay:0.0000s, distance:141.13m (Euclidean)
[2025-03-07 13:59:06,915] [INFO] [30144] Received PREPARE: id:1741323542381, from:30085, delay:0.0000s, distance:184.93m (Euclidean)
[2025-03-07 13:59:07,038] [INFO] [30144] Received PREPARE: id:1741323542381, from:30169, delay:0.0002s, distance:294.20m (Euclidean)
[2025-03-07 13:59:07,043] [INFO] [30144] Received PREPARE: id:1741323542381, from:30102, delay:0.0000s, distance:98.98m (Euclidean)
[2025-03-07 13:59:07,087] [INFO] [30144] Received COMMIT: id:1741323542381, from:30110, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:59:07,109] [INFO] [30144] Received PREPARE: id:1741323542381, from:30024, delay:0.0000s, distance:119.54m (Euclidean)
[2025-03-07 13:59:07,111] [INFO] [30144] Received COMMIT: id:1741323542381, from:30024, delay:0.0000s, distance:119.54m (Euclidean)
[2025-03-07 13:59:07,178] [INFO] [30144] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:131.76m (Euclidean)
[2025-03-07 13:59:07,182] [INFO] [30144] Received COMMIT: id:1741323542381, from:30169, delay:0.0002s, distance:294.20m (Euclidean)
[2025-03-07 13:59:07,242] [INFO] [30144] Received COMMIT: id:1741323542381, from:30196, delay:0.0001s, distance:183.64m (Euclidean)
[2025-03-07 13:59:07,404] [INFO] [30144] Received COMMIT: id:1741323542381, from:30150, delay:0.0000s, distance:117.69m (Euclidean)
[2025-03-07 13:59:07,404] [INFO] [30144] Received COMMIT: id:1741323542381, from:30102, delay:0.0000s, distance:98.98m (Euclidean)
[2025-03-07 13:59:07,404] [INFO] [30144] Received PREPARE: id:1741323542381, from:30089, delay:0.0001s, distance:215.40m (Euclidean)
[2025-03-07 13:59:07,406] [INFO] [30144] Received COMMIT: id:1741323542381, from:30085, delay:0.0000s, distance:184.93m (Euclidean)
[2025-03-07 13:59:07,530] [INFO] [30144] Received PREPARE: id:1741323542381, from:30056, delay:0.0001s, distance:159.27m (Euclidean)
[2025-03-07 13:59:07,534] [INFO] [30144] Received COMMIT: id:1741323542381, from:30056, delay:0.0001s, distance:159.27m (Euclidean)
[2025-03-07 13:59:07,623] [INFO] [30144] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:106.97m (Euclidean)
[2025-03-07 13:59:07,623] [INFO] [30144] Received COMMIT: id:1741323542381, from:30199, delay:0.0001s, distance:192.48m (Euclidean)
[2025-03-07 13:59:07,638] [INFO] [30144] Received PREPARE: id:1741323542381, from:30118, delay:0.0001s, distance:205.29m (Euclidean)
[2025-03-07 13:59:07,638] [INFO] [30144] Received PREPARE: id:1741323542381, from:30133, delay:0.0001s, distance:165.96m (Euclidean)
[2025-03-07 13:59:07,652] [INFO] [30144] Received COMMIT: id:1741323542381, from:30089, delay:0.0001s, distance:215.40m (Euclidean)
[2025-03-07 13:59:07,772] [INFO] [30144] Received PREPARE: id:1741323542381, from:30070, delay:0.0000s, distance:136.22m (Euclidean)
[2025-03-07 13:59:07,772] [INFO] [30144] Received PREPARE: id:1741323542381, from:30040, delay:0.0001s, distance:178.28m (Euclidean)
[2025-03-07 13:59:07,777] [INFO] [30144] Received COMMIT: id:1741323542381, from:30040, delay:0.0001s, distance:178.28m (Euclidean)
[2025-03-07 13:59:07,805] [INFO] [30144] Received PREPARE: id:1741323542381, from:30121, delay:0.0001s, distance:210.50m (Euclidean)
[2025-03-07 13:59:07,807] [INFO] [30144] Received COMMIT: id:1741323542381, from:30121, delay:0.0001s, distance:210.50m (Euclidean)
[2025-03-07 13:59:07,819] [INFO] [30144] Received PREPARE: id:1741323542381, from:30109, delay:0.0000s, distance:124.57m (Euclidean)
[2025-03-07 13:59:07,825] [INFO] [30144] Received COMMIT: id:1741323542381, from:30076, delay:0.0000s, distance:141.13m (Euclidean)
[2025-03-07 13:59:07,841] [INFO] [30144] Received COMMIT: id:1741323542381, from:30119, delay:0.0000s, distance:123.99m (Euclidean)
[2025-03-07 13:59:07,904] [INFO] [30144] Received PREPARE: id:1741323542381, from:30112, delay:0.0001s, distance:240.72m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30144] Received COMMIT: id:1741323542381, from:30070, delay:0.0000s, distance:136.22m (Euclidean)
[2025-03-07 13:59:07,951] [INFO] [30144] Received PREPARE: id:1741323542381, from:30174, delay:0.0000s, distance:130.80m (Euclidean)
[2025-03-07 13:59:07,971] [INFO] [30144] Received PREPARE: id:1741323542381, from:30181, delay:0.0001s, distance:187.05m (Euclidean)
[2025-03-07 13:59:07,976] [INFO] [30144] Received COMMIT: id:1741323542381, from:30181, delay:0.0001s, distance:187.05m (Euclidean)
[2025-03-07 13:59:08,056] [INFO] [30144] Received COMMIT: id:1741323542381, from:30133, delay:0.0001s, distance:165.96m (Euclidean)
[2025-03-07 13:59:08,090] [INFO] [30144] Received COMMIT: id:1741323542381, from:30092, delay:0.0001s, distance:169.31m (Euclidean)
[2025-03-07 13:59:08,090] [INFO] [30144] Received PREPARE: id:1741323542381, from:30060, delay:0.0001s, distance:218.65m (Euclidean)
[2025-03-07 13:59:08,090] [INFO] [30144] Received COMMIT: id:1741323542381, from:30060, delay:0.0001s, distance:218.65m (Euclidean)
[2025-03-07 13:59:08,140] [INFO] [30144] Received COMMIT: id:1741323542381, from:30112, delay:0.0001s, distance:240.72m (Euclidean)
[2025-03-07 13:59:08,193] [INFO] [30144] Received COMMIT: id:1741323542381, from:30035, delay:0.0000s, distance:89.29m (Euclidean)
[2025-03-07 13:59:08,195] [INFO] [30144] Received COMMIT: id:1741323542381, from:30109, delay:0.0000s, distance:124.57m (Euclidean)
[2025-03-07 13:59:08,211] [INFO] [30144] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:131.76m (Euclidean)
[2025-03-07 13:59:08,281] [INFO] [30144] Received PREPARE: id:1741323542381, from:30157, delay:0.0001s, distance:163.42m (Euclidean)
[2025-03-07 13:59:08,281] [INFO] [30144] Received COMMIT: id:1741323542381, from:30157, delay:0.0001s, distance:163.42m (Euclidean)
[2025-03-07 13:59:08,347] [INFO] [30144] Received COMMIT: id:1741323542381, from:30118, delay:0.0001s, distance:205.29m (Euclidean)
[2025-03-07 13:59:08,543] [INFO] [30144] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:157.14m (Euclidean)
[2025-03-07 13:59:08,543] [INFO] [30144] Received PREPARE: id:1741323542381, from:30029, delay:0.0001s, distance:211.87m (Euclidean)
[2025-03-07 13:59:08,565] [INFO] [30144] Received COMMIT: id:1741323542381, from:30029, delay:0.0001s, distance:211.87m (Euclidean)
[2025-03-07 13:59:08,565] [INFO] [30144] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:157.14m (Euclidean)
[2025-03-07 13:59:08,661] [INFO] [30144] Received PREPARE: id:1741323542381, from:30020, delay:0.0000s, distance:93.98m (Euclidean)
[2025-03-07 13:59:08,798] [INFO] [30144] Received COMMIT: id:1741323542381, from:30174, delay:0.0000s, distance:130.80m (Euclidean)
[2025-03-07 13:59:09,159] [INFO] [30144] Received PREPARE: id:1741323542381, from:30120, delay:0.0000s, distance:138.36m (Euclidean)
[2025-03-07 13:59:09,162] [INFO] [30144] Received COMMIT: id:1741323542381, from:30120, delay:0.0000s, distance:138.36m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30144] Received PREPARE: id:1741323542381, from:30189, delay:0.0001s, distance:153.88m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30144] Received COMMIT: id:1741323542381, from:30182, delay:0.0000s, distance:86.17m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30144] Received COMMIT: id:1741323542381, from:30020, delay:0.0000s, distance:93.98m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30144] Received PREPARE: id:1741323542381, from:30062, delay:0.0000s, distance:111.58m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30144] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:108.02m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30144] Received COMMIT: id:1741323542381, from:30062, delay:0.0000s, distance:111.58m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30144] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:108.02m (Euclidean)
[2025-03-07 13:59:09,446] [INFO] [30144] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:174.64m (Euclidean)
[2025-03-07 13:59:09,448] [INFO] [30144] Received PREPARE: id:1741323542381, from:30046, delay:0.0000s, distance:149.87m (Euclidean)
[2025-03-07 13:59:09,455] [INFO] [30144] Received COMMIT: id:1741323542381, from:30046, delay:0.0000s, distance:149.87m (Euclidean)
[2025-03-07 13:59:09,455] [INFO] [30144] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:174.64m (Euclidean)
[2025-03-07 13:59:09,594] [INFO] [30144] Received COMMIT: id:1741323542381, from:30189, delay:0.0001s, distance:153.88m (Euclidean)
[2025-03-07 13:59:09,666] [INFO] [30144] Received PREPARE: id:1741323542381, from:30051, delay:0.0001s, distance:194.26m (Euclidean)
[2025-03-07 13:59:09,666] [INFO] [30144] Received COMMIT: id:1741323542381, from:30051, delay:0.0001s, distance:194.26m (Euclidean)
[2025-03-07 13:59:09,878] [INFO] [30144] Received PREPARE: id:1741323542381, from:30116, delay:0.0001s, distance:206.11m (Euclidean)
[2025-03-07 13:59:09,886] [INFO] [30144] Received PREPARE: id:1741323542381, from:30093, delay:0.0001s, distance:179.43m (Euclidean)
[2025-03-07 13:59:09,886] [INFO] [30144] Received PREPARE: id:1741323542381, from:30123, delay:0.0001s, distance:208.39m (Euclidean)
[2025-03-07 13:59:09,886] [INFO] [30144] Received PREPARE: id:1741323542381, from:30015, delay:0.0000s, distance:90.78m (Euclidean)
[2025-03-07 13:59:09,886] [INFO] [30144] Received PREPARE: id:1741323542381, from:30103, delay:0.0000s, distance:63.87m (Euclidean)
[2025-03-07 13:59:09,927] [INFO] [30144] Received COMMIT: id:1741323542381, from:30103, delay:0.0000s, distance:63.87m (Euclidean)
[2025-03-07 13:59:09,927] [INFO] [30144] Received COMMIT: id:1741323542381, from:30123, delay:0.0001s, distance:208.39m (Euclidean)
[2025-03-07 13:59:09,927] [INFO] [30144] Received COMMIT: id:1741323542381, from:30116, delay:0.0001s, distance:206.11m (Euclidean)
[2025-03-07 13:59:09,927] [INFO] [30144] Received COMMIT: id:1741323542381, from:30015, delay:0.0000s, distance:90.78m (Euclidean)
[2025-03-07 13:59:09,929] [INFO] [30144] Received COMMIT: id:1741323542381, from:30093, delay:0.0001s, distance:179.43m (Euclidean)
[2025-03-07 13:59:09,998] [INFO] [30144] Received PREPARE: id:1741323542381, from:30059, delay:0.0001s, distance:198.91m (Euclidean)
[2025-03-07 13:59:09,998] [INFO] [30144] Received PREPARE: id:1741323542381, from:30106, delay:0.0001s, distance:239.20m (Euclidean)
[2025-03-07 13:59:10,002] [INFO] [30144] Received COMMIT: id:1741323542381, from:30059, delay:0.0001s, distance:198.91m (Euclidean)
[2025-03-07 13:59:10,002] [INFO] [30144] Received COMMIT: id:1741323542381, from:30106, delay:0.0001s, distance:239.20m (Euclidean)
[2025-03-07 13:59:10,087] [INFO] [30144] Received PREPARE: id:1741323542381, from:30057, delay:0.0001s, distance:238.09m (Euclidean)
[2025-03-07 13:59:10,087] [INFO] [30144] Received PREPARE: id:1741323542381, from:30165, delay:0.0000s, distance:299.12m (Euclidean)
[2025-03-07 13:59:10,087] [INFO] [30144] Received COMMIT: id:1741323542381, from:30057, delay:0.0001s, distance:238.09m (Euclidean)
[2025-03-07 13:59:10,500] [INFO] [30144] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:117.92m (Euclidean)
[2025-03-07 13:59:10,500] [INFO] [30144] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:117.92m (Euclidean)
[2025-03-07 13:59:10,516] [INFO] [30144] Received PREPARE: id:1741323542381, from:30096, delay:0.0001s, distance:178.30m (Euclidean)
[2025-03-07 13:59:10,569] [INFO] [30144] Received COMMIT: id:1741323542381, from:30096, delay:0.0001s, distance:178.30m (Euclidean)
[2025-03-07 13:59:10,589] [INFO] [30144] Received PREPARE: id:1741323542381, from:30179, delay:0.0000s, distance:115.49m (Euclidean)
[2025-03-07 13:59:10,589] [INFO] [30144] Received COMMIT: id:1741323542381, from:30179, delay:0.0000s, distance:115.49m (Euclidean)
[2025-03-07 13:59:10,682] [INFO] [30144] Received PREPARE: id:1741323542381, from:30177, delay:0.0000s, distance:87.91m (Euclidean)
[2025-03-07 13:59:10,684] [INFO] [30144] Received COMMIT: id:1741323542381, from:30177, delay:0.0000s, distance:87.91m (Euclidean)
[2025-03-07 13:59:10,695] [INFO] [30144] Received PREPARE: id:1741323542381, from:30158, delay:0.0000s, distance:128.77m (Euclidean)
[2025-03-07 13:59:10,700] [INFO] [30144] Received COMMIT: id:1741323542381, from:30158, delay:0.0000s, distance:128.77m (Euclidean)
[2025-03-07 13:59:10,771] [INFO] [30144] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:109.68m (Euclidean)
[2025-03-07 13:59:10,771] [INFO] [30144] Received PREPARE: id:1741323542381, from:30130, delay:0.0001s, distance:201.76m (Euclidean)
[2025-03-07 13:59:10,773] [INFO] [30144] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:109.68m (Euclidean)
[2025-03-07 13:59:10,773] [INFO] [30144] Received COMMIT: id:1741323542381, from:30130, delay:0.0001s, distance:201.76m (Euclidean)
[2025-03-07 13:59:10,984] [INFO] [30144] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:155.62m (Euclidean)
[2025-03-07 13:59:10,984] [INFO] [30144] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:155.62m (Euclidean)
[2025-03-07 13:59:11,009] [INFO] [30144] Received PREPARE: id:1741323542381, from:30090, delay:0.0000s, distance:109.30m (Euclidean)
[2025-03-07 13:59:11,009] [INFO] [30144] Received COMMIT: id:1741323542381, from:30090, delay:0.0000s, distance:109.30m (Euclidean)
[2025-03-07 13:59:11,131] [INFO] [30144] Received PREPARE: id:1741323542381, from:30074, delay:0.0000s, distance:127.02m (Euclidean)
[2025-03-07 13:59:11,131] [INFO] [30144] Received COMMIT: id:1741323542381, from:30074, delay:0.0000s, distance:127.02m (Euclidean)
[2025-03-07 13:59:11,157] [INFO] [30144] Received PREPARE: id:1741323542381, from:30065, delay:0.0000s, distance:106.14m (Euclidean)
[2025-03-07 13:59:11,157] [INFO] [30144] Received COMMIT: id:1741323542381, from:30065, delay:0.0000s, distance:106.14m (Euclidean)
[2025-03-07 13:59:11,191] [INFO] [30144] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:139.68m (Euclidean)
[2025-03-07 13:59:11,191] [INFO] [30144] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:139.68m (Euclidean)
[2025-03-07 13:59:11,308] [INFO] [30144] Received PREPARE: id:1741323542381, from:30115, delay:0.0000s, distance:140.34m (Euclidean)
[2025-03-07 13:59:11,308] [INFO] [30144] Received COMMIT: id:1741323542381, from:30115, delay:0.0000s, distance:140.34m (Euclidean)
[2025-03-07 13:59:11,655] [INFO] [30144] Received PREPARE: id:1741323542381, from:30054, delay:0.0001s, distance:194.68m (Euclidean)
[2025-03-07 13:59:11,655] [INFO] [30144] Received COMMIT: id:1741323542381, from:30054, delay:0.0001s, distance:194.68m (Euclidean)
[2025-03-07 13:59:11,705] [INFO] [30144] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:86.17m (Euclidean)
[2025-03-07 13:59:11,705] [INFO] [30144] Received PREPARE: id:1741323542381, from:30188, delay:0.0000s, distance:200.81m (Euclidean)
[2025-03-07 13:59:11,705] [INFO] [30144] Received PREPARE: id:1741323542381, from:30113, delay:0.0000s, distance:86.15m (Euclidean)
[2025-03-07 13:59:11,705] [INFO] [30144] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:86.17m (Euclidean)
[2025-03-07 13:59:11,705] [INFO] [30144] Received COMMIT: id:1741323542381, from:30113, delay:0.0000s, distance:86.15m (Euclidean)
[2025-03-07 13:59:11,745] [INFO] [30144] Received PREPARE: id:1741323542381, from:30191, delay:0.0000s, distance:63.68m (Euclidean)
[2025-03-07 13:59:11,747] [INFO] [30144] Received COMMIT: id:1741323542381, from:30191, delay:0.0000s, distance:63.68m (Euclidean)
[2025-03-07 13:59:11,960] [INFO] [30144] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:136.20m (Euclidean)
[2025-03-07 13:59:11,977] [INFO] [30144] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:136.20m (Euclidean)
[2025-03-07 13:59:12,020] [INFO] [30144] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:149.27m (Euclidean)
[2025-03-07 13:59:12,020] [INFO] [30144] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:149.27m (Euclidean)
[2025-03-07 13:59:12,164] [INFO] [30144] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:159.98m (Euclidean)
[2025-03-07 13:59:12,174] [INFO] [30144] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:159.98m (Euclidean)
[2025-03-07 13:59:12,205] [INFO] [30144] Received COMMIT: id:1741323542381, from:30165, delay:0.0000s, distance:299.12m (Euclidean)
[2025-03-07 13:59:12,514] [INFO] [30144] Received PREPARE: id:1741323542381, from:30063, delay:0.0001s, distance:157.07m (Euclidean)
[2025-03-07 13:59:12,518] [INFO] [30144] Received COMMIT: id:1741323542381, from:30063, delay:0.0001s, distance:157.07m (Euclidean)
[2025-03-07 13:59:12,592] [INFO] [30144] Received PREPARE: id:1741323542381, from:30043, delay:0.0000s, distance:107.86m (Euclidean)
[2025-03-07 13:59:12,595] [INFO] [30144] Received COMMIT: id:1741323542381, from:30043, delay:0.0000s, distance:107.86m (Euclidean)
[2025-03-07 13:59:12,623] [INFO] [30144] Received PREPARE: id:1741323542381, from:30079, delay:0.0000s, distance:299.36m (Euclidean)
[2025-03-07 13:59:12,636] [INFO] [30144] Received PREPARE: id:1741323542381, from:30011, delay:0.0000s, distance:141.94m (Euclidean)
[2025-03-07 13:59:12,636] [INFO] [30144] Received COMMIT: id:1741323542381, from:30011, delay:0.0000s, distance:141.94m (Euclidean)
[2025-03-07 13:59:12,696] [INFO] [30144] Received PREPARE: id:1741323542381, from:30086, delay:0.0000s, distance:88.58m (Euclidean)
[2025-03-07 13:59:13,057] [INFO] [30144] Received PREPARE: id:1741323542381, from:30026, delay:0.0001s, distance:195.08m (Euclidean)
[2025-03-07 13:59:13,057] [INFO] [30144] Received COMMIT: id:1741323542381, from:30026, delay:0.0001s, distance:195.08m (Euclidean)
[2025-03-07 13:59:13,502] [INFO] [30144] Received COMMIT: id:1741323542381, from:30086, delay:0.0000s, distance:88.58m (Euclidean)
[2025-03-07 13:59:14,011] [INFO] [30144] Received PREPARE: id:1741323542381, from:30153, delay:0.0000s, distance:90.66m (Euclidean)
[2025-03-07 13:59:14,023] [INFO] [30144] Received COMMIT: id:1741323542381, from:30153, delay:0.0000s, distance:90.66m (Euclidean)
[2025-03-07 13:59:14,793] [INFO] [30144] Received COMMIT: id:1741323542381, from:30079, delay:0.0000s, distance:299.36m (Euclidean)
[2025-03-07 13:59:15,286] [INFO] [30144] Received PREPARE: id:1741323542381, from:30010, delay:0.0001s, distance:248.56m (Euclidean)
[2025-03-07 13:59:15,286] [INFO] [30144] Received COMMIT: id:1741323542381, from:30010, delay:0.0001s, distance:248.56m (Euclidean)
[2025-03-07 13:59:15,392] [INFO] [30144] Received PREPARE: id:1741323542381, from:30003, delay:0.0000s, distance:119.34m (Euclidean)
[2025-03-07 13:59:15,392] [INFO] [30144] Received COMMIT: id:1741323542381, from:30003, delay:0.0000s, distance:119.34m (Euclidean)
[2025-03-07 13:59:15,473] [INFO] [30144] Received PREPARE: id:1741323542381, from:30194, delay:0.0000s, distance:116.77m (Euclidean)
[2025-03-07 13:59:15,473] [INFO] [30144] Received PREPARE: id:1741323542381, from:30134, delay:0.0000s, distance:138.51m (Euclidean)
[2025-03-07 13:59:15,473] [INFO] [30144] Received COMMIT: id:1741323542381, from:30194, delay:0.0000s, distance:116.77m (Euclidean)
[2025-03-07 13:59:15,473] [INFO] [30144] Received COMMIT: id:1741323542381, from:30134, delay:0.0000s, distance:138.51m (Euclidean)
[2025-03-07 13:59:15,571] [INFO] [30144] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:176.51m (Euclidean)
[2025-03-07 13:59:15,580] [INFO] [30144] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:176.51m (Euclidean)
[2025-03-07 13:59:15,889] [INFO] [30144] Received PREPARE: id:1741323542381, from:30125, delay:0.0001s, distance:174.83m (Euclidean)
[2025-03-07 13:59:15,908] [INFO] [30144] Received COMMIT: id:1741323542381, from:30125, delay:0.0001s, distance:174.83m (Euclidean)
[2025-03-07 13:59:16,184] [INFO] [30144] Received PREPARE: id:1741323542381, from:30135, delay:0.0002s, distance:265.92m (Euclidean)
[2025-03-07 13:59:16,184] [INFO] [30144] Received COMMIT: id:1741323542381, from:30135, delay:0.0002s, distance:265.92m (Euclidean)
[2025-03-07 13:59:16,459] [INFO] [30144] Received PREPARE: id:1741323542381, from:30132, delay:0.0002s, distance:273.56m (Euclidean)
[2025-03-07 13:59:16,459] [INFO] [30144] Received COMMIT: id:1741323542381, from:30132, delay:0.0002s, distance:273.56m (Euclidean)
[2025-03-07 13:59:16,461] [INFO] [30144] Received PREPARE: id:1741323542381, from:30197, delay:0.0000s, distance:129.05m (Euclidean)
[2025-03-07 13:59:16,465] [INFO] [30144] Received COMMIT: id:1741323542381, from:30197, delay:0.0000s, distance:129.05m (Euclidean)
[2025-03-07 13:59:16,609] [INFO] [30144] Received PREPARE: id:1741323542381, from:30117, delay:0.0001s, distance:182.82m (Euclidean)
[2025-03-07 13:59:16,729] [INFO] [30144] Received PREPARE: id:1741323542381, from:30019, delay:0.0000s, distance:87.23m (Euclidean)
[2025-03-07 13:59:16,729] [INFO] [30144] Received COMMIT: id:1741323542381, from:30019, delay:0.0000s, distance:87.23m (Euclidean)
[2025-03-07 13:59:16,733] [INFO] [30144] Received PREPARE: id:1741323542381, from:30067, delay:0.0002s, distance:263.66m (Euclidean)
[2025-03-07 13:59:16,733] [INFO] [30144] Received COMMIT: id:1741323542381, from:30067, delay:0.0002s, distance:263.66m (Euclidean)
[2025-03-07 13:59:16,743] [INFO] [30144] Received PREPARE: id:1741323542381, from:30198, delay:0.0001s, distance:214.03m (Euclidean)
[2025-03-07 13:59:16,743] [INFO] [30144] Received COMMIT: id:1741323542381, from:30198, delay:0.0001s, distance:214.03m (Euclidean)
[2025-03-07 13:59:16,754] [INFO] [30144] Received PREPARE: id:1741323542381, from:30159, delay:0.0000s, distance:116.61m (Euclidean)
[2025-03-07 13:59:16,754] [INFO] [30144] Received COMMIT: id:1741323542381, from:30159, delay:0.0000s, distance:116.61m (Euclidean)
[2025-03-07 13:59:16,938] [INFO] [30144] Received PREPARE: id:1741323542381, from:30091, delay:0.0001s, distance:188.42m (Euclidean)
[2025-03-07 13:59:16,940] [INFO] [30144] Received COMMIT: id:1741323542381, from:30091, delay:0.0001s, distance:188.42m (Euclidean)
[2025-03-07 13:59:16,954] [INFO] [30144] Received PREPARE: id:1741323542381, from:30146, delay:0.0002s, distance:257.43m (Euclidean)
[2025-03-07 13:59:16,969] [INFO] [30144] Received COMMIT: id:1741323542381, from:30146, delay:0.0002s, distance:257.43m (Euclidean)
[2025-03-07 13:59:17,073] [INFO] [30144] Received COMMIT: id:1741323542381, from:30117, delay:0.0001s, distance:182.82m (Euclidean)
[2025-03-07 13:59:17,511] [INFO] [30144] Received COMMIT: id:1741323542381, from:30188, delay:0.0000s, distance:200.81m (Euclidean)
[2025-03-07 13:59:17,553] [INFO] [30144] Received PREPARE: id:1741323542381, from:30017, delay:0.0000s, distance:149.71m (Euclidean)
[2025-03-07 13:59:17,695] [INFO] [30144] Received PREPARE: id:1741323542381, from:30050, delay:0.0002s, distance:273.56m (Euclidean)
[2025-03-07 13:59:17,697] [INFO] [30144] Received COMMIT: id:1741323542381, from:30050, delay:0.0002s, distance:273.56m (Euclidean)
[2025-03-07 13:59:18,089] [INFO] [30144] Received PREPARE: id:1741323542381, from:30143, delay:0.0002s, distance:279.79m (Euclidean)
[2025-03-07 13:59:18,089] [INFO] [30144] Received COMMIT: id:1741323542381, from:30143, delay:0.0002s, distance:279.79m (Euclidean)
[2025-03-07 13:59:18,253] [INFO] [30144] Received PREPARE: id:1741323542381, from:30052, delay:0.0002s, distance:264.34m (Euclidean)
[2025-03-07 13:59:18,266] [INFO] [30144] Received COMMIT: id:1741323542381, from:30052, delay:0.0002s, distance:264.34m (Euclidean)
[2025-03-07 13:59:18,783] [INFO] [30144] Received PREPARE: id:1741323542381, from:30071, delay:0.0001s, distance:240.42m (Euclidean)
[2025-03-07 13:59:18,783] [INFO] [30144] Received COMMIT: id:1741323542381, from:30071, delay:0.0001s, distance:240.42m (Euclidean)
[2025-03-07 13:59:18,914] [INFO] [30144] Received PREPARE: id:1741323542381, from:30137, delay:0.0001s, distance:246.50m (Euclidean)
[2025-03-07 13:59:18,914] [INFO] [30144] Received COMMIT: id:1741323542381, from:30137, delay:0.0001s, distance:246.50m (Euclidean)
[2025-03-07 13:59:19,217] [INFO] [30144] Received PREPARE: id:1741323542381, from:30006, delay:0.0002s, distance:264.09m (Euclidean)
[2025-03-07 13:59:19,219] [INFO] [30144] Received COMMIT: id:1741323542381, from:30006, delay:0.0002s, distance:264.09m (Euclidean)
[2025-03-07 13:59:19,239] [INFO] [30144] Received PREPARE: id:1741323542381, from:30138, delay:0.0002s, distance:250.79m (Euclidean)
[2025-03-07 13:59:19,308] [INFO] [30144] Received PREPARE: id:1741323542381, from:30105, delay:0.0002s, distance:277.51m (Euclidean)
[2025-03-07 13:59:19,308] [INFO] [30144] Received PREPARE: id:1741323542381, from:30173, delay:0.0002s, distance:254.79m (Euclidean)
[2025-03-07 13:59:19,310] [INFO] [30144] Received COMMIT: id:1741323542381, from:30173, delay:0.0002s, distance:254.79m (Euclidean)
[2025-03-07 13:59:19,310] [INFO] [30144] Received COMMIT: id:1741323542381, from:30105, delay:0.0002s, distance:277.51m (Euclidean)
[2025-03-07 13:59:19,681] [INFO] [30144] Received PREPARE: id:1741323542381, from:30061, delay:0.0001s, distance:248.28m (Euclidean)
[2025-03-07 13:59:19,681] [INFO] [30144] Received COMMIT: id:1741323542381, from:30061, delay:0.0001s, distance:248.28m (Euclidean)
[2025-03-07 13:59:19,769] [INFO] [30144] Received PREPARE: id:1741323542381, from:30131, delay:0.0001s, distance:209.41m (Euclidean)
[2025-03-07 13:59:19,773] [INFO] [30144] Received COMMIT: id:1741323542381, from:30131, delay:0.0001s, distance:209.41m (Euclidean)
[2025-03-07 13:59:19,863] [INFO] [30144] Received PREPARE: id:1741323542381, from:30058, delay:0.0002s, distance:284.95m (Euclidean)
[2025-03-07 13:59:19,863] [INFO] [30144] Received COMMIT: id:1741323542381, from:30058, delay:0.0002s, distance:284.95m (Euclidean)
[2025-03-07 13:59:19,893] [INFO] [30144] Received PREPARE: id:1741323542381, from:30160, delay:0.0001s, distance:169.25m (Euclidean)
[2025-03-07 13:59:19,893] [INFO] [30144] Received COMMIT: id:1741323542381, from:30160, delay:0.0001s, distance:169.25m (Euclidean)
[2025-03-07 13:59:19,938] [INFO] [30144] Received PREPARE: id:1741323542381, from:30094, delay:0.0001s, distance:233.21m (Euclidean)
[2025-03-07 13:59:19,938] [INFO] [30144] Received COMMIT: id:1741323542381, from:30094, delay:0.0001s, distance:233.21m (Euclidean)
[2025-03-07 13:59:20,231] [INFO] [30144] Received COMMIT: id:1741323542381, from:30138, delay:0.0002s, distance:250.79m (Euclidean)
[2025-03-07 13:59:20,256] [INFO] [30144] Received PREPARE: id:1741323542381, from:30014, delay:0.0002s, distance:298.16m (Euclidean)
[2025-03-07 13:59:20,256] [INFO] [30144] Received COMMIT: id:1741323542381, from:30014, delay:0.0002s, distance:298.16m (Euclidean)
[2025-03-07 13:59:20,307] [INFO] [30144] Received PREPARE: id:1741323542381, from:30001, delay:0.0002s, distance:270.44m (Euclidean)
[2025-03-07 13:59:20,307] [INFO] [30144] Received COMMIT: id:1741323542381, from:30001, delay:0.0002s, distance:270.44m (Euclidean)
[2025-03-07 13:59:20,571] [INFO] [30144] Received PREPARE: id:1741323542381, from:30145, delay:0.0002s, distance:282.98m (Euclidean)
[2025-03-07 13:59:20,573] [INFO] [30144] Received COMMIT: id:1741323542381, from:30145, delay:0.0002s, distance:282.98m (Euclidean)
[2025-03-07 13:59:21,190] [INFO] [30144] Received PREPARE: id:1741323542381, from:30016, delay:0.0001s, distance:227.92m (Euclidean)
[2025-03-07 13:59:21,190] [INFO] [30144] Received COMMIT: id:1741323542381, from:30016, delay:0.0001s, distance:227.92m (Euclidean)
[2025-03-07 13:59:21,399] [INFO] [30144] Received PREPARE: id:1741323542381, from:30101, delay:0.0001s, distance:173.28m (Euclidean)
[2025-03-07 13:59:21,412] [INFO] [30144] Received COMMIT: id:1741323542381, from:30101, delay:0.0001s, distance:173.28m (Euclidean)
[2025-03-07 13:59:21,645] [INFO] [30144] Received PREPARE: id:1741323542381, from:30055, delay:0.0001s, distance:214.98m (Euclidean)
[2025-03-07 13:59:21,645] [INFO] [30144] Received COMMIT: id:1741323542381, from:30055, delay:0.0001s, distance:214.98m (Euclidean)
[2025-03-07 13:59:21,740] [INFO] [30144] Received PREPARE: id:1741323542381, from:30088, delay:0.0001s, distance:234.10m (Euclidean)
[2025-03-07 13:59:21,759] [INFO] [30144] Received COMMIT: id:1741323542381, from:30088, delay:0.0001s, distance:234.10m (Euclidean)
[2025-03-07 13:59:21,895] [INFO] [30144] Received COMMIT: id:1741323542381, from:30017, delay:0.0000s, distance:149.71m (Euclidean)
[2025-03-07 13:59:22,849] [INFO] [30144] Received PREPARE: id:1741323542381, from:30141, delay:0.0000s, distance:126.63m (Euclidean)
[2025-03-07 13:59:22,849] [INFO] [30144] Received COMMIT: id:1741323542381, from:30141, delay:0.0000s, distance:126.63m (Euclidean)
[2025-03-07 13:59:22,934] [INFO] [30144] Received PREPARE: id:1741323542381, from:30193, delay:0.0001s, distance:220.52m (Euclidean)
[2025-03-07 13:59:22,936] [INFO] [30144] Received COMMIT: id:1741323542381, from:30193, delay:0.0001s, distance:220.52m (Euclidean)
[2025-03-07 13:59:23,081] [INFO] [30144] Received PREPARE: id:1741323542381, from:30068, delay:0.0000s, distance:99.22m (Euclidean)
[2025-03-07 13:59:23,081] [INFO] [30144] Received COMMIT: id:1741323542381, from:30068, delay:0.0000s, distance:99.22m (Euclidean)
[2025-03-07 13:59:23,180] [INFO] [30144] Received PREPARE: id:1741323542381, from:30032, delay:0.0002s, distance:260.45m (Euclidean)
[2025-03-07 13:59:23,182] [INFO] [30144] Received COMMIT: id:1741323542381, from:30032, delay:0.0002s, distance:260.45m (Euclidean)
[2025-03-07 13:59:23,203] [INFO] [30144] Received PREPARE: id:1741323542381, from:30008, delay:0.0001s, distance:206.22m (Euclidean)
[2025-03-07 13:59:23,203] [INFO] [30144] Received COMMIT: id:1741323542381, from:30008, delay:0.0001s, distance:206.22m (Euclidean)
[2025-03-07 13:59:23,301] [INFO] [30144] Received PREPARE: id:1741323542381, from:30038, delay:0.0002s, distance:250.72m (Euclidean)
[2025-03-07 13:59:23,301] [INFO] [30144] Received COMMIT: id:1741323542381, from:30038, delay:0.0002s, distance:250.72m (Euclidean)
[2025-03-07 13:59:23,422] [INFO] [30144] Received PREPARE: id:1741323542381, from:30069, delay:0.0002s, distance:256.94m (Euclidean)
[2025-03-07 13:59:23,422] [INFO] [30144] Received COMMIT: id:1741323542381, from:30069, delay:0.0002s, distance:256.94m (Euclidean)
[2025-03-07 13:59:23,635] [INFO] [30144] Received PREPARE: id:1741323542381, from:30073, delay:0.0001s, distance:248.61m (Euclidean)
[2025-03-07 13:59:23,645] [INFO] [30144] Received COMMIT: id:1741323542381, from:30000, delay:0.0000s, distance:86.65m (Euclidean)
[2025-03-07 13:59:23,649] [INFO] [30144] Received COMMIT: id:1741323542381, from:30073, delay:0.0001s, distance:248.61m (Euclidean)
[2025-03-07 13:59:23,772] [INFO] [30144] Received PREPARE: id:1741323542381, from:30140, delay:0.0000s, distance:147.43m (Euclidean)
[2025-03-07 13:59:23,772] [INFO] [30144] Received COMMIT: id:1741323542381, from:30140, delay:0.0000s, distance:147.43m (Euclidean)
[2025-03-07 13:59:23,778] [INFO] [30144] Received PREPARE: id:1741323542381, from:30044, delay:0.0000s, distance:299.06m (Euclidean)
[2025-03-07 13:59:23,840] [INFO] [30144] Received PREPARE: id:1741323542381, from:30022, delay:0.0001s, distance:159.18m (Euclidean)
[2025-03-07 13:59:23,840] [INFO] [30144] Received COMMIT: id:1741323542381, from:30022, delay:0.0001s, distance:159.18m (Euclidean)
[2025-03-07 13:59:24,086] [INFO] [30144] Received PREPARE: id:1741323542381, from:30156, delay:0.0001s, distance:190.40m (Euclidean)
[2025-03-07 13:59:24,088] [INFO] [30144] Received COMMIT: id:1741323542381, from:30156, delay:0.0001s, distance:190.40m (Euclidean)
[2025-03-07 13:59:24,723] [INFO] [30144] Received PREPARE: id:1741323542381, from:30083, delay:0.0001s, distance:192.58m (Euclidean)
[2025-03-07 13:59:24,726] [INFO] [30144] Received COMMIT: id:1741323542381, from:30083, delay:0.0001s, distance:192.58m (Euclidean)
[2025-03-07 13:59:24,861] [INFO] [30144] Received PREPARE: id:1741323542381, from:30162, delay:0.0001s, distance:168.06m (Euclidean)
[2025-03-07 13:59:24,861] [INFO] [30144] Received COMMIT: id:1741323542381, from:30162, delay:0.0001s, distance:168.06m (Euclidean)
[2025-03-07 13:59:24,861] [INFO] [30144] Received PREPARE: id:1741323542381, from:30033, delay:0.0001s, distance:180.50m (Euclidean)
[2025-03-07 13:59:24,861] [INFO] [30144] Received COMMIT: id:1741323542381, from:30033, delay:0.0001s, distance:180.50m (Euclidean)
[2025-03-07 13:59:24,877] [INFO] [30144] Received PREPARE: id:1741323542381, from:30081, delay:0.0001s, distance:154.17m (Euclidean)
[2025-03-07 13:59:24,877] [INFO] [30144] Received COMMIT: id:1741323542381, from:30081, delay:0.0001s, distance:154.17m (Euclidean)
[2025-03-07 13:59:25,025] [INFO] [30144] Received PREPARE: id:1741323542381, from:30084, delay:0.0001s, distance:230.57m (Euclidean)
[2025-03-07 13:59:25,026] [INFO] [30144] Received COMMIT: id:1741323542381, from:30084, delay:0.0001s, distance:230.57m (Euclidean)
[2025-03-07 13:59:25,049] [INFO] [30144] Received PREPARE: id:1741323542381, from:30187, delay:0.0002s, distance:283.06m (Euclidean)
[2025-03-07 13:59:25,065] [INFO] [30144] Received COMMIT: id:1741323542381, from:30187, delay:0.0002s, distance:283.06m (Euclidean)
[2025-03-07 13:59:25,426] [INFO] [30144] Received PREPARE: id:1741323542381, from:30064, delay:0.0001s, distance:182.21m (Euclidean)
[2025-03-07 13:59:25,430] [INFO] [30144] Received COMMIT: id:1741323542381, from:30064, delay:0.0001s, distance:182.21m (Euclidean)
[2025-03-07 13:59:25,759] [INFO] [30144] Received PREPARE: id:1741323542381, from:30039, delay:0.0002s, distance:263.37m (Euclidean)
[2025-03-07 13:59:25,759] [INFO] [30144] Received COMMIT: id:1741323542381, from:30039, delay:0.0002s, distance:263.37m (Euclidean)
[2025-03-07 13:59:25,880] [INFO] [30144] Received PREPARE: id:1741323542381, from:30151, delay:0.0001s, distance:202.63m (Euclidean)
[2025-03-07 13:59:25,880] [INFO] [30144] Received COMMIT: id:1741323542381, from:30151, delay:0.0001s, distance:202.63m (Euclidean)
[2025-03-07 13:59:25,994] [INFO] [30144] Received PREPARE: id:1741323542381, from:30104, delay:0.0002s, distance:262.01m (Euclidean)
[2025-03-07 13:59:25,994] [INFO] [30144] Received COMMIT: id:1741323542381, from:30104, delay:0.0002s, distance:262.01m (Euclidean)
[2025-03-07 13:59:26,083] [INFO] [30144] Received PREPARE: id:1741323542381, from:30042, delay:0.0001s, distance:229.95m (Euclidean)
[2025-03-07 13:59:26,096] [INFO] [30144] Received COMMIT: id:1741323542381, from:30042, delay:0.0001s, distance:229.95m (Euclidean)
[2025-03-07 13:59:26,319] [INFO] [30144] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:213.46m (Euclidean)
[2025-03-07 13:59:26,319] [INFO] [30144] Received PREPARE: id:1741323542381, from:30152, delay:0.0001s, distance:188.06m (Euclidean)
[2025-03-07 13:59:26,327] [INFO] [30144] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:213.46m (Euclidean)
[2025-03-07 13:59:26,327] [INFO] [30144] Received COMMIT: id:1741323542381, from:30152, delay:0.0001s, distance:188.06m (Euclidean)
[2025-03-07 13:59:26,608] [INFO] [30144] Received COMMIT: id:1741323542381, from:30044, delay:0.0000s, distance:299.06m (Euclidean)
[2025-03-07 13:59:26,678] [INFO] [30144] Received PREPARE: id:1741323542381, from:30142, delay:0.0002s, distance:278.01m (Euclidean)
[2025-03-07 13:59:26,678] [INFO] [30144] Received COMMIT: id:1741323542381, from:30142, delay:0.0002s, distance:278.01m (Euclidean)
[2025-03-07 13:59:26,711] [INFO] [30144] Received PREPARE: id:1741323542381, from:30075, delay:0.0001s, distance:227.56m (Euclidean)
[2025-03-07 13:59:26,711] [INFO] [30144] Received COMMIT: id:1741323542381, from:30075, delay:0.0001s, distance:227.56m (Euclidean)
[2025-03-07 13:59:26,861] [INFO] [30144] Received PREPARE: id:1741323542381, from:30166, delay:0.0002s, distance:250.07m (Euclidean)
[2025-03-07 13:59:26,861] [INFO] [30144] Received COMMIT: id:1741323542381, from:30166, delay:0.0002s, distance:250.07m (Euclidean)
[2025-03-07 13:59:27,017] [INFO] [30144] Received PREPARE: id:1741323542381, from:30045, delay:0.0002s, distance:257.27m (Euclidean)
[2025-03-07 13:59:27,017] [INFO] [30144] Received COMMIT: id:1741323542381, from:30045, delay:0.0002s, distance:257.27m (Euclidean)
[2025-03-07 13:59:27,238] [INFO] [30144] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:165.75m (Euclidean)
[2025-03-07 13:59:27,245] [INFO] [30144] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:165.75m (Euclidean)
[2025-03-07 13:59:27,526] [INFO] [30144] Received PREPARE: id:1741323542381, from:30139, delay:0.0002s, distance:252.73m (Euclidean)
[2025-03-07 13:59:27,528] [INFO] [30144] Received PREPARE: id:1741323542381, from:30009, delay:0.0001s, distance:238.14m (Euclidean)
[2025-03-07 13:59:27,528] [INFO] [30144] Received COMMIT: id:1741323542381, from:30009, delay:0.0001s, distance:238.14m (Euclidean)
[2025-03-07 13:59:27,548] [INFO] [30144] Received COMMIT: id:1741323542381, from:30139, delay:0.0002s, distance:252.73m (Euclidean)
[2025-03-07 13:59:27,784] [INFO] [30144] Received PREPARE: id:1741323542381, from:30148, delay:0.0001s, distance:246.56m (Euclidean)
[2025-03-07 13:59:27,787] [INFO] [30144] Received COMMIT: id:1741323542381, from:30148, delay:0.0001s, distance:246.56m (Euclidean)
[2025-03-07 13:59:37,196] [INFO] [30144] Received PREPARE: id:1741323542381, from:30097, delay:0.0001s, distance:214.18m (Euclidean)
[2025-03-07 13:59:37,290] [INFO] [30144] Received PREPARE: id:1741323542381, from:30030, delay:0.0001s, distance:225.38m (Euclidean)
[2025-03-07 13:59:37,963] [INFO] [30144] Received PREPARE: id:1741323542381, from:30018, delay:0.0001s, distance:202.07m (Euclidean)
[2025-03-07 13:59:38,015] [INFO] [30144] Received COMMIT: id:1741323542381, from:30018, delay:0.0001s, distance:202.07m (Euclidean)
[2025-03-07 13:59:38,111] [INFO] [30144] Received PREPARE: id:1741323542381, from:30047, delay:0.0002s, distance:296.32m (Euclidean)
[2025-03-07 13:59:38,119] [INFO] [30144] Received PREPARE: id:1741323542381, from:30002, delay:0.0001s, distance:161.75m (Euclidean)
[2025-03-07 13:59:38,156] [INFO] [30144] Received COMMIT: id:1741323542381, from:30047, delay:0.0002s, distance:296.32m (Euclidean)
[2025-03-07 13:59:38,172] [INFO] [30144] Received COMMIT: id:1741323542381, from:30002, delay:0.0001s, distance:161.75m (Euclidean)
[2025-03-07 13:59:38,202] [INFO] [30144] Received COMMIT: id:1741323542381, from:30082, delay:0.0002s, distance:265.99m (Euclidean)
[2025-03-07 13:59:38,266] [INFO] [30144] Received PREPARE: id:1741323542381, from:30185, delay:0.0002s, distance:266.41m (Euclidean)
[2025-03-07 13:59:38,268] [INFO] [30144] Received COMMIT: id:1741323542381, from:30185, delay:0.0002s, distance:266.41m (Euclidean)
[2025-03-07 13:59:38,525] [INFO] [30144] Received PREPARE: id:1741323542381, from:30183, delay:0.0001s, distance:180.83m (Euclidean)
[2025-03-07 13:59:38,531] [INFO] [30144] Received COMMIT: id:1741323542381, from:30183, delay:0.0001s, distance:180.83m (Euclidean)
[2025-03-07 13:59:38,531] [INFO] [30144] Received PREPARE: id:1741323542381, from:30192, delay:0.0002s, distance:263.52m (Euclidean)
[2025-03-07 13:59:38,543] [INFO] [30144] Received PREPARE: id:1741323542381, from:30164, delay:0.0001s, distance:217.99m (Euclidean)
[2025-03-07 13:59:38,653] [INFO] [30144] Received PREPARE: id:1741323542381, from:30172, delay:0.0001s, distance:233.89m (Euclidean)
[2025-03-07 13:59:38,664] [INFO] [30144] Received COMMIT: id:1741323542381, from:30192, delay:0.0002s, distance:263.52m (Euclidean)
[2025-03-07 13:59:38,681] [INFO] [30144] Received COMMIT: id:1741323542381, from:30078, delay:0.0001s, distance:220.98m (Euclidean)
[2025-03-07 13:59:38,687] [INFO] [30144] Received PREPARE: id:1741323542381, from:30078, delay:0.0001s, distance:220.98m (Euclidean)
[2025-03-07 13:59:38,748] [INFO] [30144] Received COMMIT: id:1741323542381, from:30163, delay:0.0002s, distance:257.66m (Euclidean)
[2025-03-07 13:59:38,748] [INFO] [30144] Received COMMIT: id:1741323542381, from:30172, delay:0.0001s, distance:233.89m (Euclidean)
[2025-03-07 13:59:38,814] [INFO] [30144] Received COMMIT: id:1741323542381, from:30164, delay:0.0001s, distance:217.99m (Euclidean)
