[2025-03-07 13:53:28,269] [INFO] Starting node at localhost:30127 | index=128 | f=1, k=4 | Role: Replica
[2025-03-07 13:53:39,004] [INFO] [30127] Received PREPARE: id:1741323218379, from:30094, delay:0.0000s, distance:249.71m (Euclidean)
[2025-03-07 13:53:39,004] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,006] [INFO] [30127] Received PREPARE: id:1741323218379, from:30073, delay:0.0000s, distance:299.50m (Euclidean)
[2025-03-07 13:53:39,006] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,164] [INFO] [30127] Received PREPARE: id:1741323218379, from:30014, delay:0.0000s, distance:100.63m (Euclidean)
[2025-03-07 13:53:39,164] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,385] [INFO] [30127] Received COMMIT: id:1741323218379, from:30073, delay:0.0000s, distance:299.50m (Euclidean)
[2025-03-07 13:53:39,428] [INFO] [30127] Received PREPARE: id:1741323218379, from:30020, delay:0.0000s, distance:62.16m (Euclidean)
[2025-03-07 13:53:39,428] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,549] [INFO] [30127] Received COMMIT: id:1741323218379, from:30020, delay:0.0000s, distance:62.16m (Euclidean)
[2025-03-07 13:53:39,573] [INFO] [30127] Received PREPARE: id:1741323218379, from:30097, delay:0.0000s, distance:114.80m (Euclidean)
[2025-03-07 13:53:39,573] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,747] [INFO] [30127] Received PREPARE: id:1741323218379, from:30087, delay:0.0000s, distance:142.43m (Euclidean)
[2025-03-07 13:53:39,747] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,747] [INFO] [30127] Received COMMIT: id:1741323218379, from:30087, delay:0.0000s, distance:142.43m (Euclidean)
[2025-03-07 13:53:40,021] [INFO] [30127] Received PREPARE: id:1741323218379, from:30006, delay:0.0000s, distance:55.18m (Euclidean)
[2025-03-07 13:53:40,021] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,021] [INFO] [30127] Received COMMIT: id:1741323218379, from:30006, delay:0.0000s, distance:55.18m (Euclidean)
[2025-03-07 13:53:40,042] [INFO] [30127] Received COMMIT: id:1741323218379, from:30014, delay:0.0000s, distance:100.63m (Euclidean)
[2025-03-07 13:53:40,371] [INFO] [30127] Received PREPARE: id:1741323218379, from:30070, delay:0.0001s, distance:191.80m (Euclidean)
[2025-03-07 13:53:40,371] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,402] [INFO] [30127] Received PREPARE: id:1741323218379, from:30037, delay:0.0000s, distance:93.23m (Euclidean)
[2025-03-07 13:53:40,402] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,561] [INFO] [30127] Received PREPARE: id:1741323218379, from:30044, delay:0.0001s, distance:202.73m (Euclidean)
[2025-03-07 13:53:40,561] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,561] [INFO] [30127] Received COMMIT: id:1741323218379, from:30044, delay:0.0001s, distance:202.73m (Euclidean)
[2025-03-07 13:53:40,630] [INFO] [30127] Received PREPARE: id:1741323218379, from:30019, delay:0.0001s, distance:174.96m (Euclidean)
[2025-03-07 13:53:40,630] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,631] [INFO] [30127] Received COMMIT: id:1741323218379, from:30019, delay:0.0001s, distance:174.96m (Euclidean)
[2025-03-07 13:53:40,640] [INFO] [30127] Received PREPARE: id:1741323218379, from:30053, delay:0.0001s, distance:190.73m (Euclidean)
[2025-03-07 13:53:40,640] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,687] [INFO] [30127] Received PREPARE: id:1741323218379, from:30092, delay:0.0000s, distance:120.11m (Euclidean)
[2025-03-07 13:53:40,687] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,687] [INFO] [30127] Received COMMIT: id:1741323218379, from:30092, delay:0.0000s, distance:120.11m (Euclidean)
[2025-03-07 13:53:40,687] [INFO] [30127] Received PREPARE: id:1741323218379, from:30042, delay:0.0001s, distance:167.95m (Euclidean)
[2025-03-07 13:53:40,687] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,732] [INFO] [30127] Received COMMIT: id:1741323218379, from:30097, delay:0.0000s, distance:114.80m (Euclidean)
[2025-03-07 13:53:40,782] [INFO] [30127] Received PREPARE: id:1741323218379, from:30090, delay:0.0001s, distance:195.86m (Euclidean)
[2025-03-07 13:53:40,782] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,782] [INFO] [30127] Received COMMIT: id:1741323218379, from:30090, delay:0.0001s, distance:195.86m (Euclidean)
[2025-03-07 13:53:40,782] [INFO] [30127] Received PREPARE: id:1741323218379, from:30058, delay:0.0000s, distance:80.99m (Euclidean)
[2025-03-07 13:53:40,782] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,798] [INFO] [30127] Received PREPARE: id:1741323218379, from:30021, delay:0.0002s, distance:289.75m (Euclidean)
[2025-03-07 13:53:40,798] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,798] [INFO] [30127] Received COMMIT: id:1741323218379, from:30021, delay:0.0002s, distance:289.75m (Euclidean)
[2025-03-07 13:53:40,856] [INFO] [30127] Received COMMIT: id:1741323218379, from:30037, delay:0.0000s, distance:93.23m (Euclidean)
[2025-03-07 13:53:40,909] [INFO] [30127] Received PREPARE: id:1741323218379, from:30072, delay:0.0000s, distance:147.68m (Euclidean)
[2025-03-07 13:53:40,909] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,972] [INFO] [30127] Received PREPARE: id:1741323218379, from:30013, delay:0.0001s, distance:151.16m (Euclidean)
[2025-03-07 13:53:40,972] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,972] [INFO] [30127] Received COMMIT: id:1741323218379, from:30013, delay:0.0001s, distance:151.16m (Euclidean)
[2025-03-07 13:53:41,067] [INFO] [30127] Received COMMIT: id:1741323218379, from:30042, delay:0.0001s, distance:167.95m (Euclidean)
[2025-03-07 13:53:41,304] [INFO] [30127] Received PREPARE: id:1741323218379, from:30026, delay:0.0001s, distance:172.38m (Euclidean)
[2025-03-07 13:53:41,304] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,354] [INFO] [30127] Received COMMIT: id:1741323218379, from:30053, delay:0.0001s, distance:190.73m (Euclidean)
[2025-03-07 13:53:41,684] [INFO] [30127] Received PREPARE: id:1741323218379, from:30081, delay:0.0000s, distance:145.90m (Euclidean)
[2025-03-07 13:53:41,684] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,684] [INFO] [30127] Received COMMIT: id:1741323218379, from:30081, delay:0.0000s, distance:145.90m (Euclidean)
[2025-03-07 13:53:41,861] [INFO] [30127] Received PREPARE: id:1741323218379, from:30096, delay:0.0002s, distance:289.73m (Euclidean)
[2025-03-07 13:53:41,861] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,032] [INFO] [30127] Received PREPARE: id:1741323218379, from:30028, delay:0.0001s, distance:178.32m (Euclidean)
[2025-03-07 13:53:42,032] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,032] [INFO] [30127] Received COMMIT: id:1741323218379, from:30028, delay:0.0001s, distance:178.32m (Euclidean)
[2025-03-07 13:53:42,080] [INFO] [30127] Received COMMIT: id:1741323218379, from:30026, delay:0.0001s, distance:172.38m (Euclidean)
[2025-03-07 13:53:42,143] [INFO] [30127] Received COMMIT: id:1741323218379, from:30058, delay:0.0000s, distance:80.99m (Euclidean)
[2025-03-07 13:53:42,177] [INFO] [30127] Received COMMIT: id:1741323218379, from:30070, delay:0.0001s, distance:191.80m (Euclidean)
[2025-03-07 13:53:42,616] [INFO] [30127] Received PREPARE: id:1741323218379, from:30055, delay:0.0001s, distance:187.38m (Euclidean)
[2025-03-07 13:53:42,616] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,616] [INFO] [30127] Received COMMIT: id:1741323218379, from:30055, delay:0.0001s, distance:187.38m (Euclidean)
[2025-03-07 13:53:42,963] [INFO] [30127] Received COMMIT: id:1741323218379, from:30096, delay:0.0002s, distance:289.73m (Euclidean)
[2025-03-07 13:53:43,011] [INFO] [30127] Received PREPARE: id:1741323218379, from:30040, delay:0.0001s, distance:177.82m (Euclidean)
[2025-03-07 13:53:43,011] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,011] [INFO] [30127] Received COMMIT: id:1741323218379, from:30040, delay:0.0001s, distance:177.82m (Euclidean)
[2025-03-07 13:53:43,066] [INFO] [30127] Received PREPARE: id:1741323218379, from:30005, delay:0.0002s, distance:257.26m (Euclidean)
[2025-03-07 13:53:43,066] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,075] [INFO] [30127] Received COMMIT: id:1741323218379, from:30005, delay:0.0002s, distance:257.26m (Euclidean)
[2025-03-07 13:53:43,110] [INFO] [30127] Received PREPARE: id:1741323218379, from:30001, delay:0.0001s, distance:215.30m (Euclidean)
[2025-03-07 13:53:43,110] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,144] [INFO] [30127] Received PREPARE: id:1741323218379, from:30033, delay:0.0002s, distance:253.67m (Euclidean)
[2025-03-07 13:53:43,144] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,144] [INFO] [30127] Received COMMIT: id:1741323218379, from:30033, delay:0.0002s, distance:253.67m (Euclidean)
[2025-03-07 13:53:43,241] [INFO] [30127] Received PREPARE: id:1741323218379, from:30012, delay:0.0002s, distance:265.65m (Euclidean)
[2025-03-07 13:53:43,241] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,241] [INFO] [30127] Received COMMIT: id:1741323218379, from:30012, delay:0.0002s, distance:265.65m (Euclidean)
[2025-03-07 13:53:43,517] [INFO] [30127] Received COMMIT: id:1741323218379, from:30072, delay:0.0000s, distance:147.68m (Euclidean)
[2025-03-07 13:53:43,913] [INFO] [30127] Received COMMIT: id:1741323218379, from:30089, delay:0.0002s, distance:270.80m (Euclidean)
[2025-03-07 13:53:43,913] [INFO] [30127] Received PREPARE: id:1741323218379, from:30089, delay:0.0002s, distance:270.80m (Euclidean)
[2025-03-07 13:53:43,913] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,014] [INFO] [30127] Received COMMIT: id:1741323218379, from:30001, delay:0.0001s, distance:215.30m (Euclidean)
[2025-03-07 13:53:44,014] [INFO] [30127] Received PREPARE: id:1741323218379, from:30009, delay:0.0002s, distance:276.90m (Euclidean)
[2025-03-07 13:53:44,015] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,015] [INFO] [30127] Received COMMIT: id:1741323218379, from:30009, delay:0.0002s, distance:276.90m (Euclidean)
[2025-03-07 13:53:44,015] [INFO] [30127] Received PREPARE: id:1741323218379, from:30048, delay:0.0002s, distance:272.37m (Euclidean)
[2025-03-07 13:53:44,015] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,015] [INFO] [30127] Received COMMIT: id:1741323218379, from:30048, delay:0.0002s, distance:272.37m (Euclidean)
[2025-03-07 13:53:44,070] [INFO] [30127] Received PREPARE: id:1741323218379, from:30102, delay:0.0001s, distance:196.54m (Euclidean)
[2025-03-07 13:53:44,070] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,072] [INFO] [30127] Received COMMIT: id:1741323218379, from:30102, delay:0.0001s, distance:196.54m (Euclidean)
[2025-03-07 13:53:44,276] [INFO] [30127] Received PREPARE: id:1741323218379, from:30004, delay:0.0001s, distance:214.79m (Euclidean)
[2025-03-07 13:53:44,276] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,276] [INFO] [30127] Received COMMIT: id:1741323218379, from:30004, delay:0.0001s, distance:214.79m (Euclidean)
[2025-03-07 13:53:44,309] [INFO] [30127] Received COMMIT: id:1741323218379, from:30094, delay:0.0000s, distance:249.71m (Euclidean)
[2025-03-07 13:53:44,402] [INFO] [30127] Received PREPARE: id:1741323218379, from:30047, delay:0.0002s, distance:266.87m (Euclidean)
[2025-03-07 13:53:44,402] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,402] [INFO] [30127] Received COMMIT: id:1741323218379, from:30047, delay:0.0002s, distance:266.87m (Euclidean)
[2025-03-07 13:53:44,513] [INFO] [30127] Received PREPARE: id:1741323218379, from:30036, delay:0.0001s, distance:215.93m (Euclidean)
[2025-03-07 13:53:44,529] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,529] [INFO] [30127] Received COMMIT: id:1741323218379, from:30036, delay:0.0001s, distance:215.93m (Euclidean)
[2025-03-07 13:53:44,640] [INFO] [30127] Received PREPARE: id:1741323218379, from:30024, delay:0.0002s, distance:266.54m (Euclidean)
[2025-03-07 13:53:44,640] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,656] [INFO] [30127] Received COMMIT: id:1741323218379, from:30024, delay:0.0002s, distance:266.54m (Euclidean)
[2025-03-07 13:53:44,801] [INFO] [30127] Received PREPARE: id:1741323218379, from:30088, delay:0.0001s, distance:191.07m (Euclidean)
[2025-03-07 13:53:44,813] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,813] [INFO] [30127] Received COMMIT: id:1741323218379, from:30088, delay:0.0001s, distance:191.07m (Euclidean)
[2025-03-07 13:53:44,869] [INFO] [30127] Received PREPARE: id:1741323218379, from:30046, delay:0.0002s, distance:285.07m (Euclidean)
[2025-03-07 13:53:44,869] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,869] [INFO] [30127] Received COMMIT: id:1741323218379, from:30046, delay:0.0002s, distance:285.07m (Euclidean)
[2025-03-07 13:53:44,879] [INFO] [30127] Received PREPARE: id:1741323218379, from:30039, delay:0.0001s, distance:212.84m (Euclidean)
[2025-03-07 13:53:44,879] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,879] [INFO] [30127] Received COMMIT: id:1741323218379, from:30039, delay:0.0001s, distance:212.84m (Euclidean)
[2025-03-07 13:53:44,892] [INFO] [30127] Received PREPARE: id:1741323218379, from:30017, delay:0.0000s, distance:196.16m (Euclidean)
[2025-03-07 13:53:44,892] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,892] [INFO] [30127] Received COMMIT: id:1741323218379, from:30017, delay:0.0000s, distance:196.16m (Euclidean)
[2025-03-07 13:53:45,027] [INFO] [30127] Received PREPARE: id:1741323218379, from:30032, delay:0.0001s, distance:253.38m (Euclidean)
[2025-03-07 13:53:45,027] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,027] [INFO] [30127] Received COMMIT: id:1741323218379, from:30032, delay:0.0001s, distance:253.38m (Euclidean)
[2025-03-07 13:53:45,066] [INFO] [30127] Received PREPARE: id:1741323218379, from:30099, delay:0.0001s, distance:224.55m (Euclidean)
[2025-03-07 13:53:45,066] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,066] [INFO] [30127] Received COMMIT: id:1741323218379, from:30099, delay:0.0001s, distance:224.55m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30127] Received PREPARE: id:1741323218379, from:30091, delay:0.0001s, distance:234.13m (Euclidean)
[2025-03-07 13:53:45,146] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,209] [INFO] [30127] Received PREPARE: id:1741323218379, from:30086, delay:0.0002s, distance:269.97m (Euclidean)
[2025-03-07 13:53:45,209] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,209] [INFO] [30127] Received COMMIT: id:1741323218379, from:30086, delay:0.0002s, distance:269.97m (Euclidean)
[2025-03-07 13:53:45,225] [INFO] [30127] Received COMMIT: id:1741323218379, from:30091, delay:0.0001s, distance:234.13m (Euclidean)
[2025-03-07 13:53:45,323] [INFO] [30127] Received PREPARE: id:1741323218379, from:30043, delay:0.0002s, distance:290.79m (Euclidean)
[2025-03-07 13:53:45,323] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,323] [INFO] [30127] Received COMMIT: id:1741323218379, from:30043, delay:0.0002s, distance:290.79m (Euclidean)
[2025-03-07 13:53:45,383] [INFO] [30127] Received PREPARE: id:1741323218379, from:30083, delay:0.0002s, distance:251.18m (Euclidean)
[2025-03-07 13:53:45,383] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,383] [INFO] [30127] Received COMMIT: id:1741323218379, from:30083, delay:0.0002s, distance:251.18m (Euclidean)
[2025-03-07 13:53:45,388] [INFO] [30127] Received PREPARE: id:1741323218379, from:30049, delay:0.0001s, distance:172.50m (Euclidean)
[2025-03-07 13:53:45,388] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,388] [INFO] [30127] Received COMMIT: id:1741323218379, from:30049, delay:0.0001s, distance:172.50m (Euclidean)
[2025-03-07 13:53:45,388] [INFO] [30127] Received PREPARE: id:1741323218379, from:30061, delay:0.0001s, distance:242.91m (Euclidean)
[2025-03-07 13:53:45,388] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,398] [INFO] [30127] Received COMMIT: id:1741323218379, from:30061, delay:0.0001s, distance:242.91m (Euclidean)
[2025-03-07 13:53:45,419] [INFO] [30127] Received PREPARE: id:1741323218379, from:30062, delay:0.0000s, distance:115.61m (Euclidean)
[2025-03-07 13:53:45,419] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,434] [INFO] [30127] Received COMMIT: id:1741323218379, from:30062, delay:0.0000s, distance:115.61m (Euclidean)
[2025-03-07 13:53:45,636] [INFO] [30127] Received PREPARE: id:1741323218379, from:30002, delay:0.0001s, distance:212.08m (Euclidean)
[2025-03-07 13:53:45,636] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,636] [INFO] [30127] Received COMMIT: id:1741323218379, from:30002, delay:0.0001s, distance:212.08m (Euclidean)
[2025-03-07 13:53:45,668] [INFO] [30127] Received PREPARE: id:1741323218379, from:30011, delay:0.0001s, distance:196.40m (Euclidean)
[2025-03-07 13:53:45,668] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,668] [INFO] [30127] Received COMMIT: id:1741323218379, from:30011, delay:0.0001s, distance:196.40m (Euclidean)
[2025-03-07 13:53:45,715] [INFO] [30127] Received PREPARE: id:1741323218379, from:30034, delay:0.0001s, distance:224.13m (Euclidean)
[2025-03-07 13:53:45,715] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,715] [INFO] [30127] Received COMMIT: id:1741323218379, from:30034, delay:0.0001s, distance:224.13m (Euclidean)
[2025-03-07 13:53:45,739] [INFO] [30127] Received PREPARE: id:1741323218379, from:30078, delay:0.0001s, distance:194.07m (Euclidean)
[2025-03-07 13:53:45,739] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,747] [INFO] [30127] Received COMMIT: id:1741323218379, from:30078, delay:0.0001s, distance:194.07m (Euclidean)
[2025-03-07 13:53:45,797] [INFO] [30127] Received PREPARE: id:1741323218379, from:30098, delay:0.0002s, distance:278.24m (Euclidean)
[2025-03-07 13:53:45,797] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,797] [INFO] [30127] Received COMMIT: id:1741323218379, from:30098, delay:0.0002s, distance:278.24m (Euclidean)
[2025-03-07 13:53:45,892] [INFO] [30127] Received PREPARE: id:1741323218379, from:30135, delay:0.0000s, distance:75.11m (Euclidean)
[2025-03-07 13:53:45,892] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,968] [INFO] [30127] Received PREPARE: id:1741323218379, from:30010, delay:0.0001s, distance:236.22m (Euclidean)
[2025-03-07 13:53:45,968] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,968] [INFO] [30127] Received COMMIT: id:1741323218379, from:30010, delay:0.0001s, distance:236.22m (Euclidean)
[2025-03-07 13:53:46,256] [INFO] [30127] Received PREPARE: id:1741323218379, from:30104, delay:0.0002s, distance:271.38m (Euclidean)
[2025-03-07 13:53:46,256] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,256] [INFO] [30127] Received COMMIT: id:1741323218379, from:30104, delay:0.0002s, distance:271.38m (Euclidean)
[2025-03-07 13:53:46,285] [INFO] [30127] Received PREPARE: id:1741323218379, from:30016, delay:0.0001s, distance:159.24m (Euclidean)
[2025-03-07 13:53:46,285] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,301] [INFO] [30127] Received COMMIT: id:1741323218379, from:30016, delay:0.0001s, distance:159.24m (Euclidean)
[2025-03-07 13:53:46,396] [INFO] [30127] Received PREPARE: id:1741323218379, from:30031, delay:0.0000s, distance:143.09m (Euclidean)
[2025-03-07 13:53:46,398] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,398] [INFO] [30127] Received COMMIT: id:1741323218379, from:30031, delay:0.0000s, distance:143.09m (Euclidean)
[2025-03-07 13:53:46,733] [INFO] [30127] Received PREPARE: id:1741323218379, from:30041, delay:0.0001s, distance:259.38m (Euclidean)
[2025-03-07 13:53:46,733] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,733] [INFO] [30127] Received COMMIT: id:1741323218379, from:30041, delay:0.0001s, distance:259.38m (Euclidean)
[2025-03-07 13:53:46,918] [INFO] [30127] Received PREPARE: id:1741323218379, from:30035, delay:0.0001s, distance:175.11m (Euclidean)
[2025-03-07 13:53:46,918] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,918] [INFO] [30127] Received COMMIT: id:1741323218379, from:30035, delay:0.0001s, distance:175.11m (Euclidean)
[2025-03-07 13:53:46,997] [INFO] [30127] Received PREPARE: id:1741323218379, from:30003, delay:0.0001s, distance:274.42m (Euclidean)
[2025-03-07 13:53:46,997] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,002] [INFO] [30127] Received COMMIT: id:1741323218379, from:30003, delay:0.0001s, distance:274.42m (Euclidean)
[2025-03-07 13:53:47,521] [INFO] [30127] Received PREPARE: id:1741323218379, from:30122, delay:0.0002s, distance:274.76m (Euclidean)
[2025-03-07 13:53:47,521] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,665] [INFO] [30127] Received COMMIT: id:1741323218379, from:30122, delay:0.0002s, distance:274.76m (Euclidean)
[2025-03-07 13:53:47,756] [INFO] [30127] Received PREPARE: id:1741323218379, from:30154, delay:0.0001s, distance:166.05m (Euclidean)
[2025-03-07 13:53:47,756] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,772] [INFO] [30127] Received COMMIT: id:1741323218379, from:30154, delay:0.0001s, distance:166.05m (Euclidean)
[2025-03-07 13:53:47,897] [INFO] [30127] Received PREPARE: id:1741323218379, from:30158, delay:0.0002s, distance:266.60m (Euclidean)
[2025-03-07 13:53:47,897] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,897] [INFO] [30127] Received COMMIT: id:1741323218379, from:30158, delay:0.0002s, distance:266.60m (Euclidean)
[2025-03-07 13:53:47,947] [INFO] [30127] Received COMMIT: id:1741323218379, from:30135, delay:0.0000s, distance:75.11m (Euclidean)
[2025-03-07 13:53:47,947] [INFO] [30127] Received PREPARE: id:1741323218379, from:30105, delay:0.0002s, distance:296.67m (Euclidean)
[2025-03-07 13:53:47,947] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,947] [INFO] [30127] Received COMMIT: id:1741323218379, from:30105, delay:0.0002s, distance:296.67m (Euclidean)
[2025-03-07 13:53:47,947] [INFO] [30127] Received PREPARE: id:1741323218379, from:30147, delay:0.0002s, distance:270.19m (Euclidean)
[2025-03-07 13:53:47,947] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,947] [INFO] [30127] Received PREPARE: id:1741323218379, from:30134, delay:0.0002s, distance:278.74m (Euclidean)
[2025-03-07 13:53:47,947] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,947] [INFO] [30127] Received COMMIT: id:1741323218379, from:30134, delay:0.0002s, distance:278.74m (Euclidean)
[2025-03-07 13:53:47,947] [INFO] [30127] Received COMMIT: id:1741323218379, from:30147, delay:0.0002s, distance:270.19m (Euclidean)
[2025-03-07 13:53:48,031] [INFO] [30127] Received PREPARE: id:1741323218379, from:30153, delay:0.0002s, distance:290.42m (Euclidean)
[2025-03-07 13:53:48,031] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,031] [INFO] [30127] Received COMMIT: id:1741323218379, from:30153, delay:0.0002s, distance:290.42m (Euclidean)
[2025-03-07 13:53:48,249] [INFO] [30127] Received PREPARE: id:1741323218379, from:30136, delay:0.0000s, distance:105.56m (Euclidean)
[2025-03-07 13:53:48,249] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,249] [INFO] [30127] Received COMMIT: id:1741323218379, from:30136, delay:0.0000s, distance:105.56m (Euclidean)
[2025-03-07 13:53:48,612] [INFO] [30127] Received PREPARE: id:1741323218379, from:30157, delay:0.0001s, distance:222.17m (Euclidean)
[2025-03-07 13:53:48,612] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,612] [INFO] [30127] Received PREPARE: id:1741323218379, from:30139, delay:0.0002s, distance:289.51m (Euclidean)
[2025-03-07 13:53:48,612] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,612] [INFO] [30127] Received COMMIT: id:1741323218379, from:30139, delay:0.0002s, distance:289.51m (Euclidean)
[2025-03-07 13:53:48,627] [INFO] [30127] Received COMMIT: id:1741323218379, from:30157, delay:0.0001s, distance:222.17m (Euclidean)
[2025-03-07 13:53:48,829] [INFO] [30127] Received PREPARE: id:1741323218379, from:30128, delay:0.0001s, distance:186.29m (Euclidean)
[2025-03-07 13:53:48,829] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,829] [INFO] [30127] Received COMMIT: id:1741323218379, from:30128, delay:0.0001s, distance:186.29m (Euclidean)
[2025-03-07 13:53:48,861] [INFO] [30127] Received PREPARE: id:1741323218379, from:30131, delay:0.0001s, distance:211.52m (Euclidean)
[2025-03-07 13:53:48,861] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,861] [INFO] [30127] Received COMMIT: id:1741323218379, from:30131, delay:0.0001s, distance:211.52m (Euclidean)
[2025-03-07 13:53:48,902] [INFO] [30127] Received PREPARE: id:1741323218379, from:30107, delay:0.0001s, distance:183.76m (Euclidean)
[2025-03-07 13:53:48,902] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,912] [INFO] [30127] Received COMMIT: id:1741323218379, from:30107, delay:0.0001s, distance:183.76m (Euclidean)
[2025-03-07 13:53:49,272] [INFO] [30127] Received PREPARE: id:1741323218379, from:30151, delay:0.0002s, distance:263.79m (Euclidean)
[2025-03-07 13:53:49,272] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:49,304] [INFO] [30127] Received COMMIT: id:1741323218379, from:30151, delay:0.0002s, distance:263.79m (Euclidean)
[2025-03-07 13:53:50,238] [INFO] [30127] Received PREPARE: id:1741323218379, from:30119, delay:0.0000s, distance:92.72m (Euclidean)
[2025-03-07 13:53:50,238] [INFO] [30127] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:50,476] [INFO] [30127] Received PRE-PREPARE: id:1741323218379, from:Leader(30000), delay:0.0000s, distance:182.65m (Euclidean)
[2025-03-07 13:53:50,476] [INFO] [30127] Broadcasting PREPARE for REQUEST 1741323218379
[2025-03-07 13:53:50,934] [INFO] [30127] Received COMMIT: id:1741323218379, from:30119, delay:0.0000s, distance:92.72m (Euclidean)
[2025-03-07 13:53:50,934] [INFO] [30127] Received COMMIT: id:1741323218379, from:30000, delay:0.0000s, distance:182.65m (Euclidean)
[2025-03-07 13:53:51,000] [INFO] [30127] Received PREPARE: id:1741323218379, from:30123, delay:0.0000s, distance:130.43m (Euclidean)
[2025-03-07 13:53:51,000] [INFO] [30127] Broadcasting COMMIT for REQUEST 1741323218379
[2025-03-07 13:53:51,273] [INFO] [30127] Received PREPARE: id:1741323218379, from:30126, delay:0.0002s, distance:286.92m (Euclidean)
[2025-03-07 13:53:51,273] [INFO] [30127] Received COMMIT: id:1741323218379, from:30126, delay:0.0002s, distance:286.92m (Euclidean)
[2025-03-07 13:53:52,009] [INFO] [30127] Received PREPARE: id:1741323218379, from:30116, delay:0.0001s, distance:215.38m (Euclidean)
[2025-03-07 13:53:52,024] [INFO] [30127] Received COMMIT: id:1741323218379, from:30116, delay:0.0001s, distance:215.38m (Euclidean)
[2025-03-07 13:53:52,501] [INFO] [30127] Received PREPARE: id:1741323218379, from:30150, delay:0.0000s, distance:10.56m (Euclidean)
[2025-03-07 13:53:52,501] [INFO] [30127] Received COMMIT: id:1741323218379, from:30150, delay:0.0000s, distance:10.56m (Euclidean)
[2025-03-07 13:53:53,163] [INFO] [30127] Received COMMIT: id:1741323218379, from:30123, delay:0.0000s, distance:130.43m (Euclidean)
[2025-03-07 13:53:53,309] [INFO] [30127] Received PREPARE: id:1741323218379, from:30129, delay:0.0001s, distance:268.45m (Euclidean)
[2025-03-07 13:53:53,321] [INFO] [30127] Received COMMIT: id:1741323218379, from:30129, delay:0.0001s, distance:268.45m (Euclidean)
[2025-03-07 13:53:53,327] [INFO] [30127] Received PREPARE: id:1741323218379, from:30121, delay:0.0001s, distance:227.75m (Euclidean)
[2025-03-07 13:53:53,327] [INFO] [30127] Received PREPARE: id:1741323218379, from:30118, delay:0.0000s, distance:152.83m (Euclidean)
[2025-03-07 13:53:53,327] [INFO] [30127] Received COMMIT: id:1741323218379, from:30121, delay:0.0001s, distance:227.75m (Euclidean)
[2025-03-07 13:53:53,327] [INFO] [30127] Received COMMIT: id:1741323218379, from:30118, delay:0.0000s, distance:152.83m (Euclidean)
[2025-03-07 13:53:53,416] [INFO] [30127] Received PREPARE: id:1741323218379, from:30108, delay:0.0001s, distance:188.63m (Euclidean)
[2025-03-07 13:53:53,416] [INFO] [30127] Received COMMIT: id:1741323218379, from:30108, delay:0.0001s, distance:188.63m (Euclidean)
[2025-03-07 13:53:53,437] [INFO] [30127] Received PREPARE: id:1741323218379, from:30146, delay:0.0000s, distance:127.71m (Euclidean)
[2025-03-07 13:53:53,437] [INFO] [30127] Received COMMIT: id:1741323218379, from:30146, delay:0.0000s, distance:127.71m (Euclidean)
[2025-03-07 13:53:53,543] [INFO] [30127] Received PREPARE: id:1741323218379, from:30106, delay:0.0001s, distance:210.50m (Euclidean)
[2025-03-07 13:53:53,543] [INFO] [30127] Received COMMIT: id:1741323218379, from:30106, delay:0.0001s, distance:210.50m (Euclidean)
[2025-03-07 13:53:53,669] [INFO] [30127] Received PREPARE: id:1741323218379, from:30159, delay:0.0002s, distance:250.35m (Euclidean)
[2025-03-07 13:53:53,844] [INFO] [30127] Received COMMIT: id:1741323218379, from:30159, delay:0.0002s, distance:250.35m (Euclidean)
[2025-03-07 13:53:54,076] [INFO] [30127] Received PREPARE: id:1741323218379, from:30152, delay:0.0001s, distance:177.54m (Euclidean)
[2025-03-07 13:53:54,081] [INFO] [30127] Received COMMIT: id:1741323218379, from:30152, delay:0.0001s, distance:177.54m (Euclidean)
[2025-03-07 13:53:55,498] [ERROR] [30127] Error sending to http://localhost:30029/prepare: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30029)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
[2025-03-07 13:53:55,503] [ERROR] [30127] Error sending to http://localhost:30085/prepare: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30085)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
[2025-03-07 13:53:55,503] [ERROR] [30127] Error sending to http://localhost:30101/prepare: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30101)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
[2025-03-07 13:53:55,517] [ERROR] [30127] Error sending to http://localhost:30027/prepare: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30027)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
[2025-03-07 13:53:55,535] [INFO] [30127] Received PREPARE: id:1741323218379, from:30149, delay:0.0002s, distance:276.36m (Euclidean)
[2025-03-07 13:53:55,555] [INFO] [30127] Received COMMIT: id:1741323218379, from:30149, delay:0.0002s, distance:276.36m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received COMMIT: id:1741323218379, from:30111, delay:0.0000s, distance:142.04m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received COMMIT: id:1741323218379, from:30113, delay:0.0001s, distance:246.63m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received COMMIT: id:1741323218379, from:30115, delay:0.0001s, distance:263.97m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received PREPARE: id:1741323218379, from:30113, delay:0.0001s, distance:246.63m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received COMMIT: id:1741323218379, from:30156, delay:0.0001s, distance:245.17m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received PREPARE: id:1741323218379, from:30156, delay:0.0001s, distance:245.17m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received PREPARE: id:1741323218379, from:30111, delay:0.0000s, distance:142.04m (Euclidean)
[2025-03-07 13:53:55,559] [INFO] [30127] Received PREPARE: id:1741323218379, from:30115, delay:0.0001s, distance:263.97m (Euclidean)
[2025-03-07 13:53:55,613] [ERROR] [30127] Error sending to http://localhost:30023/prepare: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30023)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
[2025-03-07 13:53:55,613] [ERROR] [30127] Error sending to http://localhost:30025/prepare: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('127.0.0.1', 30025)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30025)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('127.0.0.1', 30025)]
[2025-03-07 13:53:55,660] [INFO] [30127] Received PREPARE: id:1741323218379, from:30022, delay:0.0002s, distance:285.36m (Euclidean)
[2025-03-07 13:53:55,669] [INFO] [30127] Received COMMIT: id:1741323218379, from:30022, delay:0.0002s, distance:285.36m (Euclidean)
[2025-03-07 13:53:55,676] [ERROR] [30127] Error sending to http://localhost:30008/prepare: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30008)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
[2025-03-07 13:53:55,692] [ERROR] [30127] Error sending to http://localhost:30008/commit: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30008, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
[2025-03-07 13:53:55,866] [ERROR] [30127] Error sending to http://localhost:30143/prepare: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('127.0.0.1', 30143)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30143)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('127.0.0.1', 30143)]
[2025-03-07 13:53:55,914] [ERROR] [30127] Error sending to http://localhost:30141/prepare: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('127.0.0.1', 30141)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30141)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('127.0.0.1', 30141)]
[2025-03-07 13:53:55,978] [ERROR] [30127] Error sending to http://localhost:30027/commit: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30027, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
[2025-03-07 13:53:57,508] [ERROR] [30127] Error sending to http://localhost:30093/prepare: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30093)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
[2025-03-07 13:53:57,521] [ERROR] [30127] Error sending to http://localhost:30141/commit: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('::1', 30141, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30141, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30141 ssl:default [Connect call failed ('::1', 30141, 0, 0)]
[2025-03-07 13:53:57,537] [ERROR] [30127] Error sending to http://localhost:30063/commit: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30063, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
[2025-03-07 13:53:57,537] [ERROR] [30127] Error sending to http://localhost:30093/commit: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30093, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
[2025-03-07 13:53:57,537] [ERROR] [30127] Error sending to http://localhost:30023/commit: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30023, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
[2025-03-07 13:53:57,537] [ERROR] [30127] Error sending to http://localhost:30063/prepare: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30063)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
[2025-03-07 13:53:57,537] [ERROR] [30127] Error sending to http://localhost:30143/commit: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('::1', 30143, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30143, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('::1', 30143, 0, 0)]
[2025-03-07 13:53:57,537] [ERROR] [30127] Error sending to http://localhost:30025/commit: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('::1', 30025, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30025, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30025 ssl:default [Connect call failed ('::1', 30025, 0, 0)]
[2025-03-07 13:53:57,537] [ERROR] [30127] Error sending to http://localhost:30137/commit: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30137, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
[2025-03-07 13:53:57,553] [ERROR] [30127] Error sending to http://localhost:30075/commit: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30075, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
[2025-03-07 13:53:57,553] [ERROR] [30127] Error sending to http://localhost:30101/commit: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30101, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
[2025-03-07 13:53:57,553] [ERROR] [30127] Error sending to http://localhost:30085/commit: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30085, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
[2025-03-07 13:53:57,555] [ERROR] [30127] Error sending to http://localhost:30075/prepare: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30075)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30124/prepare: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30065/commit: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('::1', 30065, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30065, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('::1', 30065, 0, 0)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30137/prepare: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30137)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30124/commit: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30124, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30029/commit: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30029, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:53:57,569] [ERROR] [30127] Error sending to http://localhost:30065/prepare: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('127.0.0.1', 30065)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30065)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30065 ssl:default [Connect call failed ('127.0.0.1', 30065)]
[2025-03-07 13:53:57,600] [ERROR] [30127] Error sending to http://localhost:30138/prepare: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30138)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
[2025-03-07 13:53:57,600] [ERROR] [30127] Error sending to http://localhost:30138/commit: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30138, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
[2025-03-07 13:53:57,854] [ERROR] [30127] Error sending to http://localhost:30066/commit: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30066, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
[2025-03-07 13:53:57,854] [ERROR] [30127] Error sending to http://localhost:30066/prepare: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30066)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
[2025-03-07 13:53:57,888] [ERROR] [30127] Error sending to http://localhost:30100/prepare: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('127.0.0.1', 30100)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30100)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('127.0.0.1', 30100)]
[2025-03-07 13:53:57,902] [ERROR] [30127] Error sending to http://localhost:30100/commit: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('::1', 30100, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30100, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30100 ssl:default [Connect call failed ('::1', 30100, 0, 0)]
[2025-03-07 13:53:58,028] [ERROR] [30127] Error sending to http://localhost:30064/prepare: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30064)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
[2025-03-07 13:53:58,030] [ERROR] [30127] Error sending to http://localhost:30064/commit: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30064, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
[2025-03-07 13:53:59,624] [ERROR] [30127] Error sending to http://localhost:30076/prepare: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
[2025-03-07 13:53:59,628] [ERROR] [30127] Error sending to http://localhost:30076/commit: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30076, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
[2025-03-07 13:54:53,258] [INFO] Starting node at localhost:30127 | index=128 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:39,695] [INFO] Starting node at localhost:30127 | index=128 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:42,116] [INFO] Starting node at localhost:30127 | index=128 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:02,625] [INFO] [30127] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0000s, distance:158.33m (Euclidean)
[2025-03-07 13:59:02,625] [INFO] [30127] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:02,634] [INFO] [30127] Not broadcasting to fault node: 30077
[2025-03-07 13:59:02,648] [INFO] [30127] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,148] [INFO] [30127] Received PREPARE: id:1741323542381, from:30167, delay:0.0000s, distance:299.85m (Euclidean)
[2025-03-07 13:59:03,532] [INFO] [30127] Received PREPARE: id:1741323542381, from:30089, delay:0.0000s, distance:35.38m (Euclidean)
[2025-03-07 13:59:03,532] [INFO] [30127] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:03,556] [INFO] [30127] Not broadcasting to fault node: 30077
[2025-03-07 13:59:03,574] [INFO] [30127] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,805] [INFO] [30127] Received PREPARE: id:1741323542381, from:30196, delay:0.0000s, distance:147.85m (Euclidean)
[2025-03-07 13:59:04,088] [INFO] [30127] Received PREPARE: id:1741323542381, from:30133, delay:0.0001s, distance:175.91m (Euclidean)
[2025-03-07 13:59:04,088] [INFO] [30127] Received PREPARE: id:1741323542381, from:30095, delay:0.0000s, distance:149.94m (Euclidean)
[2025-03-07 13:59:04,088] [INFO] [30127] Received PREPARE: id:1741323542381, from:30113, delay:0.0000s, distance:146.10m (Euclidean)
[2025-03-07 13:59:04,119] [INFO] [30127] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:114.52m (Euclidean)
[2025-03-07 13:59:04,119] [INFO] [30127] Received PREPARE: id:1741323542381, from:30115, delay:0.0000s, distance:103.71m (Euclidean)
[2025-03-07 13:59:04,190] [INFO] [30127] Received PREPARE: id:1741323542381, from:30102, delay:0.0000s, distance:173.65m (Euclidean)
[2025-03-07 13:59:04,190] [INFO] [30127] Received PREPARE: id:1741323542381, from:30169, delay:0.0001s, distance:156.47m (Euclidean)
[2025-03-07 13:59:04,197] [INFO] [30127] Received PREPARE: id:1741323542381, from:30057, delay:0.0000s, distance:41.72m (Euclidean)
[2025-03-07 13:59:04,197] [INFO] [30127] Received PREPARE: id:1741323542381, from:30112, delay:0.0000s, distance:74.15m (Euclidean)
[2025-03-07 13:59:04,209] [INFO] [30127] Received PREPARE: id:1741323542381, from:30110, delay:0.0001s, distance:204.51m (Euclidean)
[2025-03-07 13:59:04,277] [INFO] [30127] Received PREPARE: id:1741323542381, from:30013, delay:0.0000s, distance:146.49m (Euclidean)
[2025-03-07 13:59:04,322] [INFO] [30127] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:117.89m (Euclidean)
[2025-03-07 13:59:04,322] [INFO] [30127] Received PREPARE: id:1741323542381, from:30181, delay:0.0000s, distance:72.47m (Euclidean)
[2025-03-07 13:59:04,386] [INFO] [30127] Received PREPARE: id:1741323542381, from:30046, delay:0.0000s, distance:87.92m (Euclidean)
[2025-03-07 13:59:04,419] [INFO] [30127] Received COMMIT: id:1741323542381, from:30112, delay:0.0000s, distance:74.15m (Euclidean)
[2025-03-07 13:59:04,601] [INFO] [30127] Received COMMIT: id:1741323542381, from:30113, delay:0.0000s, distance:146.10m (Euclidean)
[2025-03-07 13:59:04,601] [INFO] [LEADER 30127] Sending REPLY for REQUEST 1741323542381 to CLIENT
[2025-03-07 13:59:04,612] [INFO] [30127] Received PREPARE: id:1741323542381, from:30130, delay:0.0000s, distance:85.72m (Euclidean)
[2025-03-07 13:59:04,614] [INFO] [30127] Received COMMIT: id:1741323542381, from:30130, delay:0.0000s, distance:85.72m (Euclidean)
[2025-03-07 13:59:04,628] [INFO] [30127] Received PREPARE: id:1741323542381, from:30106, delay:0.0000s, distance:29.60m (Euclidean)
[2025-03-07 13:59:04,628] [INFO] [30127] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:114.52m (Euclidean)
[2025-03-07 13:59:04,646] [INFO] [30127] Received COMMIT: id:1741323542381, from:30133, delay:0.0001s, distance:175.91m (Euclidean)
[2025-03-07 13:59:04,699] [INFO] [30127] Received PREPARE: id:1741323542381, from:30074, delay:0.0001s, distance:211.80m (Euclidean)
[2025-03-07 13:59:04,699] [INFO] [30127] Received COMMIT: id:1741323542381, from:30106, delay:0.0000s, distance:29.60m (Euclidean)
[2025-03-07 13:59:04,699] [INFO] [30127] Received PREPARE: id:1741323542381, from:30182, delay:0.0001s, distance:204.82m (Euclidean)
[2025-03-07 13:59:04,701] [INFO] [30127] Received COMMIT: id:1741323542381, from:30182, delay:0.0001s, distance:204.82m (Euclidean)
[2025-03-07 13:59:04,730] [INFO] [30127] Received COMMIT: id:1741323542381, from:30110, delay:0.0001s, distance:204.51m (Euclidean)
[2025-03-07 13:59:04,740] [INFO] [30127] Received PREPARE: id:1741323542381, from:30189, delay:0.0000s, distance:145.28m (Euclidean)
[2025-03-07 13:59:04,756] [INFO] [30127] Received COMMIT: id:1741323542381, from:30189, delay:0.0000s, distance:145.28m (Euclidean)
[2025-03-07 13:59:04,812] [INFO] [30127] Received PREPARE: id:1741323542381, from:30190, delay:0.0002s, distance:280.85m (Euclidean)
[2025-03-07 13:59:04,842] [INFO] [30127] Received COMMIT: id:1741323542381, from:30196, delay:0.0000s, distance:147.85m (Euclidean)
[2025-03-07 13:59:04,853] [INFO] [30127] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:93.93m (Euclidean)
[2025-03-07 13:59:04,877] [INFO] [30127] Received PREPARE: id:1741323542381, from:30093, delay:0.0000s, distance:106.08m (Euclidean)
[2025-03-07 13:59:04,878] [INFO] [30127] Received PREPARE: id:1741323542381, from:30023, delay:0.0000s, distance:115.52m (Euclidean)
[2025-03-07 13:59:04,878] [INFO] [30127] Received PREPARE: id:1741323542381, from:30085, delay:0.0000s, distance:122.80m (Euclidean)
[2025-03-07 13:59:04,879] [INFO] [30127] Received COMMIT: id:1741323542381, from:30093, delay:0.0000s, distance:106.08m (Euclidean)
[2025-03-07 13:59:04,879] [INFO] [30127] Received COMMIT: id:1741323542381, from:30023, delay:0.0000s, distance:115.52m (Euclidean)
[2025-03-07 13:59:04,974] [INFO] [30127] Received COMMIT: id:1741323542381, from:30095, delay:0.0000s, distance:149.94m (Euclidean)
[2025-03-07 13:59:05,097] [INFO] [30127] Received PREPARE: id:1741323542381, from:30060, delay:0.0000s, distance:57.79m (Euclidean)
[2025-03-07 13:59:05,351] [INFO] [30127] Received PREPARE: id:1741323542381, from:30168, delay:0.0000s, distance:112.79m (Euclidean)
[2025-03-07 13:59:05,476] [INFO] [30127] Received PREPARE: id:1741323542381, from:30124, delay:0.0001s, distance:215.90m (Euclidean)
[2025-03-07 13:59:05,476] [INFO] [30127] Received PREPARE: id:1741323542381, from:30035, delay:0.0001s, distance:173.00m (Euclidean)
[2025-03-07 13:59:05,476] [INFO] [30127] Received COMMIT: id:1741323542381, from:30190, delay:0.0002s, distance:280.85m (Euclidean)
[2025-03-07 13:59:05,692] [INFO] [30127] Received PREPARE: id:1741323542381, from:30120, delay:0.0000s, distance:148.33m (Euclidean)
[2025-03-07 13:59:05,693] [INFO] [30127] Received COMMIT: id:1741323542381, from:30168, delay:0.0000s, distance:112.79m (Euclidean)
[2025-03-07 13:59:05,693] [INFO] [30127] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:93.93m (Euclidean)
[2025-03-07 13:59:05,695] [INFO] [30127] Received PREPARE: id:1741323542381, from:30174, delay:0.0001s, distance:163.71m (Euclidean)
[2025-03-07 13:59:05,834] [INFO] [30127] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:121.52m (Euclidean)
[2025-03-07 13:59:05,987] [INFO] [30127] Received PREPARE: id:1741323542381, from:30180, delay:0.0002s, distance:255.01m (Euclidean)
[2025-03-07 13:59:05,987] [INFO] [30127] Received COMMIT: id:1741323542381, from:30102, delay:0.0000s, distance:173.65m (Euclidean)
[2025-03-07 13:59:06,201] [INFO] [30127] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:135.75m (Euclidean)
[2025-03-07 13:59:06,201] [INFO] [30127] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:92.89m (Euclidean)
[2025-03-07 13:59:06,201] [INFO] [30127] Received PREPARE: id:1741323542381, from:30199, delay:0.0001s, distance:225.86m (Euclidean)
[2025-03-07 13:59:06,203] [INFO] [30127] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:121.52m (Euclidean)
[2025-03-07 13:59:06,203] [INFO] [30127] Received PREPARE: id:1741323542381, from:30037, delay:0.0001s, distance:231.28m (Euclidean)
[2025-03-07 13:59:06,203] [INFO] [30127] Received PREPARE: id:1741323542381, from:30054, delay:0.0000s, distance:138.35m (Euclidean)
[2025-03-07 13:59:06,361] [INFO] [30127] Received COMMIT: id:1741323542381, from:30060, delay:0.0000s, distance:57.79m (Euclidean)
[2025-03-07 13:59:06,363] [INFO] [30127] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:127.67m (Euclidean)
[2025-03-07 13:59:06,363] [INFO] [30127] Received COMMIT: id:1741323542381, from:30037, delay:0.0001s, distance:231.28m (Euclidean)
[2025-03-07 13:59:06,363] [INFO] [30127] Received COMMIT: id:1741323542381, from:30035, delay:0.0001s, distance:173.00m (Euclidean)
[2025-03-07 13:59:06,452] [INFO] [30127] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:127.67m (Euclidean)
[2025-03-07 13:59:06,454] [INFO] [30127] Received PREPARE: id:1741323542381, from:30048, delay:0.0000s, distance:189.30m (Euclidean)
[2025-03-07 13:59:06,454] [INFO] [30127] Received COMMIT: id:1741323542381, from:30057, delay:0.0000s, distance:41.72m (Euclidean)
[2025-03-07 13:59:06,454] [INFO] [30127] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:153.91m (Euclidean)
[2025-03-07 13:59:06,594] [INFO] [30127] Received COMMIT: id:1741323542381, from:30054, delay:0.0000s, distance:138.35m (Euclidean)
[2025-03-07 13:59:06,594] [INFO] [30127] Received COMMIT: id:1741323542381, from:30048, delay:0.0000s, distance:189.30m (Euclidean)
[2025-03-07 13:59:06,594] [INFO] [30127] Received PREPARE: id:1741323542381, from:30128, delay:0.0002s, distance:290.99m (Euclidean)
[2025-03-07 13:59:06,635] [INFO] [30127] Received PREPARE: id:1741323542381, from:30154, delay:0.0000s, distance:161.01m (Euclidean)
[2025-03-07 13:59:06,635] [INFO] [30127] Received COMMIT: id:1741323542381, from:30013, delay:0.0000s, distance:146.49m (Euclidean)
[2025-03-07 13:59:06,635] [INFO] [30127] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:153.91m (Euclidean)
[2025-03-07 13:59:06,635] [INFO] [30127] Received COMMIT: id:1741323542381, from:30128, delay:0.0002s, distance:290.99m (Euclidean)
[2025-03-07 13:59:06,635] [INFO] [30127] Received PREPARE: id:1741323542381, from:30015, delay:0.0000s, distance:137.29m (Euclidean)
[2025-03-07 13:59:06,640] [INFO] [30127] Received COMMIT: id:1741323542381, from:30169, delay:0.0001s, distance:156.47m (Euclidean)
[2025-03-07 13:59:06,736] [INFO] [30127] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:99.42m (Euclidean)
[2025-03-07 13:59:06,736] [INFO] [30127] Received COMMIT: id:1741323542381, from:30120, delay:0.0000s, distance:148.33m (Euclidean)
[2025-03-07 13:59:06,840] [INFO] [30127] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:92.89m (Euclidean)
[2025-03-07 13:59:06,840] [INFO] [30127] Received COMMIT: id:1741323542381, from:30154, delay:0.0000s, distance:161.01m (Euclidean)
[2025-03-07 13:59:06,915] [INFO] [30127] Received PREPARE: id:1741323542381, from:30107, delay:0.0002s, distance:266.05m (Euclidean)
[2025-03-07 13:59:07,022] [INFO] [30127] Received COMMIT: id:1741323542381, from:30124, delay:0.0001s, distance:215.90m (Euclidean)
[2025-03-07 13:59:07,024] [INFO] [30127] Received COMMIT: id:1741323542381, from:30046, delay:0.0000s, distance:87.92m (Euclidean)
[2025-03-07 13:59:07,066] [INFO] [30127] Received PREPARE: id:1741323542381, from:30191, delay:0.0001s, distance:203.96m (Euclidean)
[2025-03-07 13:59:07,066] [INFO] [30127] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:177.56m (Euclidean)
[2025-03-07 13:59:07,103] [INFO] [30127] Received COMMIT: id:1741323542381, from:30085, delay:0.0000s, distance:122.80m (Euclidean)
[2025-03-07 13:59:07,103] [INFO] [30127] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:99.42m (Euclidean)
[2025-03-07 13:59:07,103] [INFO] [30127] Received COMMIT: id:1741323542381, from:30015, delay:0.0000s, distance:137.29m (Euclidean)
[2025-03-07 13:59:07,149] [INFO] [30127] Received PREPARE: id:1741323542381, from:30020, delay:0.0001s, distance:214.98m (Euclidean)
[2025-03-07 13:59:07,149] [INFO] [30127] Received PREPARE: id:1741323542381, from:30126, delay:0.0001s, distance:210.41m (Euclidean)
[2025-03-07 13:59:07,239] [INFO] [30127] Received COMMIT: id:1741323542381, from:30126, delay:0.0001s, distance:210.41m (Euclidean)
[2025-03-07 13:59:07,239] [INFO] [30127] Received COMMIT: id:1741323542381, from:30020, delay:0.0001s, distance:214.98m (Euclidean)
[2025-03-07 13:59:07,400] [INFO] [30127] Received COMMIT: id:1741323542381, from:30167, delay:0.0000s, distance:299.85m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30127] Received COMMIT: id:1741323542381, from:30028, delay:0.0001s, distance:222.09m (Euclidean)
[2025-03-07 13:59:07,479] [INFO] [30127] Received PREPARE: id:1741323542381, from:30028, delay:0.0001s, distance:222.09m (Euclidean)
[2025-03-07 13:59:07,652] [INFO] [30127] Received PREPARE: id:1741323542381, from:30136, delay:0.0001s, distance:221.20m (Euclidean)
[2025-03-07 13:59:07,652] [INFO] [30127] Received PREPARE: id:1741323542381, from:30147, delay:0.0001s, distance:237.15m (Euclidean)
[2025-03-07 13:59:07,652] [INFO] [30127] Received COMMIT: id:1741323542381, from:30115, delay:0.0000s, distance:103.71m (Euclidean)
[2025-03-07 13:59:07,768] [INFO] [30127] Received PREPARE: id:1741323542381, from:30076, delay:0.0001s, distance:167.75m (Euclidean)
[2025-03-07 13:59:07,794] [INFO] [30127] Received COMMIT: id:1741323542381, from:30180, delay:0.0002s, distance:255.01m (Euclidean)
[2025-03-07 13:59:07,795] [INFO] [30127] Received COMMIT: id:1741323542381, from:30107, delay:0.0002s, distance:266.05m (Euclidean)
[2025-03-07 13:59:07,795] [INFO] [30127] Received COMMIT: id:1741323542381, from:30147, delay:0.0001s, distance:237.15m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30127] Received PREPARE: id:1741323542381, from:30119, delay:0.0001s, distance:248.24m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30127] Received PREPARE: id:1741323542381, from:30062, delay:0.0002s, distance:259.50m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30127] Received PREPARE: id:1741323542381, from:30123, delay:0.0000s, distance:125.20m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30127] Received PREPARE: id:1741323542381, from:30063, delay:0.0001s, distance:154.77m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30127] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:117.89m (Euclidean)
[2025-03-07 13:59:07,894] [INFO] [30127] Received COMMIT: id:1741323542381, from:30174, delay:0.0001s, distance:163.71m (Euclidean)
[2025-03-07 13:59:07,912] [INFO] [30127] Received COMMIT: id:1741323542381, from:30063, delay:0.0001s, distance:154.77m (Euclidean)
[2025-03-07 13:59:07,912] [INFO] [30127] Received COMMIT: id:1741323542381, from:30062, delay:0.0002s, distance:259.50m (Euclidean)
[2025-03-07 13:59:07,912] [INFO] [30127] Received COMMIT: id:1741323542381, from:30029, delay:0.0001s, distance:248.48m (Euclidean)
[2025-03-07 13:59:07,912] [INFO] [30127] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:166.41m (Euclidean)
[2025-03-07 13:59:07,912] [INFO] [30127] Received COMMIT: id:1741323542381, from:30171, delay:0.0000s, distance:91.39m (Euclidean)
[2025-03-07 13:59:07,978] [INFO] [30127] Received PREPARE: id:1741323542381, from:30171, delay:0.0000s, distance:91.39m (Euclidean)
[2025-03-07 13:59:07,978] [INFO] [30127] Received COMMIT: id:1741323542381, from:30076, delay:0.0001s, distance:167.75m (Euclidean)
[2025-03-07 13:59:07,978] [INFO] [30127] Received PREPARE: id:1741323542381, from:30029, delay:0.0001s, distance:248.48m (Euclidean)
[2025-03-07 13:59:07,980] [INFO] [30127] Received COMMIT: id:1741323542381, from:30119, delay:0.0001s, distance:248.24m (Euclidean)
[2025-03-07 13:59:07,980] [INFO] [30127] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:166.41m (Euclidean)
[2025-03-07 13:59:08,023] [INFO] [30127] Received COMMIT: id:1741323542381, from:30123, delay:0.0000s, distance:125.20m (Euclidean)
[2025-03-07 13:59:08,023] [INFO] [30127] Received COMMIT: id:1741323542381, from:30074, delay:0.0001s, distance:211.80m (Euclidean)
[2025-03-07 13:59:08,025] [INFO] [30127] Received COMMIT: id:1741323542381, from:30098, delay:0.0001s, distance:168.50m (Euclidean)
[2025-03-07 13:59:08,025] [INFO] [30127] Received PREPARE: id:1741323542381, from:30098, delay:0.0001s, distance:168.50m (Euclidean)
[2025-03-07 13:59:08,025] [INFO] [30127] Received COMMIT: id:1741323542381, from:30199, delay:0.0001s, distance:225.86m (Euclidean)
[2025-03-07 13:59:08,046] [INFO] [30127] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:177.56m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30127] Received COMMIT: id:1741323542381, from:30025, delay:0.0000s, distance:135.76m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30127] Received COMMIT: id:1741323542381, from:30181, delay:0.0000s, distance:72.47m (Euclidean)
[2025-03-07 13:59:08,074] [INFO] [30127] Received PREPARE: id:1741323542381, from:30025, delay:0.0000s, distance:135.76m (Euclidean)
[2025-03-07 13:59:08,127] [INFO] [30127] Received COMMIT: id:1741323542381, from:30089, delay:0.0000s, distance:35.38m (Euclidean)
[2025-03-07 13:59:08,141] [INFO] [30127] Received PREPARE: id:1741323542381, from:30157, delay:0.0000s, distance:116.42m (Euclidean)
[2025-03-07 13:59:08,143] [INFO] [30127] Received COMMIT: id:1741323542381, from:30157, delay:0.0000s, distance:116.42m (Euclidean)
[2025-03-07 13:59:08,174] [INFO] [30127] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:135.75m (Euclidean)
[2025-03-07 13:59:08,222] [INFO] [30127] Received PREPARE: id:1741323542381, from:30179, delay:0.0002s, distance:268.85m (Euclidean)
[2025-03-07 13:59:08,222] [INFO] [30127] Received COMMIT: id:1741323542381, from:30179, delay:0.0002s, distance:268.85m (Euclidean)
[2025-03-07 13:59:08,289] [INFO] [30127] Received COMMIT: id:1741323542381, from:30191, delay:0.0001s, distance:203.96m (Euclidean)
[2025-03-07 13:59:08,302] [INFO] [30127] Received COMMIT: id:1741323542381, from:30136, delay:0.0001s, distance:221.20m (Euclidean)
[2025-03-07 13:59:08,425] [INFO] [30127] Received PREPARE: id:1741323542381, from:30109, delay:0.0001s, distance:242.78m (Euclidean)
[2025-03-07 13:59:08,558] [INFO] [30127] Received COMMIT: id:1741323542381, from:30109, delay:0.0001s, distance:242.78m (Euclidean)
[2025-03-07 13:59:08,671] [INFO] [30127] Received PREPARE: id:1741323542381, from:30103, delay:0.0000s, distance:173.65m (Euclidean)
[2025-03-07 13:59:08,671] [INFO] [30127] Received COMMIT: id:1741323542381, from:30103, delay:0.0000s, distance:173.65m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30127] Received PREPARE: id:1741323542381, from:30195, delay:0.0000s, distance:139.44m (Euclidean)
[2025-03-07 13:59:08,721] [INFO] [30127] Received COMMIT: id:1741323542381, from:30195, delay:0.0000s, distance:139.44m (Euclidean)
[2025-03-07 13:59:09,130] [INFO] [30127] Received PREPARE: id:1741323542381, from:30158, delay:0.0001s, distance:239.87m (Euclidean)
[2025-03-07 13:59:09,130] [INFO] [30127] Received PREPARE: id:1741323542381, from:30070, delay:0.0000s, distance:106.38m (Euclidean)
[2025-03-07 13:59:09,130] [INFO] [30127] Received PREPARE: id:1741323542381, from:30024, delay:0.0001s, distance:163.59m (Euclidean)
[2025-03-07 13:59:09,130] [INFO] [30127] Received PREPARE: id:1741323542381, from:30005, delay:0.0001s, distance:212.50m (Euclidean)
[2025-03-07 13:59:09,140] [INFO] [30127] Received COMMIT: id:1741323542381, from:30024, delay:0.0001s, distance:163.59m (Euclidean)
[2025-03-07 13:59:09,142] [INFO] [30127] Received COMMIT: id:1741323542381, from:30070, delay:0.0000s, distance:106.38m (Euclidean)
[2025-03-07 13:59:09,142] [INFO] [30127] Received COMMIT: id:1741323542381, from:30005, delay:0.0001s, distance:212.50m (Euclidean)
[2025-03-07 13:59:09,278] [INFO] [30127] Received PREPARE: id:1741323542381, from:30090, delay:0.0001s, distance:210.28m (Euclidean)
[2025-03-07 13:59:09,280] [INFO] [30127] Received PREPARE: id:1741323542381, from:30027, delay:0.0000s, distance:129.19m (Euclidean)
[2025-03-07 13:59:09,280] [INFO] [30127] Received COMMIT: id:1741323542381, from:30027, delay:0.0000s, distance:129.19m (Euclidean)
[2025-03-07 13:59:09,280] [INFO] [30127] Received COMMIT: id:1741323542381, from:30090, delay:0.0001s, distance:210.28m (Euclidean)
[2025-03-07 13:59:09,298] [INFO] [30127] Received PREPARE: id:1741323542381, from:30118, delay:0.0000s, distance:87.31m (Euclidean)
[2025-03-07 13:59:09,298] [INFO] [30127] Received COMMIT: id:1741323542381, from:30118, delay:0.0000s, distance:87.31m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30127] Received PREPARE: id:1741323542381, from:30092, delay:0.0001s, distance:164.27m (Euclidean)
[2025-03-07 13:59:09,328] [INFO] [30127] Received COMMIT: id:1741323542381, from:30092, delay:0.0001s, distance:164.27m (Euclidean)
[2025-03-07 13:59:09,455] [INFO] [30127] Received PREPARE: id:1741323542381, from:30011, delay:0.0000s, distance:171.22m (Euclidean)
[2025-03-07 13:59:09,455] [INFO] [30127] Received COMMIT: id:1741323542381, from:30011, delay:0.0000s, distance:171.22m (Euclidean)
[2025-03-07 13:59:09,537] [INFO] [30127] Received COMMIT: id:1741323542381, from:30158, delay:0.0001s, distance:239.87m (Euclidean)
[2025-03-07 13:59:09,610] [INFO] [30127] Received PREPARE: id:1741323542381, from:30144, delay:0.0001s, distance:220.58m (Euclidean)
[2025-03-07 13:59:09,612] [INFO] [30127] Received COMMIT: id:1741323542381, from:30144, delay:0.0001s, distance:220.58m (Euclidean)
[2025-03-07 13:59:09,878] [INFO] [30127] Received PREPARE: id:1741323542381, from:30121, delay:0.0000s, distance:136.89m (Euclidean)
[2025-03-07 13:59:09,878] [INFO] [30127] Received COMMIT: id:1741323542381, from:30121, delay:0.0000s, distance:136.89m (Euclidean)
[2025-03-07 13:59:10,035] [INFO] [30127] Received PREPARE: id:1741323542381, from:30100, delay:0.0001s, distance:230.95m (Euclidean)
[2025-03-07 13:59:10,040] [INFO] [30127] Received COMMIT: id:1741323542381, from:30100, delay:0.0001s, distance:230.95m (Euclidean)
[2025-03-07 13:59:10,303] [INFO] [30127] Received PREPARE: id:1741323542381, from:30066, delay:0.0000s, distance:136.20m (Euclidean)
[2025-03-07 13:59:10,303] [INFO] [30127] Received COMMIT: id:1741323542381, from:30066, delay:0.0000s, distance:136.20m (Euclidean)
[2025-03-07 13:59:10,478] [INFO] [30127] Received PREPARE: id:1741323542381, from:30056, delay:0.0001s, distance:203.43m (Euclidean)
[2025-03-07 13:59:10,478] [INFO] [30127] Received COMMIT: id:1741323542381, from:30056, delay:0.0001s, distance:203.43m (Euclidean)
[2025-03-07 13:59:10,569] [INFO] [30127] Received PREPARE: id:1741323542381, from:30065, delay:0.0000s, distance:148.33m (Euclidean)
[2025-03-07 13:59:10,569] [INFO] [30127] Received COMMIT: id:1741323542381, from:30065, delay:0.0000s, distance:148.33m (Euclidean)
[2025-03-07 13:59:10,651] [INFO] [30127] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:107.46m (Euclidean)
[2025-03-07 13:59:10,652] [INFO] [30127] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:107.46m (Euclidean)
[2025-03-07 13:59:10,887] [INFO] [30127] Received PREPARE: id:1741323542381, from:30170, delay:0.0000s, distance:176.83m (Euclidean)
[2025-03-07 13:59:10,887] [INFO] [30127] Received COMMIT: id:1741323542381, from:30170, delay:0.0000s, distance:176.83m (Euclidean)
[2025-03-07 13:59:10,952] [INFO] [30127] Received PREPARE: id:1741323542381, from:30043, delay:0.0000s, distance:118.66m (Euclidean)
[2025-03-07 13:59:11,003] [INFO] [30127] Received COMMIT: id:1741323542381, from:30043, delay:0.0000s, distance:118.66m (Euclidean)
[2025-03-07 13:59:11,141] [INFO] [30127] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:74.02m (Euclidean)
[2025-03-07 13:59:11,143] [INFO] [30127] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:74.02m (Euclidean)
[2025-03-07 13:59:11,339] [INFO] [30127] Received PREPARE: id:1741323542381, from:30150, delay:0.0000s, distance:177.38m (Euclidean)
[2025-03-07 13:59:11,339] [INFO] [30127] Received COMMIT: id:1741323542381, from:30150, delay:0.0000s, distance:177.38m (Euclidean)
[2025-03-07 13:59:11,368] [INFO] [30127] Received PREPARE: id:1741323542381, from:30051, delay:0.0000s, distance:84.86m (Euclidean)
[2025-03-07 13:59:11,368] [INFO] [30127] Received COMMIT: id:1741323542381, from:30051, delay:0.0000s, distance:84.86m (Euclidean)
[2025-03-07 13:59:11,441] [INFO] [30127] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:67.19m (Euclidean)
[2025-03-07 13:59:11,441] [INFO] [30127] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:67.19m (Euclidean)
[2025-03-07 13:59:11,516] [INFO] [30127] Received PREPARE: id:1741323542381, from:30040, delay:0.0001s, distance:171.90m (Euclidean)
[2025-03-07 13:59:11,516] [INFO] [30127] Received COMMIT: id:1741323542381, from:30040, delay:0.0001s, distance:171.90m (Euclidean)
[2025-03-07 13:59:11,749] [INFO] [30127] Received PREPARE: id:1741323542381, from:30096, delay:0.0001s, distance:195.03m (Euclidean)
[2025-03-07 13:59:11,752] [INFO] [30127] Received COMMIT: id:1741323542381, from:30096, delay:0.0001s, distance:195.03m (Euclidean)
[2025-03-07 13:59:11,827] [INFO] [30127] Received PREPARE: id:1741323542381, from:30116, delay:0.0000s, distance:155.44m (Euclidean)
[2025-03-07 13:59:11,827] [INFO] [30127] Received COMMIT: id:1741323542381, from:30116, delay:0.0000s, distance:155.44m (Euclidean)
[2025-03-07 13:59:11,827] [INFO] [30127] Received PREPARE: id:1741323542381, from:30061, delay:0.0000s, distance:78.55m (Euclidean)
[2025-03-07 13:59:12,155] [INFO] [30127] Received PREPARE: id:1741323542381, from:30177, delay:0.0001s, distance:173.46m (Euclidean)
[2025-03-07 13:59:12,158] [INFO] [30127] Received COMMIT: id:1741323542381, from:30177, delay:0.0001s, distance:173.46m (Euclidean)
[2025-03-07 13:59:12,358] [INFO] [30127] Received PREPARE: id:1741323542381, from:30059, delay:0.0000s, distance:136.54m (Euclidean)
[2025-03-07 13:59:12,360] [INFO] [30127] Received COMMIT: id:1741323542381, from:30059, delay:0.0000s, distance:136.54m (Euclidean)
[2025-03-07 13:59:13,241] [INFO] [30127] Received COMMIT: id:1741323542381, from:30000, delay:0.0000s, distance:158.33m (Euclidean)
[2025-03-07 13:59:13,559] [INFO] [30127] Received PREPARE: id:1741323542381, from:30165, delay:0.0000s, distance:124.36m (Euclidean)
[2025-03-07 13:59:13,559] [INFO] [30127] Received COMMIT: id:1741323542381, from:30165, delay:0.0000s, distance:124.36m (Euclidean)
[2025-03-07 13:59:13,844] [INFO] [30127] Received PREPARE: id:1741323542381, from:30198, delay:0.0000s, distance:137.72m (Euclidean)
[2025-03-07 13:59:13,903] [INFO] [30127] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:149.22m (Euclidean)
[2025-03-07 13:59:13,903] [INFO] [30127] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:149.22m (Euclidean)
[2025-03-07 13:59:14,159] [INFO] [30127] Received PREPARE: id:1741323542381, from:30010, delay:0.0001s, distance:189.88m (Euclidean)
[2025-03-07 13:59:14,159] [INFO] [30127] Received COMMIT: id:1741323542381, from:30010, delay:0.0001s, distance:189.88m (Euclidean)
[2025-03-07 13:59:14,254] [INFO] [30127] Received PREPARE: id:1741323542381, from:30016, delay:0.0000s, distance:55.98m (Euclidean)
[2025-03-07 13:59:14,254] [INFO] [30127] Received COMMIT: id:1741323542381, from:30016, delay:0.0000s, distance:55.98m (Euclidean)
[2025-03-07 13:59:14,254] [INFO] [30127] Received PREPARE: id:1741323542381, from:30132, delay:0.0000s, distance:108.09m (Euclidean)
[2025-03-07 13:59:14,326] [INFO] [30127] Received COMMIT: id:1741323542381, from:30061, delay:0.0000s, distance:78.55m (Euclidean)
[2025-03-07 13:59:14,375] [INFO] [30127] Received COMMIT: id:1741323542381, from:30198, delay:0.0000s, distance:137.72m (Euclidean)
[2025-03-07 13:59:14,514] [INFO] [30127] Received PREPARE: id:1741323542381, from:30137, delay:0.0000s, distance:140.93m (Euclidean)
[2025-03-07 13:59:14,514] [INFO] [30127] Received COMMIT: id:1741323542381, from:30137, delay:0.0000s, distance:140.93m (Euclidean)
[2025-03-07 13:59:14,642] [INFO] [30127] Received PREPARE: id:1741323542381, from:30052, delay:0.0000s, distance:142.95m (Euclidean)
[2025-03-07 13:59:14,944] [INFO] [30127] Received PREPARE: id:1741323542381, from:30001, delay:0.0000s, distance:117.37m (Euclidean)
[2025-03-07 13:59:15,483] [INFO] [30127] Received COMMIT: id:1741323542381, from:30052, delay:0.0000s, distance:142.95m (Euclidean)
[2025-03-07 13:59:15,483] [INFO] [30127] Received PREPARE: id:1741323542381, from:30114, delay:0.0000s, distance:128.98m (Euclidean)
[2025-03-07 13:59:15,513] [INFO] [30127] Received PREPARE: id:1741323542381, from:30036, delay:0.0001s, distance:164.17m (Euclidean)
[2025-03-07 13:59:15,515] [INFO] [30127] Received COMMIT: id:1741323542381, from:30036, delay:0.0001s, distance:164.17m (Euclidean)
[2025-03-07 13:59:15,515] [INFO] [30127] Received PREPARE: id:1741323542381, from:30087, delay:0.0001s, distance:159.32m (Euclidean)
[2025-03-07 13:59:15,517] [INFO] [30127] Received COMMIT: id:1741323542381, from:30087, delay:0.0001s, distance:159.32m (Euclidean)
[2025-03-07 13:59:15,691] [INFO] [30127] Received PREPARE: id:1741323542381, from:30117, delay:0.0001s, distance:242.54m (Euclidean)
[2025-03-07 13:59:15,774] [INFO] [30127] Received PREPARE: id:1741323542381, from:30088, delay:0.0001s, distance:209.29m (Euclidean)
[2025-03-07 13:59:15,783] [INFO] [30127] Received COMMIT: id:1741323542381, from:30088, delay:0.0001s, distance:209.29m (Euclidean)
[2025-03-07 13:59:15,828] [INFO] [30127] Received COMMIT: id:1741323542381, from:30117, delay:0.0001s, distance:242.54m (Euclidean)
[2025-03-07 13:59:15,917] [INFO] [30127] Received PREPARE: id:1741323542381, from:30042, delay:0.0000s, distance:131.89m (Euclidean)
[2025-03-07 13:59:16,128] [INFO] [30127] Received PREPARE: id:1741323542381, from:30141, delay:0.0001s, distance:192.84m (Euclidean)
[2025-03-07 13:59:16,128] [INFO] [30127] Received COMMIT: id:1741323542381, from:30141, delay:0.0001s, distance:192.84m (Euclidean)
[2025-03-07 13:59:16,137] [INFO] [30127] Received COMMIT: id:1741323542381, from:30132, delay:0.0000s, distance:108.09m (Euclidean)
[2025-03-07 13:59:16,283] [INFO] [30127] Received PREPARE: id:1741323542381, from:30079, delay:0.0000s, distance:149.35m (Euclidean)
[2025-03-07 13:59:16,290] [INFO] [30127] Received COMMIT: id:1741323542381, from:30079, delay:0.0000s, distance:149.35m (Euclidean)
[2025-03-07 13:59:16,461] [INFO] [30127] Received PREPARE: id:1741323542381, from:30145, delay:0.0001s, distance:216.34m (Euclidean)
[2025-03-07 13:59:16,461] [INFO] [30127] Received COMMIT: id:1741323542381, from:30145, delay:0.0001s, distance:216.34m (Euclidean)
[2025-03-07 13:59:16,512] [INFO] [30127] Received COMMIT: id:1741323542381, from:30001, delay:0.0000s, distance:117.37m (Euclidean)
[2025-03-07 13:59:16,642] [INFO] [30127] Received PREPARE: id:1741323542381, from:30069, delay:0.0002s, distance:282.38m (Euclidean)
[2025-03-07 13:59:16,647] [INFO] [30127] Received COMMIT: id:1741323542381, from:30069, delay:0.0002s, distance:282.38m (Euclidean)
[2025-03-07 13:59:16,703] [INFO] [30127] Received PREPARE: id:1741323542381, from:30038, delay:0.0000s, distance:58.72m (Euclidean)
[2025-03-07 13:59:16,934] [INFO] [30127] Received COMMIT: id:1741323542381, from:30114, delay:0.0000s, distance:128.98m (Euclidean)
[2025-03-07 13:59:16,934] [INFO] [30127] Received PREPARE: id:1741323542381, from:30187, delay:0.0000s, distance:145.66m (Euclidean)
[2025-03-07 13:59:16,934] [INFO] [30127] Received COMMIT: id:1741323542381, from:30038, delay:0.0000s, distance:58.72m (Euclidean)
[2025-03-07 13:59:16,934] [INFO] [30127] Received COMMIT: id:1741323542381, from:30187, delay:0.0000s, distance:145.66m (Euclidean)
[2025-03-07 13:59:17,017] [INFO] [30127] Received PREPARE: id:1741323542381, from:30081, delay:0.0000s, distance:145.72m (Euclidean)
[2025-03-07 13:59:17,033] [INFO] [30127] Received PREPARE: id:1741323542381, from:30026, delay:0.0002s, distance:261.02m (Euclidean)
[2025-03-07 13:59:17,033] [INFO] [30127] Received COMMIT: id:1741323542381, from:30026, delay:0.0002s, distance:261.02m (Euclidean)
[2025-03-07 13:59:17,062] [INFO] [30127] Received PREPARE: id:1741323542381, from:30071, delay:0.0002s, distance:292.98m (Euclidean)
[2025-03-07 13:59:17,064] [INFO] [30127] Received COMMIT: id:1741323542381, from:30071, delay:0.0002s, distance:292.98m (Euclidean)
[2025-03-07 13:59:17,148] [INFO] [30127] Received PREPARE: id:1741323542381, from:30055, delay:0.0001s, distance:179.20m (Euclidean)
[2025-03-07 13:59:17,237] [INFO] [30127] Received PREPARE: id:1741323542381, from:30194, delay:0.0001s, distance:203.49m (Euclidean)
[2025-03-07 13:59:17,237] [INFO] [30127] Received COMMIT: id:1741323542381, from:30194, delay:0.0001s, distance:203.49m (Euclidean)
[2025-03-07 13:59:17,259] [INFO] [30127] Received COMMIT: id:1741323542381, from:30042, delay:0.0000s, distance:131.89m (Euclidean)
[2025-03-07 13:59:17,708] [INFO] [30127] Received PREPARE: id:1741323542381, from:30156, delay:0.0000s, distance:133.74m (Euclidean)
[2025-03-07 13:59:17,710] [INFO] [30127] Received COMMIT: id:1741323542381, from:30156, delay:0.0000s, distance:133.74m (Euclidean)
[2025-03-07 13:59:18,065] [INFO] [30127] Received PREPARE: id:1741323542381, from:30031, delay:0.0001s, distance:209.07m (Euclidean)
[2025-03-07 13:59:18,067] [INFO] [30127] Received COMMIT: id:1741323542381, from:30031, delay:0.0001s, distance:209.07m (Euclidean)
[2025-03-07 13:59:18,462] [INFO] [30127] Received PREPARE: id:1741323542381, from:30067, delay:0.0002s, distance:271.25m (Euclidean)
[2025-03-07 13:59:18,463] [INFO] [30127] Received COMMIT: id:1741323542381, from:30067, delay:0.0002s, distance:271.25m (Euclidean)
[2025-03-07 13:59:18,751] [INFO] [30127] Received PREPARE: id:1741323542381, from:30058, delay:0.0001s, distance:227.31m (Euclidean)
[2025-03-07 13:59:18,751] [INFO] [30127] Received COMMIT: id:1741323542381, from:30058, delay:0.0001s, distance:227.31m (Euclidean)
[2025-03-07 13:59:18,921] [INFO] [30127] Received PREPARE: id:1741323542381, from:30193, delay:0.0001s, distance:234.03m (Euclidean)
[2025-03-07 13:59:18,976] [INFO] [30127] Received COMMIT: id:1741323542381, from:30081, delay:0.0000s, distance:145.72m (Euclidean)
[2025-03-07 13:59:19,194] [INFO] [30127] Received PREPARE: id:1741323542381, from:30073, delay:0.0001s, distance:212.20m (Euclidean)
[2025-03-07 13:59:19,194] [INFO] [30127] Received COMMIT: id:1741323542381, from:30073, delay:0.0001s, distance:212.20m (Euclidean)
[2025-03-07 13:59:19,196] [INFO] [30127] Received PREPARE: id:1741323542381, from:30033, delay:0.0002s, distance:265.19m (Euclidean)
[2025-03-07 13:59:19,198] [INFO] [30127] Received COMMIT: id:1741323542381, from:30033, delay:0.0002s, distance:265.19m (Euclidean)
[2025-03-07 13:59:19,295] [INFO] [30127] Received PREPARE: id:1741323542381, from:30153, delay:0.0002s, distance:252.78m (Euclidean)
[2025-03-07 13:59:19,295] [INFO] [30127] Received COMMIT: id:1741323542381, from:30153, delay:0.0002s, distance:252.78m (Euclidean)
[2025-03-07 13:59:19,633] [INFO] [30127] Received PREPARE: id:1741323542381, from:30159, delay:0.0001s, distance:207.56m (Euclidean)
[2025-03-07 13:59:19,647] [INFO] [30127] Received PREPARE: id:1741323542381, from:30083, delay:0.0000s, distance:135.64m (Euclidean)
[2025-03-07 13:59:19,893] [INFO] [30127] Received COMMIT: id:1741323542381, from:30193, delay:0.0001s, distance:234.03m (Euclidean)
[2025-03-07 13:59:20,129] [INFO] [30127] Received PREPARE: id:1741323542381, from:30006, delay:0.0001s, distance:234.48m (Euclidean)
[2025-03-07 13:59:20,131] [INFO] [30127] Received COMMIT: id:1741323542381, from:30006, delay:0.0001s, distance:234.48m (Euclidean)
[2025-03-07 13:59:20,131] [INFO] [30127] Received COMMIT: id:1741323542381, from:30135, delay:0.0002s, distance:281.54m (Euclidean)
[2025-03-07 13:59:20,131] [INFO] [30127] Received PREPARE: id:1741323542381, from:30135, delay:0.0002s, distance:281.54m (Euclidean)
[2025-03-07 13:59:20,219] [INFO] [30127] Received PREPARE: id:1741323542381, from:30134, delay:0.0002s, distance:261.07m (Euclidean)
[2025-03-07 13:59:20,219] [INFO] [30127] Received COMMIT: id:1741323542381, from:30134, delay:0.0002s, distance:261.07m (Euclidean)
[2025-03-07 13:59:20,228] [INFO] [30127] Received PREPARE: id:1741323542381, from:30138, delay:0.0000s, distance:130.85m (Euclidean)
[2025-03-07 13:59:20,228] [INFO] [30127] Received COMMIT: id:1741323542381, from:30138, delay:0.0000s, distance:130.85m (Euclidean)
[2025-03-07 13:59:20,530] [INFO] [30127] Received PREPARE: id:1741323542381, from:30008, delay:0.0000s, distance:126.92m (Euclidean)
[2025-03-07 13:59:20,532] [INFO] [30127] Received COMMIT: id:1741323542381, from:30008, delay:0.0000s, distance:126.92m (Euclidean)
[2025-03-07 13:59:20,611] [INFO] [30127] Received PREPARE: id:1741323542381, from:30019, delay:0.0002s, distance:292.82m (Euclidean)
[2025-03-07 13:59:20,616] [INFO] [30127] Received COMMIT: id:1741323542381, from:30019, delay:0.0002s, distance:292.82m (Euclidean)
[2025-03-07 13:59:20,782] [INFO] [30127] Received PREPARE: id:1741323542381, from:30039, delay:0.0001s, distance:169.34m (Euclidean)
[2025-03-07 13:59:20,803] [INFO] [30127] Received PREPARE: id:1741323542381, from:30009, delay:0.0000s, distance:141.70m (Euclidean)
[2025-03-07 13:59:20,865] [INFO] [30127] Received PREPARE: id:1741323542381, from:30143, delay:0.0000s, distance:102.42m (Euclidean)
[2025-03-07 13:59:20,865] [INFO] [30127] Received COMMIT: id:1741323542381, from:30143, delay:0.0000s, distance:102.42m (Euclidean)
[2025-03-07 13:59:20,873] [INFO] [30127] Received COMMIT: id:1741323542381, from:30083, delay:0.0000s, distance:135.64m (Euclidean)
[2025-03-07 13:59:20,923] [INFO] [30127] Received PREPARE: id:1741323542381, from:30140, delay:0.0002s, distance:265.76m (Euclidean)
[2025-03-07 13:59:20,925] [INFO] [30127] Received COMMIT: id:1741323542381, from:30140, delay:0.0002s, distance:265.76m (Euclidean)
[2025-03-07 13:59:20,970] [INFO] [30127] Received PREPARE: id:1741323542381, from:30188, delay:0.0001s, distance:227.65m (Euclidean)
[2025-03-07 13:59:20,972] [INFO] [30127] Received COMMIT: id:1741323542381, from:30188, delay:0.0001s, distance:227.65m (Euclidean)
[2025-03-07 13:59:21,041] [INFO] [30127] Received COMMIT: id:1741323542381, from:30159, delay:0.0001s, distance:207.56m (Euclidean)
[2025-03-07 13:59:21,221] [INFO] [30127] Received PREPARE: id:1741323542381, from:30101, delay:0.0001s, distance:160.43m (Euclidean)
[2025-03-07 13:59:21,221] [INFO] [30127] Received COMMIT: id:1741323542381, from:30101, delay:0.0001s, distance:160.43m (Euclidean)
[2025-03-07 13:59:21,432] [INFO] [30127] Received COMMIT: id:1741323542381, from:30055, delay:0.0001s, distance:179.20m (Euclidean)
[2025-03-07 13:59:21,432] [INFO] [30127] Received PREPARE: id:1741323542381, from:30122, delay:0.0000s, distance:135.78m (Euclidean)
[2025-03-07 13:59:21,432] [INFO] [30127] Received COMMIT: id:1741323542381, from:30122, delay:0.0000s, distance:135.78m (Euclidean)
[2025-03-07 13:59:21,687] [INFO] [30127] Received PREPARE: id:1741323542381, from:30084, delay:0.0001s, distance:247.77m (Euclidean)
[2025-03-07 13:59:21,687] [INFO] [30127] Received COMMIT: id:1741323542381, from:30084, delay:0.0001s, distance:247.77m (Euclidean)
[2025-03-07 13:59:21,687] [INFO] [30127] Received COMMIT: id:1741323542381, from:30173, delay:0.0001s, distance:185.28m (Euclidean)
[2025-03-07 13:59:21,689] [INFO] [30127] Received PREPARE: id:1741323542381, from:30173, delay:0.0001s, distance:185.28m (Euclidean)
[2025-03-07 13:59:21,800] [INFO] [30127] Received PREPARE: id:1741323542381, from:30014, delay:0.0001s, distance:172.93m (Euclidean)
[2025-03-07 13:59:21,800] [INFO] [30127] Received COMMIT: id:1741323542381, from:30014, delay:0.0001s, distance:172.93m (Euclidean)
[2025-03-07 13:59:22,108] [INFO] [30127] Received PREPARE: id:1741323542381, from:30091, delay:0.0001s, distance:203.67m (Euclidean)
[2025-03-07 13:59:22,110] [INFO] [30127] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:121.51m (Euclidean)
[2025-03-07 13:59:22,110] [INFO] [30127] Received COMMIT: id:1741323542381, from:30091, delay:0.0001s, distance:203.67m (Euclidean)
[2025-03-07 13:59:22,110] [INFO] [30127] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:121.51m (Euclidean)
[2025-03-07 13:59:22,218] [INFO] [30127] Received PREPARE: id:1741323542381, from:30105, delay:0.0000s, distance:58.86m (Euclidean)
[2025-03-07 13:59:22,218] [INFO] [30127] Received COMMIT: id:1741323542381, from:30105, delay:0.0000s, distance:58.86m (Euclidean)
[2025-03-07 13:59:22,284] [INFO] [30127] Received PREPARE: id:1741323542381, from:30160, delay:0.0001s, distance:202.84m (Euclidean)
[2025-03-07 13:59:22,286] [INFO] [30127] Received COMMIT: id:1741323542381, from:30160, delay:0.0001s, distance:202.84m (Euclidean)
[2025-03-07 13:59:22,667] [INFO] [30127] Received PREPARE: id:1741323542381, from:30166, delay:0.0001s, distance:197.13m (Euclidean)
[2025-03-07 13:59:22,674] [INFO] [30127] Received COMMIT: id:1741323542381, from:30166, delay:0.0001s, distance:197.13m (Euclidean)
[2025-03-07 13:59:22,697] [INFO] [30127] Received PREPARE: id:1741323542381, from:30064, delay:0.0001s, distance:221.30m (Euclidean)
[2025-03-07 13:59:22,709] [INFO] [30127] Received COMMIT: id:1741323542381, from:30064, delay:0.0001s, distance:221.30m (Euclidean)
[2025-03-07 13:59:22,889] [INFO] [30127] Received PREPARE: id:1741323542381, from:30162, delay:0.0001s, distance:239.73m (Euclidean)
[2025-03-07 13:59:22,889] [INFO] [30127] Received COMMIT: id:1741323542381, from:30162, delay:0.0001s, distance:239.73m (Euclidean)
[2025-03-07 13:59:23,128] [INFO] [30127] Received PREPARE: id:1741323542381, from:30050, delay:0.0002s, distance:273.86m (Euclidean)
[2025-03-07 13:59:23,128] [INFO] [30127] Received COMMIT: id:1741323542381, from:30050, delay:0.0002s, distance:273.86m (Euclidean)
[2025-03-07 13:59:23,173] [INFO] [30127] Received PREPARE: id:1741323542381, from:30131, delay:0.0001s, distance:186.71m (Euclidean)
[2025-03-07 13:59:23,175] [INFO] [30127] Received COMMIT: id:1741323542381, from:30131, delay:0.0001s, distance:186.71m (Euclidean)
[2025-03-07 13:59:23,505] [INFO] [30127] Received PREPARE: id:1741323542381, from:30151, delay:0.0000s, distance:156.78m (Euclidean)
[2025-03-07 13:59:23,505] [INFO] [30127] Received COMMIT: id:1741323542381, from:30039, delay:0.0001s, distance:169.34m (Euclidean)
[2025-03-07 13:59:23,505] [INFO] [30127] Received COMMIT: id:1741323542381, from:30151, delay:0.0000s, distance:156.78m (Euclidean)
[2025-03-07 13:59:23,583] [INFO] [30127] Received PREPARE: id:1741323542381, from:30139, delay:0.0001s, distance:160.02m (Euclidean)
[2025-03-07 13:59:23,583] [INFO] [30127] Received COMMIT: id:1741323542381, from:30139, delay:0.0001s, distance:160.02m (Euclidean)
[2025-03-07 13:59:23,972] [INFO] [30127] Received PREPARE: id:1741323542381, from:30094, delay:0.0000s, distance:139.77m (Euclidean)
[2025-03-07 13:59:23,972] [INFO] [30127] Received COMMIT: id:1741323542381, from:30094, delay:0.0000s, distance:139.77m (Euclidean)
[2025-03-07 13:59:25,111] [INFO] [30127] Received PREPARE: id:1741323542381, from:30082, delay:0.0000s, distance:75.01m (Euclidean)
[2025-03-07 13:59:25,244] [INFO] [30127] Received PREPARE: id:1741323542381, from:30142, delay:0.0000s, distance:114.62m (Euclidean)
[2025-03-07 13:59:25,246] [INFO] [30127] Received COMMIT: id:1741323542381, from:30142, delay:0.0000s, distance:114.62m (Euclidean)
[2025-03-07 13:59:25,335] [INFO] [30127] Received COMMIT: id:1741323542381, from:30009, delay:0.0000s, distance:141.70m (Euclidean)
[2025-03-07 13:59:25,578] [INFO] [30127] Received PREPARE: id:1741323542381, from:30022, delay:0.0002s, distance:252.67m (Euclidean)
[2025-03-07 13:59:25,587] [INFO] [30127] Received COMMIT: id:1741323542381, from:30022, delay:0.0002s, distance:252.67m (Euclidean)
[2025-03-07 13:59:25,662] [INFO] [30127] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:233.32m (Euclidean)
[2025-03-07 13:59:25,731] [INFO] [30127] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:233.32m (Euclidean)
[2025-03-07 13:59:26,036] [INFO] [30127] Received PREPARE: id:1741323542381, from:30068, delay:0.0002s, distance:263.84m (Euclidean)
[2025-03-07 13:59:26,060] [INFO] [30127] Received COMMIT: id:1741323542381, from:30068, delay:0.0002s, distance:263.84m (Euclidean)
[2025-03-07 13:59:26,238] [INFO] [30127] Received PREPARE: id:1741323542381, from:30185, delay:0.0000s, distance:110.67m (Euclidean)
[2025-03-07 13:59:26,319] [INFO] [30127] Received PREPARE: id:1741323542381, from:30045, delay:0.0001s, distance:243.05m (Euclidean)
[2025-03-07 13:59:26,319] [INFO] [30127] Received COMMIT: id:1741323542381, from:30045, delay:0.0001s, distance:243.05m (Euclidean)
[2025-03-07 13:59:26,328] [INFO] [30127] Received PREPARE: id:1741323542381, from:30017, delay:0.0002s, distance:253.93m (Euclidean)
[2025-03-07 13:59:26,328] [INFO] [30127] Received COMMIT: id:1741323542381, from:30017, delay:0.0002s, distance:253.93m (Euclidean)
[2025-03-07 13:59:26,427] [INFO] [30127] Received COMMIT: id:1741323542381, from:30185, delay:0.0000s, distance:110.67m (Euclidean)
[2025-03-07 13:59:26,434] [INFO] [30127] Received PREPARE: id:1741323542381, from:30018, delay:0.0000s, distance:128.42m (Euclidean)
[2025-03-07 13:59:26,580] [INFO] [30127] Received PREPARE: id:1741323542381, from:30152, delay:0.0002s, distance:254.28m (Euclidean)
[2025-03-07 13:59:26,580] [INFO] [30127] Received COMMIT: id:1741323542381, from:30152, delay:0.0002s, distance:254.28m (Euclidean)
[2025-03-07 13:59:27,027] [INFO] [30127] Received PREPARE: id:1741323542381, from:30104, delay:0.0000s, distance:89.89m (Euclidean)
[2025-03-07 13:59:27,050] [INFO] [30127] Received COMMIT: id:1741323542381, from:30104, delay:0.0000s, distance:89.89m (Euclidean)
[2025-03-07 13:59:27,707] [INFO] [30127] Received PREPARE: id:1741323542381, from:30075, delay:0.0001s, distance:170.84m (Euclidean)
[2025-03-07 13:59:27,707] [INFO] [30127] Received COMMIT: id:1741323542381, from:30075, delay:0.0001s, distance:170.84m (Euclidean)
[2025-03-07 13:59:27,737] [INFO] [30127] Received COMMIT: id:1741323542381, from:30018, delay:0.0000s, distance:128.42m (Euclidean)
[2025-03-07 13:59:27,977] [INFO] [30127] Received PREPARE: id:1741323542381, from:30047, delay:0.0001s, distance:172.10m (Euclidean)
[2025-03-07 13:59:27,977] [INFO] [30127] Received COMMIT: id:1741323542381, from:30047, delay:0.0001s, distance:172.10m (Euclidean)
[2025-03-07 13:59:28,158] [INFO] [30127] Received PREPARE: id:1741323542381, from:30163, delay:0.0001s, distance:166.84m (Euclidean)
[2025-03-07 13:59:28,195] [INFO] [30127] Received COMMIT: id:1741323542381, from:30163, delay:0.0001s, distance:166.84m (Euclidean)
[2025-03-07 13:59:28,332] [INFO] [30127] Received PREPARE: id:1741323542381, from:30012, delay:0.0001s, distance:238.53m (Euclidean)
[2025-03-07 13:59:28,338] [INFO] [30127] Received COMMIT: id:1741323542381, from:30012, delay:0.0001s, distance:238.53m (Euclidean)
[2025-03-07 13:59:28,713] [INFO] [30127] Received PREPARE: id:1741323542381, from:30164, delay:0.0001s, distance:239.92m (Euclidean)
[2025-03-07 13:59:28,717] [INFO] [30127] Received COMMIT: id:1741323542381, from:30164, delay:0.0001s, distance:239.92m (Euclidean)
[2025-03-07 13:59:28,730] [INFO] [30127] Received PREPARE: id:1741323542381, from:30192, delay:0.0001s, distance:238.76m (Euclidean)
[2025-03-07 13:59:28,767] [INFO] [30127] Received COMMIT: id:1741323542381, from:30192, delay:0.0001s, distance:238.76m (Euclidean)
[2025-03-07 13:59:28,830] [INFO] [30127] Received COMMIT: id:1741323542381, from:30082, delay:0.0000s, distance:75.01m (Euclidean)
[2025-03-07 13:59:33,200] [INFO] [30127] Received PREPARE: id:1741323542381, from:30072, delay:0.0002s, distance:271.54m (Euclidean)
[2025-03-07 13:59:37,382] [INFO] [30127] Received PREPARE: id:1741323542381, from:30078, delay:0.0001s, distance:227.99m (Euclidean)
[2025-03-07 13:59:38,119] [INFO] [30127] Received PREPARE: id:1741323542381, from:30002, delay:0.0000s, distance:144.15m (Euclidean)
[2025-03-07 13:59:38,172] [INFO] [30127] Received COMMIT: id:1741323542381, from:30002, delay:0.0000s, distance:144.15m (Euclidean)
[2025-03-07 13:59:38,261] [INFO] [30127] Received PREPARE: id:1741323542381, from:30030, delay:0.0002s, distance:255.11m (Euclidean)
[2025-03-07 13:59:38,287] [INFO] [30127] Received PREPARE: id:1741323542381, from:30044, delay:0.0001s, distance:178.30m (Euclidean)
[2025-03-07 13:59:38,326] [INFO] [30127] Received COMMIT: id:1741323542381, from:30044, delay:0.0001s, distance:178.30m (Euclidean)
[2025-03-07 13:59:38,355] [INFO] [30127] Received PREPARE: id:1741323542381, from:30097, delay:0.0001s, distance:202.23m (Euclidean)
[2025-03-07 13:59:38,371] [INFO] [30127] Received COMMIT: id:1741323542381, from:30030, delay:0.0002s, distance:255.11m (Euclidean)
[2025-03-07 13:59:38,502] [INFO] [30127] Received COMMIT: id:1741323542381, from:30097, delay:0.0001s, distance:202.23m (Euclidean)
[2025-03-07 13:59:38,526] [INFO] [30127] Received PREPARE: id:1741323542381, from:30183, delay:0.0001s, distance:235.03m (Euclidean)
[2025-03-07 13:59:38,526] [INFO] [30127] Received COMMIT: id:1741323542381, from:30183, delay:0.0001s, distance:235.03m (Euclidean)
[2025-03-07 13:59:38,793] [INFO] [30127] Received COMMIT: id:1741323542381, from:30172, delay:0.0001s, distance:207.80m (Euclidean)
