[2025-03-07 13:50:45,727] [INFO] Starting node at localhost:30101 | index=102 | f=1, k=4 | Role: Replica
[2025-03-07 13:51:29,423] [INFO] Starting node at localhost:30101 | index=102 | f=1, k=4 | Role: Replica
[2025-03-07 13:51:35,459] [INFO] [30101] Received PRE-PREPARE: id:1741323095323, from:Leader(30000), delay:0.0000s, distance:151.15m (Euclidean)
[2025-03-07 13:51:35,459] [INFO] [30101] Broadcasting PREPARE for REQUEST 1741323095323
[2025-03-07 13:51:35,807] [INFO] [30101] Received PREPARE: id:1741323095323, from:30076, delay:0.0000s, distance:249.52m (Euclidean)
[2025-03-07 13:51:35,807] [INFO] [30101] Received PREPARE: id:1741323095323, from:30113, delay:0.0000s, distance:139.27m (Euclidean)
[2025-03-07 13:51:35,807] [INFO] [30101] Broadcasting COMMIT for REQUEST 1741323095323
[2025-03-07 13:51:35,980] [INFO] [30101] Received PREPARE: id:1741323095323, from:30028, delay:0.0000s, distance:249.07m (Euclidean)
[2025-03-07 13:51:35,982] [INFO] [30101] Received PREPARE: id:1741323095323, from:30053, delay:0.0000s, distance:37.28m (Euclidean)
[2025-03-07 13:51:36,155] [INFO] [30101] Received PREPARE: id:1741323095323, from:30108, delay:0.0001s, distance:158.71m (Euclidean)
[2025-03-07 13:51:36,173] [INFO] [30101] Received PREPARE: id:1741323095323, from:30119, delay:0.0000s, distance:165.56m (Euclidean)
[2025-03-07 13:51:36,247] [INFO] [30101] Received PREPARE: id:1741323095323, from:30032, delay:0.0001s, distance:161.53m (Euclidean)
[2025-03-07 13:51:36,292] [INFO] [30101] Received COMMIT: id:1741323095323, from:30032, delay:0.0001s, distance:161.53m (Euclidean)
[2025-03-07 13:51:36,304] [INFO] [30101] Received PREPARE: id:1741323095323, from:30103, delay:0.0000s, distance:136.32m (Euclidean)
[2025-03-07 13:51:36,463] [INFO] [30101] Received COMMIT: id:1741323095323, from:30095, delay:0.0000s, distance:136.38m (Euclidean)
[2025-03-07 13:51:36,463] [INFO] [LEADER 30101] Sending REPLY for REQUEST 1741323095323 to CLIENT
[2025-03-07 13:51:36,463] [INFO] [30101] Received PREPARE: id:1741323095323, from:30095, delay:0.0000s, distance:136.38m (Euclidean)
[2025-03-07 13:51:36,477] [INFO] [30101] Received COMMIT: id:1741323095323, from:30119, delay:0.0000s, distance:165.56m (Euclidean)
[2025-03-07 13:51:36,477] [INFO] [30101] Received PREPARE: id:1741323095323, from:30001, delay:0.0001s, distance:161.17m (Euclidean)
[2025-03-07 13:51:36,555] [INFO] [30101] Received PREPARE: id:1741323095323, from:30007, delay:0.0000s, distance:84.62m (Euclidean)
[2025-03-07 13:51:36,587] [INFO] [30101] Received COMMIT: id:1741323095323, from:30108, delay:0.0001s, distance:158.71m (Euclidean)
[2025-03-07 13:51:36,636] [INFO] [30101] Received COMMIT: id:1741323095323, from:30053, delay:0.0000s, distance:37.28m (Euclidean)
[2025-03-07 13:51:36,638] [INFO] [30101] Received PREPARE: id:1741323095323, from:30102, delay:0.0002s, distance:258.15m (Euclidean)
[2025-03-07 13:51:36,638] [INFO] [30101] Received COMMIT: id:1741323095323, from:30102, delay:0.0002s, distance:258.15m (Euclidean)
[2025-03-07 13:51:36,673] [INFO] [30101] Received PREPARE: id:1741323095323, from:30015, delay:0.0000s, distance:124.57m (Euclidean)
[2025-03-07 13:51:36,713] [INFO] [30101] Received PREPARE: id:1741323095323, from:30003, delay:0.0001s, distance:173.91m (Euclidean)
[2025-03-07 13:51:36,729] [INFO] [30101] Received PREPARE: id:1741323095323, from:30044, delay:0.0000s, distance:107.51m (Euclidean)
[2025-03-07 13:51:36,777] [INFO] [30101] Received COMMIT: id:1741323095323, from:30007, delay:0.0000s, distance:84.62m (Euclidean)
[2025-03-07 13:51:36,824] [INFO] [30101] Received COMMIT: id:1741323095323, from:30001, delay:0.0001s, distance:161.17m (Euclidean)
[2025-03-07 13:51:36,826] [INFO] [30101] Received PREPARE: id:1741323095323, from:30114, delay:0.0002s, distance:258.44m (Euclidean)
[2025-03-07 13:51:36,856] [INFO] [30101] Received COMMIT: id:1741323095323, from:30114, delay:0.0002s, distance:258.44m (Euclidean)
[2025-03-07 13:51:36,856] [INFO] [30101] Received COMMIT: id:1741323095323, from:30044, delay:0.0000s, distance:107.51m (Euclidean)
[2025-03-07 13:51:36,903] [INFO] [30101] Received PREPARE: id:1741323095323, from:30008, delay:0.0001s, distance:181.38m (Euclidean)
[2025-03-07 13:51:36,907] [INFO] [30101] Received COMMIT: id:1741323095323, from:30103, delay:0.0000s, distance:136.32m (Euclidean)
[2025-03-07 13:51:36,907] [INFO] [30101] Received PREPARE: id:1741323095323, from:30024, delay:0.0000s, distance:104.52m (Euclidean)
[2025-03-07 13:51:36,922] [INFO] [30101] Received PREPARE: id:1741323095323, from:30065, delay:0.0000s, distance:57.75m (Euclidean)
[2025-03-07 13:51:36,937] [INFO] [30101] Received COMMIT: id:1741323095323, from:30065, delay:0.0000s, distance:57.75m (Euclidean)
[2025-03-07 13:51:36,937] [INFO] [30101] Received COMMIT: id:1741323095323, from:30113, delay:0.0000s, distance:139.27m (Euclidean)
[2025-03-07 13:51:36,937] [INFO] [30101] Received PREPARE: id:1741323095323, from:30005, delay:0.0001s, distance:244.67m (Euclidean)
[2025-03-07 13:51:36,937] [INFO] [30101] Received PREPARE: id:1741323095323, from:30043, delay:0.0000s, distance:144.40m (Euclidean)
[2025-03-07 13:51:36,937] [INFO] [30101] Received COMMIT: id:1741323095323, from:30043, delay:0.0000s, distance:144.40m (Euclidean)
[2025-03-07 13:51:36,959] [INFO] [30101] Received PREPARE: id:1741323095323, from:30023, delay:0.0000s, distance:80.22m (Euclidean)
[2025-03-07 13:51:36,966] [INFO] [30101] Received COMMIT: id:1741323095323, from:30008, delay:0.0001s, distance:181.38m (Euclidean)
[2025-03-07 13:51:36,969] [INFO] [30101] Received PREPARE: id:1741323095323, from:30036, delay:0.0000s, distance:82.87m (Euclidean)
[2025-03-07 13:51:36,969] [INFO] [30101] Received COMMIT: id:1741323095323, from:30028, delay:0.0000s, distance:249.07m (Euclidean)
[2025-03-07 13:51:37,004] [INFO] [30101] Received PREPARE: id:1741323095323, from:30002, delay:0.0000s, distance:137.65m (Euclidean)
[2025-03-07 13:51:37,046] [INFO] [30101] Received PREPARE: id:1741323095323, from:30094, delay:0.0000s, distance:148.56m (Euclidean)
[2025-03-07 13:51:37,046] [INFO] [30101] Received COMMIT: id:1741323095323, from:30003, delay:0.0001s, distance:173.91m (Euclidean)
[2025-03-07 13:51:37,046] [INFO] [30101] Received COMMIT: id:1741323095323, from:30094, delay:0.0000s, distance:148.56m (Euclidean)
[2025-03-07 13:51:37,109] [INFO] [30101] Received COMMIT: id:1741323095323, from:30015, delay:0.0000s, distance:124.57m (Euclidean)
[2025-03-07 13:51:37,109] [INFO] [30101] Received COMMIT: id:1741323095323, from:30005, delay:0.0001s, distance:244.67m (Euclidean)
[2025-03-07 13:51:37,178] [INFO] [30101] Received PREPARE: id:1741323095323, from:30014, delay:0.0001s, distance:153.78m (Euclidean)
[2025-03-07 13:51:37,178] [INFO] [30101] Received COMMIT: id:1741323095323, from:30023, delay:0.0000s, distance:80.22m (Euclidean)
[2025-03-07 13:51:37,180] [INFO] [30101] Received PREPARE: id:1741323095323, from:30078, delay:0.0000s, distance:101.84m (Euclidean)
[2025-03-07 13:51:37,180] [INFO] [30101] Received COMMIT: id:1741323095323, from:30036, delay:0.0000s, distance:82.87m (Euclidean)
[2025-03-07 13:51:37,236] [INFO] [30101] Received COMMIT: id:1741323095323, from:30078, delay:0.0000s, distance:101.84m (Euclidean)
[2025-03-07 13:51:37,252] [INFO] [30101] Received COMMIT: id:1741323095323, from:30004, delay:0.0000s, distance:192.31m (Euclidean)
[2025-03-07 13:51:37,252] [INFO] [30101] Received PREPARE: id:1741323095323, from:30004, delay:0.0000s, distance:192.31m (Euclidean)
[2025-03-07 13:51:37,277] [INFO] [30101] Received COMMIT: id:1741323095323, from:30024, delay:0.0000s, distance:104.52m (Euclidean)
[2025-03-07 13:51:37,277] [INFO] [30101] Received COMMIT: id:1741323095323, from:30076, delay:0.0000s, distance:249.52m (Euclidean)
[2025-03-07 13:51:37,296] [INFO] [30101] Received COMMIT: id:1741323095323, from:30002, delay:0.0000s, distance:137.65m (Euclidean)
[2025-03-07 13:51:37,342] [INFO] [30101] Received PREPARE: id:1741323095323, from:30042, delay:0.0001s, distance:155.48m (Euclidean)
[2025-03-07 13:51:37,342] [INFO] [30101] Received PREPARE: id:1741323095323, from:30033, delay:0.0000s, distance:127.83m (Euclidean)
[2025-03-07 13:51:37,407] [INFO] [30101] Received PREPARE: id:1741323095323, from:30110, delay:0.0000s, distance:160.12m (Euclidean)
[2025-03-07 13:51:37,407] [INFO] [30101] Received PREPARE: id:1741323095323, from:30109, delay:0.0001s, distance:234.59m (Euclidean)
[2025-03-07 13:51:37,407] [INFO] [30101] Received COMMIT: id:1741323095323, from:30110, delay:0.0000s, distance:160.12m (Euclidean)
[2025-03-07 13:51:37,494] [INFO] [30101] Received COMMIT: id:1741323095323, from:30014, delay:0.0001s, distance:153.78m (Euclidean)
[2025-03-07 13:51:37,504] [INFO] [30101] Received PREPARE: id:1741323095323, from:30013, delay:0.0001s, distance:208.54m (Euclidean)
[2025-03-07 13:51:37,504] [INFO] [30101] Received COMMIT: id:1741323095323, from:30013, delay:0.0001s, distance:208.54m (Euclidean)
[2025-03-07 13:51:37,504] [INFO] [30101] Received COMMIT: id:1741323095323, from:30009, delay:0.0000s, distance:124.32m (Euclidean)
[2025-03-07 13:51:37,504] [INFO] [30101] Received COMMIT: id:1741323095323, from:30019, delay:0.0001s, distance:199.18m (Euclidean)
[2025-03-07 13:51:37,520] [INFO] [30101] Received PREPARE: id:1741323095323, from:30019, delay:0.0001s, distance:199.18m (Euclidean)
[2025-03-07 13:51:37,520] [INFO] [30101] Received PREPARE: id:1741323095323, from:30009, delay:0.0000s, distance:124.32m (Euclidean)
[2025-03-07 13:51:37,520] [INFO] [30101] Received PREPARE: id:1741323095323, from:30046, delay:0.0000s, distance:135.54m (Euclidean)
[2025-03-07 13:51:37,523] [INFO] [30101] Received COMMIT: id:1741323095323, from:30109, delay:0.0001s, distance:234.59m (Euclidean)
[2025-03-07 13:51:37,630] [INFO] [30101] Received PREPARE: id:1741323095323, from:30025, delay:0.0000s, distance:140.82m (Euclidean)
[2025-03-07 13:51:37,630] [INFO] [30101] Received PREPARE: id:1741323095323, from:30047, delay:0.0001s, distance:183.79m (Euclidean)
[2025-03-07 13:51:37,630] [INFO] [30101] Received PREPARE: id:1741323095323, from:30050, delay:0.0000s, distance:126.86m (Euclidean)
[2025-03-07 13:51:37,630] [INFO] [30101] Received COMMIT: id:1741323095323, from:30047, delay:0.0001s, distance:183.79m (Euclidean)
[2025-03-07 13:51:37,630] [INFO] [30101] Received COMMIT: id:1741323095323, from:30050, delay:0.0000s, distance:126.86m (Euclidean)
[2025-03-07 13:51:37,662] [INFO] [30101] Received COMMIT: id:1741323095323, from:30025, delay:0.0000s, distance:140.82m (Euclidean)
[2025-03-07 13:51:37,662] [INFO] [30101] Received PREPARE: id:1741323095323, from:30104, delay:0.0002s, distance:250.97m (Euclidean)
[2025-03-07 13:51:37,679] [INFO] [30101] Received PREPARE: id:1741323095323, from:30021, delay:0.0001s, distance:211.28m (Euclidean)
[2025-03-07 13:51:37,679] [INFO] [30101] Received COMMIT: id:1741323095323, from:30104, delay:0.0002s, distance:250.97m (Euclidean)
[2025-03-07 13:51:37,679] [INFO] [30101] Received COMMIT: id:1741323095323, from:30021, delay:0.0001s, distance:211.28m (Euclidean)
[2025-03-07 13:51:37,725] [INFO] [30101] Received COMMIT: id:1741323095323, from:30046, delay:0.0000s, distance:135.54m (Euclidean)
[2025-03-07 13:51:37,741] [INFO] [30101] Received PREPARE: id:1741323095323, from:30117, delay:0.0002s, distance:267.77m (Euclidean)
[2025-03-07 13:51:37,741] [INFO] [30101] Received COMMIT: id:1741323095323, from:30117, delay:0.0002s, distance:267.77m (Euclidean)
[2025-03-07 13:51:37,916] [INFO] [30101] Received PREPARE: id:1741323095323, from:30116, delay:0.0001s, distance:187.43m (Euclidean)
[2025-03-07 13:51:37,923] [INFO] [30101] Received COMMIT: id:1741323095323, from:30033, delay:0.0000s, distance:127.83m (Euclidean)
[2025-03-07 13:51:37,935] [INFO] [30101] Received COMMIT: id:1741323095323, from:30116, delay:0.0001s, distance:187.43m (Euclidean)
[2025-03-07 13:51:37,935] [INFO] [30101] Received PREPARE: id:1741323095323, from:30106, delay:0.0001s, distance:176.20m (Euclidean)
[2025-03-07 13:51:38,026] [INFO] [30101] Received PREPARE: id:1741323095323, from:30098, delay:0.0002s, distance:295.51m (Euclidean)
[2025-03-07 13:51:38,105] [INFO] [30101] Received COMMIT: id:1741323095323, from:30098, delay:0.0002s, distance:295.51m (Euclidean)
[2025-03-07 13:51:38,105] [INFO] [30101] Received PREPARE: id:1741323095323, from:30016, delay:0.0002s, distance:284.17m (Euclidean)
[2025-03-07 13:51:38,127] [INFO] [30101] Received COMMIT: id:1741323095323, from:30106, delay:0.0001s, distance:176.20m (Euclidean)
[2025-03-07 13:51:38,127] [INFO] [30101] Received COMMIT: id:1741323095323, from:30042, delay:0.0001s, distance:155.48m (Euclidean)
[2025-03-07 13:51:38,168] [INFO] [30101] Received COMMIT: id:1741323095323, from:30016, delay:0.0002s, distance:284.17m (Euclidean)
[2025-03-07 13:51:38,200] [INFO] [30101] Received PREPARE: id:1741323095323, from:30075, delay:0.0002s, distance:297.98m (Euclidean)
[2025-03-07 13:51:38,208] [INFO] [30101] Received PREPARE: id:1741323095323, from:30006, delay:0.0000s, distance:104.20m (Euclidean)
[2025-03-07 13:51:38,208] [INFO] [30101] Received PREPARE: id:1741323095323, from:30045, delay:0.0000s, distance:126.53m (Euclidean)
[2025-03-07 13:51:38,208] [INFO] [30101] Received PREPARE: id:1741323095323, from:30029, delay:0.0001s, distance:206.37m (Euclidean)
[2025-03-07 13:51:38,224] [INFO] [30101] Received COMMIT: id:1741323095323, from:30045, delay:0.0000s, distance:126.53m (Euclidean)
[2025-03-07 13:51:38,224] [INFO] [30101] Received COMMIT: id:1741323095323, from:30006, delay:0.0000s, distance:104.20m (Euclidean)
[2025-03-07 13:51:38,224] [INFO] [30101] Received COMMIT: id:1741323095323, from:30029, delay:0.0001s, distance:206.37m (Euclidean)
[2025-03-07 13:51:38,247] [INFO] [30101] Received COMMIT: id:1741323095323, from:30075, delay:0.0002s, distance:297.98m (Euclidean)
[2025-03-07 13:51:38,270] [INFO] [30101] Received PREPARE: id:1741323095323, from:30107, delay:0.0002s, distance:275.49m (Euclidean)
[2025-03-07 13:51:38,270] [INFO] [30101] Received COMMIT: id:1741323095323, from:30107, delay:0.0002s, distance:275.49m (Euclidean)
[2025-03-07 13:51:38,294] [INFO] [30101] Received PREPARE: id:1741323095323, from:30012, delay:0.0002s, distance:296.82m (Euclidean)
[2025-03-07 13:51:38,294] [INFO] [30101] Received COMMIT: id:1741323095323, from:30012, delay:0.0002s, distance:296.82m (Euclidean)
[2025-03-07 13:51:38,294] [INFO] [30101] Received PREPARE: id:1741323095323, from:30060, delay:0.0001s, distance:185.27m (Euclidean)
[2025-03-07 13:51:38,298] [INFO] [30101] Received COMMIT: id:1741323095323, from:30060, delay:0.0001s, distance:185.27m (Euclidean)
[2025-03-07 13:51:38,298] [INFO] [30101] Received PREPARE: id:1741323095323, from:30052, delay:0.0001s, distance:273.93m (Euclidean)
[2025-03-07 13:51:38,298] [INFO] [30101] Received PREPARE: id:1741323095323, from:30017, delay:0.0000s, distance:148.14m (Euclidean)
[2025-03-07 13:51:38,298] [INFO] [30101] Received COMMIT: id:1741323095323, from:30017, delay:0.0000s, distance:148.14m (Euclidean)
[2025-03-07 13:51:38,335] [INFO] [30101] Received PREPARE: id:1741323095323, from:30030, delay:0.0000s, distance:125.56m (Euclidean)
[2025-03-07 13:51:38,339] [INFO] [30101] Received COMMIT: id:1741323095323, from:30030, delay:0.0000s, distance:125.56m (Euclidean)
[2025-03-07 13:51:38,339] [INFO] [30101] Received COMMIT: id:1741323095323, from:30097, delay:0.0001s, distance:199.41m (Euclidean)
[2025-03-07 13:51:38,339] [INFO] [30101] Received PREPARE: id:1741323095323, from:30097, delay:0.0001s, distance:199.41m (Euclidean)
[2025-03-07 13:51:38,384] [INFO] [30101] Received COMMIT: id:1741323095323, from:30052, delay:0.0001s, distance:273.93m (Euclidean)
[2025-03-07 13:51:38,386] [INFO] [30101] Received PREPARE: id:1741323095323, from:30069, delay:0.0001s, distance:235.56m (Euclidean)
[2025-03-07 13:51:38,442] [INFO] [30101] Received PREPARE: id:1741323095323, from:30022, delay:0.0001s, distance:209.46m (Euclidean)
[2025-03-07 13:51:38,468] [INFO] [30101] Received COMMIT: id:1741323095323, from:30022, delay:0.0001s, distance:209.46m (Euclidean)
[2025-03-07 13:51:38,468] [INFO] [30101] Received COMMIT: id:1741323095323, from:30069, delay:0.0001s, distance:235.56m (Euclidean)
[2025-03-07 13:51:38,490] [INFO] [30101] Received COMMIT: id:1741323095323, from:30084, delay:0.0000s, distance:134.92m (Euclidean)
[2025-03-07 13:51:38,490] [INFO] [30101] Received PREPARE: id:1741323095323, from:30084, delay:0.0000s, distance:134.92m (Euclidean)
[2025-03-07 13:51:38,658] [INFO] [30101] Received PREPARE: id:1741323095323, from:30099, delay:0.0001s, distance:213.87m (Euclidean)
[2025-03-07 13:51:38,685] [INFO] [30101] Received PREPARE: id:1741323095323, from:30082, delay:0.0001s, distance:204.69m (Euclidean)
[2025-03-07 13:51:38,690] [INFO] [30101] Received PREPARE: id:1741323095323, from:30112, delay:0.0000s, distance:155.92m (Euclidean)
[2025-03-07 13:51:38,690] [INFO] [30101] Received PREPARE: id:1741323095323, from:30090, delay:0.0000s, distance:167.49m (Euclidean)
[2025-03-07 13:51:38,690] [INFO] [30101] Received COMMIT: id:1741323095323, from:30099, delay:0.0001s, distance:213.87m (Euclidean)
[2025-03-07 13:51:38,690] [INFO] [30101] Received COMMIT: id:1741323095323, from:30090, delay:0.0000s, distance:167.49m (Euclidean)
[2025-03-07 13:51:38,711] [INFO] [30101] Received COMMIT: id:1741323095323, from:30082, delay:0.0001s, distance:204.69m (Euclidean)
[2025-03-07 13:51:38,769] [INFO] [30101] Received COMMIT: id:1741323095323, from:30112, delay:0.0000s, distance:155.92m (Euclidean)
[2025-03-07 13:51:38,814] [INFO] [30101] Received PREPARE: id:1741323095323, from:30027, delay:0.0001s, distance:189.33m (Euclidean)
[2025-03-07 13:51:38,814] [INFO] [30101] Received COMMIT: id:1741323095323, from:30027, delay:0.0001s, distance:189.33m (Euclidean)
[2025-03-07 13:51:38,822] [INFO] [30101] Received PREPARE: id:1741323095323, from:30041, delay:0.0000s, distance:154.39m (Euclidean)
[2025-03-07 13:51:38,822] [INFO] [30101] Received COMMIT: id:1741323095323, from:30041, delay:0.0000s, distance:154.39m (Euclidean)
[2025-03-07 13:51:38,873] [INFO] [30101] Received PREPARE: id:1741323095323, from:30031, delay:0.0002s, distance:280.13m (Euclidean)
[2025-03-07 13:51:38,873] [INFO] [30101] Received PREPARE: id:1741323095323, from:30057, delay:0.0001s, distance:224.03m (Euclidean)
[2025-03-07 13:51:38,875] [INFO] [30101] Received COMMIT: id:1741323095323, from:30031, delay:0.0002s, distance:280.13m (Euclidean)
[2025-03-07 13:51:38,875] [INFO] [30101] Received COMMIT: id:1741323095323, from:30057, delay:0.0001s, distance:224.03m (Euclidean)
[2025-03-07 13:51:38,905] [INFO] [30101] Received PREPARE: id:1741323095323, from:30055, delay:0.0001s, distance:210.87m (Euclidean)
[2025-03-07 13:51:38,905] [INFO] [30101] Received COMMIT: id:1741323095323, from:30055, delay:0.0001s, distance:210.87m (Euclidean)
[2025-03-07 13:51:38,912] [INFO] [30101] Received PREPARE: id:1741323095323, from:30040, delay:0.0001s, distance:154.49m (Euclidean)
[2025-03-07 13:51:38,912] [INFO] [30101] Received COMMIT: id:1741323095323, from:30040, delay:0.0001s, distance:154.49m (Euclidean)
[2025-03-07 13:51:39,016] [INFO] [30101] Received PREPARE: id:1741323095323, from:30051, delay:0.0002s, distance:256.67m (Euclidean)
[2025-03-07 13:51:39,021] [INFO] [30101] Received COMMIT: id:1741323095323, from:30051, delay:0.0002s, distance:256.67m (Euclidean)
[2025-03-07 13:51:39,026] [INFO] [30101] Received PREPARE: id:1741323095323, from:30067, delay:0.0001s, distance:211.46m (Euclidean)
[2025-03-07 13:51:39,026] [INFO] [30101] Received COMMIT: id:1741323095323, from:30067, delay:0.0001s, distance:211.46m (Euclidean)
[2025-03-07 13:51:39,053] [INFO] [30101] Received PREPARE: id:1741323095323, from:30037, delay:0.0001s, distance:221.69m (Euclidean)
[2025-03-07 13:51:39,053] [INFO] [30101] Received COMMIT: id:1741323095323, from:30037, delay:0.0001s, distance:221.69m (Euclidean)
[2025-03-07 13:51:39,083] [INFO] [30101] Received PREPARE: id:1741323095323, from:30056, delay:0.0001s, distance:230.56m (Euclidean)
[2025-03-07 13:51:39,084] [INFO] [30101] Received COMMIT: id:1741323095323, from:30056, delay:0.0001s, distance:230.56m (Euclidean)
[2025-03-07 13:51:39,132] [INFO] [30101] Received PREPARE: id:1741323095323, from:30054, delay:0.0002s, distance:256.67m (Euclidean)
[2025-03-07 13:51:39,137] [INFO] [30101] Received COMMIT: id:1741323095323, from:30054, delay:0.0002s, distance:256.67m (Euclidean)
[2025-03-07 13:51:39,244] [INFO] [30101] Received PREPARE: id:1741323095323, from:30026, delay:0.0002s, distance:259.40m (Euclidean)
[2025-03-07 13:51:39,258] [INFO] [30101] Received COMMIT: id:1741323095323, from:30026, delay:0.0002s, distance:259.40m (Euclidean)
[2025-03-07 13:51:39,260] [INFO] [30101] Received PREPARE: id:1741323095323, from:30079, delay:0.0002s, distance:262.61m (Euclidean)
[2025-03-07 13:51:39,260] [INFO] [30101] Received COMMIT: id:1741323095323, from:30079, delay:0.0002s, distance:262.61m (Euclidean)
[2025-03-07 13:51:39,262] [INFO] [30101] Received PREPARE: id:1741323095323, from:30020, delay:0.0001s, distance:206.99m (Euclidean)
[2025-03-07 13:51:39,262] [INFO] [30101] Received COMMIT: id:1741323095323, from:30020, delay:0.0001s, distance:206.99m (Euclidean)
[2025-03-07 13:51:39,290] [INFO] [30101] Received PREPARE: id:1741323095323, from:30092, delay:0.0001s, distance:211.29m (Euclidean)
[2025-03-07 13:51:39,290] [INFO] [30101] Received COMMIT: id:1741323095323, from:30092, delay:0.0001s, distance:211.29m (Euclidean)
[2025-03-07 13:51:39,507] [INFO] [30101] Received COMMIT: id:1741323095323, from:30000, delay:0.0000s, distance:151.15m (Euclidean)
[2025-03-07 13:51:39,720] [INFO] [30101] Received PREPARE: id:1741323095323, from:30018, delay:0.0001s, distance:191.02m (Euclidean)
[2025-03-07 13:51:39,740] [INFO] [30101] Received PREPARE: id:1741323095323, from:30077, delay:0.0001s, distance:190.25m (Euclidean)
[2025-03-07 13:51:39,783] [INFO] [30101] Received COMMIT: id:1741323095323, from:30018, delay:0.0001s, distance:191.02m (Euclidean)
[2025-03-07 13:51:39,881] [ERROR] [30101] Error sending to http://localhost:30061/prepare: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('127.0.0.1', 30061)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30061)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('127.0.0.1', 30061)]
[2025-03-07 13:51:39,885] [INFO] [30101] Received COMMIT: id:1741323095323, from:30077, delay:0.0001s, distance:190.25m (Euclidean)
[2025-03-07 13:51:39,976] [INFO] [30101] Received PREPARE: id:1741323095323, from:30083, delay:0.0001s, distance:215.21m (Euclidean)
[2025-03-07 13:51:40,005] [INFO] [30101] Received PREPARE: id:1741323095323, from:30066, delay:0.0002s, distance:262.54m (Euclidean)
[2025-03-07 13:51:40,043] [INFO] [30101] Received COMMIT: id:1741323095323, from:30066, delay:0.0002s, distance:262.54m (Euclidean)
[2025-03-07 13:51:40,069] [INFO] [30101] Received COMMIT: id:1741323095323, from:30083, delay:0.0001s, distance:215.21m (Euclidean)
[2025-03-07 13:51:40,152] [ERROR] [30101] Error sending to http://localhost:30091/prepare: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('127.0.0.1', 30091)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('127.0.0.1', 30091)]
[2025-03-07 13:51:40,180] [ERROR] [30101] Error sending to http://localhost:30085/prepare: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30085)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
[2025-03-07 13:51:40,212] [ERROR] [30101] Error sending to http://localhost:30063/prepare: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30063)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
[2025-03-07 13:51:40,262] [ERROR] [30101] Error sending to http://localhost:30058/prepare: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('127.0.0.1', 30058)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30058)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('127.0.0.1', 30058)]
[2025-03-07 13:51:41,468] [ERROR] [30101] Error sending to http://localhost:30061/commit: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('::1', 30061, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30061, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('::1', 30061, 0, 0)]
[2025-03-07 13:51:41,468] [ERROR] [30101] Error sending to http://localhost:30072/prepare: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('127.0.0.1', 30072)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30072)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('127.0.0.1', 30072)]
[2025-03-07 13:51:41,468] [ERROR] [30101] Error sending to http://localhost:30063/commit: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30063, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
[2025-03-07 13:51:41,468] [ERROR] [30101] Error sending to http://localhost:30087/prepare: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('127.0.0.1', 30087)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30087)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('127.0.0.1', 30087)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30072/commit: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('::1', 30072, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30072, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('::1', 30072, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30086/prepare: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('127.0.0.1', 30086)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30086)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('127.0.0.1', 30086)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30070/prepare: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('127.0.0.1', 30070)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30070)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('127.0.0.1', 30070)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30091/commit: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('::1', 30091, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30091, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('::1', 30091, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30070/commit: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('::1', 30070, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30070, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('::1', 30070, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30085/commit: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30085, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30093/commit: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30093, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30058/commit: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('::1', 30058, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30058, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('::1', 30058, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30064/prepare: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30064)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30093/prepare: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30093)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30064/commit: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30064, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30062/prepare: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('127.0.0.1', 30062)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30062)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('127.0.0.1', 30062)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30062/commit: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('::1', 30062, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30062, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('::1', 30062, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30101] Error sending to http://localhost:30086/commit: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('::1', 30086, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30086, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('::1', 30086, 0, 0)]
[2025-03-07 13:51:41,499] [ERROR] [30101] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:51:41,502] [ERROR] [30101] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:51:41,502] [ERROR] [30101] Error sending to http://localhost:30087/commit: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('::1', 30087, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30087, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('::1', 30087, 0, 0)]
[2025-03-07 13:51:41,504] [INFO] [30101] Received PREPARE: id:1741323095323, from:30034, delay:0.0002s, distance:270.38m (Euclidean)
[2025-03-07 13:51:41,769] [ERROR] [30101] Error sending to http://localhost:30105/prepare: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('127.0.0.1', 30105)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30105)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('127.0.0.1', 30105)]
[2025-03-07 13:51:41,787] [ERROR] [30101] Error sending to http://localhost:30105/commit: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('::1', 30105, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30105, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('::1', 30105, 0, 0)]
[2025-03-07 13:51:41,929] [INFO] [30101] Received COMMIT: id:1741323095323, from:30034, delay:0.0002s, distance:270.38m (Euclidean)
[2025-03-07 13:51:42,071] [ERROR] [30101] Error sending to http://localhost:30081/prepare: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('127.0.0.1', 30081)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30081)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('127.0.0.1', 30081)]
[2025-03-07 13:51:42,087] [ERROR] [30101] Error sending to http://localhost:30081/commit: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('::1', 30081, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30081, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('::1', 30081, 0, 0)]
[2025-03-07 13:51:42,150] [ERROR] [30101] Error sending to http://localhost:30089/prepare: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('127.0.0.1', 30089)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30089)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('127.0.0.1', 30089)]
[2025-03-07 13:51:42,153] [ERROR] [30101] Error sending to http://localhost:30089/commit: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('::1', 30089, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30089, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('::1', 30089, 0, 0)]
[2025-03-07 13:51:42,153] [INFO] [30101] Received PREPARE: id:1741323095323, from:30038, delay:0.0002s, distance:261.70m (Euclidean)
[2025-03-07 13:51:42,182] [ERROR] [30101] Error sending to http://localhost:30073/commit: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('::1', 30073, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30073, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('::1', 30073, 0, 0)]
[2025-03-07 13:51:42,182] [ERROR] [30101] Error sending to http://localhost:30073/prepare: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('127.0.0.1', 30073)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30073)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('127.0.0.1', 30073)]
[2025-03-07 13:51:42,341] [INFO] [30101] Received PREPARE: id:1741323095323, from:30080, delay:0.0002s, distance:271.20m (Euclidean)
[2025-03-07 13:51:42,383] [INFO] [30101] Received COMMIT: id:1741323095323, from:30038, delay:0.0002s, distance:261.70m (Euclidean)
[2025-03-07 13:51:42,573] [INFO] [30101] Received COMMIT: id:1741323095323, from:30080, delay:0.0002s, distance:271.20m (Euclidean)
[2025-03-07 13:52:34,989] [INFO] Starting node at localhost:30101 | index=102 | f=1, k=4 | Role: Replica
[2025-03-07 13:54:48,023] [INFO] Starting node at localhost:30101 | index=102 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:34,477] [INFO] Starting node at localhost:30101 | index=102 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:36,895] [INFO] Starting node at localhost:30101 | index=102 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:03,209] [INFO] [30101] Received PREPARE: id:1741323542381, from:30189, delay:0.0000s, distance:67.19m (Euclidean)
[2025-03-07 13:59:03,209] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,284] [INFO] [30101] Received PREPARE: id:1741323542381, from:30154, delay:0.0000s, distance:165.34m (Euclidean)
[2025-03-07 13:59:03,284] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,525] [INFO] [30101] Received PREPARE: id:1741323542381, from:30179, delay:0.0001s, distance:193.42m (Euclidean)
[2025-03-07 13:59:03,525] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,554] [INFO] [30101] Received PREPARE: id:1741323542381, from:30157, delay:0.0001s, distance:175.69m (Euclidean)
[2025-03-07 13:59:03,554] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,595] [INFO] [30101] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:105.65m (Euclidean)
[2025-03-07 13:59:03,595] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,600] [INFO] [30101] Received PREPARE: id:1741323542381, from:30028, delay:0.0000s, distance:76.07m (Euclidean)
[2025-03-07 13:59:03,600] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,613] [INFO] [30101] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:100.76m (Euclidean)
[2025-03-07 13:59:03,613] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,639] [INFO] [30101] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:106.66m (Euclidean)
[2025-03-07 13:59:03,639] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,652] [INFO] [30101] Received PREPARE: id:1741323542381, from:30065, delay:0.0000s, distance:93.65m (Euclidean)
[2025-03-07 13:59:03,652] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,803] [INFO] [30101] Received PREPARE: id:1741323542381, from:30119, delay:0.0000s, distance:141.69m (Euclidean)
[2025-03-07 13:59:03,803] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,821] [INFO] [30101] Received PREPARE: id:1741323542381, from:30168, delay:0.0000s, distance:124.19m (Euclidean)
[2025-03-07 13:59:03,821] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,825] [INFO] [30101] Received PREPARE: id:1741323542381, from:30115, delay:0.0000s, distance:118.25m (Euclidean)
[2025-03-07 13:59:03,825] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,891] [INFO] [30101] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:105.65m (Euclidean)
[2025-03-07 13:59:03,942] [INFO] [30101] Received PREPARE: id:1741323542381, from:30196, delay:0.0001s, distance:245.81m (Euclidean)
[2025-03-07 13:59:03,942] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,990] [INFO] [30101] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:114.67m (Euclidean)
[2025-03-07 13:59:03,990] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,065] [INFO] [30101] Received PREPARE: id:1741323542381, from:30133, delay:0.0001s, distance:233.66m (Euclidean)
[2025-03-07 13:59:04,065] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,119] [INFO] [30101] Received PREPARE: id:1741323542381, from:30113, delay:0.0000s, distance:155.90m (Euclidean)
[2025-03-07 13:59:04,119] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,135] [INFO] [30101] Received PREPARE: id:1741323542381, from:30123, delay:0.0000s, distance:107.20m (Euclidean)
[2025-03-07 13:59:04,135] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,170] [INFO] [30101] Received PREPARE: id:1741323542381, from:30027, delay:0.0000s, distance:46.67m (Euclidean)
[2025-03-07 13:59:04,170] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,184] [INFO] [30101] Received COMMIT: id:1741323542381, from:30179, delay:0.0001s, distance:193.42m (Euclidean)
[2025-03-07 13:59:04,184] [INFO] [30101] Received PREPARE: id:1741323542381, from:30118, delay:0.0001s, distance:216.96m (Euclidean)
[2025-03-07 13:59:04,184] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,190] [INFO] [30101] Received PREPARE: id:1741323542381, from:30147, delay:0.0002s, distance:260.73m (Euclidean)
[2025-03-07 13:59:04,190] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,223] [INFO] [30101] Received PREPARE: id:1741323542381, from:30136, delay:0.0001s, distance:193.54m (Euclidean)
[2025-03-07 13:59:04,223] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,229] [INFO] [30101] Received PREPARE: id:1741323542381, from:30195, delay:0.0000s, distance:71.13m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,229] [INFO] [30101] Received COMMIT: id:1741323542381, from:30195, delay:0.0000s, distance:71.13m (Euclidean)
[2025-03-07 13:59:04,464] [INFO] [30101] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:100.76m (Euclidean)
[2025-03-07 13:59:04,464] [INFO] [30101] Received PREPARE: id:1741323542381, from:30089, delay:0.0000s, distance:131.04m (Euclidean)
[2025-03-07 13:59:04,464] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,464] [INFO] [30101] Received PREPARE: id:1741323542381, from:30015, delay:0.0000s, distance:141.65m (Euclidean)
[2025-03-07 13:59:04,464] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,467] [INFO] [30101] Received COMMIT: id:1741323542381, from:30147, delay:0.0002s, distance:260.73m (Euclidean)
[2025-03-07 13:59:04,467] [INFO] [30101] Received COMMIT: id:1741323542381, from:30136, delay:0.0001s, distance:193.54m (Euclidean)
[2025-03-07 13:59:04,467] [INFO] [30101] Received PREPARE: id:1741323542381, from:30174, delay:0.0000s, distance:42.72m (Euclidean)
[2025-03-07 13:59:04,467] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,469] [INFO] [30101] Received PREPARE: id:1741323542381, from:30025, delay:0.0001s, distance:242.20m (Euclidean)
[2025-03-07 13:59:04,469] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,469] [INFO] [30101] Received PREPARE: id:1741323542381, from:30182, delay:0.0000s, distance:108.53m (Euclidean)
[2025-03-07 13:59:04,469] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,482] [INFO] [30101] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:96.15m (Euclidean)
[2025-03-07 13:59:04,482] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,535] [INFO] [30101] Received COMMIT: id:1741323542381, from:30182, delay:0.0000s, distance:108.53m (Euclidean)
[2025-03-07 13:59:04,546] [INFO] [30101] Received COMMIT: id:1741323542381, from:30123, delay:0.0000s, distance:107.20m (Euclidean)
[2025-03-07 13:59:04,648] [INFO] [30101] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:114.67m (Euclidean)
[2025-03-07 13:59:04,675] [INFO] [30101] Received PREPARE: id:1741323542381, from:30120, delay:0.0000s, distance:95.03m (Euclidean)
[2025-03-07 13:59:04,675] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,685] [INFO] [30101] Received PREPARE: id:1741323542381, from:30035, delay:0.0000s, distance:101.80m (Euclidean)
[2025-03-07 13:59:04,685] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,685] [INFO] [30101] Received COMMIT: id:1741323542381, from:30035, delay:0.0000s, distance:101.80m (Euclidean)
[2025-03-07 13:59:04,693] [INFO] [30101] Received PREPARE: id:1741323542381, from:30102, delay:0.0001s, distance:207.76m (Euclidean)
[2025-03-07 13:59:04,693] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,707] [INFO] [30101] Received PREPARE: id:1741323542381, from:30181, delay:0.0000s, distance:88.17m (Euclidean)
[2025-03-07 13:59:04,707] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,741] [INFO] [30101] Received COMMIT: id:1741323542381, from:30118, delay:0.0001s, distance:216.96m (Euclidean)
[2025-03-07 13:59:04,768] [INFO] [30101] Received PREPARE: id:1741323542381, from:30110, delay:0.0001s, distance:248.64m (Euclidean)
[2025-03-07 13:59:04,768] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,769] [INFO] [30101] Received COMMIT: id:1741323542381, from:30110, delay:0.0001s, distance:248.64m (Euclidean)
[2025-03-07 13:59:04,882] [INFO] [30101] Received COMMIT: id:1741323542381, from:30196, delay:0.0001s, distance:245.81m (Euclidean)
[2025-03-07 13:59:04,886] [INFO] [30101] Received PREPARE: id:1741323542381, from:30150, delay:0.0001s, distance:216.43m (Euclidean)
[2025-03-07 13:59:04,886] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,939] [INFO] [30101] Received PREPARE: id:1741323542381, from:30005, delay:0.0000s, distance:107.31m (Euclidean)
[2025-03-07 13:59:04,939] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,944] [INFO] [30101] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:147.56m (Euclidean)
[2025-03-07 13:59:04,944] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,980] [INFO] [30101] Received PREPARE: id:1741323542381, from:30144, delay:0.0001s, distance:173.28m (Euclidean)
[2025-03-07 13:59:04,980] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,980] [INFO] [30101] Received COMMIT: id:1741323542381, from:30144, delay:0.0001s, distance:173.28m (Euclidean)
[2025-03-07 13:59:04,989] [INFO] [30101] Received COMMIT: id:1741323542381, from:30157, delay:0.0001s, distance:175.69m (Euclidean)
[2025-03-07 13:59:05,040] [INFO] [30101] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:106.66m (Euclidean)
[2025-03-07 13:59:05,056] [INFO] [30101] Received PREPARE: id:1741323542381, from:30170, delay:0.0001s, distance:241.46m (Euclidean)
[2025-03-07 13:59:05,058] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,066] [INFO] [30101] Received COMMIT: id:1741323542381, from:30005, delay:0.0000s, distance:107.31m (Euclidean)
[2025-03-07 13:59:05,168] [INFO] [30101] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:176.57m (Euclidean)
[2025-03-07 13:59:05,168] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,309] [INFO] [30101] Received PREPARE: id:1741323542381, from:30043, delay:0.0000s, distance:123.65m (Euclidean)
[2025-03-07 13:59:05,309] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,533] [INFO] [30101] Received PREPARE: id:1741323542381, from:30024, delay:0.0000s, distance:77.97m (Euclidean)
[2025-03-07 13:59:05,533] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,584] [INFO] [30101] Received PREPARE: id:1741323542381, from:30066, delay:0.0001s, distance:220.96m (Euclidean)
[2025-03-07 13:59:05,584] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,601] [INFO] [30101] Received COMMIT: id:1741323542381, from:30027, delay:0.0000s, distance:46.67m (Euclidean)
[2025-03-07 13:59:05,679] [INFO] [30101] Received PREPARE: id:1741323542381, from:30054, delay:0.0000s, distance:90.40m (Euclidean)
[2025-03-07 13:59:05,679] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,786] [INFO] [30101] Received PREPARE: id:1741323542381, from:30076, delay:0.0000s, distance:34.96m (Euclidean)
[2025-03-07 13:59:05,786] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,820] [INFO] [30101] Received COMMIT: id:1741323542381, from:30025, delay:0.0001s, distance:242.20m (Euclidean)
[2025-03-07 13:59:05,911] [INFO] [30101] Received PREPARE: id:1741323542381, from:30063, delay:0.0001s, distance:235.17m (Euclidean)
[2025-03-07 13:59:05,911] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,940] [INFO] [30101] Received PREPARE: id:1741323542381, from:30051, delay:0.0001s, distance:154.92m (Euclidean)
[2025-03-07 13:59:05,940] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,964] [INFO] [30101] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:187.92m (Euclidean)
[2025-03-07 13:59:05,964] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,082] [INFO] [30101] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:102.93m (Euclidean)
[2025-03-07 13:59:06,082] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,082] [INFO] [30101] Received COMMIT: id:1741323542381, from:30113, delay:0.0000s, distance:155.90m (Euclidean)
[2025-03-07 13:59:06,120] [INFO] [30101] Received COMMIT: id:1741323542381, from:30043, delay:0.0000s, distance:123.65m (Euclidean)
[2025-03-07 13:59:06,142] [INFO] [30101] Received PREPARE: id:1741323542381, from:30013, delay:0.0002s, distance:271.09m (Euclidean)
[2025-03-07 13:59:06,142] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,243] [INFO] [30101] Received PREPARE: id:1741323542381, from:30121, delay:0.0002s, distance:256.04m (Euclidean)
[2025-03-07 13:59:06,243] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,243] [INFO] [30101] Received COMMIT: id:1741323542381, from:30028, delay:0.0000s, distance:76.07m (Euclidean)
[2025-03-07 13:59:06,245] [INFO] [30101] Received COMMIT: id:1741323542381, from:30013, delay:0.0002s, distance:271.09m (Euclidean)
[2025-03-07 13:59:06,292] [INFO] [30101] Received PREPARE: id:1741323542381, from:30037, delay:0.0002s, distance:295.23m (Euclidean)
[2025-03-07 13:59:06,292] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,327] [INFO] [30101] Received COMMIT: id:1741323542381, from:30121, delay:0.0002s, distance:256.04m (Euclidean)
[2025-03-07 13:59:06,333] [INFO] [30101] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:90.22m (Euclidean)
[2025-03-07 13:59:06,333] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,347] [INFO] [30101] Received PREPARE: id:1741323542381, from:30023, delay:0.0000s, distance:104.31m (Euclidean)
[2025-03-07 13:59:06,347] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,357] [INFO] [30101] Received COMMIT: id:1741323542381, from:30115, delay:0.0000s, distance:118.25m (Euclidean)
[2025-03-07 13:59:06,381] [INFO] [30101] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:102.93m (Euclidean)
[2025-03-07 13:59:06,433] [INFO] [30101] Received COMMIT: id:1741323542381, from:30133, delay:0.0001s, distance:233.66m (Euclidean)
[2025-03-07 13:59:06,435] [INFO] [30101] Received COMMIT: id:1741323542381, from:30023, delay:0.0000s, distance:104.31m (Euclidean)
[2025-03-07 13:59:06,486] [INFO] [30101] Received COMMIT: id:1741323542381, from:30024, delay:0.0000s, distance:77.97m (Euclidean)
[2025-03-07 13:59:06,486] [INFO] [30101] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:147.56m (Euclidean)
[2025-03-07 13:59:06,503] [INFO] [30101] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:187.92m (Euclidean)
[2025-03-07 13:59:06,529] [INFO] [30101] Received COMMIT: id:1741323542381, from:30037, delay:0.0002s, distance:295.23m (Euclidean)
[2025-03-07 13:59:06,539] [INFO] [30101] Received PREPARE: id:1741323542381, from:30080, delay:0.0002s, distance:293.15m (Euclidean)
[2025-03-07 13:59:06,539] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,542] [INFO] [30101] Received COMMIT: id:1741323542381, from:30089, delay:0.0000s, distance:131.04m (Euclidean)
[2025-03-07 13:59:06,667] [INFO] [30101] Received PREPARE: id:1741323542381, from:30177, delay:0.0001s, distance:152.18m (Euclidean)
[2025-03-07 13:59:06,667] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,785] [INFO] [30101] Received PREPARE: id:1741323542381, from:30191, delay:0.0000s, distance:126.01m (Euclidean)
[2025-03-07 13:59:06,785] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,785] [INFO] [30101] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:90.22m (Euclidean)
[2025-03-07 13:59:06,805] [INFO] [30101] Received COMMIT: id:1741323542381, from:30066, delay:0.0001s, distance:220.96m (Euclidean)
[2025-03-07 13:59:06,821] [INFO] [30101] Received PREPARE: id:1741323542381, from:30128, delay:0.0002s, distance:274.85m (Euclidean)
[2025-03-07 13:59:06,821] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,847] [INFO] [30101] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:187.67m (Euclidean)
[2025-03-07 13:59:06,847] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,862] [INFO] [30101] Received PREPARE: id:1741323542381, from:30062, delay:0.0001s, distance:192.78m (Euclidean)
[2025-03-07 13:59:06,872] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,878] [INFO] [30101] Received COMMIT: id:1741323542381, from:30128, delay:0.0002s, distance:274.85m (Euclidean)
[2025-03-07 13:59:06,942] [INFO] [30101] Received COMMIT: id:1741323542381, from:30120, delay:0.0000s, distance:95.03m (Euclidean)
[2025-03-07 13:59:06,967] [INFO] [30101] Received PREPARE: id:1741323542381, from:30112, delay:0.0001s, distance:187.69m (Euclidean)
[2025-03-07 13:59:06,967] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,969] [INFO] [30101] Received PREPARE: id:1741323542381, from:30096, delay:0.0002s, distance:257.88m (Euclidean)
[2025-03-07 13:59:06,969] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,973] [INFO] [30101] Received PREPARE: id:1741323542381, from:30169, delay:0.0002s, distance:271.42m (Euclidean)
[2025-03-07 13:59:06,973] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,975] [INFO] [30101] Received COMMIT: id:1741323542381, from:30062, delay:0.0001s, distance:192.78m (Euclidean)
[2025-03-07 13:59:06,977] [INFO] [30101] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:134.50m (Euclidean)
[2025-03-07 13:59:06,977] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,989] [INFO] [30101] Received COMMIT: id:1741323542381, from:30060, delay:0.0001s, distance:194.42m (Euclidean)
[2025-03-07 13:59:06,991] [INFO] [30101] Received PREPARE: id:1741323542381, from:30060, delay:0.0001s, distance:194.42m (Euclidean)
[2025-03-07 13:59:06,991] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,011] [INFO] [30101] Received COMMIT: id:1741323542381, from:30154, delay:0.0000s, distance:165.34m (Euclidean)
[2025-03-07 13:59:07,045] [INFO] [30101] Received COMMIT: id:1741323542381, from:30177, delay:0.0001s, distance:152.18m (Euclidean)
[2025-03-07 13:59:07,072] [INFO] [30101] Received COMMIT: id:1741323542381, from:30102, delay:0.0001s, distance:207.76m (Euclidean)
[2025-03-07 13:59:07,081] [INFO] [30101] Received COMMIT: id:1741323542381, from:30015, delay:0.0000s, distance:141.65m (Euclidean)
[2025-03-07 13:59:07,089] [INFO] [30101] Received COMMIT: id:1741323542381, from:30054, delay:0.0000s, distance:90.40m (Euclidean)
[2025-03-07 13:59:07,098] [INFO] [30101] Received COMMIT: id:1741323542381, from:30107, delay:0.0001s, distance:223.17m (Euclidean)
[2025-03-07 13:59:07,098] [INFO] [30101] Received PREPARE: id:1741323542381, from:30107, delay:0.0001s, distance:223.17m (Euclidean)
[2025-03-07 13:59:07,099] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,129] [INFO] [30101] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:96.15m (Euclidean)
[2025-03-07 13:59:07,282] [INFO] [30101] Received COMMIT: id:1741323542381, from:30065, delay:0.0000s, distance:93.65m (Euclidean)
[2025-03-07 13:59:07,291] [INFO] [30101] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:176.57m (Euclidean)
[2025-03-07 13:59:07,327] [INFO] [30101] Received PREPARE: id:1741323542381, from:30103, delay:0.0000s, distance:170.65m (Euclidean)
[2025-03-07 13:59:07,327] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,327] [INFO] [30101] Received COMMIT: id:1741323542381, from:30080, delay:0.0002s, distance:293.15m (Euclidean)
[2025-03-07 13:59:07,384] [INFO] [30101] Received COMMIT: id:1741323542381, from:30191, delay:0.0000s, distance:126.01m (Euclidean)
[2025-03-07 13:59:07,384] [INFO] [30101] Received PREPARE: id:1741323542381, from:30167, delay:0.0001s, distance:231.03m (Euclidean)
[2025-03-07 13:59:07,384] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,384] [INFO] [30101] Received COMMIT: id:1741323542381, from:30167, delay:0.0001s, distance:231.03m (Euclidean)
[2025-03-07 13:59:07,421] [INFO] [30101] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:187.67m (Euclidean)
[2025-03-07 13:59:07,457] [INFO] [30101] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:147.69m (Euclidean)
[2025-03-07 13:59:07,457] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,457] [INFO] [30101] Received COMMIT: id:1741323542381, from:30096, delay:0.0002s, distance:257.88m (Euclidean)
[2025-03-07 13:59:07,476] [INFO] [30101] Received PREPARE: id:1741323542381, from:30040, delay:0.0000s, distance:62.79m (Euclidean)
[2025-03-07 13:59:07,476] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,510] [INFO] [30101] Received COMMIT: id:1741323542381, from:30051, delay:0.0001s, distance:154.92m (Euclidean)
[2025-03-07 13:59:07,596] [INFO] [30101] Received COMMIT: id:1741323542381, from:30170, delay:0.0001s, distance:241.46m (Euclidean)
[2025-03-07 13:59:07,596] [INFO] [30101] Received COMMIT: id:1741323542381, from:30169, delay:0.0002s, distance:271.42m (Euclidean)
[2025-03-07 13:59:07,620] [INFO] [30101] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:147.69m (Euclidean)
[2025-03-07 13:59:07,667] [INFO] [30101] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:134.50m (Euclidean)
[2025-03-07 13:59:07,807] [INFO] [30101] Received COMMIT: id:1741323542381, from:30103, delay:0.0000s, distance:170.65m (Euclidean)
[2025-03-07 13:59:07,813] [INFO] [30101] Received COMMIT: id:1741323542381, from:30119, delay:0.0000s, distance:141.69m (Euclidean)
[2025-03-07 13:59:07,857] [INFO] [30101] Received COMMIT: id:1741323542381, from:30040, delay:0.0000s, distance:62.79m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30101] Received PREPARE: id:1741323542381, from:30127, delay:0.0001s, distance:160.43m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,877] [INFO] [30101] Received PREPARE: id:1741323542381, from:30059, delay:0.0001s, distance:237.01m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,877] [INFO] [30101] Received COMMIT: id:1741323542381, from:30059, delay:0.0001s, distance:237.01m (Euclidean)
[2025-03-07 13:59:07,904] [INFO] [30101] Received PREPARE: id:1741323542381, from:30190, delay:0.0002s, distance:276.00m (Euclidean)
[2025-03-07 13:59:07,904] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,951] [INFO] [30101] Received COMMIT: id:1741323542381, from:30174, delay:0.0000s, distance:42.72m (Euclidean)
[2025-03-07 13:59:07,978] [INFO] [30101] Received COMMIT: id:1741323542381, from:30127, delay:0.0001s, distance:160.43m (Euclidean)
[2025-03-07 13:59:07,989] [INFO] [30101] Received COMMIT: id:1741323542381, from:30168, delay:0.0000s, distance:124.19m (Euclidean)
[2025-03-07 13:59:08,030] [INFO] [30101] Received PREPARE: id:1741323542381, from:30155, delay:0.0002s, distance:256.60m (Euclidean)
[2025-03-07 13:59:08,030] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,040] [INFO] [30101] Received PREPARE: id:1741323542381, from:30126, delay:0.0002s, distance:271.24m (Euclidean)
[2025-03-07 13:59:08,040] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,040] [INFO] [30101] Received COMMIT: id:1741323542381, from:30126, delay:0.0002s, distance:271.24m (Euclidean)
[2025-03-07 13:59:08,048] [INFO] [30101] Received COMMIT: id:1741323542381, from:30155, delay:0.0002s, distance:256.60m (Euclidean)
[2025-03-07 13:59:08,109] [INFO] [30101] Received PREPARE: id:1741323542381, from:30074, delay:0.0002s, distance:251.47m (Euclidean)
[2025-03-07 13:59:08,109] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,109] [INFO] [30101] Received COMMIT: id:1741323542381, from:30074, delay:0.0002s, distance:251.47m (Euclidean)
[2025-03-07 13:59:08,116] [INFO] [30101] Received COMMIT: id:1741323542381, from:30181, delay:0.0000s, distance:88.17m (Euclidean)
[2025-03-07 13:59:08,327] [INFO] [30101] Received COMMIT: id:1741323542381, from:30190, delay:0.0002s, distance:276.00m (Euclidean)
[2025-03-07 13:59:08,593] [INFO] [30101] Received COMMIT: id:1741323542381, from:30112, delay:0.0001s, distance:187.69m (Euclidean)
[2025-03-07 13:59:08,665] [INFO] [30101] Received COMMIT: id:1741323542381, from:30063, delay:0.0001s, distance:235.17m (Euclidean)
[2025-03-07 13:59:08,703] [INFO] [30101] Received PREPARE: id:1741323542381, from:30180, delay:0.0001s, distance:188.65m (Euclidean)
[2025-03-07 13:59:08,703] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,703] [INFO] [30101] Received COMMIT: id:1741323542381, from:30180, delay:0.0001s, distance:188.65m (Euclidean)
[2025-03-07 13:59:08,703] [INFO] [30101] Received PREPARE: id:1741323542381, from:30070, delay:0.0000s, distance:112.03m (Euclidean)
[2025-03-07 13:59:08,705] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,705] [INFO] [30101] Received COMMIT: id:1741323542381, from:30070, delay:0.0000s, distance:112.03m (Euclidean)
[2025-03-07 13:59:08,713] [INFO] [30101] Received COMMIT: id:1741323542381, from:30150, delay:0.0001s, distance:216.43m (Euclidean)
[2025-03-07 13:59:08,863] [INFO] [30101] Received COMMIT: id:1741323542381, from:30076, delay:0.0000s, distance:34.96m (Euclidean)
[2025-03-07 13:59:08,914] [INFO] [30101] Received PREPARE: id:1741323542381, from:30056, delay:0.0001s, distance:228.85m (Euclidean)
[2025-03-07 13:59:08,914] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,916] [INFO] [30101] Received COMMIT: id:1741323542381, from:30056, delay:0.0001s, distance:228.85m (Euclidean)
[2025-03-07 13:59:09,011] [INFO] [30101] Received PREPARE: id:1741323542381, from:30100, delay:0.0002s, distance:269.62m (Euclidean)
[2025-03-07 13:59:09,011] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,011] [INFO] [30101] Received COMMIT: id:1741323542381, from:30100, delay:0.0002s, distance:269.62m (Euclidean)
[2025-03-07 13:59:09,049] [INFO] [30101] Received PREPARE: id:1741323542381, from:30048, delay:0.0000s, distance:182.47m (Euclidean)
[2025-03-07 13:59:09,049] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,051] [INFO] [30101] Received COMMIT: id:1741323542381, from:30048, delay:0.0000s, distance:182.47m (Euclidean)
[2025-03-07 13:59:09,190] [INFO] [30101] Received PREPARE: id:1741323542381, from:30171, delay:0.0000s, distance:138.36m (Euclidean)
[2025-03-07 13:59:09,190] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,190] [INFO] [30101] Received COMMIT: id:1741323542381, from:30171, delay:0.0000s, distance:138.36m (Euclidean)
[2025-03-07 13:59:09,231] [INFO] [30101] Received PREPARE: id:1741323542381, from:30093, delay:0.0001s, distance:206.42m (Euclidean)
[2025-03-07 13:59:09,231] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,231] [INFO] [30101] Received COMMIT: id:1741323542381, from:30093, delay:0.0001s, distance:206.42m (Euclidean)
[2025-03-07 13:59:09,316] [INFO] [30101] Received COMMIT: id:1741323542381, from:30189, delay:0.0000s, distance:67.19m (Euclidean)
[2025-03-07 13:59:09,941] [INFO] [30101] Received PREPARE: id:1741323542381, from:30046, delay:0.0000s, distance:96.11m (Euclidean)
[2025-03-07 13:59:09,941] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,941] [INFO] [30101] Received COMMIT: id:1741323542381, from:30046, delay:0.0000s, distance:96.11m (Euclidean)
[2025-03-07 13:59:10,467] [INFO] [30101] Received PREPARE: id:1741323542381, from:30124, delay:0.0002s, distance:257.37m (Euclidean)
[2025-03-07 13:59:10,467] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,467] [INFO] [30101] Received COMMIT: id:1741323542381, from:30124, delay:0.0002s, distance:257.37m (Euclidean)
[2025-03-07 13:59:10,605] [INFO] [30101] Received PREPARE: id:1741323542381, from:30158, delay:0.0002s, distance:257.84m (Euclidean)
[2025-03-07 13:59:10,605] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,605] [INFO] [30101] Received COMMIT: id:1741323542381, from:30158, delay:0.0002s, distance:257.84m (Euclidean)
[2025-03-07 13:59:10,617] [INFO] [30101] Received PREPARE: id:1741323542381, from:30095, delay:0.0002s, distance:250.58m (Euclidean)
[2025-03-07 13:59:10,617] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,617] [INFO] [30101] Received COMMIT: id:1741323542381, from:30095, delay:0.0002s, distance:250.58m (Euclidean)
[2025-03-07 13:59:10,673] [INFO] [30101] Received PREPARE: id:1741323542381, from:30130, delay:0.0001s, distance:182.25m (Euclidean)
[2025-03-07 13:59:10,673] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,673] [INFO] [30101] Received COMMIT: id:1741323542381, from:30130, delay:0.0001s, distance:182.25m (Euclidean)
[2025-03-07 13:59:10,749] [INFO] [30101] Received PREPARE: id:1741323542381, from:30106, delay:0.0001s, distance:179.44m (Euclidean)
[2025-03-07 13:59:10,749] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,749] [INFO] [30101] Received COMMIT: id:1741323542381, from:30106, delay:0.0001s, distance:179.44m (Euclidean)
[2025-03-07 13:59:10,862] [INFO] [30101] Received PREPARE: id:1741323542381, from:30020, delay:0.0001s, distance:151.61m (Euclidean)
[2025-03-07 13:59:10,863] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,863] [INFO] [30101] Received PREPARE: id:1741323542381, from:30109, delay:0.0002s, distance:270.81m (Euclidean)
[2025-03-07 13:59:10,863] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,863] [INFO] [30101] Received COMMIT: id:1741323542381, from:30020, delay:0.0001s, distance:151.61m (Euclidean)
[2025-03-07 13:59:10,863] [INFO] [30101] Received COMMIT: id:1741323542381, from:30109, delay:0.0002s, distance:270.81m (Euclidean)
[2025-03-07 13:59:11,206] [INFO] [30101] Received PREPARE: id:1741323542381, from:30098, delay:0.0001s, distance:247.63m (Euclidean)
[2025-03-07 13:59:11,206] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,206] [INFO] [30101] Received COMMIT: id:1741323542381, from:30098, delay:0.0001s, distance:247.63m (Euclidean)
[2025-03-07 13:59:11,260] [INFO] [30101] Received PREPARE: id:1741323542381, from:30092, delay:0.0001s, distance:236.68m (Euclidean)
[2025-03-07 13:59:11,260] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,262] [INFO] [30101] Received COMMIT: id:1741323542381, from:30092, delay:0.0001s, distance:236.68m (Euclidean)
[2025-03-07 13:59:11,323] [INFO] [30101] Received PREPARE: id:1741323542381, from:30057, delay:0.0001s, distance:185.39m (Euclidean)
[2025-03-07 13:59:11,323] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,323] [INFO] [30101] Received COMMIT: id:1741323542381, from:30057, delay:0.0001s, distance:185.39m (Euclidean)
[2025-03-07 13:59:11,637] [INFO] [30101] Received PREPARE: id:1741323542381, from:30090, delay:0.0001s, distance:212.64m (Euclidean)
[2025-03-07 13:59:11,637] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,640] [INFO] [30101] Received COMMIT: id:1741323542381, from:30090, delay:0.0001s, distance:212.64m (Euclidean)
[2025-03-07 13:59:11,885] [INFO] [30101] Received PREPARE: id:1741323542381, from:30085, delay:0.0001s, distance:222.15m (Euclidean)
[2025-03-07 13:59:11,885] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,885] [INFO] [30101] Received COMMIT: id:1741323542381, from:30085, delay:0.0001s, distance:222.15m (Euclidean)
[2025-03-07 13:59:11,917] [INFO] [30101] Received PREPARE: id:1741323542381, from:30116, delay:0.0001s, distance:228.87m (Euclidean)
[2025-03-07 13:59:11,917] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,917] [INFO] [30101] Received COMMIT: id:1741323542381, from:30116, delay:0.0001s, distance:228.87m (Euclidean)
[2025-03-07 13:59:12,627] [INFO] [30101] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:198.40m (Euclidean)
[2025-03-07 13:59:12,627] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,629] [INFO] [30101] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:198.40m (Euclidean)
[2025-03-07 13:59:12,708] [INFO] [30101] Received PREPARE: id:1741323542381, from:30194, delay:0.0000s, distance:134.92m (Euclidean)
[2025-03-07 13:59:12,708] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,817] [INFO] [30101] Received COMMIT: id:1741323542381, from:30194, delay:0.0000s, distance:134.92m (Euclidean)
[2025-03-07 13:59:12,824] [INFO] [30101] Received PREPARE: id:1741323542381, from:30134, delay:0.0000s, distance:127.41m (Euclidean)
[2025-03-07 13:59:12,824] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,895] [INFO] [30101] Received PREPARE: id:1741323542381, from:30026, delay:0.0000s, distance:113.01m (Euclidean)
[2025-03-07 13:59:12,895] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,098] [INFO] [30101] Received PREPARE: id:1741323542381, from:30061, delay:0.0001s, distance:153.63m (Euclidean)
[2025-03-07 13:59:13,098] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,098] [INFO] [30101] Received COMMIT: id:1741323542381, from:30061, delay:0.0001s, distance:153.63m (Euclidean)
[2025-03-07 13:59:13,134] [INFO] [30101] Received COMMIT: id:1741323542381, from:30026, delay:0.0000s, distance:113.01m (Euclidean)
[2025-03-07 13:59:13,264] [INFO] [30101] Received PREPARE: id:1741323542381, from:30198, delay:0.0000s, distance:146.39m (Euclidean)
[2025-03-07 13:59:13,264] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,327] [INFO] [30101] Received PREPARE: id:1741323542381, from:30011, delay:0.0001s, distance:233.30m (Euclidean)
[2025-03-07 13:59:13,327] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,332] [INFO] [30101] Received COMMIT: id:1741323542381, from:30011, delay:0.0001s, distance:233.30m (Euclidean)
[2025-03-07 13:59:13,480] [INFO] [30101] Received PREPARE: id:1741323542381, from:30064, delay:0.0000s, distance:130.15m (Euclidean)
[2025-03-07 13:59:13,480] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,622] [INFO] [30101] Received PREPARE: id:1741323542381, from:30010, delay:0.0000s, distance:145.50m (Euclidean)
[2025-03-07 13:59:13,622] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,622] [INFO] [30101] Received COMMIT: id:1741323542381, from:30010, delay:0.0000s, distance:145.50m (Euclidean)
[2025-03-07 13:59:13,717] [INFO] [30101] Received PREPARE: id:1741323542381, from:30086, delay:0.0001s, distance:238.97m (Euclidean)
[2025-03-07 13:59:13,717] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,717] [INFO] [30101] Received COMMIT: id:1741323542381, from:30086, delay:0.0001s, distance:238.97m (Euclidean)
[2025-03-07 13:59:13,742] [INFO] [30101] Received PREPARE: id:1741323542381, from:30067, delay:0.0002s, distance:297.91m (Euclidean)
[2025-03-07 13:59:13,742] [INFO] [30101] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:13,742] [INFO] [30101] Received COMMIT: id:1741323542381, from:30067, delay:0.0002s, distance:297.91m (Euclidean)
[2025-03-07 13:59:13,759] [INFO] [30101] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0000s, distance:174.01m (Euclidean)
[2025-03-07 13:59:13,759] [INFO] [30101] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:13,767] [INFO] [30101] Not broadcasting to fault node: 30077
[2025-03-07 13:59:13,777] [INFO] [30101] Not broadcasting to fault node: 30184
[2025-03-07 13:59:13,868] [INFO] [30101] Received PREPARE: id:1741323542381, from:30050, delay:0.0001s, distance:244.91m (Euclidean)
[2025-03-07 13:59:13,868] [INFO] [30101] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:13,875] [INFO] [30101] Not broadcasting to fault node: 30077
[2025-03-07 13:59:13,897] [INFO] [30101] Not broadcasting to fault node: 30184
[2025-03-07 13:59:14,061] [INFO] [30101] Received PREPARE: id:1741323542381, from:30137, delay:0.0000s, distance:143.76m (Euclidean)
[2025-03-07 13:59:14,122] [INFO] [30101] Received PREPARE: id:1741323542381, from:30104, delay:0.0000s, distance:150.86m (Euclidean)
[2025-03-07 13:59:14,144] [INFO] [30101] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:144.47m (Euclidean)
[2025-03-07 13:59:14,144] [INFO] [30101] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:144.47m (Euclidean)
[2025-03-07 13:59:14,286] [INFO] [30101] Received PREPARE: id:1741323542381, from:30160, delay:0.0000s, distance:131.82m (Euclidean)
[2025-03-07 13:59:14,574] [INFO] [30101] Received PREPARE: id:1741323542381, from:30132, delay:0.0001s, distance:195.62m (Euclidean)
[2025-03-07 13:59:14,574] [INFO] [30101] Received COMMIT: id:1741323542381, from:30132, delay:0.0001s, distance:195.62m (Euclidean)
[2025-03-07 13:59:14,666] [INFO] [30101] Received PREPARE: id:1741323542381, from:30141, delay:0.0000s, distance:71.02m (Euclidean)
[2025-03-07 13:59:15,643] [INFO] [30101] Received COMMIT: id:1741323542381, from:30104, delay:0.0000s, distance:150.86m (Euclidean)
[2025-03-07 13:59:15,643] [INFO] [30101] Received COMMIT: id:1741323542381, from:30137, delay:0.0000s, distance:143.76m (Euclidean)
[2025-03-07 13:59:15,643] [INFO] [30101] Received COMMIT: id:1741323542381, from:30134, delay:0.0000s, distance:127.41m (Euclidean)
[2025-03-07 13:59:15,643] [INFO] [30101] Received COMMIT: id:1741323542381, from:30198, delay:0.0000s, distance:146.39m (Euclidean)
[2025-03-07 13:59:15,722] [INFO] [30101] Received COMMIT: id:1741323542381, from:30141, delay:0.0000s, distance:71.02m (Euclidean)
[2025-03-07 13:59:15,727] [INFO] [30101] Received PREPARE: id:1741323542381, from:30117, delay:0.0001s, distance:155.40m (Euclidean)
[2025-03-07 13:59:15,727] [INFO] [30101] Received PREPARE: id:1741323542381, from:30016, delay:0.0000s, distance:140.97m (Euclidean)
[2025-03-07 13:59:15,727] [INFO] [30101] Received COMMIT: id:1741323542381, from:30016, delay:0.0000s, distance:140.97m (Euclidean)
[2025-03-07 13:59:15,727] [INFO] [30101] Received PREPARE: id:1741323542381, from:30081, delay:0.0000s, distance:28.15m (Euclidean)
[2025-03-07 13:59:15,727] [INFO] [30101] Received COMMIT: id:1741323542381, from:30081, delay:0.0000s, distance:28.15m (Euclidean)
[2025-03-07 13:59:15,727] [INFO] [30101] Received PREPARE: id:1741323542381, from:30055, delay:0.0000s, distance:125.75m (Euclidean)
[2025-03-07 13:59:15,727] [INFO] [30101] Received COMMIT: id:1741323542381, from:30055, delay:0.0000s, distance:125.75m (Euclidean)
[2025-03-07 13:59:15,729] [INFO] [30101] Received PREPARE: id:1741323542381, from:30019, delay:0.0002s, distance:252.74m (Euclidean)
[2025-03-07 13:59:15,729] [INFO] [30101] Received COMMIT: id:1741323542381, from:30019, delay:0.0002s, distance:252.74m (Euclidean)
[2025-03-07 13:59:15,729] [INFO] [30101] Received PREPARE: id:1741323542381, from:30069, delay:0.0001s, distance:242.12m (Euclidean)
[2025-03-07 13:59:15,729] [INFO] [30101] Received COMMIT: id:1741323542381, from:30050, delay:0.0001s, distance:244.91m (Euclidean)
[2025-03-07 13:59:15,729] [INFO] [30101] Received PREPARE: id:1741323542381, from:30105, delay:0.0001s, distance:190.70m (Euclidean)
[2025-03-07 13:59:15,729] [INFO] [30101] Received PREPARE: id:1741323542381, from:30143, delay:0.0001s, distance:223.12m (Euclidean)
[2025-03-07 13:59:16,189] [INFO] [30101] Received COMMIT: id:1741323542381, from:30143, delay:0.0001s, distance:223.12m (Euclidean)
[2025-03-07 13:59:16,733] [INFO] [30101] Received PREPARE: id:1741323542381, from:30036, delay:0.0001s, distance:247.74m (Euclidean)
[2025-03-07 13:59:16,795] [INFO] [30101] Received COMMIT: id:1741323542381, from:30064, delay:0.0000s, distance:130.15m (Euclidean)
[2025-03-07 13:59:16,860] [INFO] [30101] Received COMMIT: id:1741323542381, from:30069, delay:0.0001s, distance:242.12m (Euclidean)
[2025-03-07 13:59:16,922] [INFO] [30101] Received COMMIT: id:1741323542381, from:30160, delay:0.0000s, distance:131.82m (Euclidean)
[2025-03-07 13:59:16,967] [INFO] [30101] Received PREPARE: id:1741323542381, from:30165, delay:0.0002s, distance:250.83m (Euclidean)
[2025-03-07 13:59:16,967] [INFO] [30101] Received COMMIT: id:1741323542381, from:30165, delay:0.0002s, distance:250.83m (Euclidean)
[2025-03-07 13:59:17,009] [INFO] [30101] Received PREPARE: id:1741323542381, from:30159, delay:0.0000s, distance:126.51m (Euclidean)
[2025-03-07 13:59:17,043] [INFO] [30101] Received COMMIT: id:1741323542381, from:30159, delay:0.0000s, distance:126.51m (Euclidean)
[2025-03-07 13:59:17,070] [INFO] [30101] Received PREPARE: id:1741323542381, from:30140, delay:0.0002s, distance:255.86m (Euclidean)
[2025-03-07 13:59:17,070] [INFO] [30101] Received COMMIT: id:1741323542381, from:30140, delay:0.0002s, distance:255.86m (Euclidean)
[2025-03-07 13:59:17,130] [INFO] [30101] Received PREPARE: id:1741323542381, from:30188, delay:0.0002s, distance:263.13m (Euclidean)
[2025-03-07 13:59:17,130] [INFO] [30101] Received COMMIT: id:1741323542381, from:30188, delay:0.0002s, distance:263.13m (Euclidean)
[2025-03-07 13:59:17,299] [INFO] [30101] Received PREPARE: id:1741323542381, from:30031, delay:0.0001s, distance:227.36m (Euclidean)
[2025-03-07 13:59:17,300] [INFO] [30101] Received COMMIT: id:1741323542381, from:30091, delay:0.0001s, distance:236.46m (Euclidean)
[2025-03-07 13:59:17,300] [INFO] [30101] Received PREPARE: id:1741323542381, from:30091, delay:0.0001s, distance:236.46m (Euclidean)
[2025-03-07 13:59:17,300] [INFO] [30101] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:168.82m (Euclidean)
[2025-03-07 13:59:17,300] [INFO] [30101] Received COMMIT: id:1741323542381, from:30031, delay:0.0001s, distance:227.36m (Euclidean)
[2025-03-07 13:59:17,544] [INFO] [30101] Received PREPARE: id:1741323542381, from:30122, delay:0.0002s, distance:270.39m (Euclidean)
[2025-03-07 13:59:17,553] [INFO] [30101] Received COMMIT: id:1741323542381, from:30122, delay:0.0002s, distance:270.39m (Euclidean)
[2025-03-07 13:59:17,993] [INFO] [30101] Received PREPARE: id:1741323542381, from:30068, delay:0.0001s, distance:224.88m (Euclidean)
[2025-03-07 13:59:18,003] [INFO] [30101] Received PREPARE: id:1741323542381, from:30114, delay:0.0002s, distance:261.42m (Euclidean)
[2025-03-07 13:59:18,003] [INFO] [30101] Received COMMIT: id:1741323542381, from:30114, delay:0.0002s, distance:261.42m (Euclidean)
[2025-03-07 13:59:18,243] [INFO] [30101] Received PREPARE: id:1741323542381, from:30087, delay:0.0002s, distance:291.15m (Euclidean)
[2025-03-07 13:59:18,243] [INFO] [30101] Received COMMIT: id:1741323542381, from:30087, delay:0.0002s, distance:291.15m (Euclidean)
[2025-03-07 13:59:18,506] [INFO] [30101] Received PREPARE: id:1741323542381, from:30003, delay:0.0002s, distance:286.64m (Euclidean)
[2025-03-07 13:59:18,506] [INFO] [30101] Received COMMIT: id:1741323542381, from:30117, delay:0.0001s, distance:155.40m (Euclidean)
[2025-03-07 13:59:18,506] [INFO] [30101] Received COMMIT: id:1741323542381, from:30003, delay:0.0002s, distance:286.64m (Euclidean)
[2025-03-07 13:59:18,544] [INFO] [30101] Received PREPARE: id:1741323542381, from:30008, delay:0.0000s, distance:163.83m (Euclidean)
[2025-03-07 13:59:18,597] [INFO] [30101] Received COMMIT: id:1741323542381, from:30008, delay:0.0000s, distance:163.83m (Euclidean)
[2025-03-07 13:59:18,623] [INFO] [30101] Received COMMIT: id:1741323542381, from:30036, delay:0.0001s, distance:247.74m (Euclidean)
[2025-03-07 13:59:18,867] [INFO] [30101] Received PREPARE: id:1741323542381, from:30197, delay:0.0002s, distance:295.16m (Euclidean)
[2025-03-07 13:59:18,914] [INFO] [30101] Received COMMIT: id:1741323542381, from:30197, delay:0.0002s, distance:295.16m (Euclidean)
[2025-03-07 13:59:19,295] [INFO] [30101] Received PREPARE: id:1741323542381, from:30079, delay:0.0002s, distance:284.56m (Euclidean)
[2025-03-07 13:59:19,340] [INFO] [30101] Received COMMIT: id:1741323542381, from:30079, delay:0.0002s, distance:284.56m (Euclidean)
[2025-03-07 13:59:19,801] [INFO] [30101] Received PREPARE: id:1741323542381, from:30083, delay:0.0000s, distance:110.07m (Euclidean)
[2025-03-07 13:59:19,801] [INFO] [30101] Received COMMIT: id:1741323542381, from:30105, delay:0.0001s, distance:190.70m (Euclidean)
[2025-03-07 13:59:19,803] [INFO] [30101] Received PREPARE: id:1741323542381, from:30038, delay:0.0001s, distance:155.00m (Euclidean)
[2025-03-07 13:59:19,803] [INFO] [30101] Received COMMIT: id:1741323542381, from:30083, delay:0.0000s, distance:110.07m (Euclidean)
[2025-03-07 13:59:20,068] [INFO] [30101] Received PREPARE: id:1741323542381, from:30052, delay:0.0002s, distance:261.86m (Euclidean)
[2025-03-07 13:59:20,081] [INFO] [30101] Received COMMIT: id:1741323542381, from:30052, delay:0.0002s, distance:261.86m (Euclidean)
[2025-03-07 13:59:20,311] [INFO] [30101] Received PREPARE: id:1741323542381, from:30173, delay:0.0001s, distance:230.47m (Euclidean)
[2025-03-07 13:59:20,321] [INFO] [30101] Received COMMIT: id:1741323542381, from:30173, delay:0.0001s, distance:230.47m (Euclidean)
[2025-03-07 13:59:20,409] [INFO] [30101] Received PREPARE: id:1741323542381, from:30042, delay:0.0001s, distance:217.55m (Euclidean)
[2025-03-07 13:59:20,420] [INFO] [30101] Received COMMIT: id:1741323542381, from:30042, delay:0.0001s, distance:217.55m (Euclidean)
[2025-03-07 13:59:20,451] [INFO] [30101] Received COMMIT: id:1741323542381, from:30068, delay:0.0001s, distance:224.88m (Euclidean)
[2025-03-07 13:59:20,618] [INFO] [30101] Received PREPARE: id:1741323542381, from:30039, delay:0.0001s, distance:232.94m (Euclidean)
[2025-03-07 13:59:20,620] [INFO] [30101] Received COMMIT: id:1741323542381, from:30039, delay:0.0001s, distance:232.94m (Euclidean)
[2025-03-07 13:59:20,648] [INFO] [30101] Received PREPARE: id:1741323542381, from:30131, delay:0.0002s, distance:274.18m (Euclidean)
[2025-03-07 13:59:20,648] [INFO] [30101] Received COMMIT: id:1741323542381, from:30131, delay:0.0002s, distance:274.18m (Euclidean)
[2025-03-07 13:59:20,648] [INFO] [30101] Received COMMIT: id:1741323542381, from:30000, delay:0.0000s, distance:174.01m (Euclidean)
[2025-03-07 13:59:20,679] [INFO] [30101] Received PREPARE: id:1741323542381, from:30142, delay:0.0002s, distance:262.76m (Euclidean)
[2025-03-07 13:59:20,822] [INFO] [30101] Received PREPARE: id:1741323542381, from:30138, delay:0.0002s, distance:253.85m (Euclidean)
[2025-03-07 13:59:20,822] [INFO] [30101] Received COMMIT: id:1741323542381, from:30138, delay:0.0002s, distance:253.85m (Euclidean)
[2025-03-07 13:59:20,958] [INFO] [30101] Received PREPARE: id:1741323542381, from:30166, delay:0.0002s, distance:256.25m (Euclidean)
[2025-03-07 13:59:20,960] [INFO] [30101] Received COMMIT: id:1741323542381, from:30166, delay:0.0002s, distance:256.25m (Euclidean)
[2025-03-07 13:59:20,960] [INFO] [30101] Received COMMIT: id:1741323542381, from:30142, delay:0.0002s, distance:262.76m (Euclidean)
[2025-03-07 13:59:22,008] [INFO] [30101] Received COMMIT: id:1741323542381, from:30038, delay:0.0001s, distance:155.00m (Euclidean)
[2025-03-07 13:59:22,548] [INFO] [30101] Received PREPARE: id:1741323542381, from:30009, delay:0.0001s, distance:157.36m (Euclidean)
[2025-03-07 13:59:22,548] [INFO] [30101] Received COMMIT: id:1741323542381, from:30009, delay:0.0001s, distance:157.36m (Euclidean)
[2025-03-07 13:59:23,023] [INFO] [30101] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:168.82m (Euclidean)
[2025-03-07 13:59:23,356] [INFO] [30101] Received PREPARE: id:1741323542381, from:30001, delay:0.0002s, distance:259.78m (Euclidean)
[2025-03-07 13:59:23,356] [INFO] [30101] Received COMMIT: id:1741323542381, from:30001, delay:0.0002s, distance:259.78m (Euclidean)
[2025-03-07 13:59:23,611] [INFO] [30101] Received PREPARE: id:1741323542381, from:30071, delay:0.0002s, distance:280.65m (Euclidean)
[2025-03-07 13:59:23,611] [INFO] [30101] Received COMMIT: id:1741323542381, from:30071, delay:0.0002s, distance:280.65m (Euclidean)
[2025-03-07 13:59:24,077] [INFO] [30101] Received PREPARE: id:1741323542381, from:30094, delay:0.0001s, distance:246.77m (Euclidean)
[2025-03-07 13:59:24,079] [INFO] [30101] Received COMMIT: id:1741323542381, from:30094, delay:0.0001s, distance:246.77m (Euclidean)
[2025-03-07 13:59:24,113] [INFO] [30101] Received PREPARE: id:1741323542381, from:30058, delay:0.0001s, distance:241.00m (Euclidean)
[2025-03-07 13:59:24,115] [INFO] [30101] Received COMMIT: id:1741323542381, from:30058, delay:0.0001s, distance:241.00m (Euclidean)
[2025-03-07 13:59:24,150] [INFO] [30101] Received PREPARE: id:1741323542381, from:30033, delay:0.0001s, distance:235.49m (Euclidean)
[2025-03-07 13:59:24,150] [INFO] [30101] Received COMMIT: id:1741323542381, from:30033, delay:0.0001s, distance:235.49m (Euclidean)
[2025-03-07 13:59:24,512] [INFO] [30101] Received PREPARE: id:1741323542381, from:30156, delay:0.0000s, distance:124.75m (Euclidean)
[2025-03-07 13:59:24,513] [INFO] [30101] Received COMMIT: id:1741323542381, from:30156, delay:0.0000s, distance:124.75m (Euclidean)
[2025-03-07 13:59:24,592] [INFO] [30101] Received PREPARE: id:1741323542381, from:30153, delay:0.0001s, distance:201.17m (Euclidean)
[2025-03-07 13:59:24,592] [INFO] [30101] Received COMMIT: id:1741323542381, from:30153, delay:0.0001s, distance:201.17m (Euclidean)
[2025-03-07 13:59:24,662] [INFO] [30101] Received PREPARE: id:1741323542381, from:30193, delay:0.0002s, distance:252.04m (Euclidean)
[2025-03-07 13:59:24,662] [INFO] [30101] Received COMMIT: id:1741323542381, from:30193, delay:0.0002s, distance:252.04m (Euclidean)
[2025-03-07 13:59:25,677] [INFO] [30101] Received PREPARE: id:1741323542381, from:30002, delay:0.0000s, distance:24.83m (Euclidean)
[2025-03-07 13:59:26,029] [INFO] [30101] Received PREPARE: id:1741323542381, from:30162, delay:0.0002s, distance:286.01m (Euclidean)
[2025-03-07 13:59:26,029] [INFO] [30101] Received COMMIT: id:1741323542381, from:30162, delay:0.0002s, distance:286.01m (Euclidean)
[2025-03-07 13:59:26,047] [INFO] [30101] Received PREPARE: id:1741323542381, from:30151, delay:0.0001s, distance:229.74m (Euclidean)
[2025-03-07 13:59:26,058] [INFO] [30101] Received COMMIT: id:1741323542381, from:30151, delay:0.0001s, distance:229.74m (Euclidean)
[2025-03-07 13:59:26,072] [INFO] [30101] Received PREPARE: id:1741323542381, from:30022, delay:0.0001s, distance:224.05m (Euclidean)
[2025-03-07 13:59:26,072] [INFO] [30101] Received COMMIT: id:1741323542381, from:30022, delay:0.0001s, distance:224.05m (Euclidean)
[2025-03-07 13:59:26,190] [INFO] [30101] Received PREPARE: id:1741323542381, from:30075, delay:0.0002s, distance:282.82m (Euclidean)
[2025-03-07 13:59:26,190] [INFO] [30101] Received COMMIT: id:1741323542381, from:30075, delay:0.0002s, distance:282.82m (Euclidean)
[2025-03-07 13:59:26,215] [INFO] [30101] Received PREPARE: id:1741323542381, from:30152, delay:0.0002s, distance:281.06m (Euclidean)
[2025-03-07 13:59:26,215] [INFO] [30101] Received COMMIT: id:1741323542381, from:30152, delay:0.0002s, distance:281.06m (Euclidean)
[2025-03-07 13:59:26,217] [INFO] [30101] Received PREPARE: id:1741323542381, from:30187, delay:0.0001s, distance:233.96m (Euclidean)
[2025-03-07 13:59:26,262] [INFO] [30101] Received COMMIT: id:1741323542381, from:30187, delay:0.0001s, distance:233.96m (Euclidean)
[2025-03-07 13:59:26,319] [INFO] [30101] Received PREPARE: id:1741323542381, from:30017, delay:0.0002s, distance:272.68m (Euclidean)
[2025-03-07 13:59:26,328] [INFO] [30101] Received COMMIT: id:1741323542381, from:30017, delay:0.0002s, distance:272.68m (Euclidean)
[2025-03-07 13:59:26,615] [INFO] [30101] Received PREPARE: id:1741323542381, from:30084, delay:0.0002s, distance:289.80m (Euclidean)
[2025-03-07 13:59:26,615] [INFO] [30101] Received COMMIT: id:1741323542381, from:30084, delay:0.0002s, distance:289.80m (Euclidean)
[2025-03-07 13:59:26,661] [INFO] [30101] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:103.92m (Euclidean)
[2025-03-07 13:59:26,661] [INFO] [30101] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:103.92m (Euclidean)
[2025-03-07 13:59:27,242] [INFO] [30101] Received PREPARE: id:1741323542381, from:30082, delay:0.0001s, distance:199.81m (Euclidean)
[2025-03-07 13:59:27,242] [INFO] [30101] Received COMMIT: id:1741323542381, from:30082, delay:0.0001s, distance:199.81m (Euclidean)
[2025-03-07 13:59:27,395] [INFO] [30101] Received PREPARE: id:1741323542381, from:30185, delay:0.0001s, distance:199.60m (Euclidean)
[2025-03-07 13:59:27,420] [INFO] [30101] Received COMMIT: id:1741323542381, from:30185, delay:0.0001s, distance:199.60m (Euclidean)
[2025-03-07 13:59:27,512] [INFO] [30101] Received PREPARE: id:1741323542381, from:30045, delay:0.0001s, distance:215.44m (Euclidean)
[2025-03-07 13:59:27,512] [INFO] [30101] Received COMMIT: id:1741323542381, from:30045, delay:0.0001s, distance:215.44m (Euclidean)
[2025-03-07 13:59:27,526] [INFO] [30101] Received PREPARE: id:1741323542381, from:30139, delay:0.0001s, distance:229.34m (Euclidean)
[2025-03-07 13:59:27,548] [INFO] [30101] Received COMMIT: id:1741323542381, from:30139, delay:0.0001s, distance:229.34m (Euclidean)
[2025-03-07 13:59:28,174] [INFO] [30101] Received PREPARE: id:1741323542381, from:30047, delay:0.0002s, distance:290.53m (Euclidean)
[2025-03-07 13:59:28,195] [INFO] [30101] Received COMMIT: id:1741323542381, from:30047, delay:0.0002s, distance:290.53m (Euclidean)
[2025-03-07 13:59:28,274] [INFO] [30101] Received PREPARE: id:1741323542381, from:30163, delay:0.0001s, distance:191.11m (Euclidean)
[2025-03-07 13:59:28,310] [INFO] [30101] Received COMMIT: id:1741323542381, from:30163, delay:0.0001s, distance:191.11m (Euclidean)
[2025-03-07 13:59:28,413] [INFO] [30101] Received COMMIT: id:1741323542381, from:30002, delay:0.0000s, distance:24.83m (Euclidean)
[2025-03-07 13:59:28,959] [INFO] [30101] Received PREPARE: id:1741323542381, from:30078, delay:0.0002s, distance:298.71m (Euclidean)
[2025-03-07 13:59:33,328] [INFO] [30101] Received PREPARE: id:1741323542381, from:30018, delay:0.0001s, distance:213.68m (Euclidean)
[2025-03-07 13:59:36,956] [INFO] [30101] Received COMMIT: id:1741323542381, from:30018, delay:0.0001s, distance:213.68m (Euclidean)
[2025-03-07 13:59:37,291] [INFO] [30101] Received PREPARE: id:1741323542381, from:30030, delay:0.0001s, distance:206.06m (Euclidean)
[2025-03-07 13:59:38,074] [INFO] [30101] Received COMMIT: id:1741323542381, from:30030, delay:0.0001s, distance:206.06m (Euclidean)
[2025-03-07 13:59:38,287] [INFO] [30101] Received PREPARE: id:1741323542381, from:30044, delay:0.0001s, distance:232.77m (Euclidean)
[2025-03-07 13:59:38,326] [INFO] [30101] Received COMMIT: id:1741323542381, from:30044, delay:0.0001s, distance:232.77m (Euclidean)
[2025-03-07 13:59:38,340] [INFO] [30101] Received COMMIT: id:1741323542381, from:30078, delay:0.0002s, distance:298.71m (Euclidean)
[2025-03-07 13:59:38,363] [INFO] [30101] Received PREPARE: id:1741323542381, from:30097, delay:0.0000s, distance:139.09m (Euclidean)
[2025-03-07 13:59:38,502] [INFO] [30101] Received COMMIT: id:1741323542381, from:30097, delay:0.0000s, distance:139.09m (Euclidean)
[2025-03-07 13:59:38,526] [INFO] [30101] Received COMMIT: id:1741323542381, from:30183, delay:0.0002s, distance:281.62m (Euclidean)
[2025-03-07 13:59:38,531] [INFO] [30101] Received PREPARE: id:1741323542381, from:30192, delay:0.0001s, distance:241.92m (Euclidean)
[2025-03-07 13:59:38,543] [INFO] [30101] Received PREPARE: id:1741323542381, from:30164, delay:0.0002s, distance:280.39m (Euclidean)
[2025-03-07 13:59:38,664] [INFO] [30101] Received COMMIT: id:1741323542381, from:30192, delay:0.0001s, distance:241.92m (Euclidean)
[2025-03-07 13:59:38,675] [INFO] [30101] Received COMMIT: id:1741323542381, from:30164, delay:0.0002s, distance:280.39m (Euclidean)
