[2025-03-07 13:53:33,083] [INFO] Starting node at localhost:30151 | index=152 | f=1, k=4 | Role: Replica
[2025-03-07 13:53:39,183] [INFO] [30151] Received PREPARE: id:1741323218379, from:30096, delay:0.0000s, distance:299.29m (Euclidean)
[2025-03-07 13:53:39,183] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,440] [INFO] [30151] Received PREPARE: id:1741323218379, from:30028, delay:0.0000s, distance:299.76m (Euclidean)
[2025-03-07 13:53:39,440] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,543] [INFO] [30151] Received COMMIT: id:1741323218379, from:30096, delay:0.0000s, distance:299.29m (Euclidean)
[2025-03-07 13:53:39,891] [INFO] [30151] Received PREPARE: id:1741323218379, from:30033, delay:0.0000s, distance:93.01m (Euclidean)
[2025-03-07 13:53:39,891] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:39,891] [INFO] [30151] Received COMMIT: id:1741323218379, from:30033, delay:0.0000s, distance:93.01m (Euclidean)
[2025-03-07 13:53:40,180] [INFO] [30151] Received PREPARE: id:1741323218379, from:30039, delay:0.0000s, distance:69.66m (Euclidean)
[2025-03-07 13:53:40,180] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,355] [INFO] [30151] Received PREPARE: id:1741323218379, from:30060, delay:0.0001s, distance:181.28m (Euclidean)
[2025-03-07 13:53:40,355] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,355] [INFO] [30151] Received COMMIT: id:1741323218379, from:30060, delay:0.0001s, distance:181.28m (Euclidean)
[2025-03-07 13:53:40,371] [INFO] [30151] Received COMMIT: id:1741323218379, from:30039, delay:0.0000s, distance:69.66m (Euclidean)
[2025-03-07 13:53:40,371] [INFO] [30151] Received PREPARE: id:1741323218379, from:30012, delay:0.0001s, distance:159.40m (Euclidean)
[2025-03-07 13:53:40,371] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,371] [INFO] [30151] Received COMMIT: id:1741323218379, from:30012, delay:0.0001s, distance:159.40m (Euclidean)
[2025-03-07 13:53:40,608] [INFO] [30151] Received COMMIT: id:1741323218379, from:30028, delay:0.0000s, distance:299.76m (Euclidean)
[2025-03-07 13:53:40,634] [INFO] [30151] Received PREPARE: id:1741323218379, from:30009, delay:0.0001s, distance:244.17m (Euclidean)
[2025-03-07 13:53:40,634] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,634] [INFO] [30151] Received COMMIT: id:1741323218379, from:30009, delay:0.0001s, distance:244.17m (Euclidean)
[2025-03-07 13:53:40,814] [INFO] [30151] Received PREPARE: id:1741323218379, from:30021, delay:0.0000s, distance:33.69m (Euclidean)
[2025-03-07 13:53:40,814] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:40,818] [INFO] [30151] Received COMMIT: id:1741323218379, from:30021, delay:0.0000s, distance:33.69m (Euclidean)
[2025-03-07 13:53:41,006] [INFO] [30151] Received PREPARE: id:1741323218379, from:30094, delay:0.0000s, distance:105.81m (Euclidean)
[2025-03-07 13:53:41,006] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,130] [INFO] [30151] Received PREPARE: id:1741323218379, from:30117, delay:0.0000s, distance:135.01m (Euclidean)
[2025-03-07 13:53:41,130] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:41,130] [INFO] [30151] Received COMMIT: id:1741323218379, from:30117, delay:0.0000s, distance:135.01m (Euclidean)
[2025-03-07 13:53:41,178] [INFO] [30151] Received PREPARE: id:1741323218379, from:30089, delay:0.0000s, distance:104.88m (Euclidean)
[2025-03-07 13:53:41,178] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,143] [INFO] [30151] Received PREPARE: id:1741323218379, from:30044, delay:0.0001s, distance:207.44m (Euclidean)
[2025-03-07 13:53:42,143] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,143] [INFO] [30151] Received COMMIT: id:1741323218379, from:30044, delay:0.0001s, distance:207.44m (Euclidean)
[2025-03-07 13:53:42,269] [INFO] [30151] Received PREPARE: id:1741323218379, from:30099, delay:0.0000s, distance:179.17m (Euclidean)
[2025-03-07 13:53:42,269] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,269] [INFO] [30151] Received COMMIT: id:1741323218379, from:30099, delay:0.0000s, distance:179.17m (Euclidean)
[2025-03-07 13:53:42,379] [INFO] [30151] Received PREPARE: id:1741323218379, from:30097, delay:0.0001s, distance:229.37m (Euclidean)
[2025-03-07 13:53:42,379] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,379] [INFO] [30151] Received COMMIT: id:1741323218379, from:30097, delay:0.0001s, distance:229.37m (Euclidean)
[2025-03-07 13:53:42,824] [INFO] [30151] Received PREPARE: id:1741323218379, from:30078, delay:0.0001s, distance:225.16m (Euclidean)
[2025-03-07 13:53:42,824] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,824] [INFO] [30151] Received PREPARE: id:1741323218379, from:30052, delay:0.0001s, distance:201.18m (Euclidean)
[2025-03-07 13:53:42,824] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:42,837] [INFO] [30151] Received COMMIT: id:1741323218379, from:30052, delay:0.0001s, distance:201.18m (Euclidean)
[2025-03-07 13:53:42,837] [INFO] [30151] Received COMMIT: id:1741323218379, from:30078, delay:0.0001s, distance:225.16m (Euclidean)
[2025-03-07 13:53:43,066] [INFO] [30151] Received COMMIT: id:1741323218379, from:30089, delay:0.0000s, distance:104.88m (Euclidean)
[2025-03-07 13:53:43,122] [INFO] [30151] Received PREPARE: id:1741323218379, from:30073, delay:0.0002s, distance:265.90m (Euclidean)
[2025-03-07 13:53:43,122] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,122] [INFO] [30151] Received PREPARE: id:1741323218379, from:30048, delay:0.0001s, distance:193.30m (Euclidean)
[2025-03-07 13:53:43,122] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,139] [INFO] [30151] Received COMMIT: id:1741323218379, from:30048, delay:0.0001s, distance:193.30m (Euclidean)
[2025-03-07 13:53:43,148] [INFO] [30151] Received COMMIT: id:1741323218379, from:30073, delay:0.0002s, distance:265.90m (Euclidean)
[2025-03-07 13:53:43,580] [INFO] [30151] Received PREPARE: id:1741323218379, from:30037, delay:0.0002s, distance:269.20m (Euclidean)
[2025-03-07 13:53:43,580] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,580] [INFO] [30151] Received COMMIT: id:1741323218379, from:30037, delay:0.0002s, distance:269.20m (Euclidean)
[2025-03-07 13:53:43,648] [INFO] [30151] Received PREPARE: id:1741323218379, from:30087, delay:0.0001s, distance:231.41m (Euclidean)
[2025-03-07 13:53:43,648] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:43,648] [INFO] [30151] Received COMMIT: id:1741323218379, from:30087, delay:0.0001s, distance:231.41m (Euclidean)
[2025-03-07 13:53:43,939] [INFO] [30151] Received PREPARE: id:1741323218379, from:30072, delay:0.0002s, distance:251.57m (Euclidean)
[2025-03-07 13:53:43,939] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,091] [INFO] [30151] Received COMMIT: id:1741323218379, from:30072, delay:0.0002s, distance:251.57m (Euclidean)
[2025-03-07 13:53:44,208] [INFO] [30151] Received COMMIT: id:1741323218379, from:30094, delay:0.0000s, distance:105.81m (Euclidean)
[2025-03-07 13:53:44,208] [INFO] [30151] Received PREPARE: id:1741323218379, from:30058, delay:0.0001s, distance:210.69m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,212] [INFO] [30151] Received PREPARE: id:1741323218379, from:30026, delay:0.0001s, distance:241.92m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,212] [INFO] [30151] Received PREPARE: id:1741323218379, from:30043, delay:0.0001s, distance:230.95m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,212] [INFO] [30151] Received COMMIT: id:1741323218379, from:30058, delay:0.0001s, distance:210.69m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Received COMMIT: id:1741323218379, from:30043, delay:0.0001s, distance:230.95m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Received COMMIT: id:1741323218379, from:30026, delay:0.0001s, distance:241.92m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Received COMMIT: id:1741323218379, from:30104, delay:0.0002s, distance:275.76m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Received PREPARE: id:1741323218379, from:30104, delay:0.0002s, distance:275.76m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,212] [INFO] [30151] Received PREPARE: id:1741323218379, from:30046, delay:0.0001s, distance:171.71m (Euclidean)
[2025-03-07 13:53:44,212] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,212] [INFO] [30151] Received COMMIT: id:1741323218379, from:30046, delay:0.0001s, distance:171.71m (Euclidean)
[2025-03-07 13:53:44,260] [INFO] [30151] Received PREPARE: id:1741323218379, from:30019, delay:0.0002s, distance:250.94m (Euclidean)
[2025-03-07 13:53:44,260] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,260] [INFO] [30151] Received PREPARE: id:1741323218379, from:30030, delay:0.0001s, distance:232.89m (Euclidean)
[2025-03-07 13:53:44,260] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,260] [INFO] [30151] Received COMMIT: id:1741323218379, from:30030, delay:0.0001s, distance:232.89m (Euclidean)
[2025-03-07 13:53:44,309] [INFO] [30151] Received COMMIT: id:1741323218379, from:30019, delay:0.0002s, distance:250.94m (Euclidean)
[2025-03-07 13:53:44,323] [INFO] [30151] Received PREPARE: id:1741323218379, from:30053, delay:0.0001s, distance:165.37m (Euclidean)
[2025-03-07 13:53:44,323] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,339] [INFO] [30151] Received COMMIT: id:1741323218379, from:30053, delay:0.0001s, distance:165.37m (Euclidean)
[2025-03-07 13:53:44,418] [INFO] [30151] Received PREPARE: id:1741323218379, from:30014, delay:0.0001s, distance:214.21m (Euclidean)
[2025-03-07 13:53:44,418] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,418] [INFO] [30151] Received PREPARE: id:1741323218379, from:30092, delay:0.0002s, distance:284.74m (Euclidean)
[2025-03-07 13:53:44,418] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,418] [INFO] [30151] Received COMMIT: id:1741323218379, from:30014, delay:0.0001s, distance:214.21m (Euclidean)
[2025-03-07 13:53:44,418] [INFO] [30151] Received COMMIT: id:1741323218379, from:30092, delay:0.0002s, distance:284.74m (Euclidean)
[2025-03-07 13:53:44,466] [INFO] [30151] Received PREPARE: id:1741323218379, from:30040, delay:0.0001s, distance:179.97m (Euclidean)
[2025-03-07 13:53:44,466] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,466] [INFO] [30151] Received COMMIT: id:1741323218379, from:30040, delay:0.0001s, distance:179.97m (Euclidean)
[2025-03-07 13:53:44,513] [INFO] [30151] Received PREPARE: id:1741323218379, from:30102, delay:0.0001s, distance:211.48m (Euclidean)
[2025-03-07 13:53:44,513] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,513] [INFO] [30151] Received COMMIT: id:1741323218379, from:30102, delay:0.0001s, distance:211.48m (Euclidean)
[2025-03-07 13:53:44,829] [INFO] [30151] Received PREPARE: id:1741323218379, from:30090, delay:0.0001s, distance:209.76m (Euclidean)
[2025-03-07 13:53:44,829] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,829] [INFO] [30151] Received COMMIT: id:1741323218379, from:30090, delay:0.0001s, distance:209.76m (Euclidean)
[2025-03-07 13:53:44,940] [INFO] [30151] Received PREPARE: id:1741323218379, from:30055, delay:0.0002s, distance:292.69m (Euclidean)
[2025-03-07 13:53:44,940] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:44,940] [INFO] [30151] Received COMMIT: id:1741323218379, from:30055, delay:0.0002s, distance:292.69m (Euclidean)
[2025-03-07 13:53:45,162] [INFO] [30151] Received PREPARE: id:1741323218379, from:30062, delay:0.0002s, distance:267.26m (Euclidean)
[2025-03-07 13:53:45,165] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,165] [INFO] [30151] Received COMMIT: id:1741323218379, from:30062, delay:0.0002s, distance:267.26m (Euclidean)
[2025-03-07 13:53:45,225] [INFO] [30151] Received PREPARE: id:1741323218379, from:30091, delay:0.0002s, distance:266.59m (Euclidean)
[2025-03-07 13:53:45,225] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,225] [INFO] [30151] Received COMMIT: id:1741323218379, from:30091, delay:0.0002s, distance:266.59m (Euclidean)
[2025-03-07 13:53:45,351] [INFO] [30151] Received PREPARE: id:1741323218379, from:30034, delay:0.0000s, distance:148.11m (Euclidean)
[2025-03-07 13:53:45,351] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,351] [INFO] [30151] Received COMMIT: id:1741323218379, from:30034, delay:0.0000s, distance:148.11m (Euclidean)
[2025-03-07 13:53:45,434] [INFO] [30151] Received PREPARE: id:1741323218379, from:30017, delay:0.0001s, distance:207.39m (Euclidean)
[2025-03-07 13:53:45,434] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,446] [INFO] [30151] Received COMMIT: id:1741323218379, from:30017, delay:0.0001s, distance:207.39m (Euclidean)
[2025-03-07 13:53:45,541] [INFO] [30151] Received PREPARE: id:1741323218379, from:30098, delay:0.0001s, distance:209.42m (Euclidean)
[2025-03-07 13:53:45,541] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,541] [INFO] [30151] Received COMMIT: id:1741323218379, from:30098, delay:0.0001s, distance:209.42m (Euclidean)
[2025-03-07 13:53:45,889] [INFO] [30151] Received PREPARE: id:1741323218379, from:30049, delay:0.0002s, distance:252.58m (Euclidean)
[2025-03-07 13:53:45,889] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,889] [INFO] [30151] Received COMMIT: id:1741323218379, from:30049, delay:0.0002s, distance:252.58m (Euclidean)
[2025-03-07 13:53:45,921] [INFO] [30151] Received PREPARE: id:1741323218379, from:30086, delay:0.0002s, distance:282.27m (Euclidean)
[2025-03-07 13:53:45,921] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:45,921] [INFO] [30151] Received COMMIT: id:1741323218379, from:30086, delay:0.0002s, distance:282.27m (Euclidean)
[2025-03-07 13:53:46,003] [INFO] [30151] Received PREPARE: id:1741323218379, from:30095, delay:0.0001s, distance:199.75m (Euclidean)
[2025-03-07 13:53:46,003] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,003] [INFO] [30151] Received COMMIT: id:1741323218379, from:30095, delay:0.0001s, distance:199.75m (Euclidean)
[2025-03-07 13:53:46,037] [INFO] [30151] Received PREPARE: id:1741323218379, from:30083, delay:0.0002s, distance:269.09m (Euclidean)
[2025-03-07 13:53:46,037] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,037] [INFO] [30151] Received COMMIT: id:1741323218379, from:30083, delay:0.0002s, distance:269.09m (Euclidean)
[2025-03-07 13:53:46,079] [INFO] [30151] Received PREPARE: id:1741323218379, from:30031, delay:0.0001s, distance:220.69m (Euclidean)
[2025-03-07 13:53:46,079] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,079] [INFO] [30151] Received COMMIT: id:1741323218379, from:30031, delay:0.0001s, distance:220.69m (Euclidean)
[2025-03-07 13:53:46,221] [INFO] [30151] Received PREPARE: id:1741323218379, from:30041, delay:0.0001s, distance:211.18m (Euclidean)
[2025-03-07 13:53:46,221] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,221] [INFO] [30151] Received COMMIT: id:1741323218379, from:30041, delay:0.0001s, distance:211.18m (Euclidean)
[2025-03-07 13:53:46,253] [INFO] [30151] Received PREPARE: id:1741323218379, from:30010, delay:0.0000s, distance:189.66m (Euclidean)
[2025-03-07 13:53:46,256] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,256] [INFO] [30151] Received COMMIT: id:1741323218379, from:30010, delay:0.0000s, distance:189.66m (Euclidean)
[2025-03-07 13:53:46,285] [INFO] [30151] Received PREPARE: id:1741323218379, from:30036, delay:0.0002s, distance:253.32m (Euclidean)
[2025-03-07 13:53:46,285] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,301] [INFO] [30151] Received COMMIT: id:1741323218379, from:30036, delay:0.0002s, distance:253.32m (Euclidean)
[2025-03-07 13:53:46,301] [INFO] [30151] Received COMMIT: id:1741323218379, from:30042, delay:0.0001s, distance:246.14m (Euclidean)
[2025-03-07 13:53:46,301] [INFO] [30151] Received PREPARE: id:1741323218379, from:30042, delay:0.0001s, distance:246.14m (Euclidean)
[2025-03-07 13:53:46,301] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,398] [INFO] [30151] Received PREPARE: id:1741323218379, from:30016, delay:0.0002s, distance:293.06m (Euclidean)
[2025-03-07 13:53:46,398] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,398] [INFO] [30151] Received COMMIT: id:1741323218379, from:30016, delay:0.0002s, distance:293.06m (Euclidean)
[2025-03-07 13:53:46,466] [INFO] [30151] Received PREPARE: id:1741323218379, from:30006, delay:0.0002s, distance:265.70m (Euclidean)
[2025-03-07 13:53:46,466] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,466] [INFO] [30151] Received COMMIT: id:1741323218379, from:30006, delay:0.0002s, distance:265.70m (Euclidean)
[2025-03-07 13:53:46,491] [INFO] [30151] Received PREPARE: id:1741323218379, from:30035, delay:0.0002s, distance:290.63m (Euclidean)
[2025-03-07 13:53:46,491] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,491] [INFO] [30151] Received COMMIT: id:1741323218379, from:30035, delay:0.0002s, distance:290.63m (Euclidean)
[2025-03-07 13:53:46,534] [INFO] [30151] Received PREPARE: id:1741323218379, from:30004, delay:0.0001s, distance:226.00m (Euclidean)
[2025-03-07 13:53:46,534] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,539] [INFO] [30151] Received COMMIT: id:1741323218379, from:30004, delay:0.0001s, distance:226.00m (Euclidean)
[2025-03-07 13:53:46,586] [INFO] [30151] Received PREPARE: id:1741323218379, from:30070, delay:0.0002s, distance:296.03m (Euclidean)
[2025-03-07 13:53:46,586] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,586] [INFO] [30151] Received COMMIT: id:1741323218379, from:30070, delay:0.0002s, distance:296.03m (Euclidean)
[2025-03-07 13:53:46,791] [INFO] [30151] Received PREPARE: id:1741323218379, from:30032, delay:0.0001s, distance:205.95m (Euclidean)
[2025-03-07 13:53:46,791] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,791] [INFO] [30151] Received COMMIT: id:1741323218379, from:30032, delay:0.0001s, distance:205.95m (Euclidean)
[2025-03-07 13:53:46,842] [INFO] [30151] Received PREPARE: id:1741323218379, from:30007, delay:0.0000s, distance:51.99m (Euclidean)
[2025-03-07 13:53:46,842] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,842] [INFO] [30151] Received COMMIT: id:1741323218379, from:30007, delay:0.0000s, distance:51.99m (Euclidean)
[2025-03-07 13:53:46,902] [INFO] [30151] Received PREPARE: id:1741323218379, from:30003, delay:0.0001s, distance:233.18m (Euclidean)
[2025-03-07 13:53:46,902] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:46,902] [INFO] [30151] Received COMMIT: id:1741323218379, from:30003, delay:0.0001s, distance:233.18m (Euclidean)
[2025-03-07 13:53:47,505] [INFO] [30151] Received PREPARE: id:1741323218379, from:30134, delay:0.0001s, distance:222.05m (Euclidean)
[2025-03-07 13:53:47,505] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,505] [INFO] [30151] Received COMMIT: id:1741323218379, from:30134, delay:0.0001s, distance:222.05m (Euclidean)
[2025-03-07 13:53:47,677] [INFO] [30151] Received PREPARE: id:1741323218379, from:30139, delay:0.0000s, distance:64.70m (Euclidean)
[2025-03-07 13:53:47,677] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,677] [INFO] [30151] Received COMMIT: id:1741323218379, from:30139, delay:0.0000s, distance:64.70m (Euclidean)
[2025-03-07 13:53:47,787] [INFO] [30151] Received PREPARE: id:1741323218379, from:30122, delay:0.0002s, distance:280.02m (Euclidean)
[2025-03-07 13:53:47,787] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,787] [INFO] [30151] Received COMMIT: id:1741323218379, from:30122, delay:0.0002s, distance:280.02m (Euclidean)
[2025-03-07 13:53:47,791] [INFO] [30151] Received PREPARE: id:1741323218379, from:30158, delay:0.0002s, distance:278.35m (Euclidean)
[2025-03-07 13:53:47,791] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,791] [INFO] [30151] Received COMMIT: id:1741323218379, from:30158, delay:0.0002s, distance:278.35m (Euclidean)
[2025-03-07 13:53:47,850] [INFO] [30151] Received PREPARE: id:1741323218379, from:30135, delay:0.0001s, distance:204.29m (Euclidean)
[2025-03-07 13:53:47,850] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,850] [INFO] [30151] Received COMMIT: id:1741323218379, from:30135, delay:0.0001s, distance:204.29m (Euclidean)
[2025-03-07 13:53:47,866] [INFO] [30151] Received PREPARE: id:1741323218379, from:30110, delay:0.0002s, distance:296.91m (Euclidean)
[2025-03-07 13:53:47,866] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:47,866] [INFO] [30151] Received COMMIT: id:1741323218379, from:30110, delay:0.0002s, distance:296.91m (Euclidean)
[2025-03-07 13:53:48,120] [INFO] [30151] Received PREPARE: id:1741323218379, from:30105, delay:0.0000s, distance:103.94m (Euclidean)
[2025-03-07 13:53:48,120] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,120] [INFO] [30151] Received COMMIT: id:1741323218379, from:30105, delay:0.0000s, distance:103.94m (Euclidean)
[2025-03-07 13:53:48,293] [INFO] [30151] Received PREPARE: id:1741323218379, from:30136, delay:0.0001s, distance:192.97m (Euclidean)
[2025-03-07 13:53:48,293] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,305] [INFO] [30151] Received COMMIT: id:1741323218379, from:30136, delay:0.0001s, distance:192.97m (Euclidean)
[2025-03-07 13:53:48,396] [INFO] [30151] Received PREPARE: id:1741323218379, from:30154, delay:0.0001s, distance:205.63m (Euclidean)
[2025-03-07 13:53:48,396] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,396] [INFO] [30151] Received COMMIT: id:1741323218379, from:30154, delay:0.0001s, distance:205.63m (Euclidean)
[2025-03-07 13:53:48,417] [INFO] [30151] Received PREPARE: id:1741323218379, from:30153, delay:0.0001s, distance:209.68m (Euclidean)
[2025-03-07 13:53:48,417] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323218379; ignoring PREPARE
[2025-03-07 13:53:48,417] [INFO] [30151] Received COMMIT: id:1741323218379, from:30153, delay:0.0001s, distance:209.68m (Euclidean)
[2025-03-07 13:53:48,455] [INFO] [30151] Received PRE-PREPARE: id:1741323218379, from:Leader(30000), delay:0.0001s, distance:214.77m (Euclidean)
[2025-03-07 13:53:48,455] [INFO] [30151] Broadcasting PREPARE for REQUEST 1741323218379
[2025-03-07 13:53:48,548] [INFO] [30151] Received PREPARE: id:1741323218379, from:30147, delay:0.0001s, distance:234.05m (Euclidean)
[2025-03-07 13:53:48,548] [INFO] [30151] Broadcasting COMMIT for REQUEST 1741323218379
[2025-03-07 13:53:48,563] [INFO] [30151] Received COMMIT: id:1741323218379, from:30147, delay:0.0001s, distance:234.05m (Euclidean)
[2025-03-07 13:53:48,612] [INFO] [30151] Received PREPARE: id:1741323218379, from:30109, delay:0.0001s, distance:160.66m (Euclidean)
[2025-03-07 13:53:48,641] [INFO] [30151] Received PREPARE: id:1741323218379, from:30157, delay:0.0001s, distance:235.90m (Euclidean)
[2025-03-07 13:53:48,646] [INFO] [30151] Received COMMIT: id:1741323218379, from:30157, delay:0.0001s, distance:235.90m (Euclidean)
[2025-03-07 13:53:48,709] [INFO] [30151] Received PREPARE: id:1741323218379, from:30131, delay:0.0001s, distance:228.72m (Euclidean)
[2025-03-07 13:53:48,709] [INFO] [30151] Received COMMIT: id:1741323218379, from:30131, delay:0.0001s, distance:228.72m (Euclidean)
[2025-03-07 13:53:48,715] [INFO] [30151] Received PREPARE: id:1741323218379, from:30128, delay:0.0001s, distance:213.29m (Euclidean)
[2025-03-07 13:53:48,717] [INFO] [30151] Received COMMIT: id:1741323218379, from:30128, delay:0.0001s, distance:213.29m (Euclidean)
[2025-03-07 13:53:48,735] [INFO] [30151] Received COMMIT: id:1741323218379, from:30109, delay:0.0001s, distance:160.66m (Euclidean)
[2025-03-07 13:53:48,853] [INFO] [30151] Received PREPARE: id:1741323218379, from:30107, delay:0.0000s, distance:102.17m (Euclidean)
[2025-03-07 13:53:49,012] [INFO] [30151] Received COMMIT: id:1741323218379, from:30107, delay:0.0000s, distance:102.17m (Euclidean)
[2025-03-07 13:53:49,288] [INFO] [30151] Received PREPARE: id:1741323218379, from:30133, delay:0.0002s, distance:272.27m (Euclidean)
[2025-03-07 13:53:49,320] [INFO] [30151] Received COMMIT: id:1741323218379, from:30133, delay:0.0002s, distance:272.27m (Euclidean)
[2025-03-07 13:53:49,407] [INFO] [30151] Received PREPARE: id:1741323218379, from:30144, delay:0.0002s, distance:298.59m (Euclidean)
[2025-03-07 13:53:49,447] [INFO] [30151] Received COMMIT: id:1741323218379, from:30144, delay:0.0002s, distance:298.59m (Euclidean)
[2025-03-07 13:53:49,639] [INFO] [30151] Received PREPARE: id:1741323218379, from:30112, delay:0.0002s, distance:252.02m (Euclidean)
[2025-03-07 13:53:49,639] [INFO] [30151] Received COMMIT: id:1741323218379, from:30112, delay:0.0002s, distance:252.02m (Euclidean)
[2025-03-07 13:53:50,175] [INFO] [30151] Received COMMIT: id:1741323218379, from:30000, delay:0.0001s, distance:214.77m (Euclidean)
[2025-03-07 13:53:50,175] [INFO] [30151] Received PREPARE: id:1741323218379, from:30114, delay:0.0002s, distance:272.85m (Euclidean)
[2025-03-07 13:53:50,175] [INFO] [30151] Received COMMIT: id:1741323218379, from:30114, delay:0.0002s, distance:272.85m (Euclidean)
[2025-03-07 13:53:50,467] [INFO] [30151] Received PREPARE: id:1741323218379, from:30142, delay:0.0000s, distance:249.20m (Euclidean)
[2025-03-07 13:53:50,469] [INFO] [30151] Received PREPARE: id:1741323218379, from:30121, delay:0.0000s, distance:92.49m (Euclidean)
[2025-03-07 13:53:51,157] [INFO] [30151] Received COMMIT: id:1741323218379, from:30142, delay:0.0000s, distance:249.20m (Euclidean)
[2025-03-07 13:53:51,266] [INFO] [30151] Received PREPARE: id:1741323218379, from:30146, delay:0.0000s, distance:299.31m (Euclidean)
[2025-03-07 13:53:51,393] [INFO] [30151] Received PREPARE: id:1741323218379, from:30130, delay:0.0002s, distance:259.17m (Euclidean)
[2025-03-07 13:53:51,393] [INFO] [30151] Received COMMIT: id:1741323218379, from:30130, delay:0.0002s, distance:259.17m (Euclidean)
[2025-03-07 13:53:51,440] [INFO] [30151] Received PREPARE: id:1741323218379, from:30119, delay:0.0002s, distance:292.54m (Euclidean)
[2025-03-07 13:53:51,440] [INFO] [30151] Received COMMIT: id:1741323218379, from:30119, delay:0.0002s, distance:292.54m (Euclidean)
[2025-03-07 13:53:51,440] [INFO] [30151] Received COMMIT: id:1741323218379, from:30015, delay:0.0002s, distance:265.03m (Euclidean)
[2025-03-07 13:53:51,440] [INFO] [30151] Received PREPARE: id:1741323218379, from:30015, delay:0.0002s, distance:265.03m (Euclidean)
[2025-03-07 13:53:51,678] [INFO] [30151] Received PREPARE: id:1741323218379, from:30116, delay:0.0001s, distance:184.69m (Euclidean)
[2025-03-07 13:53:51,678] [INFO] [30151] Received COMMIT: id:1741323218379, from:30116, delay:0.0001s, distance:184.69m (Euclidean)
[2025-03-07 13:53:51,852] [INFO] [30151] Received COMMIT: id:1741323218379, from:30121, delay:0.0000s, distance:92.49m (Euclidean)
[2025-03-07 13:53:52,449] [INFO] [30151] Received PREPARE: id:1741323218379, from:30129, delay:0.0001s, distance:234.77m (Euclidean)
[2025-03-07 13:53:52,449] [INFO] [30151] Received COMMIT: id:1741323218379, from:30129, delay:0.0001s, distance:234.77m (Euclidean)
[2025-03-07 13:53:52,655] [ERROR] [30151] Error sending to http://localhost:30143/prepare: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('127.0.0.1', 30143)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30143)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('127.0.0.1', 30143)]
[2025-03-07 13:53:52,687] [ERROR] [30151] Error sending to http://localhost:30143/commit: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('::1', 30143, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30143, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30143 ssl:default [Connect call failed ('::1', 30143, 0, 0)]
[2025-03-07 13:53:52,735] [ERROR] [30151] Error sending to http://localhost:30029/prepare: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30029)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('127.0.0.1', 30029)]
[2025-03-07 13:53:52,751] [ERROR] [30151] Error sending to http://localhost:30008/prepare: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30008)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('127.0.0.1', 30008)]
[2025-03-07 13:53:52,815] [ERROR] [30151] Error sending to http://localhost:30023/prepare: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30023)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('127.0.0.1', 30023)]
[2025-03-07 13:53:52,815] [ERROR] [30151] Error sending to http://localhost:30023/commit: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30023, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30023 ssl:default [Connect call failed ('::1', 30023, 0, 0)]
[2025-03-07 13:53:52,830] [ERROR] [30151] Error sending to http://localhost:30029/commit: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30029, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30029 ssl:default [Connect call failed ('::1', 30029, 0, 0)]
[2025-03-07 13:53:52,909] [ERROR] [30151] Error sending to http://localhost:30038/prepare: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('127.0.0.1', 30038)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30038)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('127.0.0.1', 30038)]
[2025-03-07 13:53:52,909] [INFO] [30151] Received PREPARE: id:1741323218379, from:30118, delay:0.0000s, distance:167.78m (Euclidean)
[2025-03-07 13:53:52,909] [INFO] [30151] Received COMMIT: id:1741323218379, from:30118, delay:0.0000s, distance:167.78m (Euclidean)
[2025-03-07 13:53:52,941] [ERROR] [30151] Error sending to http://localhost:30027/prepare: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30027)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('127.0.0.1', 30027)]
[2025-03-07 13:53:52,973] [ERROR] [30151] Error sending to http://localhost:30027/commit: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30027, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30027 ssl:default [Connect call failed ('::1', 30027, 0, 0)]
[2025-03-07 13:53:53,005] [ERROR] [30151] Error sending to http://localhost:30138/prepare: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30138)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('127.0.0.1', 30138)]
[2025-03-07 13:53:53,020] [ERROR] [30151] Error sending to http://localhost:30063/prepare: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30063)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
[2025-03-07 13:53:53,052] [ERROR] [30151] Error sending to http://localhost:30063/commit: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30063, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
[2025-03-07 13:53:53,052] [ERROR] [30151] Error sending to http://localhost:30124/prepare: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30124)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('127.0.0.1', 30124)]
[2025-03-07 13:53:53,068] [ERROR] [30151] Error sending to http://localhost:30101/prepare: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30101)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('127.0.0.1', 30101)]
[2025-03-07 13:53:53,116] [ERROR] [30151] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:53:53,147] [ERROR] [30151] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:53:53,147] [ERROR] [30151] Error sending to http://localhost:30124/commit: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30124, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30124 ssl:default [Connect call failed ('::1', 30124, 0, 0)]
[2025-03-07 13:53:53,163] [ERROR] [30151] Error sending to http://localhost:30101/commit: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30101, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30101 ssl:default [Connect call failed ('::1', 30101, 0, 0)]
[2025-03-07 13:53:53,194] [ERROR] [30151] Error sending to http://localhost:30076/prepare: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('127.0.0.1', 30076)]
[2025-03-07 13:53:53,196] [ERROR] [30151] Error sending to http://localhost:30075/prepare: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30075)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('127.0.0.1', 30075)]
[2025-03-07 13:53:53,226] [ERROR] [30151] Error sending to http://localhost:30076/commit: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30076, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30076 ssl:default [Connect call failed ('::1', 30076, 0, 0)]
[2025-03-07 13:53:53,226] [ERROR] [30151] Error sending to http://localhost:30066/prepare: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30066)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('127.0.0.1', 30066)]
[2025-03-07 13:53:53,226] [ERROR] [30151] Error sending to http://localhost:30138/commit: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30138, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30138 ssl:default [Connect call failed ('::1', 30138, 0, 0)]
[2025-03-07 13:53:53,242] [ERROR] [30151] Error sending to http://localhost:30066/commit: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30066, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30066 ssl:default [Connect call failed ('::1', 30066, 0, 0)]
[2025-03-07 13:53:53,242] [ERROR] [30151] Error sending to http://localhost:30125/prepare: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('127.0.0.1', 30125)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30125)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('127.0.0.1', 30125)]
[2025-03-07 13:53:53,274] [ERROR] [30151] Error sending to http://localhost:30125/commit: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('::1', 30125, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30125, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30125 ssl:default [Connect call failed ('::1', 30125, 0, 0)]
[2025-03-07 13:53:53,298] [INFO] [30151] Received PREPARE: id:1741323218379, from:30149, delay:0.0001s, distance:155.05m (Euclidean)
[2025-03-07 13:53:53,298] [INFO] [30151] Received COMMIT: id:1741323218379, from:30149, delay:0.0001s, distance:155.05m (Euclidean)
[2025-03-07 13:53:53,305] [ERROR] [30151] Error sending to http://localhost:30140/prepare: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('127.0.0.1', 30140)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30140)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('127.0.0.1', 30140)]
[2025-03-07 13:53:53,337] [ERROR] [30151] Error sending to http://localhost:30140/commit: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('::1', 30140, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30140, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30140 ssl:default [Connect call failed ('::1', 30140, 0, 0)]
[2025-03-07 13:53:53,368] [ERROR] [30151] Error sending to http://localhost:30064/prepare: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30064)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
[2025-03-07 13:53:53,384] [ERROR] [30151] Error sending to http://localhost:30038/commit: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('::1', 30038, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30038, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30038 ssl:default [Connect call failed ('::1', 30038, 0, 0)]
[2025-03-07 13:53:53,384] [ERROR] [30151] Error sending to http://localhost:30064/commit: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30064, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
[2025-03-07 13:53:53,400] [ERROR] [30151] Error sending to http://localhost:30008/commit: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30008, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30008 ssl:default [Connect call failed ('::1', 30008, 0, 0)]
[2025-03-07 13:53:53,416] [ERROR] [30151] Error sending to http://localhost:30137/prepare: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30137)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('127.0.0.1', 30137)]
[2025-03-07 13:53:53,432] [ERROR] [30151] Error sending to http://localhost:30075/commit: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30075, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30075 ssl:default [Connect call failed ('::1', 30075, 0, 0)]
[2025-03-07 13:53:53,432] [ERROR] [30151] Error sending to http://localhost:30137/commit: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30137, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30137 ssl:default [Connect call failed ('::1', 30137, 0, 0)]
[2025-03-07 13:53:53,711] [INFO] [30151] Received PREPARE: id:1741323218379, from:30123, delay:0.0002s, distance:253.84m (Euclidean)
[2025-03-07 13:53:53,711] [INFO] [30151] Received COMMIT: id:1741323218379, from:30123, delay:0.0002s, distance:253.84m (Euclidean)
[2025-03-07 13:53:53,828] [INFO] [30151] Received PREPARE: id:1741323218379, from:30111, delay:0.0000s, distance:182.14m (Euclidean)
[2025-03-07 13:53:53,828] [INFO] [30151] Received COMMIT: id:1741323218379, from:30111, delay:0.0000s, distance:182.14m (Euclidean)
[2025-03-07 13:53:53,831] [INFO] [30151] Received PREPARE: id:1741323218379, from:30127, delay:0.0002s, distance:263.79m (Euclidean)
[2025-03-07 13:53:53,844] [INFO] [30151] Received COMMIT: id:1741323218379, from:30127, delay:0.0002s, distance:263.79m (Euclidean)
[2025-03-07 13:53:53,933] [INFO] [30151] Received PREPARE: id:1741323218379, from:30106, delay:0.0000s, distance:67.84m (Euclidean)
[2025-03-07 13:53:53,944] [INFO] [30151] Received PREPARE: id:1741323218379, from:30113, delay:0.0000s, distance:194.60m (Euclidean)
[2025-03-07 13:53:53,944] [INFO] [30151] Received COMMIT: id:1741323218379, from:30113, delay:0.0000s, distance:194.60m (Euclidean)
[2025-03-07 13:53:53,970] [INFO] [30151] Received COMMIT: id:1741323218379, from:30146, delay:0.0000s, distance:299.31m (Euclidean)
[2025-03-07 13:53:54,041] [INFO] [30151] Received COMMIT: id:1741323218379, from:30106, delay:0.0000s, distance:67.84m (Euclidean)
[2025-03-07 13:53:54,066] [INFO] [30151] Received PREPARE: id:1741323218379, from:30120, delay:0.0002s, distance:269.90m (Euclidean)
[2025-03-07 13:53:54,066] [INFO] [30151] Received COMMIT: id:1741323218379, from:30120, delay:0.0002s, distance:269.90m (Euclidean)
[2025-03-07 13:53:54,224] [INFO] [30151] Received PREPARE: id:1741323218379, from:30159, delay:0.0001s, distance:236.65m (Euclidean)
[2025-03-07 13:53:54,224] [INFO] [30151] Received COMMIT: id:1741323218379, from:30159, delay:0.0001s, distance:236.65m (Euclidean)
[2025-03-07 13:53:54,239] [INFO] [30151] Received PREPARE: id:1741323218379, from:30132, delay:0.0002s, distance:275.63m (Euclidean)
[2025-03-07 13:53:54,246] [INFO] [30151] Received COMMIT: id:1741323218379, from:30132, delay:0.0002s, distance:275.63m (Euclidean)
[2025-03-07 13:53:54,356] [INFO] [30151] Received PREPARE: id:1741323218379, from:30150, delay:0.0002s, distance:269.70m (Euclidean)
[2025-03-07 13:53:54,365] [INFO] [30151] Received PREPARE: id:1741323218379, from:30152, delay:0.0001s, distance:209.74m (Euclidean)
[2025-03-07 13:53:54,387] [INFO] [30151] Received COMMIT: id:1741323218379, from:30150, delay:0.0002s, distance:269.70m (Euclidean)
[2025-03-07 13:53:54,511] [INFO] [30151] Received COMMIT: id:1741323218379, from:30152, delay:0.0001s, distance:209.74m (Euclidean)
[2025-03-07 13:53:54,533] [INFO] [30151] Received PREPARE: id:1741323218379, from:30115, delay:0.0000s, distance:191.29m (Euclidean)
[2025-03-07 13:53:54,543] [INFO] [30151] Received PREPARE: id:1741323218379, from:30156, delay:0.0001s, distance:218.93m (Euclidean)
[2025-03-07 13:53:54,546] [INFO] [30151] Received COMMIT: id:1741323218379, from:30115, delay:0.0000s, distance:191.29m (Euclidean)
[2025-03-07 13:53:54,554] [INFO] [30151] Received COMMIT: id:1741323218379, from:30156, delay:0.0001s, distance:218.93m (Euclidean)
[2025-03-07 13:53:55,658] [INFO] [30151] Received PREPARE: id:1741323218379, from:30022, delay:0.0000s, distance:47.30m (Euclidean)
[2025-03-07 13:53:55,669] [INFO] [30151] Received COMMIT: id:1741323218379, from:30022, delay:0.0000s, distance:47.30m (Euclidean)
[2025-03-07 13:54:58,072] [INFO] Starting node at localhost:30151 | index=152 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:44,524] [INFO] Starting node at localhost:30151 | index=152 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:46,929] [INFO] Starting node at localhost:30151 | index=152 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:03,075] [INFO] [30151] Received PREPARE: id:1741323542381, from:30040, delay:0.0000s, distance:200.62m (Euclidean)
[2025-03-07 13:59:03,075] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,538] [INFO] [30151] Received PREPARE: id:1741323542381, from:30196, delay:0.0001s, distance:158.84m (Euclidean)
[2025-03-07 13:59:03,538] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:03,583] [INFO] [30151] Received COMMIT: id:1741323542381, from:30040, delay:0.0000s, distance:200.62m (Euclidean)
[2025-03-07 13:59:03,880] [INFO] [30151] Received PREPARE: id:1741323542381, from:30126, delay:0.0000s, distance:65.49m (Euclidean)
[2025-03-07 13:59:03,880] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,081] [INFO] [30151] Received PREPARE: id:1741323542381, from:30116, delay:0.0000s, distance:5.86m (Euclidean)
[2025-03-07 13:59:04,081] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,170] [INFO] [30151] Received COMMIT: id:1741323542381, from:30126, delay:0.0000s, distance:65.49m (Euclidean)
[2025-03-07 13:59:04,179] [INFO] [30151] Received PREPARE: id:1741323542381, from:30128, delay:0.0001s, distance:209.76m (Euclidean)
[2025-03-07 13:59:04,179] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,316] [INFO] [30151] Received PREPARE: id:1741323542381, from:30110, delay:0.0000s, distance:98.87m (Euclidean)
[2025-03-07 13:59:04,316] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,322] [INFO] [30151] Received COMMIT: id:1741323542381, from:30110, delay:0.0000s, distance:98.87m (Euclidean)
[2025-03-07 13:59:04,411] [INFO] [30151] Received PREPARE: id:1741323542381, from:30037, delay:0.0001s, distance:186.95m (Euclidean)
[2025-03-07 13:59:04,411] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,485] [INFO] [30151] Received PREPARE: id:1741323542381, from:30180, delay:0.0001s, distance:210.71m (Euclidean)
[2025-03-07 13:59:04,485] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,485] [INFO] [30151] Received COMMIT: id:1741323542381, from:30180, delay:0.0001s, distance:210.71m (Euclidean)
[2025-03-07 13:59:04,531] [INFO] [30151] Received PREPARE: id:1741323542381, from:30144, delay:0.0001s, distance:202.63m (Euclidean)
[2025-03-07 13:59:04,531] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,654] [INFO] [30151] Received PREPARE: id:1741323542381, from:30098, delay:0.0000s, distance:65.79m (Euclidean)
[2025-03-07 13:59:04,654] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,662] [INFO] [30151] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:165.16m (Euclidean)
[2025-03-07 13:59:04,662] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,669] [INFO] [30151] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:165.16m (Euclidean)
[2025-03-07 13:59:04,693] [INFO] [30151] Received PREPARE: id:1741323542381, from:30147, delay:0.0001s, distance:193.50m (Euclidean)
[2025-03-07 13:59:04,693] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:04,699] [INFO] [30151] Received COMMIT: id:1741323542381, from:30147, delay:0.0001s, distance:193.50m (Euclidean)
[2025-03-07 13:59:04,868] [INFO] [30151] Received COMMIT: id:1741323542381, from:30128, delay:0.0001s, distance:209.76m (Euclidean)
[2025-03-07 13:59:05,014] [INFO] [30151] Received PREPARE: id:1741323542381, from:30115, delay:0.0001s, distance:190.51m (Euclidean)
[2025-03-07 13:59:05,014] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,072] [INFO] [30151] Received COMMIT: id:1741323542381, from:30144, delay:0.0001s, distance:202.63m (Euclidean)
[2025-03-07 13:59:05,152] [INFO] [30151] Received PREPARE: id:1741323542381, from:30028, delay:0.0001s, distance:247.54m (Euclidean)
[2025-03-07 13:59:05,152] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,158] [INFO] [30151] Received PREPARE: id:1741323542381, from:30181, delay:0.0001s, distance:179.40m (Euclidean)
[2025-03-07 13:59:05,158] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,266] [INFO] [30151] Received PREPARE: id:1741323542381, from:30057, delay:0.0000s, distance:132.53m (Euclidean)
[2025-03-07 13:59:05,268] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,328] [INFO] [30151] Received COMMIT: id:1741323542381, from:30057, delay:0.0000s, distance:132.53m (Euclidean)
[2025-03-07 13:59:05,385] [INFO] [30151] Received PREPARE: id:1741323542381, from:30095, delay:0.0000s, distance:69.04m (Euclidean)
[2025-03-07 13:59:05,385] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,516] [INFO] [30151] Received PREPARE: id:1741323542381, from:30112, delay:0.0000s, distance:111.58m (Euclidean)
[2025-03-07 13:59:05,516] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,836] [INFO] [30151] Received COMMIT: id:1741323542381, from:30095, delay:0.0000s, distance:69.04m (Euclidean)
[2025-03-07 13:59:05,836] [INFO] [30151] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:138.00m (Euclidean)
[2025-03-07 13:59:05,836] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:05,836] [INFO] [30151] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:138.00m (Euclidean)
[2025-03-07 13:59:05,843] [INFO] [30151] Received PREPARE: id:1741323542381, from:30199, delay:0.0001s, distance:202.53m (Euclidean)
[2025-03-07 13:59:05,843] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,012] [INFO] [30151] Received PREPARE: id:1741323542381, from:30123, delay:0.0001s, distance:157.01m (Euclidean)
[2025-03-07 13:59:06,012] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,012] [INFO] [30151] Received PREPARE: id:1741323542381, from:30121, delay:0.0000s, distance:132.12m (Euclidean)
[2025-03-07 13:59:06,012] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,012] [INFO] [30151] Received PREPARE: id:1741323542381, from:30005, delay:0.0001s, distance:234.64m (Euclidean)
[2025-03-07 13:59:06,012] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,012] [INFO] [30151] Received PREPARE: id:1741323542381, from:30182, delay:0.0001s, distance:201.12m (Euclidean)
[2025-03-07 13:59:06,013] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,013] [INFO] [30151] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:126.08m (Euclidean)
[2025-03-07 13:59:06,013] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,013] [INFO] [30151] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:126.08m (Euclidean)
[2025-03-07 13:59:06,028] [INFO] [30151] Received COMMIT: id:1741323542381, from:30005, delay:0.0001s, distance:234.64m (Euclidean)
[2025-03-07 13:59:06,108] [INFO] [30151] Received PREPARE: id:1741323542381, from:30130, delay:0.0001s, distance:201.51m (Euclidean)
[2025-03-07 13:59:06,108] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,207] [INFO] [30151] Received COMMIT: id:1741323542381, from:30121, delay:0.0000s, distance:132.12m (Euclidean)
[2025-03-07 13:59:06,264] [INFO] [30151] Received COMMIT: id:1741323542381, from:30123, delay:0.0001s, distance:157.01m (Euclidean)
[2025-03-07 13:59:06,314] [INFO] [30151] Received PREPARE: id:1741323542381, from:30063, delay:0.0000s, distance:140.19m (Euclidean)
[2025-03-07 13:59:06,316] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,325] [INFO] [30151] Received COMMIT: id:1741323542381, from:30116, delay:0.0000s, distance:5.86m (Euclidean)
[2025-03-07 13:59:06,345] [INFO] [30151] Received COMMIT: id:1741323542381, from:30182, delay:0.0001s, distance:201.12m (Euclidean)
[2025-03-07 13:59:06,359] [INFO] [30151] Received PREPARE: id:1741323542381, from:30170, delay:0.0000s, distance:85.74m (Euclidean)
[2025-03-07 13:59:06,359] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,379] [INFO] [30151] Received COMMIT: id:1741323542381, from:30028, delay:0.0001s, distance:247.54m (Euclidean)
[2025-03-07 13:59:06,415] [INFO] [30151] Received COMMIT: id:1741323542381, from:30098, delay:0.0000s, distance:65.79m (Euclidean)
[2025-03-07 13:59:06,415] [INFO] [30151] Received COMMIT: id:1741323542381, from:30170, delay:0.0000s, distance:85.74m (Euclidean)
[2025-03-07 13:59:06,452] [INFO] [30151] Received COMMIT: id:1741323542381, from:30199, delay:0.0001s, distance:202.53m (Euclidean)
[2025-03-07 13:59:06,486] [INFO] [30151] Received PREPARE: id:1741323542381, from:30060, delay:0.0001s, distance:172.82m (Euclidean)
[2025-03-07 13:59:06,486] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,531] [INFO] [30151] Received PREPARE: id:1741323542381, from:30056, delay:0.0000s, distance:74.65m (Euclidean)
[2025-03-07 13:59:06,531] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,531] [INFO] [30151] Received PREPARE: id:1741323542381, from:30013, delay:0.0000s, distance:141.93m (Euclidean)
[2025-03-07 13:59:06,531] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,531] [INFO] [30151] Received COMMIT: id:1741323542381, from:30013, delay:0.0000s, distance:141.93m (Euclidean)
[2025-03-07 13:59:06,531] [INFO] [30151] Received COMMIT: id:1741323542381, from:30063, delay:0.0000s, distance:140.19m (Euclidean)
[2025-03-07 13:59:06,586] [INFO] [30151] Received COMMIT: id:1741323542381, from:30037, delay:0.0001s, distance:186.95m (Euclidean)
[2025-03-07 13:59:06,610] [INFO] [30151] Received PREPARE: id:1741323542381, from:30027, delay:0.0001s, distance:219.00m (Euclidean)
[2025-03-07 13:59:06,610] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,612] [INFO] [30151] Received COMMIT: id:1741323542381, from:30115, delay:0.0001s, distance:190.51m (Euclidean)
[2025-03-07 13:59:06,612] [INFO] [30151] Received COMMIT: id:1741323542381, from:30027, delay:0.0001s, distance:219.00m (Euclidean)
[2025-03-07 13:59:06,623] [INFO] [30151] Received PREPARE: id:1741323542381, from:30113, delay:0.0000s, distance:168.62m (Euclidean)
[2025-03-07 13:59:06,623] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,710] [INFO] [30151] Received PREPARE: id:1741323542381, from:30102, delay:0.0000s, distance:140.34m (Euclidean)
[2025-03-07 13:59:06,710] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,710] [INFO] [30151] Received COMMIT: id:1741323542381, from:30113, delay:0.0000s, distance:168.62m (Euclidean)
[2025-03-07 13:59:06,716] [INFO] [30151] Received COMMIT: id:1741323542381, from:30060, delay:0.0001s, distance:172.82m (Euclidean)
[2025-03-07 13:59:06,751] [INFO] [30151] Received PREPARE: id:1741323542381, from:30062, delay:0.0001s, distance:192.60m (Euclidean)
[2025-03-07 13:59:06,751] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,769] [INFO] [30151] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:135.17m (Euclidean)
[2025-03-07 13:59:06,772] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,838] [INFO] [30151] Received PREPARE: id:1741323542381, from:30177, delay:0.0001s, distance:216.64m (Euclidean)
[2025-03-07 13:59:06,838] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,840] [INFO] [30151] Received PREPARE: id:1741323542381, from:30127, delay:0.0001s, distance:156.78m (Euclidean)
[2025-03-07 13:59:06,840] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,896] [INFO] [30151] Received PREPARE: id:1741323542381, from:30168, delay:0.0001s, distance:235.60m (Euclidean)
[2025-03-07 13:59:06,896] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:06,896] [INFO] [30151] Received COMMIT: id:1741323542381, from:30062, delay:0.0001s, distance:192.60m (Euclidean)
[2025-03-07 13:59:06,969] [INFO] [30151] Received COMMIT: id:1741323542381, from:30102, delay:0.0000s, distance:140.34m (Euclidean)
[2025-03-07 13:59:07,033] [INFO] [30151] Received PREPARE: id:1741323542381, from:30106, delay:0.0001s, distance:179.64m (Euclidean)
[2025-03-07 13:59:07,033] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,035] [INFO] [30151] Received COMMIT: id:1741323542381, from:30106, delay:0.0001s, distance:179.64m (Euclidean)
[2025-03-07 13:59:07,036] [INFO] [30151] Received COMMIT: id:1741323542381, from:30196, delay:0.0001s, distance:158.84m (Euclidean)
[2025-03-07 13:59:07,158] [INFO] [30151] Received COMMIT: id:1741323542381, from:30181, delay:0.0001s, distance:179.40m (Euclidean)
[2025-03-07 13:59:07,352] [INFO] [30151] Received PREPARE: id:1741323542381, from:30107, delay:0.0001s, distance:230.68m (Euclidean)
[2025-03-07 13:59:07,371] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,371] [INFO] [30151] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:143.38m (Euclidean)
[2025-03-07 13:59:07,373] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,384] [INFO] [30151] Received PREPARE: id:1741323542381, from:30191, delay:0.0001s, distance:228.43m (Euclidean)
[2025-03-07 13:59:07,384] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,384] [INFO] [30151] Received PREPARE: id:1741323542381, from:30020, delay:0.0001s, distance:167.30m (Euclidean)
[2025-03-07 13:59:07,384] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,384] [INFO] [30151] Received COMMIT: id:1741323542381, from:30020, delay:0.0001s, distance:167.30m (Euclidean)
[2025-03-07 13:59:07,516] [INFO] [30151] Received COMMIT: id:1741323542381, from:30168, delay:0.0001s, distance:235.60m (Euclidean)
[2025-03-07 13:59:07,526] [INFO] [30151] Received COMMIT: id:1741323542381, from:30107, delay:0.0001s, distance:230.68m (Euclidean)
[2025-03-07 13:59:07,557] [INFO] [30151] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:135.17m (Euclidean)
[2025-03-07 13:59:07,579] [INFO] [30151] Received PREPARE: id:1741323542381, from:30118, delay:0.0000s, distance:137.29m (Euclidean)
[2025-03-07 13:59:07,579] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,638] [INFO] [30151] Received PREPARE: id:1741323542381, from:30070, delay:0.0001s, distance:189.91m (Euclidean)
[2025-03-07 13:59:07,638] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,638] [INFO] [30151] Received PREPARE: id:1741323542381, from:30119, delay:0.0001s, distance:221.62m (Euclidean)
[2025-03-07 13:59:07,638] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,695] [INFO] [30151] Received PREPARE: id:1741323542381, from:30109, delay:0.0001s, distance:178.14m (Euclidean)
[2025-03-07 13:59:07,695] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,695] [INFO] [30151] Received PREPARE: id:1741323542381, from:30124, delay:0.0000s, distance:88.92m (Euclidean)
[2025-03-07 13:59:07,695] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,699] [INFO] [30151] Received PREPARE: id:1741323542381, from:30157, delay:0.0001s, distance:202.51m (Euclidean)
[2025-03-07 13:59:07,699] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,699] [INFO] [30151] Received COMMIT: id:1741323542381, from:30157, delay:0.0001s, distance:202.51m (Euclidean)
[2025-03-07 13:59:07,741] [INFO] [30151] Received PREPARE: id:1741323542381, from:30136, delay:0.0001s, distance:189.08m (Euclidean)
[2025-03-07 13:59:07,741] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,768] [INFO] [30151] Received COMMIT: id:1741323542381, from:30127, delay:0.0001s, distance:156.78m (Euclidean)
[2025-03-07 13:59:07,777] [INFO] [30151] Received PREPARE: id:1741323542381, from:30133, delay:0.0001s, distance:223.58m (Euclidean)
[2025-03-07 13:59:07,777] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,825] [INFO] [30151] Received COMMIT: id:1741323542381, from:30070, delay:0.0001s, distance:189.91m (Euclidean)
[2025-03-07 13:59:07,857] [INFO] [30151] Received PREPARE: id:1741323542381, from:30015, delay:0.0000s, distance:169.88m (Euclidean)
[2025-03-07 13:59:07,857] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,877] [INFO] [30151] Received COMMIT: id:1741323542381, from:30015, delay:0.0000s, distance:169.88m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30151] Received COMMIT: id:1741323542381, from:30177, delay:0.0001s, distance:216.64m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30151] Received COMMIT: id:1741323542381, from:30136, delay:0.0001s, distance:189.08m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30151] Received PREPARE: id:1741323542381, from:30029, delay:0.0001s, distance:244.64m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:07,877] [INFO] [30151] Received COMMIT: id:1741323542381, from:30029, delay:0.0001s, distance:244.64m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30151] Received PREPARE: id:1741323542381, from:30089, delay:0.0001s, distance:163.30m (Euclidean)
[2025-03-07 13:59:07,877] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,030] [INFO] [30151] Received COMMIT: id:1741323542381, from:30109, delay:0.0001s, distance:178.14m (Euclidean)
[2025-03-07 13:59:08,030] [INFO] [30151] Received COMMIT: id:1741323542381, from:30089, delay:0.0001s, distance:163.30m (Euclidean)
[2025-03-07 13:59:08,040] [INFO] [30151] Received PREPARE: id:1741323542381, from:30155, delay:0.0002s, distance:258.71m (Euclidean)
[2025-03-07 13:59:08,040] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,048] [INFO] [30151] Received PREPARE: id:1741323542381, from:30080, delay:0.0001s, distance:189.23m (Euclidean)
[2025-03-07 13:59:08,048] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,048] [INFO] [30151] Received COMMIT: id:1741323542381, from:30056, delay:0.0000s, distance:74.65m (Euclidean)
[2025-03-07 13:59:08,048] [INFO] [30151] Received COMMIT: id:1741323542381, from:30080, delay:0.0001s, distance:189.23m (Euclidean)
[2025-03-07 13:59:08,048] [INFO] [30151] Received COMMIT: id:1741323542381, from:30155, delay:0.0002s, distance:258.71m (Euclidean)
[2025-03-07 13:59:08,058] [INFO] [30151] Received COMMIT: id:1741323542381, from:30130, delay:0.0001s, distance:201.51m (Euclidean)
[2025-03-07 13:59:08,174] [INFO] [30151] Received COMMIT: id:1741323542381, from:30118, delay:0.0000s, distance:137.29m (Euclidean)
[2025-03-07 13:59:08,174] [INFO] [30151] Received PREPARE: id:1741323542381, from:30092, delay:0.0001s, distance:202.42m (Euclidean)
[2025-03-07 13:59:08,174] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,174] [INFO] [30151] Received PREPARE: id:1741323542381, from:30179, delay:0.0001s, distance:206.64m (Euclidean)
[2025-03-07 13:59:08,174] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,182] [INFO] [30151] Received PREPARE: id:1741323542381, from:30154, delay:0.0000s, distance:181.26m (Euclidean)
[2025-03-07 13:59:08,182] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,182] [INFO] [30151] Received COMMIT: id:1741323542381, from:30154, delay:0.0000s, distance:181.26m (Euclidean)
[2025-03-07 13:59:08,182] [INFO] [30151] Received COMMIT: id:1741323542381, from:30179, delay:0.0001s, distance:206.64m (Euclidean)
[2025-03-07 13:59:08,236] [INFO] [30151] Received COMMIT: id:1741323542381, from:30133, delay:0.0001s, distance:223.58m (Euclidean)
[2025-03-07 13:59:08,272] [INFO] [30151] Received COMMIT: id:1741323542381, from:30092, delay:0.0001s, distance:202.42m (Euclidean)
[2025-03-07 13:59:08,327] [INFO] [30151] Received COMMIT: id:1741323542381, from:30119, delay:0.0001s, distance:221.62m (Euclidean)
[2025-03-07 13:59:08,335] [INFO] [30151] Received COMMIT: id:1741323542381, from:30124, delay:0.0000s, distance:88.92m (Euclidean)
[2025-03-07 13:59:08,477] [INFO] [30151] Received PREPARE: id:1741323542381, from:30103, delay:0.0000s, distance:141.70m (Euclidean)
[2025-03-07 13:59:08,477] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,505] [INFO] [30151] Received COMMIT: id:1741323542381, from:30103, delay:0.0000s, distance:141.70m (Euclidean)
[2025-03-07 13:59:08,798] [INFO] [30151] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:148.73m (Euclidean)
[2025-03-07 13:59:08,798] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,798] [INFO] [30151] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:148.73m (Euclidean)
[2025-03-07 13:59:08,879] [INFO] [30151] Received PREPARE: id:1741323542381, from:30189, delay:0.0001s, distance:234.91m (Euclidean)
[2025-03-07 13:59:08,879] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:08,885] [INFO] [30151] Received COMMIT: id:1741323542381, from:30191, delay:0.0001s, distance:228.43m (Euclidean)
[2025-03-07 13:59:08,966] [INFO] [30151] Received COMMIT: id:1741323542381, from:30112, delay:0.0000s, distance:111.58m (Euclidean)
[2025-03-07 13:59:09,091] [INFO] [30151] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:143.38m (Euclidean)
[2025-03-07 13:59:09,130] [INFO] [30151] Received PREPARE: id:1741323542381, from:30043, delay:0.0000s, distance:168.90m (Euclidean)
[2025-03-07 13:59:09,130] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,130] [INFO] [30151] Received COMMIT: id:1741323542381, from:30043, delay:0.0000s, distance:168.90m (Euclidean)
[2025-03-07 13:59:09,290] [INFO] [30151] Received PREPARE: id:1741323542381, from:30169, delay:0.0000s, distance:104.61m (Euclidean)
[2025-03-07 13:59:09,290] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,290] [INFO] [30151] Received COMMIT: id:1741323542381, from:30169, delay:0.0000s, distance:104.61m (Euclidean)
[2025-03-07 13:59:09,320] [INFO] [30151] Received PREPARE: id:1741323542381, from:30120, delay:0.0000s, distance:146.35m (Euclidean)
[2025-03-07 13:59:09,320] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,320] [INFO] [30151] Received COMMIT: id:1741323542381, from:30120, delay:0.0000s, distance:146.35m (Euclidean)
[2025-03-07 13:59:09,455] [INFO] [30151] Received PREPARE: id:1741323542381, from:30051, delay:0.0001s, distance:209.92m (Euclidean)
[2025-03-07 13:59:09,455] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,455] [INFO] [30151] Received COMMIT: id:1741323542381, from:30051, delay:0.0001s, distance:209.92m (Euclidean)
[2025-03-07 13:59:09,488] [INFO] [30151] Received PREPARE: id:1741323542381, from:30074, delay:0.0001s, distance:195.61m (Euclidean)
[2025-03-07 13:59:09,488] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,490] [INFO] [30151] Received COMMIT: id:1741323542381, from:30074, delay:0.0001s, distance:195.61m (Euclidean)
[2025-03-07 13:59:09,510] [INFO] [30151] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:159.11m (Euclidean)
[2025-03-07 13:59:09,510] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,512] [INFO] [30151] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:159.11m (Euclidean)
[2025-03-07 13:59:09,608] [INFO] [30151] Received COMMIT: id:1741323542381, from:30189, delay:0.0001s, distance:234.91m (Euclidean)
[2025-03-07 13:59:09,649] [INFO] [30151] Received PREPARE: id:1741323542381, from:30085, delay:0.0000s, distance:70.30m (Euclidean)
[2025-03-07 13:59:09,649] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,649] [INFO] [30151] Received COMMIT: id:1741323542381, from:30085, delay:0.0000s, distance:70.30m (Euclidean)
[2025-03-07 13:59:09,728] [INFO] [30151] Received PREPARE: id:1741323542381, from:30190, delay:0.0000s, distance:146.63m (Euclidean)
[2025-03-07 13:59:09,728] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,728] [INFO] [30151] Received COMMIT: id:1741323542381, from:30190, delay:0.0000s, distance:146.63m (Euclidean)
[2025-03-07 13:59:09,828] [INFO] [30151] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:131.59m (Euclidean)
[2025-03-07 13:59:09,828] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,828] [INFO] [30151] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:131.59m (Euclidean)
[2025-03-07 13:59:09,878] [INFO] [30151] Received PREPARE: id:1741323542381, from:30158, delay:0.0000s, distance:138.14m (Euclidean)
[2025-03-07 13:59:09,878] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:09,878] [INFO] [30151] Received COMMIT: id:1741323542381, from:30158, delay:0.0000s, distance:138.14m (Euclidean)
[2025-03-07 13:59:10,069] [INFO] [30151] Received PREPARE: id:1741323542381, from:30065, delay:0.0001s, distance:207.75m (Euclidean)
[2025-03-07 13:59:10,069] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,069] [INFO] [30151] Received PREPARE: id:1741323542381, from:30093, delay:0.0001s, distance:165.49m (Euclidean)
[2025-03-07 13:59:10,069] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,069] [INFO] [30151] Received COMMIT: id:1741323542381, from:30065, delay:0.0001s, distance:207.75m (Euclidean)
[2025-03-07 13:59:10,069] [INFO] [30151] Received COMMIT: id:1741323542381, from:30093, delay:0.0001s, distance:165.49m (Euclidean)
[2025-03-07 13:59:10,069] [INFO] [30151] Received PREPARE: id:1741323542381, from:30025, delay:0.0000s, distance:144.46m (Euclidean)
[2025-03-07 13:59:10,069] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,069] [INFO] [30151] Received COMMIT: id:1741323542381, from:30025, delay:0.0000s, distance:144.46m (Euclidean)
[2025-03-07 13:59:10,216] [INFO] [30151] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:160.58m (Euclidean)
[2025-03-07 13:59:10,216] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,216] [INFO] [30151] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:160.58m (Euclidean)
[2025-03-07 13:59:10,355] [INFO] [30151] Received PREPARE: id:1741323542381, from:30046, delay:0.0001s, distance:178.16m (Euclidean)
[2025-03-07 13:59:10,355] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,355] [INFO] [30151] Received COMMIT: id:1741323542381, from:30046, delay:0.0001s, distance:178.16m (Euclidean)
[2025-03-07 13:59:10,609] [INFO] [30151] Received PREPARE: id:1741323542381, from:30150, delay:0.0000s, distance:104.68m (Euclidean)
[2025-03-07 13:59:10,609] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,609] [INFO] [30151] Received COMMIT: id:1741323542381, from:30150, delay:0.0000s, distance:104.68m (Euclidean)
[2025-03-07 13:59:10,673] [INFO] [30151] Received PREPARE: id:1741323542381, from:30195, delay:0.0001s, distance:172.31m (Euclidean)
[2025-03-07 13:59:10,673] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,673] [INFO] [30151] Received COMMIT: id:1741323542381, from:30195, delay:0.0001s, distance:172.31m (Euclidean)
[2025-03-07 13:59:10,700] [INFO] [30151] Received PREPARE: id:1741323542381, from:30167, delay:0.0001s, distance:241.78m (Euclidean)
[2025-03-07 13:59:10,700] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,700] [INFO] [30151] Received COMMIT: id:1741323542381, from:30167, delay:0.0001s, distance:241.78m (Euclidean)
[2025-03-07 13:59:10,785] [INFO] [30151] Received PREPARE: id:1741323542381, from:30023, delay:0.0001s, distance:162.72m (Euclidean)
[2025-03-07 13:59:10,785] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,785] [INFO] [30151] Received COMMIT: id:1741323542381, from:30023, delay:0.0001s, distance:162.72m (Euclidean)
[2025-03-07 13:59:10,851] [INFO] [30151] Received PREPARE: id:1741323542381, from:30035, delay:0.0001s, distance:169.76m (Euclidean)
[2025-03-07 13:59:10,851] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,851] [INFO] [30151] Received COMMIT: id:1741323542381, from:30035, delay:0.0001s, distance:169.76m (Euclidean)
[2025-03-07 13:59:10,920] [INFO] [30151] Received PREPARE: id:1741323542381, from:30100, delay:0.0001s, distance:172.29m (Euclidean)
[2025-03-07 13:59:10,920] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:10,920] [INFO] [30151] Received COMMIT: id:1741323542381, from:30100, delay:0.0001s, distance:172.29m (Euclidean)
[2025-03-07 13:59:11,314] [INFO] [30151] Received PREPARE: id:1741323542381, from:30048, delay:0.0000s, distance:144.35m (Euclidean)
[2025-03-07 13:59:11,314] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,314] [INFO] [30151] Received COMMIT: id:1741323542381, from:30048, delay:0.0000s, distance:144.35m (Euclidean)
[2025-03-07 13:59:11,323] [INFO] [30151] Received PREPARE: id:1741323542381, from:30174, delay:0.0001s, distance:214.19m (Euclidean)
[2025-03-07 13:59:11,323] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,380] [INFO] [30151] Received PREPARE: id:1741323542381, from:30096, delay:0.0000s, distance:69.59m (Euclidean)
[2025-03-07 13:59:11,380] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,388] [INFO] [30151] Received COMMIT: id:1741323542381, from:30096, delay:0.0000s, distance:69.59m (Euclidean)
[2025-03-07 13:59:11,388] [INFO] [30151] Received PREPARE: id:1741323542381, from:30076, delay:0.0001s, distance:225.53m (Euclidean)
[2025-03-07 13:59:11,388] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,391] [INFO] [30151] Received COMMIT: id:1741323542381, from:30076, delay:0.0001s, distance:225.53m (Euclidean)
[2025-03-07 13:59:11,403] [INFO] [30151] Received COMMIT: id:1741323542381, from:30174, delay:0.0001s, distance:214.19m (Euclidean)
[2025-03-07 13:59:11,529] [INFO] [30151] Received PREPARE: id:1741323542381, from:30059, delay:0.0000s, distance:57.96m (Euclidean)
[2025-03-07 13:59:11,529] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,529] [INFO] [30151] Received COMMIT: id:1741323542381, from:30059, delay:0.0000s, distance:57.96m (Euclidean)
[2025-03-07 13:59:11,727] [INFO] [30151] Received PREPARE: id:1741323542381, from:30171, delay:0.0001s, distance:180.66m (Euclidean)
[2025-03-07 13:59:11,727] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,734] [INFO] [30151] Received COMMIT: id:1741323542381, from:30171, delay:0.0001s, distance:180.66m (Euclidean)
[2025-03-07 13:59:11,843] [INFO] [30151] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:53.44m (Euclidean)
[2025-03-07 13:59:11,846] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,846] [INFO] [30151] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:53.44m (Euclidean)
[2025-03-07 13:59:11,893] [INFO] [30151] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:57.57m (Euclidean)
[2025-03-07 13:59:11,893] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,893] [INFO] [30151] Received PREPARE: id:1741323542381, from:30090, delay:0.0000s, distance:116.25m (Euclidean)
[2025-03-07 13:59:11,893] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:11,895] [INFO] [30151] Received COMMIT: id:1741323542381, from:30090, delay:0.0000s, distance:116.25m (Euclidean)
[2025-03-07 13:59:11,895] [INFO] [30151] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:57.57m (Euclidean)
[2025-03-07 13:59:12,014] [INFO] [30151] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:95.62m (Euclidean)
[2025-03-07 13:59:12,014] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,016] [INFO] [30151] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:95.62m (Euclidean)
[2025-03-07 13:59:12,205] [INFO] [30151] Received PREPARE: id:1741323542381, from:30066, delay:0.0000s, distance:89.43m (Euclidean)
[2025-03-07 13:59:12,205] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,207] [INFO] [30151] Received COMMIT: id:1741323542381, from:30066, delay:0.0000s, distance:89.43m (Euclidean)
[2025-03-07 13:59:12,225] [INFO] [30151] Received PREPARE: id:1741323542381, from:30117, delay:0.0000s, distance:200.03m (Euclidean)
[2025-03-07 13:59:12,228] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,381] [INFO] [30151] Received PREPARE: id:1741323542381, from:30054, delay:0.0001s, distance:166.57m (Euclidean)
[2025-03-07 13:59:12,381] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,381] [INFO] [30151] Received COMMIT: id:1741323542381, from:30054, delay:0.0001s, distance:166.57m (Euclidean)
[2025-03-07 13:59:12,453] [INFO] [30151] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:103.79m (Euclidean)
[2025-03-07 13:59:12,453] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,453] [INFO] [30151] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:103.79m (Euclidean)
[2025-03-07 13:59:12,516] [INFO] [30151] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:145.54m (Euclidean)
[2025-03-07 13:59:12,516] [INFO] [30151] Missing PRE-PREPARE for REQUEST 1741323542381; ignoring PREPARE
[2025-03-07 13:59:12,518] [INFO] [30151] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:145.54m (Euclidean)
[2025-03-07 13:59:12,725] [INFO] [30151] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0000s, distance:173.95m (Euclidean)
[2025-03-07 13:59:12,725] [INFO] [30151] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:12,742] [INFO] [30151] Not broadcasting to fault node: 30077
[2025-03-07 13:59:12,753] [INFO] [30151] Not broadcasting to fault node: 30184
[2025-03-07 13:59:12,879] [INFO] [30151] Received PREPARE: id:1741323542381, from:30024, delay:0.0001s, distance:228.56m (Euclidean)
[2025-03-07 13:59:12,879] [INFO] [30151] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:12,890] [INFO] [30151] Not broadcasting to fault node: 30077
[2025-03-07 13:59:12,903] [INFO] [30151] Not broadcasting to fault node: 30184
[2025-03-07 13:59:12,940] [INFO] [30151] Received COMMIT: id:1741323542381, from:30024, delay:0.0001s, distance:228.56m (Euclidean)
[2025-03-07 13:59:13,028] [INFO] [30151] Received COMMIT: id:1741323542381, from:30011, delay:0.0000s, distance:105.90m (Euclidean)
[2025-03-07 13:59:13,028] [INFO] [30151] Received PREPARE: id:1741323542381, from:30011, delay:0.0000s, distance:105.90m (Euclidean)
[2025-03-07 13:59:13,465] [INFO] [30151] Received PREPARE: id:1741323542381, from:30165, delay:0.0000s, distance:134.57m (Euclidean)
[2025-03-07 13:59:13,465] [INFO] [30151] Received COMMIT: id:1741323542381, from:30165, delay:0.0000s, distance:134.57m (Euclidean)
[2025-03-07 13:59:13,828] [INFO] [30151] Received PREPARE: id:1741323542381, from:30146, delay:0.0001s, distance:156.99m (Euclidean)
[2025-03-07 13:59:13,842] [INFO] [30151] Received COMMIT: id:1741323542381, from:30146, delay:0.0001s, distance:156.99m (Euclidean)
[2025-03-07 13:59:13,875] [INFO] [30151] Received PREPARE: id:1741323542381, from:30091, delay:0.0000s, distance:61.55m (Euclidean)
[2025-03-07 13:59:13,933] [INFO] [30151] Received COMMIT: id:1741323542381, from:30117, delay:0.0000s, distance:200.03m (Euclidean)
[2025-03-07 13:59:13,972] [INFO] [30151] Received PREPARE: id:1741323542381, from:30010, delay:0.0001s, distance:191.08m (Euclidean)
[2025-03-07 13:59:13,972] [INFO] [30151] Received COMMIT: id:1741323542381, from:30010, delay:0.0001s, distance:191.08m (Euclidean)
[2025-03-07 13:59:14,023] [INFO] [30151] Received PREPARE: id:1741323542381, from:30193, delay:0.0000s, distance:97.97m (Euclidean)
[2025-03-07 13:59:14,023] [INFO] [30151] Received COMMIT: id:1741323542381, from:30193, delay:0.0000s, distance:97.97m (Euclidean)
[2025-03-07 13:59:14,381] [INFO] [30151] Received PREPARE: id:1741323542381, from:30088, delay:0.0000s, distance:115.65m (Euclidean)
[2025-03-07 13:59:14,481] [INFO] [30151] Received PREPARE: id:1741323542381, from:30052, delay:0.0000s, distance:77.69m (Euclidean)
[2025-03-07 13:59:14,481] [INFO] [30151] Received COMMIT: id:1741323542381, from:30086, delay:0.0002s, distance:260.25m (Euclidean)
[2025-03-07 13:59:14,483] [INFO] [30151] Received COMMIT: id:1741323542381, from:30052, delay:0.0000s, distance:77.69m (Euclidean)
[2025-03-07 13:59:14,483] [INFO] [30151] Received PREPARE: id:1741323542381, from:30086, delay:0.0002s, distance:260.25m (Euclidean)
[2025-03-07 13:59:14,574] [INFO] [30151] Received PREPARE: id:1741323542381, from:30026, delay:0.0002s, distance:277.49m (Euclidean)
[2025-03-07 13:59:14,574] [INFO] [30151] Received COMMIT: id:1741323542381, from:30026, delay:0.0002s, distance:277.49m (Euclidean)
[2025-03-07 13:59:14,696] [INFO] [30151] Received PREPARE: id:1741323542381, from:30145, delay:0.0000s, distance:134.71m (Euclidean)
[2025-03-07 13:59:14,696] [INFO] [30151] Received COMMIT: id:1741323542381, from:30145, delay:0.0000s, distance:134.71m (Euclidean)
[2025-03-07 13:59:15,763] [INFO] [30151] Received COMMIT: id:1741323542381, from:30088, delay:0.0000s, distance:115.65m (Euclidean)
[2025-03-07 13:59:15,765] [INFO] [30151] Received PREPARE: id:1741323542381, from:30033, delay:0.0001s, distance:154.47m (Euclidean)
[2025-03-07 13:59:15,765] [INFO] [30151] Received COMMIT: id:1741323542381, from:30033, delay:0.0001s, distance:154.47m (Euclidean)
[2025-03-07 13:59:15,998] [INFO] [30151] Received PREPARE: id:1741323542381, from:30006, delay:0.0000s, distance:88.19m (Euclidean)
[2025-03-07 13:59:15,998] [INFO] [30151] Received COMMIT: id:1741323542381, from:30006, delay:0.0000s, distance:88.19m (Euclidean)
[2025-03-07 13:59:16,263] [INFO] [30151] Received PREPARE: id:1741323542381, from:30094, delay:0.0000s, distance:48.68m (Euclidean)
[2025-03-07 13:59:16,278] [INFO] [30151] Received COMMIT: id:1741323542381, from:30094, delay:0.0000s, distance:48.68m (Euclidean)
[2025-03-07 13:59:16,586] [INFO] [30151] Received PREPARE: id:1741323542381, from:30194, delay:0.0001s, distance:163.01m (Euclidean)
[2025-03-07 13:59:16,586] [INFO] [30151] Received COMMIT: id:1741323542381, from:30194, delay:0.0001s, distance:163.01m (Euclidean)
[2025-03-07 13:59:16,754] [INFO] [30151] Received PREPARE: id:1741323542381, from:30067, delay:0.0000s, distance:126.59m (Euclidean)
[2025-03-07 13:59:16,754] [INFO] [30151] Received COMMIT: id:1741323542381, from:30067, delay:0.0000s, distance:126.59m (Euclidean)
[2025-03-07 13:59:16,815] [INFO] [30151] Received PREPARE: id:1741323542381, from:30187, delay:0.0000s, distance:113.60m (Euclidean)
[2025-03-07 13:59:16,835] [INFO] [30151] Received COMMIT: id:1741323542381, from:30187, delay:0.0000s, distance:113.60m (Euclidean)
[2025-03-07 13:59:16,892] [INFO] [30151] Received PREPARE: id:1741323542381, from:30135, delay:0.0000s, distance:125.77m (Euclidean)
[2025-03-07 13:59:16,892] [INFO] [30151] Received COMMIT: id:1741323542381, from:30135, delay:0.0000s, distance:125.77m (Euclidean)
[2025-03-07 13:59:16,922] [INFO] [30151] Received PREPARE: id:1741323542381, from:30050, delay:0.0001s, distance:189.25m (Euclidean)
[2025-03-07 13:59:16,922] [INFO] [30151] Received COMMIT: id:1741323542381, from:30050, delay:0.0001s, distance:189.25m (Euclidean)
[2025-03-07 13:59:17,067] [INFO] [30151] Received PREPARE: id:1741323542381, from:30153, delay:0.0001s, distance:182.67m (Euclidean)
[2025-03-07 13:59:17,142] [INFO] [30151] Received PREPARE: id:1741323542381, from:30138, delay:0.0000s, distance:75.47m (Euclidean)
[2025-03-07 13:59:17,186] [INFO] [30151] Received PREPARE: id:1741323542381, from:30139, delay:0.0000s, distance:75.54m (Euclidean)
[2025-03-07 13:59:17,190] [INFO] [30151] Received PREPARE: id:1741323542381, from:30073, delay:0.0000s, distance:96.08m (Euclidean)
[2025-03-07 13:59:17,471] [INFO] [30151] Received PREPARE: id:1741323542381, from:30114, delay:0.0001s, distance:155.71m (Euclidean)
[2025-03-07 13:59:17,483] [INFO] [30151] Received PREPARE: id:1741323542381, from:30160, delay:0.0001s, distance:168.37m (Euclidean)
[2025-03-07 13:59:17,493] [INFO] [30151] Received COMMIT: id:1741323542381, from:30114, delay:0.0001s, distance:155.71m (Euclidean)
[2025-03-07 13:59:17,567] [INFO] [30151] Received PREPARE: id:1741323542381, from:30188, delay:0.0000s, distance:78.07m (Euclidean)
[2025-03-07 13:59:17,567] [INFO] [30151] Received COMMIT: id:1741323542381, from:30188, delay:0.0000s, distance:78.07m (Euclidean)
[2025-03-07 13:59:17,576] [INFO] [30151] Received PREPARE: id:1741323542381, from:30125, delay:0.0001s, distance:205.55m (Euclidean)
[2025-03-07 13:59:17,576] [INFO] [30151] Received PREPARE: id:1741323542381, from:30198, delay:0.0002s, distance:268.08m (Euclidean)
[2025-03-07 13:59:17,578] [INFO] [30151] Received COMMIT: id:1741323542381, from:30125, delay:0.0001s, distance:205.55m (Euclidean)
[2025-03-07 13:59:17,578] [INFO] [30151] Received COMMIT: id:1741323542381, from:30198, delay:0.0002s, distance:268.08m (Euclidean)
[2025-03-07 13:59:17,785] [INFO] [30151] Received PREPARE: id:1741323542381, from:30166, delay:0.0000s, distance:66.28m (Euclidean)
[2025-03-07 13:59:17,828] [INFO] [30151] Received COMMIT: id:1741323542381, from:30166, delay:0.0000s, distance:66.28m (Euclidean)
[2025-03-07 13:59:17,828] [INFO] [30151] Received PREPARE: id:1741323542381, from:30039, delay:0.0000s, distance:90.63m (Euclidean)
[2025-03-07 13:59:17,850] [INFO] [30151] Received COMMIT: id:1741323542381, from:30000, delay:0.0000s, distance:173.95m (Euclidean)
[2025-03-07 13:59:18,365] [INFO] [30151] Received PREPARE: id:1741323542381, from:30071, delay:0.0001s, distance:164.30m (Euclidean)
[2025-03-07 13:59:18,365] [INFO] [30151] Received COMMIT: id:1741323542381, from:30071, delay:0.0001s, distance:164.30m (Euclidean)
[2025-03-07 13:59:18,583] [INFO] [30151] Received PREPARE: id:1741323542381, from:30055, delay:0.0001s, distance:173.76m (Euclidean)
[2025-03-07 13:59:18,587] [INFO] [30151] Received COMMIT: id:1741323542381, from:30055, delay:0.0001s, distance:173.76m (Euclidean)
[2025-03-07 13:59:18,630] [INFO] [30151] Received PREPARE: id:1741323542381, from:30079, delay:0.0000s, distance:119.92m (Euclidean)
[2025-03-07 13:59:18,631] [INFO] [30151] Received COMMIT: id:1741323542381, from:30079, delay:0.0000s, distance:119.92m (Euclidean)
[2025-03-07 13:59:18,771] [INFO] [30151] Received COMMIT: id:1741323542381, from:30160, delay:0.0001s, distance:168.37m (Euclidean)
[2025-03-07 13:59:18,871] [INFO] [30151] Received PREPARE: id:1741323542381, from:30019, delay:0.0001s, distance:231.36m (Euclidean)
[2025-03-07 13:59:18,906] [INFO] [30151] Received COMMIT: id:1741323542381, from:30019, delay:0.0001s, distance:231.36m (Euclidean)
[2025-03-07 13:59:19,037] [INFO] [30151] Received COMMIT: id:1741323542381, from:30091, delay:0.0000s, distance:61.55m (Euclidean)
[2025-03-07 13:59:19,097] [INFO] [30151] Received PREPARE: id:1741323542381, from:30058, delay:0.0001s, distance:151.21m (Euclidean)
[2025-03-07 13:59:19,134] [INFO] [30151] Received PREPARE: id:1741323542381, from:30016, delay:0.0001s, distance:207.43m (Euclidean)
[2025-03-07 13:59:19,134] [INFO] [30151] Received COMMIT: id:1741323542381, from:30058, delay:0.0001s, distance:151.21m (Euclidean)
[2025-03-07 13:59:19,134] [INFO] [30151] Received COMMIT: id:1741323542381, from:30016, delay:0.0001s, distance:207.43m (Euclidean)
[2025-03-07 13:59:19,172] [INFO] [30151] Received PREPARE: id:1741323542381, from:30134, delay:0.0002s, distance:262.64m (Euclidean)
[2025-03-07 13:59:19,172] [INFO] [30151] Received COMMIT: id:1741323542381, from:30134, delay:0.0002s, distance:262.64m (Euclidean)
[2025-03-07 13:59:19,584] [INFO] [30151] Received PREPARE: id:1741323542381, from:30173, delay:0.0000s, distance:92.92m (Euclidean)
[2025-03-07 13:59:19,702] [INFO] [30151] Received PREPARE: id:1741323542381, from:30137, delay:0.0001s, distance:164.07m (Euclidean)
[2025-03-07 13:59:19,706] [INFO] [30151] Received COMMIT: id:1741323542381, from:30152, delay:0.0000s, distance:112.91m (Euclidean)
[2025-03-07 13:59:19,706] [INFO] [30151] Received COMMIT: id:1741323542381, from:30143, delay:0.0000s, distance:129.79m (Euclidean)
[2025-03-07 13:59:19,706] [INFO] [30151] Received PREPARE: id:1741323542381, from:30143, delay:0.0000s, distance:129.79m (Euclidean)
[2025-03-07 13:59:19,706] [INFO] [30151] Received PREPARE: id:1741323542381, from:30152, delay:0.0000s, distance:112.91m (Euclidean)
[2025-03-07 13:59:19,708] [INFO] [30151] Received COMMIT: id:1741323542381, from:30137, delay:0.0001s, distance:164.07m (Euclidean)
[2025-03-07 13:59:19,744] [INFO] [30151] Received PREPARE: id:1741323542381, from:30031, delay:0.0001s, distance:172.49m (Euclidean)
[2025-03-07 13:59:19,744] [INFO] [30151] Received COMMIT: id:1741323542381, from:30031, delay:0.0001s, distance:172.49m (Euclidean)
[2025-03-07 13:59:19,783] [INFO] [30151] Received PREPARE: id:1741323542381, from:30042, delay:0.0000s, distance:51.24m (Euclidean)
[2025-03-07 13:59:19,789] [INFO] [30151] Received COMMIT: id:1741323542381, from:30042, delay:0.0000s, distance:51.24m (Euclidean)
[2025-03-07 13:59:19,838] [INFO] [30151] Received COMMIT: id:1741323542381, from:30138, delay:0.0000s, distance:75.47m (Euclidean)
[2025-03-07 13:59:19,940] [INFO] [30151] Received PREPARE: id:1741323542381, from:30014, delay:0.0000s, distance:119.60m (Euclidean)
[2025-03-07 13:59:19,983] [INFO] [30151] Received COMMIT: id:1741323542381, from:30014, delay:0.0000s, distance:119.60m (Euclidean)
[2025-03-07 13:59:20,009] [INFO] [30151] Received PREPARE: id:1741323542381, from:30069, delay:0.0001s, distance:193.74m (Euclidean)
[2025-03-07 13:59:20,033] [INFO] [30151] Received COMMIT: id:1741323542381, from:30069, delay:0.0001s, distance:193.74m (Euclidean)
[2025-03-07 13:59:20,064] [INFO] [30151] Received PREPARE: id:1741323542381, from:30003, delay:0.0002s, distance:256.34m (Euclidean)
[2025-03-07 13:59:20,066] [INFO] [30151] Received COMMIT: id:1741323542381, from:30003, delay:0.0002s, distance:256.34m (Euclidean)
[2025-03-07 13:59:20,161] [INFO] [30151] Received PREPARE: id:1741323542381, from:30075, delay:0.0000s, distance:99.52m (Euclidean)
[2025-03-07 13:59:20,163] [INFO] [30151] Received COMMIT: id:1741323542381, from:30075, delay:0.0000s, distance:99.52m (Euclidean)
[2025-03-07 13:59:20,304] [INFO] [30151] Received PREPARE: id:1741323542381, from:30131, delay:0.0000s, distance:68.10m (Euclidean)
[2025-03-07 13:59:20,304] [INFO] [30151] Received COMMIT: id:1741323542381, from:30039, delay:0.0000s, distance:90.63m (Euclidean)
[2025-03-07 13:59:20,304] [INFO] [30151] Received COMMIT: id:1741323542381, from:30131, delay:0.0000s, distance:68.10m (Euclidean)
[2025-03-07 13:59:20,329] [INFO] [30151] Received PREPARE: id:1741323542381, from:30068, delay:0.0001s, distance:181.84m (Euclidean)
[2025-03-07 13:59:20,329] [INFO] [30151] Received COMMIT: id:1741323542381, from:30068, delay:0.0001s, distance:181.84m (Euclidean)
[2025-03-07 13:59:20,573] [INFO] [30151] Received PREPARE: id:1741323542381, from:30017, delay:0.0000s, distance:137.40m (Euclidean)
[2025-03-07 13:59:20,790] [INFO] [30151] Received COMMIT: id:1741323542381, from:30173, delay:0.0000s, distance:92.92m (Euclidean)
[2025-03-07 13:59:20,869] [INFO] [30151] Received COMMIT: id:1741323542381, from:30073, delay:0.0000s, distance:96.08m (Euclidean)
[2025-03-07 13:59:21,041] [INFO] [30151] Received PREPARE: id:1741323542381, from:30141, delay:0.0001s, distance:210.51m (Euclidean)
[2025-03-07 13:59:21,041] [INFO] [30151] Received COMMIT: id:1741323542381, from:30141, delay:0.0001s, distance:210.51m (Euclidean)
[2025-03-07 13:59:21,148] [INFO] [30151] Received PREPARE: id:1741323542381, from:30061, delay:0.0001s, distance:155.85m (Euclidean)
[2025-03-07 13:59:21,156] [INFO] [30151] Received COMMIT: id:1741323542381, from:30061, delay:0.0001s, distance:155.85m (Euclidean)
[2025-03-07 13:59:21,177] [INFO] [30151] Received PREPARE: id:1741323542381, from:30001, delay:0.0000s, distance:112.98m (Euclidean)
[2025-03-07 13:59:21,177] [INFO] [30151] Received COMMIT: id:1741323542381, from:30001, delay:0.0000s, distance:112.98m (Euclidean)
[2025-03-07 13:59:21,373] [INFO] [30151] Received PREPARE: id:1741323542381, from:30032, delay:0.0001s, distance:154.66m (Euclidean)
[2025-03-07 13:59:21,471] [INFO] [30151] Received COMMIT: id:1741323542381, from:30032, delay:0.0001s, distance:154.66m (Euclidean)
[2025-03-07 13:59:21,730] [INFO] [30151] Received PREPARE: id:1741323542381, from:30036, delay:0.0001s, distance:174.37m (Euclidean)
[2025-03-07 13:59:21,732] [INFO] [30151] Received COMMIT: id:1741323542381, from:30036, delay:0.0001s, distance:174.37m (Euclidean)
[2025-03-07 13:59:21,818] [INFO] [30151] Received COMMIT: id:1741323542381, from:30153, delay:0.0001s, distance:182.67m (Euclidean)
[2025-03-07 13:59:21,899] [INFO] [30151] Received PREPARE: id:1741323542381, from:30008, delay:0.0000s, distance:91.02m (Euclidean)
[2025-03-07 13:59:21,931] [INFO] [30151] Received COMMIT: id:1741323542381, from:30008, delay:0.0000s, distance:91.02m (Euclidean)
[2025-03-07 13:59:22,021] [INFO] [30151] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:106.21m (Euclidean)
[2025-03-07 13:59:22,021] [INFO] [30151] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:106.21m (Euclidean)
[2025-03-07 13:59:22,401] [INFO] [30151] Received PREPARE: id:1741323542381, from:30159, delay:0.0001s, distance:176.29m (Euclidean)
[2025-03-07 13:59:22,401] [INFO] [30151] Received COMMIT: id:1741323542381, from:30159, delay:0.0001s, distance:176.29m (Euclidean)
[2025-03-07 13:59:22,523] [INFO] [30151] Received PREPARE: id:1741323542381, from:30081, delay:0.0001s, distance:202.73m (Euclidean)
[2025-03-07 13:59:22,533] [INFO] [30151] Received COMMIT: id:1741323542381, from:30081, delay:0.0001s, distance:202.73m (Euclidean)
[2025-03-07 13:59:22,596] [INFO] [30151] Received PREPARE: id:1741323542381, from:30087, delay:0.0001s, distance:168.90m (Euclidean)
[2025-03-07 13:59:22,596] [INFO] [30151] Received COMMIT: id:1741323542381, from:30087, delay:0.0001s, distance:168.90m (Euclidean)
[2025-03-07 13:59:22,873] [INFO] [30151] Received COMMIT: id:1741323542381, from:30017, delay:0.0000s, distance:137.40m (Euclidean)
[2025-03-07 13:59:22,876] [INFO] [30151] Received PREPARE: id:1741323542381, from:30140, delay:0.0000s, distance:149.77m (Euclidean)
[2025-03-07 13:59:23,006] [INFO] [30151] Received COMMIT: id:1741323542381, from:30140, delay:0.0000s, distance:149.77m (Euclidean)
[2025-03-07 13:59:23,041] [INFO] [30151] Received COMMIT: id:1741323542381, from:30045, delay:0.0001s, distance:172.84m (Euclidean)
[2025-03-07 13:59:23,041] [INFO] [30151] Received COMMIT: id:1741323542381, from:30132, delay:0.0000s, distance:141.39m (Euclidean)
[2025-03-07 13:59:23,041] [INFO] [30151] Received PREPARE: id:1741323542381, from:30132, delay:0.0000s, distance:141.39m (Euclidean)
[2025-03-07 13:59:23,041] [INFO] [30151] Received PREPARE: id:1741323542381, from:30045, delay:0.0001s, distance:172.84m (Euclidean)
[2025-03-07 13:59:23,101] [INFO] [30151] Received PREPARE: id:1741323542381, from:30047, delay:0.0000s, distance:101.00m (Euclidean)
[2025-03-07 13:59:23,323] [INFO] [30151] Received PREPARE: id:1741323542381, from:30197, delay:0.0002s, distance:267.34m (Euclidean)
[2025-03-07 13:59:23,323] [INFO] [30151] Received COMMIT: id:1741323542381, from:30197, delay:0.0002s, distance:267.34m (Euclidean)
[2025-03-07 13:59:23,424] [INFO] [30151] Received PREPARE: id:1741323542381, from:30122, delay:0.0000s, distance:141.55m (Euclidean)
[2025-03-07 13:59:23,457] [INFO] [30151] Received COMMIT: id:1741323542381, from:30122, delay:0.0000s, distance:141.55m (Euclidean)
[2025-03-07 13:59:23,788] [INFO] [30151] Received COMMIT: id:1741323542381, from:30139, delay:0.0000s, distance:75.54m (Euclidean)
[2025-03-07 13:59:24,417] [INFO] [30151] Received PREPARE: id:1741323542381, from:30105, delay:0.0001s, distance:197.25m (Euclidean)
[2025-03-07 13:59:24,417] [INFO] [30151] Received PREPARE: id:1741323542381, from:30084, delay:0.0000s, distance:92.65m (Euclidean)
[2025-03-07 13:59:24,417] [INFO] [30151] Received PREPARE: id:1741323542381, from:30083, delay:0.0002s, distance:255.43m (Euclidean)
[2025-03-07 13:59:24,453] [INFO] [30151] Received COMMIT: id:1741323542381, from:30084, delay:0.0000s, distance:92.65m (Euclidean)
[2025-03-07 13:59:24,453] [INFO] [30151] Received COMMIT: id:1741323542381, from:30083, delay:0.0002s, distance:255.43m (Euclidean)
[2025-03-07 13:59:24,453] [INFO] [30151] Received COMMIT: id:1741323542381, from:30105, delay:0.0001s, distance:197.25m (Euclidean)
[2025-03-07 13:59:24,786] [INFO] [30151] Received PREPARE: id:1741323542381, from:30142, delay:0.0000s, distance:127.19m (Euclidean)
[2025-03-07 13:59:24,798] [INFO] [30151] Received COMMIT: id:1741323542381, from:30142, delay:0.0000s, distance:127.19m (Euclidean)
[2025-03-07 13:59:25,041] [INFO] [30151] Received PREPARE: id:1741323542381, from:30101, delay:0.0001s, distance:229.74m (Euclidean)
[2025-03-07 13:59:25,042] [INFO] [30151] Received COMMIT: id:1741323542381, from:30101, delay:0.0001s, distance:229.74m (Euclidean)
[2025-03-07 13:59:25,642] [INFO] [30151] Received PREPARE: id:1741323542381, from:30172, delay:0.0000s, distance:85.17m (Euclidean)
[2025-03-07 13:59:25,880] [INFO] [30151] Received PREPARE: id:1741323542381, from:30064, delay:0.0001s, distance:196.25m (Euclidean)
[2025-03-07 13:59:25,880] [INFO] [30151] Received PREPARE: id:1741323542381, from:30156, delay:0.0000s, distance:127.36m (Euclidean)
[2025-03-07 13:59:25,880] [INFO] [30151] Received COMMIT: id:1741323542381, from:30156, delay:0.0000s, distance:127.36m (Euclidean)
[2025-03-07 13:59:25,880] [INFO] [30151] Received COMMIT: id:1741323542381, from:30064, delay:0.0001s, distance:196.25m (Euclidean)
[2025-03-07 13:59:25,978] [INFO] [30151] Received PREPARE: id:1741323542381, from:30038, delay:0.0001s, distance:169.20m (Euclidean)
[2025-03-07 13:59:25,978] [INFO] [30151] Received COMMIT: id:1741323542381, from:30038, delay:0.0001s, distance:169.20m (Euclidean)
[2025-03-07 13:59:25,978] [INFO] [30151] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:185.03m (Euclidean)
[2025-03-07 13:59:25,978] [INFO] [30151] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:185.03m (Euclidean)
[2025-03-07 13:59:26,272] [INFO] [30151] Received PREPARE: id:1741323542381, from:30185, delay:0.0000s, distance:125.11m (Euclidean)
[2025-03-07 13:59:26,328] [INFO] [30151] Received PREPARE: id:1741323542381, from:30148, delay:0.0001s, distance:154.55m (Euclidean)
[2025-03-07 13:59:26,361] [INFO] [30151] Received COMMIT: id:1741323542381, from:30047, delay:0.0000s, distance:101.00m (Euclidean)
[2025-03-07 13:59:26,760] [INFO] [30151] Received PREPARE: id:1741323542381, from:30104, delay:0.0001s, distance:180.06m (Euclidean)
[2025-03-07 13:59:26,761] [INFO] [30151] Received COMMIT: id:1741323542381, from:30104, delay:0.0001s, distance:180.06m (Euclidean)
[2025-03-07 13:59:27,126] [INFO] [30151] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:131.17m (Euclidean)
[2025-03-07 13:59:27,126] [INFO] [30151] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:131.17m (Euclidean)
[2025-03-07 13:59:27,132] [INFO] [30151] Received PREPARE: id:1741323542381, from:30163, delay:0.0000s, distance:133.64m (Euclidean)
[2025-03-07 13:59:27,133] [INFO] [30151] Received COMMIT: id:1741323542381, from:30163, delay:0.0000s, distance:133.64m (Euclidean)
[2025-03-07 13:59:27,286] [INFO] [30151] Received COMMIT: id:1741323542381, from:30148, delay:0.0001s, distance:154.55m (Euclidean)
[2025-03-07 13:59:27,315] [INFO] [30151] Received PREPARE: id:1741323542381, from:30009, delay:0.0002s, distance:281.47m (Euclidean)
[2025-03-07 13:59:27,316] [INFO] [30151] Received COMMIT: id:1741323542381, from:30009, delay:0.0002s, distance:281.47m (Euclidean)
[2025-03-07 13:59:27,467] [INFO] [30151] Received PREPARE: id:1741323542381, from:30162, delay:0.0000s, distance:128.17m (Euclidean)
[2025-03-07 13:59:27,501] [INFO] [30151] Received COMMIT: id:1741323542381, from:30162, delay:0.0000s, distance:128.17m (Euclidean)
[2025-03-07 13:59:27,539] [INFO] [30151] Received PREPARE: id:1741323542381, from:30022, delay:0.0000s, distance:146.27m (Euclidean)
[2025-03-07 13:59:27,539] [INFO] [30151] Received COMMIT: id:1741323542381, from:30022, delay:0.0000s, distance:146.27m (Euclidean)
[2025-03-07 13:59:27,765] [INFO] [30151] Received PREPARE: id:1741323542381, from:30012, delay:0.0000s, distance:149.11m (Euclidean)
[2025-03-07 13:59:27,765] [INFO] [30151] Received COMMIT: id:1741323542381, from:30012, delay:0.0000s, distance:149.11m (Euclidean)
[2025-03-07 13:59:27,851] [INFO] [30151] Received COMMIT: id:1741323542381, from:30172, delay:0.0000s, distance:85.17m (Euclidean)
[2025-03-07 13:59:27,879] [INFO] [30151] Received PREPARE: id:1741323542381, from:30072, delay:0.0001s, distance:157.90m (Euclidean)
[2025-03-07 13:59:27,879] [INFO] [30151] Received COMMIT: id:1741323542381, from:30072, delay:0.0001s, distance:157.90m (Euclidean)
[2025-03-07 13:59:28,057] [INFO] [30151] Received PREPARE: id:1741323542381, from:30078, delay:0.0000s, distance:85.97m (Euclidean)
[2025-03-07 13:59:28,057] [INFO] [30151] Received COMMIT: id:1741323542381, from:30078, delay:0.0000s, distance:85.97m (Euclidean)
[2025-03-07 13:59:28,095] [INFO] [30151] Received PREPARE: id:1741323542381, from:30044, delay:0.0000s, distance:145.88m (Euclidean)
[2025-03-07 13:59:28,095] [INFO] [30151] Received COMMIT: id:1741323542381, from:30044, delay:0.0000s, distance:145.88m (Euclidean)
[2025-03-07 13:59:28,247] [INFO] [30151] Received PREPARE: id:1741323542381, from:30030, delay:0.0001s, distance:179.56m (Euclidean)
[2025-03-07 13:59:28,247] [INFO] [30151] Received COMMIT: id:1741323542381, from:30030, delay:0.0001s, distance:179.56m (Euclidean)
[2025-03-07 13:59:28,307] [INFO] [30151] Received PREPARE: id:1741323542381, from:30192, delay:0.0000s, distance:142.26m (Euclidean)
[2025-03-07 13:59:28,309] [INFO] [30151] Received COMMIT: id:1741323542381, from:30185, delay:0.0000s, distance:125.11m (Euclidean)
[2025-03-07 13:59:28,680] [INFO] [30151] Received COMMIT: id:1741323542381, from:30192, delay:0.0000s, distance:142.26m (Euclidean)
[2025-03-07 13:59:28,684] [INFO] [30151] Received PREPARE: id:1741323542381, from:30097, delay:0.0001s, distance:180.79m (Euclidean)
[2025-03-07 13:59:28,830] [INFO] [30151] Received PREPARE: id:1741323542381, from:30183, delay:0.0000s, distance:103.99m (Euclidean)
[2025-03-07 13:59:28,842] [INFO] [30151] Received COMMIT: id:1741323542381, from:30183, delay:0.0000s, distance:103.99m (Euclidean)
[2025-03-07 13:59:37,965] [INFO] [30151] Received PREPARE: id:1741323542381, from:30018, delay:0.0000s, distance:28.94m (Euclidean)
[2025-03-07 13:59:38,017] [INFO] [30151] Received COMMIT: id:1741323542381, from:30018, delay:0.0000s, distance:28.94m (Euclidean)
[2025-03-07 13:59:38,117] [INFO] [30151] Received PREPARE: id:1741323542381, from:30002, delay:0.0001s, distance:220.89m (Euclidean)
[2025-03-07 13:59:38,176] [INFO] [30151] Received COMMIT: id:1741323542381, from:30002, delay:0.0001s, distance:220.89m (Euclidean)
[2025-03-07 13:59:38,204] [INFO] [30151] Received COMMIT: id:1741323542381, from:30082, delay:0.0000s, distance:139.30m (Euclidean)
[2025-03-07 13:59:38,227] [INFO] [30151] Received COMMIT: id:1741323542381, from:30097, delay:0.0001s, distance:180.79m (Euclidean)
[2025-03-07 13:59:38,833] [INFO] [30151] Received COMMIT: id:1741323542381, from:30164, delay:0.0000s, distance:86.09m (Euclidean)
[2025-03-07 13:59:38,835] [INFO] [30151] Received PREPARE: id:1741323542381, from:30164, delay:0.0000s, distance:86.09m (Euclidean)
